borgbackup/borg

setup.py

(cherry picked from commit 5be756a0c6d526fc513fa0ad08767b127b941e90)

update msgpack requirement, fixes #3753 (master)

---

src/borg/archiver.py

Config repo without key (fwd port to master)

---

src/borg/archive.py

(cherry picked from commit 85bc590c7580e5b27808e9c846172b8754c026b5)
(fwd port of #3794)

borg check: show progress while rebuilding missing manifest, fixes #3787

---

docs/quickstart.rst

docs: fix and deduplicate encryption quickstart docs (forward-port)

---

src/borg/archiver.py

borg delete --dry-run

---

src/borg/archiver.py

Addresses https://github.com/borgbackup/borg/issues/3504.
Related to https://github.com/borgbackup/borg/issues/3827.

Clarify --append-only flag

---

src/borg/archiver.py

Forward port of https://github.com/borgbackup/borg/pull/3869

borg prune: improve progress display (fwd port to master)

---

setup.py
src/borg/algorithms/lz4/lib/lz4.c
src/borg/algorithms/lz4/lib/lz4.h

Forward port of https://github.com/borgbackup/borg/pull/3871

update bundled lz4 code (fwd port to master)

---

setup.py

Forward ports https://github.com/borgbackup/borg/pull/3873.

revert to using system compression libs, fixes #3797 (fwd port to master)

---

src/borg/archiver.py

Backport of https://github.com/borgbackup/borg/pull/3893

docs: improve diff doc (backport)

---

scripts/shell_completions/bash/borg
scripts/shell_completions/fish/borg.fish
scripts/shell_completions/zsh/_borg

Backport of https://github.com/borgbackup/borg/pull/3921

Shell completions reflect latest changes (backport)

---

docs/usage_general.rst.inc

Backport of https://github.com/borgbackup/borg/pull/3926

docs: add link to tempfile module (backport)

---

src/borg/testsuite/archiver.py

couldn't reproduce #3494 locally.

trying to debug #3494 on travis

---

src/borg/testsuite/archiver.py

- reordered code a little, so files are touched in different order
let's see if this changes anything.
- create_regular_file: giving size AND contents is not supported
the code did not create a 4096 bytes long file, but just a 1 byte
long file. adding an assertion to avoid unsupported usage.
(cherry picked from commit 2d490aa8c88a56872afb4e173ee552f8d51510a8)

tests: trying to debug test fails on travis, #3494

---

Vagrantfile

the fix that i made in v3.3-fixed is also in official release v3.3.1.

vagrant: use pyinstaller v3.3.1

---

Vagrantfile

freebsd does not like fakeroot (we did not have fakeroot on 1.1-maint on fbsd either).
added the darwin64 machine similar as on 1.1-maint (so maybe still openssl 1.0.x).

vagrant: fix FreeBSD 12, add Darwin

---

src/borg/archive.py

Chunker: give os-level fd only

---

docs/installation.rst

Update installation instructions for macOS

---

docs/installation.rst

Update installation instructions for macOS (1.1 backport)

---

src/borg/helpers/checks.py

the check was not working as intended.
also: updated desired api version.

fix logic bug in platform module API version check

---

src/borg/helpers/checks.py
src/borg/platform/base.py
src/borg/platform/darwin.pyx
src/borg/platform/freebsd.pyx
src/borg/platform/linux.pyx
src/borg/testsuite/xattr.py

it's like we do it everywhere else because this is what we usually need.

xattrs: use follow_symlinks=False as default, more tests

---

src/borg/archiver.py
src/borg/cache.py
src/borg/locking.py

also: clarify docs
(cherry picked from commit 2f3e60d9d50d04dd5f09c7351acbcbba28646f36)

cache lock: use lock_wait everywhere to fix infinite wait (fwd port to master)

---

docs/faq.rst

Backport of #3987 into 1.1-maint

---

docs/usage_general.rst.inc
src/borg/platform/base.py

(cherry picked from commit 90348c1de9103ef867e5ca1cf3ec6a8b3c4bcf71)

add BORG_HOST_ID, fixes #3985

---

src/borg/archiver.py

(cherry picked from commit 4b31ad123fddddd42d9ea411f59ed0d5b89479b2)

init: add warning to store both key and passphrase at safe place(s)

---

src/borg/archive.py
src/borg/helpers.py

(cherry picked from commit d2e2f1b89df9ee5fa63d454c5a2ea0c72cebe362)

call socket.gethostname only once

---

Vagrantfile

vagrant: use python 3.5.6 (1.1-maint)

---

Vagrantfile

the one on vagrantcloud is not very recent...

use own openindiana box

---

docs/usage_general.rst.inc
src/borg/crypto/key.py

Read a passpharase from a file descriptor specified in the
BORG_PASSPHRASE_FD environment variable.

read a passphrase from a file descriptor

---

conftest.py
src/borg/archiver.py
src/borg/helpers.py
src/borg/shellpattern.py
src/borg/testsuite/key.py

misc backports to 1.1-maint

---

src/borg/_endian.h
src/borg/_hashindex.c

Basic MSC Compatibility

---

.travis/install.sh
requirements.d/development.lock.txt
requirements.d/development.txt
tox.ini

unbreak 1.0-maint on travis

---

src/borg/archiver.py

Fixes #3561 as #4157 for 1.1-maint.

Added PATH::archive output for creation function on info log level. Backport to 1.1-maint

---

src/borg/archiver.py

Fixes #4134 
Help text in code has been fixed and appropriate documentation files been rebuilt.

Fixed help string in CRUD documentation.

---

src/borg/helpers.py

(cherry picked from commit 65d8091245afbaf26e81d4e2a54d7101e4e4d0bd)

invalid locations: give err msg containing parsed location, fixes #4179

---

.travis.yml
.travis/install.sh
Vagrantfile
setup.py
src/borg/archiver.py
tox.ini

This reverts commit 55314f807e89d19f50fb4682adca0fb84ab0d1aa.
see #3919.

enable py35 again

---

setup.py

msgpack: also allow version 0.6.0

---

docs/quickstart.rst

* Add an info entry for the compacting step
* Add a final info entry for when no errors occurred

Docs: Improve logging in example automation script

---

src/borg/archiver.py

See https://github.com/borgbackup/borg/issues/4234.

Clarify the necessity to separately backup key in repokey mode

---

.travis/install.sh

https://github.com/Homebrew/brew/pull/5517/files

fix the homebrew 1.9 issues on travis-ci, fixes #4254

---

src/borg/remote.py
src/borg/repository.py

Use f_frsize instead of f_bsize to calculate free space. Fixes #4289

---

docs/faq.rst
docs/man/borg.1
docs/usage_general.rst.inc

Update BORG_PASSCOMMAND example and clarify variable expansion.

---

docs/faq.rst

Add FAQ regarding free disk space check. Fixes #3905

---

src/borg/archiver.py
src/borg/testsuite/archiver.py

Quit with error message when no config key is provided. Fixes #4223

---

src/borg/testsuite/archiver.py

thanks to Anthony Sottile for finding this!

fix duplicate test method name, fixes #4311

---

src/borg/helpers.py
src/borg/platform/base.py
src/borg/platform/darwin.pyx
src/borg/platform/freebsd.pyx
src/borg/platform/linux.pyx

see there:
https://github.com/borgbackup/borg/issues/1961
and especially there (not implemented sync_file_range):
https://github.com/Microsoft/WSL/issues/645

work around some Microsoft WSL issues

---

docs/faq.rst
src/borg/archive.py
src/borg/archiver.py
src/borg/remote.py
src/borg/repository.py
src/borg/testsuite/archiver.py

1.1-maint backports (15)

---

src/borg/archiver.py
src/borg/helpers/checks.py
src/borg/platform/base.py
src/borg/platform/darwin.pyx
src/borg/platform/freebsd.pyx
src/borg/platform/linux.pyx

master forward ports (16)

---

scripts/shell_completions/bash/borg
scripts/shell_completions/fish/borg.fish
scripts/shell_completions/zsh/_borg

Like #4334 but this also includes borg compact.

master - Shell completions.

---

src/borg/algorithms/lz4/lib/lz4.c
src/borg/algorithms/lz4/lib/lz4.h

Update bundled lz4 code to 1.8.3, fixes #4209

---

src/borg/xattr.py

code taken from 1.1-maint.
running as a user, with or without fakeroot does not have the test fails in test_extract_capabilities any more.

re-add the code that checks if we run under fakeroot, fixes #4291

---

LICENSE
docs/conf.py

Happy "new year"! This was done on the maintenance branches but not master.

Update copyright year

---

docs/usage.rst

Only modify window.location when redirecting (1.1 backport)

---

src/borg/archiver.py
src/borg/testsuite/archiver.py

Emit user-friendly error if repo key is exported to a directory

---

Vagrantfile

note:
- openssl 1.1.1 seems to be part of base install
- added zstd compression lib

new freebsd12 64bit vagrant box, fixes #4399

---

docs/installation.rst

docs/installation: added Alpine Linux to distribution list

docs/installation: added Alpine Linux to distribution list (#4414)

---

src/borg/archiver.py

timestamp for borg delete --info added

---

src/borg/lrucache.py
src/borg/repository.py

needs testing, e.g. with davfs.

lrucache: regularly remove old FDs, fixes #4427

---

scripts/shell_completions/bash/borg
scripts/shell_completions/fish/borg.fish
scripts/shell_completions/zsh/_borg

Added shell completions for
```borg diff repo::archive1 archive2```

Shell completions: borg diff second archive

---

docs/misc/logging.conf
docs/usage_general.rst.inc

we discussed this as issue #4376

add a sample logging.conf in docs/misc

---

docs/changes.rst

update CHANGES (master)

---

src/borg/helpers/checks.py
src/borg/platform/base.py
src/borg/platform/darwin.pyx
src/borg/platform/freebsd.pyx
src/borg/platform/linux.pyx
src/borg/testsuite/archiver.py
src/borg/testsuite/xattr.py

freebsd xattr namespace fixes

---

src/borg/archiver.py

borg command shall terminate with rc 2 for ImportErrors, fixes #4424

---

README.rst

fixes #3907 (together with changes on the web site).

README: new URL for funding options

---

src/borg/archive.py
src/borg/archiver.py
src/borg/testsuite/archiver.py

let's see if it always hangs in test 2 now.

slave hardlinks extraction issue, see #4350 (master)

---

src/borg/archiver.py
src/borg/helpers.py

- backport master changeset for --glob-archives
- implement new support for placeholders in comments, #4559

enable placeholder usage at some places

---

src/borg/testsuite/archiver.py

rename fuse based test

---

docs/quickstart.rst
docs/resources.rst

Closes https://github.com/borgbackup/borg/issues/4581.

Add note for software for automating backup docs

---

docs/installation.rst

docs: update macOS Brew link (1.1-maint)

---

setup.py
setup_checksums.py
src/borg/algorithms/checksums.pyx
src/borg/algorithms/xxhash-libselect.h

This should fix issue #4592 . I tested this (briefly) on Fedora 30 and the test suite passes for me.

ability to unbundle xxhash

---

src/borg/archiver.py

Use BORG_REPO

---

docs/usage/notes.rst

Documentation spelling fix, what else to say. :slightly_smiling_face:

Documentation spelling fix

---

Vagrantfile

fixes #2897 
no openssl 1.1 yet in oi.

vagrant: add up-to-date openindiana box (py35, openssl10)

---

docs/installation.rst

Fix osxfuse github link in installation docs (1.1 backport)

---

docs/usage/create.rst

borg create examples within documentation mention 1.1 as a future version of borg.

Update documentation of borg create

---

src/borg/archiver.py

Forward port #4705

---

src/borg/cache.py

Forward port #4646

---

src/borg/repository.py

Forward port #4698

---

docs/faq.rst
docs/usage/notes.rst

doc updates 27, 1.1-maint

---

docs/deployment/central-backup-server.rst
docs/deployment/hosting-repositories.rst
docs/development.rst
docs/faq.rst
docs/installation.rst
docs/quickstart.rst
docs/usage/notes.rst
src/borg/archiver.py

fixes #4692 
These were all occurences I could find, please comment if I missed one :)

Fix various code blocks in the docs

---

docs/quickstart.rst

Link to rendered view:
https://github.com/borgbackup/borg/blob/4e739d0bfb353bd4b60a43a24347eb10b1cc2770/docs/quickstart.rst#restoring-a-backup

add restore docs, fixes #4670

---

docs/quickstart.rst

add restore docs, fixes #4670 (1.1-maint)

---

src/borg/archive.py

Forward port of #4728

---

docs/faq.rst

See #4738 for discussion and rationale

Backport #4738 to 1.1-maint

---

src/borg/archive.py
src/borg/archiver.py
src/borg/helpers/process.py

first ctrl-c: checkpoint and abort, fixes #4606

---

docs/development.rst

Capitalized list items and finished them with a full stop. This was inconsistent.

docs: List items consistency

---

docs/man/borg.1
docs/usage_general.rst.inc

Pretty self-explanatory..
Please tag this with the label `invalid` to disqualify my minor contribution from [Hacktoberfest](https://hacktoberfest.digitalocean.com/faq). And while you're at it, tag some beginner-friendly issues with the label `hacktoberfest` or `good first issue`. :)

Fix typo: degress -> degrees

---

setup.py
src/borg/helpers/msgpack.py

This addresses https://github.com/borgbackup/borg/issues/4360#issuecomment-541860469

Support msgpack-0.6.2.

---

src/borg/archiver.py

Backport from master.
fixes #4118

[DOC] #4118 - Explain difference between --exclude and --pattern

---

docs/faq.rst

Backport from master.
fixes #4532

[DOC] #4532 - Add FAQ how to retain original paths

---

docs/man_intro.rst
setup_docs.py

Now the date is updated every time the page is regenerated.
Refers https://github.com/borgbackup/borg/pull/4789 .

Fix the borg(1) man page creation

---

docs/deployment.rst
docs/deployment/pull-backup.rst

[DOC] #1552 - Add a pull backup / push restore how-to

---

src/borg/remote.py

Have I explained the stuff correctly?

[DOC] #4674 - Add more documentation for @api decorator.

---

src/borg/archive.py
src/borg/archiver.py
src/borg/testsuite/archiver.py

I also added a test to ensure that no regression happens on this feature.
Fixes #4745.

Borg recreate timestamp is a no op

---

Vagrantfile

Fixes https://github.com/borgbackup/borg/issues/4834.

Bump Python 3.5.7 to 3.5.9

---

src/borg/archive.py
src/borg/archiver.py
src/borg/testsuite/archiver.py

Fixes the issue #4745 on 1.1-maint.

Backport #4815 changes to 1.1-maint.

---

src/borg/archiver.py

Backport #4818 to 1.1-maint

---

Vagrantfile

the patch is needed so it works with recent virtualenv.

vagrant: upgrade pyinstaller to v3.5 + patch

---

src/borg/testsuite/archiver.py

Fix the test failing due to timestamp localisation

---

src/borg/archiver.py

Document how to test exclusion patterns without performing an actual backup

---

src/borg/archiver.py

This is the same change as https://github.com/borgbackup/borg/pull/4866
@ThomasWaldmann

Elaborate on "Calculating size" message

---

docs/faq.rst

Taken from a Q/A on the mailing list.

Add FAQ describing difference between a local repo vs. repo on a server.

---

docs/faq.rst
docs/usage_general.rst.inc

Backport: Add paragraph regarding cache security assumptions #4900

---

src/borg/archiver.py

less pretty IMHO than before, though.

make the pep8 checker happy

---

docs/usage_general.rst.inc

Backport of #4919 Update usage_general.rst.inc

---

docs/internals/frontends.rst
src/borg/archive.py
src/borg/upgrader.py

fix ProgressIndicator msgids, fixes #4935

---

.travis.yml

Backport: Allow osx builds to fail #4955

---

docs/internals/frontends.rst
src/borg/archive.py
src/borg/upgrader.py

fix ProgressIndicator msgids, fixes #4935 (master)

---

.gitignore

Ignore syncfilerange.c

---

docs/changes.rst

fix changes.rst markup

---

src/borg/repository.py

if an old hints file gets converted to the new format and it has entries referring to non-existent segment files, a crash occurred.
with this code, the crash is avoided and the erroneous hints entry is removed.

fix crash when upgrading erroneous hints file, fixes #4922

---

docs/changes.rst

pre-1.1.11 advisory
changelogs of 1.1.10 and 1.1.11

update changes.rst from 1.1-maint branch, fixes #5006

---

docs/development.rst

Add updating borgbackup.org/releases to release checklist

---

docs/internals/frontends.rst

Suppress Sphinx lexer warnings in frontends.rst (1.1 backport)

---

docs/faq.rst
docs/usage_general.rst.inc

[DOCS] #4941 – How important is Borg config?

---

docs/faq.rst
docs/usage_general.rst.inc

[DOCS] #4941 – FAQ Borg config dir

---

src/borg/compress.pyx

Based on the comments in PR #4683, as a micro-optimization, do not instantiate LZ4 and none compressors on each instantiation of the auto compressor, but use global instances instead.

Optimize compressor instantiation

---

README.rst

Backport of #5051 Fix typos

---

docs/development.rst

Add a line regarding checking the markup.

[DOCS] #5000 – Add rendering docs to release todo

---

docs/faq.rst

Add new FAQ entry that lists two ways how to really delete files from archives.
fixes #2929

[DOCS] #2929 – Document how to completely delete data

---

docs/usage/general/environment.rst.inc
src/borg/helpers/fs.py

re-applied #4951 to current master.

Update prevalence of env vars to set config and cache paths

---

.travis.yml
.travis/install.sh

Backport of #4987 Adding comments and explanations to Travis config and install script, improving OS X builds

---

docs/usage/general/environment.rst.inc
src/borg/helpers.py

Backport of #5066 Update prevalence of env vars to set config and cache paths

---

src/borg/archiver.py
src/borg/helpers/manifest.py
src/borg/testsuite/archiver.py

Took a cue from #4835 
For issue #4788

Issue #4788 added consider checkpoints and relative test

---

src/borg/fuse.py

Fix FUSE low linear read speed on large files

---

src/borg/fuse.py

This patch is a quick fix for an inefficient seek algorithm used in read() function:
1) On each read call chunk list for given file is regenerated.
2) Finding needed chunk takes a lot of time for large offsets.
For 64 Gb files read speed drops to 16 MB/s, for 128 Gb - to 8 MB/s, and so on.
After applying this patch read speed becomes 270 MB/s, and does not depend on read position inside file.
Co-authored-by: Thomas Waldmann <tw@waldmann-edv.de>

Fix FUSE low linear read speed on large files, fixes #5067

---

docs/faq.rst
docs/internals/security.rst
docs/quickstart.rst

Improve the consistency of multi-client issues with same repository.
fixes #4883

[DOCS] #4883 – Doc downplays severity of Nonce reuse issue

---

docs/deployment/hosting-repositories.rst
docs/faq.rst

docs: linked recommended restrictions to ssh public keys on borg servers in faq, #4946

---

Vagrantfile

vagrant fixes (fwd port to master)

---

src/borg/helpers.py

Backport of #5100 Allow message for Error base class

---

src/borg/fuse.py

FUSE micro opt, removal of unneeded code

---

src/borg/testsuite/__init__.py

Port of #5112 Fix tests of read-only repos for non-root users

---

src/borg/helpers/parseformat.py
src/borg/testsuite/__init__.py

Accept windows style path's as repo locations.
This PR is fixing #4732

Accept absolute paths on windows

---

docs/installation.rst

[DOC] Add upgrade of tools to pip installation how-to

---

src/borg/archiver.py

Add a section that explains storage of relative paths and how patterns can be used arbitrarily since Borg 1.2.

[DOCS] Add note about patterns and stored paths, #4160

---

src/borg/testsuite/__init__.py

Fix testing of unsuccessful mount

---

src/borg/testsuite/__init__.py

Backport of #5141 Fix testing of unsuccessful mount

---

src/borg/testsuite/__init__.py

Fix read-only tests for fakeroot environment

---

src/borg/testsuite/__init__.py

Backport of #5148 Fix read-only tests for fakeroot environment

---

docs/usage/init.rst
src/borg/archiver.py

this is basically re-doing #4269 - thanks to @chrisrapson for the feedback!

docs: clarify borg init's encryption modes

---

src/borg/archive.py

The locally defined preload() function overwrites the preload boolean keyword
argument, always evaluating to true, so preloading is done, even when not
requested by the caller, causing a memory leak.
Also move its definition outside of the loop.
This issue was found by Antonio Larrosa in borg issue #5202.

rename local preload() function to not overwrite keyword argument of same name

---

docs/faq.rst

Trying to fix #4884 
I'm listening to any problem that you guys may have on the doc, but please limit yourselves.

docs: explain hash collision

---

Vagrantfile

the old box was not functional any more and too old.

use same darwin box / provisioning as master branch

---

docs/changes.rst

only change here will be to rebuild with current Cython release and do another round of testing...
fixes #5214.

release 1.1.13

---

src/borg/archive.py
src/borg/testsuite/archiver.py

hardlinked CACHEDIR.TAG issue

---

src/borg/archiver.py

docs: clarify --exclude-if-present in recreate, #5193

---

src/borg/archiver.py
src/borg/constants.py

exit with 128 + signal number, fixes #5161

---

docs/faq.rst
docs/internals/data-structures.rst
docs/man/borg.1
docs/usage/general/file-systems.rst.inc
src/borg/locking.py
src/borg/testsuite/locking.py

Fixed locking, issue #4923

---

src/borg/archiver.py
src/borg/helpers/msgpack.py
src/borg/remote.py

... and get rid of problematic blacklist/whitelist wording.

use allow/deny list wording

---

src/borg/fuse.py
src/borg/helpers/process.py
src/borg/testsuite/__init__.py
src/borg/testsuite/archiver.py

Fixed lock migration, issue #4953

---

src/borg/archiver.py

docs: add a note to create from stdin regarding files cache, fixes #5180

---

src/borg/repository.py
src/borg/testsuite/repository.py

in borg 1.1, compact_segments() was always run directly after some repo writing operation (in same borg process).
but now, only "borg compact" is used to compact segments and it is a separate borg invocation (new process), so we need to persist the shadow_index so we do not lose that information.

persist shadow_index in between borg runs, fixes #4830

---

docs/faq.rst
docs/internals/security.rst

Backport from master. I took over also the referencing faq's changes in its first paragraph after adding the reference.

docs: add security faq explaining AES-CTR crypto issues, fixes #5254

---

src/borg/archiver.py

docs: point to borg create --list item flags in recreate usage, fixes #5165

---

scripts/shell_completions/zsh/_borg

Rewrite Zsh completion for 1.1-maint.

---

docs/installation.rst

Update Homebrew install instructions. See #5185

---

src/borg/repository.py

check --repair: fix potential data loss (master)

---

docs/internals/frontends.rst
docs/usage/general/environment.rst.inc
src/borg/archiver.py
src/borg/testsuite/archiver.py

Not experimental 1.1

---

src/borg/archive.py

prettier error message when archive gets too big, fixes #5307

---

Vagrantfile
scripts/borg.exe.spec

Build directory-based binary for macOS to avoid Gatekeeper delays

---

scripts/shell_completions/zsh/_borg

Namely:
- add tags to all untagged contexts;
- don't leak $debug_commands;
- plus some cosmetic changes.

Fix a few issues in zsh completion

---

src/borg/selftest.py

if self test fails, also point to OS and hardware, fixes #5334

---

.travis.yml

there was a fixed llfuse release today, so lets try it!

try llfuse on py39

---

docs/faq.rst
src/borg/archiver.py

also: give a speed example for unchanged files
also: explicitly mention chmod/chown changing ctime
also: reformat one paragraph

docs: how to approach borg speed issues, fixes #5371

---

.travis.yml
.travis/install.sh
Vagrantfile
requirements.d/fuse.txt
setup.py
tox.ini

Includes PRs: https://github.com/borgbackup/borg/pull/5373 https://github.com/borgbackup/borg/pull/5379 
It also includes this specific commit https://github.com/borgbackup/borg/commit/7dc161067498703dca27b6e2437548a9cc4d981b

add python3.9 testing and related llfuse changes (backport to 1.1-maint)

---

src/borg/algorithms/msgpack/_packer.pyx
src/borg/algorithms/msgpack/_unpacker.pyx
src/borg/platform/syncfilerange.pyx

set cython language_level

---

docs/quickstart.rst

fix small typo in quickstart docs

---

docs/usage/list.rst

This pull request addresses #5176 
it is just a simple contribution that i find useful myself.

add example for excluding content using the --pattern cmd line arg

---

docs/usage/list.rst

https://github.com/borgbackup/borg/pull/5456#issuecomment-718246791

add example for excluding content using the --pattern cmd line arg (1.1-maint backport)

---

src/borg/archiver.py

fix --dry-run and --stats coexistence

---

docs/faq.rst
src/borg/archiver.py

docs: how to approach borg speed issues (forward port)

---

docs/development.rst

Add some documentation for new compression algorithm

---

AUTHORS

As discussed in query on IRC with @ThomasWaldmann I added myself in the authors of borg.

Add myself as an author with permission of TW

---

docs/installation.rst

Note requirement for full disk access on Catalina

5303 osx catalina security

---

docs/usage/general/environment.rst.inc
src/borg/cache.py

[1.1] Allow appending the files cache filename with BORG_FILES_CACHE_SUFFIX env var

---

src/borg/archiver.py

Complements the documentation for pattern files and exclude files

---

src/borg/repository.py

Backport of https://github.com/borgbackup/borg/pull/5463

[1.1] Allow EIO with warning when trying to hardlink

---

src/borg/testsuite/hashindex.py

for the bug, see #4829.
forward port to master.

add a test for the hashindex corruption bug, fixes #5531

---

docs/faq.rst

Add a hint on sleeping computer in the FAQ, fixes #5301 [1.1]

---

docs/development.rst

Add some documentation for new compression algorithm, see #1633 [1.1]

---

MANIFEST.in
README.rst
docs/development.rst

Closes https://github.com/borgbackup/borg/issues/5528

Change references of Travis to GitHub Actions

---

.github/workflows/ci.yml

It hasn't been running for a month https://app.codecov.io/gh/borgbackup/borg/commits?page=1

Upload coverage reports to codecov, fix macOS tests

---

src/borg/archiver.py

Backporting #5520 to 1.1-maint

Complements the documentation for pattern files and exclude files, fixes #5236 [1.1]

---

.github/workflows/ci.yml

Backport of https://github.com/borgbackup/borg/pull/5537

Upload coverage reports to codecov, fix caskroom [1.1]

---

MANIFEST.in
README.rst
docs/development.rst

Backport of https://github.com/borgbackup/borg/pull/5536

Change references of Travis to GitHub Actions (#5536) [1.1]

---

src/borg/item.pyx

Backport of https://github.com/borgbackup/borg/pull/5496
I may have broken the metadata.

PropDict: fail early if internal_dict is not a dict [1.1]

---

Vagrantfile

vagrant: add fuse2/fuse3 for archlinux box

---

.github/workflows/ci.yml

add a timeout for the github CI jobs, fixes #5548 [1.1]

---

docs/usage/delete.rst
docs/usage/delete.rst.inc
src/borg/archiver.py

Also add some documentation on this.
Fixes #5116.

Add a --list switch to borg delete

---

src/borg/archive.py

Add repo location to the stats in borg create

---

src/borg/archive.py
src/borg/archiver.py

found the leak, see last commit.

fix memory leak in export-tar with ssh: repo

---

src/borg/archive.py
src/borg/archiver.py

fix memory leak in export-tar with ssh: repo (fwd port to master)

---

Vagrantfile

brew cask install ... is deprecated.

use brew install --cask ..., fixes #5557

---

src/borg/repository.py

check: debug log segment filename

---

docs/installation.rst

Add badge with current status of package

---

docs/faq.rst

fix grammar in faq

---

docs/faq.rst

fix grammar in faq 1.1-maint port

---

docs/development.rst
docs/installation.rst

Port of https://github.com/borgbackup/borg/pull/5643 to 1.1-maint.

Update docs for dev environment installation instructions #5643 1.1-maint port

---

src/borg/archiver.py

backport of #5662 
note: 1.1-maint does not save shadow_index into hints.

implement borg debug dump-hints

---

setup.py
src/borg/helpers/msgpack.py

exclude 1.0.1 though, which had some issues (not sure whether they affect borg).

also accept msgpack up to 1.0.2

---

src/borg/repository.py

A) the compaction code needs the shadow index only for this case:
segment A: PUT x, segment B: DEL x, with A < B  (DEL shadows the PUT).
B) for the following case, we have no shadowing DEL (or rather: it does not matter,
because there is a PUT right after the DEL) and x is in the repo index,
thus the shadow_index is not needed for the special case in the compaction code:
segment A: PUT x, segment B: DEL x PUT x
see also PR #5636.
reverts f079a83fed91c1221951303f758187987be0ac47
and clarifies the code by more comments.
we keep the code deduplication of 5f32b5666af961f5256221660a7356d467f66605
and just add a update_shadow_index param to make it not look like there was
something accidentally forgotten, which was the whole reason for the reverted
"fix".

revert incorrect fix for put updating shadow_index, fixes #5661

---

docs/installation.rst

See https://github.com/borgbackup/borg/issues/5622#issuecomment-776235155

Recommend download via CLI on macOS

---

docs/installation.rst

Update macOS install instructions (Backport to 1.1-maint)

---

src/borg/archiver.py
src/borg/testsuite/archiver.py

do not recurse into duplicate roots, fixes #5603 (1.1-maint)

---

docs/installation.rst

See comment https://github.com/borgbackup/borg/issues/5660#issuecomment-778704981

Add short note on pointing setup.py to openssl on macOS

---

docs/installation.rst
setup.py

Apply dependency updates to 1.1-maint.
See https://github.com/borgbackup/borg/issues/5660#issuecomment-782998024

Apple M1 compatibility

---

src/borg/archiver.py
src/borg/repository.py

Repo config nonint values (1.1)

---

src/borg/archiver.py
src/borg/repository.py

Repo config nonint values (master)

---

src/borg/archive.py
src/borg/cache.py
src/borg/testsuite/cache.py

verbose files cache logging via --debug-topic=files_cache, fixes #5659

---

.github/workflows/ci.yml
setup.py
tox.ini

fwd port of the py310 testing part of #5684.

add support and testing for python 3.10

---

docs/internals/frontends.rst
docs/usage/diff.rst
src/borg/archiver.py
src/borg/testsuite/archiver.py

add --json-lines option to diff command

---

src/borg/archive.py
src/borg/archiver.py
src/borg/fuse.py
src/borg/item.pyx
src/borg/platform/base.py
src/borg/platform/darwin.pyx
src/borg/platform/freebsd.pyx
src/borg/platform/linux.pyx
src/borg/testsuite/platform.py

--numeric-ids

---

src/borg/archiver.py
src/borg/remote.py

--remote-* option names deprecation

---

docs/faq.rst

docs: add unsafe workaround to use an old repo copy, fixes #5722

---

src/borg/helpers.py

Fixes BORG_CACHE_DIR crashing borg if empty, fixes #5216

---

.github/workflows/ci.yml
setup.py
src/borg/__init__.py
src/borg/xattr.py

get rid of distutils, using packaging

---

src/borg/archive.py

This is a back-port attempt of #5778. It is intended to be part of issue #5838.

missing / healed chunks: always tell chunk ID, fixes #5704

---

src/borg/archiver.py

This is a back-port attempt of #5520. It is intended to be part of issue #5837.

Complements the documentation for pattern files and exclude files (#5520)

---

docs/usage/check.rst.inc

This should close #5753 and count towards completion of #5129.

add notice about defective hardware to check documentation (#5753)

---

docs/usage/check.rst.inc
src/borg/archiver.py

This is the back-port of #5860 for #5129.

resolve clarify borg check --verify-data (#5808)

---

docs/faq.rst

Fixes: https://github.com/borgbackup/borg/issues/5240

docs: add info on renaming repositories

---

docs/faq.rst

Includes changes from https://github.com/borgbackup/borg/pull/5866

docs: add info on renaming repositories (#5866)

---

docs/usage/general/environment.rst.inc
src/borg/selftest.py
src/borg/testsuite/archiver.py

on my laptop, this saved ~100ms cpu time (sys+user) per borg command invocation.

implement BORG_SELFTEST env variable, fixes #5871

---

docs/usage/general/environment.rst.inc
src/borg/selftest.py
src/borg/testsuite/archiver.py

Forward implement BORG_SELFTEST env variable (#5873)

---

src/borg/archiver.py

Docs backport to 1.1-maint

---

src/borg/helpers.py

Allow --files-cache=size

---

docs/faq.rst

fixes #5885
Waiting for a second backport.

Backport master to 1.1-maint (#5880)

---

src/borg/archiver.py

benchmark: make sure cleanup happens even on exceptions, fixes #5630

---

Vagrantfile

vagrant: fix install_pyenv

---

docs/deployment/pull-backup.rst

Forwardport pull request #5902

---

docs/usage/list.rst
src/borg/archiver.py

Includes changes for #5958 #5959

Backport documentation changes

---

.github/workflows/ci.yml
Vagrantfile
docs/development.rst
setup.py
src/borg/helpers/misc.py
tox.ini

if you do not have py38+ yet, just use borg 1.1.x.

require python 3.8+, fixes #5975

---

src/borg/archive.py

due to this, hardlink master preloading code was broken for non-regular files

fix hardlinkable file type check, fixes #6037

---

src/borg/testsuite/archiver.py

Backport two tests for xattr warnings

---

docs/deployment/hosting-repositories.rst
docs/usage/serve.rst

borg serve: improve ssh forced commands docs

---

src/borg/archiver.py
src/borg/helpers.py

You have requested a backport of #6080

Backport: Improve docs for borg list --format (#6080)

---

docs/deployment/hosting-repositories.rst
docs/usage/serve.rst

Backport #6083: borg serve: improve ssh forced commands docs

Backport #6083: borg serve: improve ssh forced commands docs

---

docs/usage/general/environment.rst.inc
src/borg/helpers/fs.py

Fixes #6024 for master. Similar to patch #6027 for maint-1.1 submitted previously.

Workaround for volume shadow copy in WSL1

---

Vagrantfile
setup.py

use "beta", fixes #6128 
use py 3.9.10

some minor updates (master)

---

src/borg/helpers.py

This is a backport of #6117
Fixes #6082

Backport: remove support for shake_* hashes

---

scripts/shell_completions/zsh/_borg
src/borg/helpers/parseformat.py

Analogous to #4184
Do I have to rebuild docs manually?

list: Add command_line to format keys

---

scripts/shell_completions/zsh/_borg
src/borg/helpers.py

Backport: list: Add command_line to format keys

---

src/borg/algorithms/xxh64/xxhash.h

somehow this is way less weird than in 1.1-maint, so there is nothing left to do besides the xxh 0.8.0 -> 0.8.1 upgrade.

fix xxh64 related build (master)

---

LICENSE
docs/conf.py

This is a backport of https://github.com/borgbackup/borg/pull/6129

Backport: it's 2022

---

docs/faq.rst

Backport: clarify who starts the remote agent

---

src/borg/archiver.py

Backport https://github.com/borgbackup/borg/pull/6006

Backport: docs: add note about GFS (#6006)

---

docs/quickstart.rst

This is a backport of https://github.com/borgbackup/borg/pull/5490

Backport: minor rewrite to make it less confusing (get rid of "Avoid to create a mixup")

---

src/borg/helpers.py
src/borg/platform/base.py

Backport atomically create the CACHE_TAG file, see #6028 (#6056)

---

Vagrantfile

Backport vagrant fixes (#6167)

---

src/borg/testsuite/archiver.py

Refactor: move a test to ArchiverTestCase

---

src/borg/archiver.py

it will neither show the archives list and ask for confirmation NOR it will ask for a passphrase in case of an encrypted repo.

delete --force: do not ask when deleting a repo, fixes #5941

---

src/borg/archiver.py

delete: don't commit if nothing was deleted, avoid cache sync, fixes #6060

---

Vagrantfile

Vagrant updates

---

docs/installation.rst

Cygwin package updates

---

docs/usage/mount.rst
src/borg/archiver.py

docs updates about features not experimental any more (1.1)

---

src/borg/archiver.py
src/borg/helpers/parseformat.py
src/borg/remote.py
src/borg/testsuite/helpers.py
src/borg/testsuite/key.py
src/borg/testsuite/repository.py

repo::archive location placeholder expansion fixes (master)

---

src/borg/archiver.py

Backport: Doc: borg key export: add examples

---

requirements.d/development.txt

setuptools 60.7.0 is incompatible with pyinstaller

---

src/borg/testsuite/archiver.py

https://github.com/borgbackup/borg/pull/6046 neglected to add a regression test

Test: borg init refuses to overwrite keyfile

---

docs/faq.rst
src/borg/testsuite/archiver.py

This is a backport of #6188
Since #6188 includes a small refactoring of tests this backport also includes it

Backport: Doc: impact of deleting path/to/repo/nonce

---

src/borg/archiver.py

Backport: diff: reduce memory consumption, fix is_hardlink_master

---

src/borg/archiver.py

Backport: Doc: borg init: explain the encryption modes better

---

src/borg/testsuite/helpers.py

I am going to backport #6301, but first I'll gift you a test for it.

Write a test for safe_unlink

---

src/borg/archiver.py

Backport:  improve linking inside docs 

---

src/borg/hashindex.pyx
src/borg/testsuite/hashindex.py

Backport: implement more standard hashindex.setdefault behaviour

---

src/borg/helpers.py
src/borg/platform/base.py
src/borg/platform/linux.pyx

* This PR depends on #6312
* This is a backport of: #6306

Backport: SaveFile: fix race conditions

---

Vagrantfile

vagrant: add ubuntu "jammy" 22.04 LTS VM

---

docs/conf.py

docs: do not transform --/--- to unicode dashes (1.1)

---

docs/conf.py

* This is a forward port of #6348

docs: do not transform --/--- to unicode dashes (master)

---

setup.py
src/borg/helpers/msgpack.py

Require msgpack 1.0.3

---

docs/installation.rst
src/borg/crypto/_crypto_helpers.c
src/borg/crypto/_crypto_helpers.h
src/borg/crypto/low_level.pyx
src/borg/testsuite/crypto.py

drop openssl 1.0.x support

---

src/borg/archiver.py

create: skip with warning if opening the parent dir of recursion root fails, fixes #6374

---

src/borg/archive.py
src/borg/helpers/process.py

Forward port: import-tar fixes

---

docs/faq.rst

Extend FAQ by adding answer from https://github.com/borgbackup/borg/discussions/6304 and note on file attrs.
Fixes #6305

Add discussion and note on file attrs.

---

src/borg/helpers/fs.py
src/borg/platform/base.py

respect umask for files / dirs (master)

---

setup.py

* This is a backport of https://github.com/borgbackup/borg/pull/6428
Conflicts:
setup.py

1.2: Allow extra compiler flags for every extension build

---

docs/deployment/pull-backup.rst

replace flag --numeric-owner with --numeric-ids

use --numeric-ids in pull doc

---

docs/deployment/pull-backup.rst

1.2: use --numeric-ids in pull doc

---

setup.py

* This is a backport of https://github.com/borgbackup/borg/pull/6428
Note: I had to resort to manually replicating the changes beacsuse setup.py had undergone a refactoring that was not backported

1.1: Allow extra compiler flags for every extension build

---

src/borg/archiver.py
src/borg/constants.py
src/borg/crypto/key.py
src/borg/helpers/passphrase.py
src/borg/repository.py
src/borg/testsuite/archiver.py
src/borg/testsuite/helpers.py
src/borg/testsuite/key.py

working on #2153, best is to review the single commits.
couldn't resist to move the passphrase-getting code out of key.py, because it didn't really fit in there and always was in the way.

borg key change-location, cleanups

---

src/borg/archiver.py

borg benchmark cpu: display benchmarks of cpu bound stuff

---

Vagrantfile

also: some stuff has pkg-config support now, remove env vars.

vagrant: use generic/freebsd13, FUSE fixes

---

src/borg/archiver.py

1.2-maint backport: delete: add repository id and location to prompt

---

src/borg/archiver.py

This is a backport of #6455.
The uses of f-strings in the original PR were changed to .format, as 1.1-maint does not seem to use f-strings anywhere.

1.1-maint backport: delete: add repository id and location to prompt

---

src/borg/archive.py
src/borg/archiver.py
src/borg/testsuite/archiver.py

import/export-tar: PAX format, ctime and atime support

---

src/borg/archive.py

OpenBSD does not have `lchmod()` causing `os.lchmod` to be unavailable
on this platform. As a result ArchiverTestCase::test_basic_functionality
fails when run manually (#2055).
OpenBSD does have `fchmodat()`, which has a flag that makes it behave
like `lchmod()`. In Python this can be used via `os.chmod(path, mode,
follow_symlinks=False)`.
As of Python 3.3 `os.lchmod(path, mode)` is equivalent to
`os.chmod(path, mode, follow_symlinks=False)`. As such, switching to the
latter is preferred as it enables more platforms to do the right thing.

1.2 - fix OpenBSD symlink mode test failure (#2055)

---

src/borg/archive.py

OpenBSD does not have `lchmod()` causing `os.lchmod` to be unavailable
on this platform. As a result ArchiverTestCase::test_basic_functionality
fails when run manually (#2055).
OpenBSD does have `fchmodat()`, which has a flag that makes it behave
like `lchmod()`. In Python this can be used via `os.chmod(path, mode,
follow_symlinks=False)`.
As of Python 3.3 `os.lchmod(path, mode)` is equivalent to
`os.chmod(path, mode, follow_symlinks=False)`. As such, switching to the
latter is preferred as it enables more platforms to do the right thing.

Fix OpenBSD symlink mode test failure (#2055)

---

docs/internals/data-structures.rst
src/borg/constants.py
src/borg/repository.py
src/borg/testsuite/repository.py

repository v2

---

docs/faq.rst

Already merged into master (#6524), requesting to merge to 1.2-maint as discussed on that PR.

(docs) 1.2: Recommend umask for passphrase file perms

---

docs/faq.rst

Already merged into master (#6524), requesting to merge to 1.1-maint as discussed on that PR.

(docs) 1.1: Recommend umask for passphrase file perms

---

src/borg/archiver.py
src/borg/crypto/key.py
src/borg/helpers/passphrase.py
src/borg/testsuite/crypto.py

Closes #6449
@ThomasWaldmann, is this what you had in mind? If so, I'll migrate argon2 the same way.

Move the key derivation code from helpers.Passphrase to crypto.FlexiKey

---

src/borg/archive.py

borg check improvements (1.1)

---

src/borg/archiver.py

docs: improve borg check --max-duration description

---

src/borg/item.pyx

diff: support presence change for blkdev, chrdev and fifo items (1.2-maint)

---

src/borg/cache.py

fix transaction rollback: use files cache filename as found in txn.active

---

src/borg/constants.py
src/borg/helpers.py

do not load files cache for commands not using it, fixes #5673

---

docs/faq.rst

* Should fix https://github.com/borgbackup/borg/issues/6562
* Bounty: https://github.com/borgbackup/borg/issues/6398

[1.2] Add a troubleshooting note to the FAQ

---

docs/faq.rst

* Should fix https://github.com/borgbackup/borg/issues/6562
* Bounty: https://github.com/borgbackup/borg/issues/6398
* See also https://github.com/borgbackup/borg/pull/6645

[1.1] Add a troubleshooting note to the FAQ

---

src/borg/crypto/key.py

give a more helpful error msg for unsupported encrypted key format

---

src/borg/cache.py
src/borg/crypto/key.py

the api already offered getting compressed data,
but not giving compressed data.
thus: cache.add_chunk and key.encrypt improved.

api: enable giving already compressed data

---

docs/faq.rst

docs: mention BORG_FILES_CACHE_SUFFIX as alternative to BORG_FILES_CACHE_TTL

---

docs/changes.rst
docs/faq.rst
docs/internals/frontends.rst
setup.cfg
src/borg/compress.pyx
src/borg/testsuite/archiver.py

Backport of #6688 to 1.1-maint

Backport Fix typos (#6688)

---

docs/changes.rst
docs/deployment/automated-local.rst
docs/deployment/pull-backup.rst
docs/faq.rst
docs/quickstart.rst
docs/usage/create.rst
src/borg/archiver.py

Remove leading slashes in examples. Replace paragraph describing pattern behaviour change in 1.2.
fixes #6407

#6407 - Document Borg 1.2 pattern behavior change

---

src/borg/archiver.py
src/borg/repository.py

Forwardport: borg debug dump-repo-objs --ghost (#6722)

---

src/borg/archiver.py
src/borg/cache.py
src/borg/constants.py

Backport of #6724 to 1.1-maint

Backport make constants for files cache mode more clear (#6724, 1.1)

---

docs/faq.rst

[DOCS] #4776 - FAQ: How to swap backup media

---

docs/installation.rst

Correct shell syntax for installation using git

---

setup.cfg

Closes #6727
See: https://github.com/pypa/setuptools/pull/2620

Use license_files instead of license_file

---

src/borg/platform/base.py

some filesystems do not support chmod, just ignore if it is failing.

SaveFile: the chmod is optional, fixes #6786

---

src/borg/archive.py
src/borg/archiver.py

The glob can also match precisely one archive,
so this does the same with less code.

borg check: remove --name, better use -a

---

src/borg/archiver.py

[DOCS] #6572 - Document FUSE limitations better

---

docs/faq.rst
docs/quickstart.rst
docs/usage/delete.rst
docs/usage/prune.rst
src/borg/archiver.py
src/borg/helpers/manifest.py
src/borg/testsuite/archiver.py

-a (aka --glob-archives) can be used for same purpose and is more powerful.

remove -P (aka --prefix) option, fixes #6806

---

src/borg/archiver.py

users will have to edit their scripts / wrappers anyway, so it's a good time to remove deprecated stuff also.

remove deprecated stuff

---

src/borg/cache.py

remove legacy_cleanup

---

docs/internals/frontends.rst

docs: update archive_progress json description about "finished"

---

docs/installation.rst

docs: add info on man page installation

---

src/borg/archive.py

the old code did just 1 attempt to detect the repo decryption key.
if the first chunkid we got from the chunks hashtable iterator was accidentally
the id of the chunk we intentionally corrupted in test_delete_double_force,
setup of the key failed and that made the test crash.
in practice, this could of course also happen if chunks are corrupted, thus
we now do many retries with other chunks before giving up.
error handling was improved: do not return None (instead of a key), it just
leads to weird crashes elsewhere, but fail early with IntegrityError and a
reasonable error msg.
rename method to make_key to avoid confusion with borg.crypto.key.identify_key.

check: try harder to create the key, fixes #5719

---

src/borg/archiver/__init__.py
src/borg/archiver/delete.py
src/borg/archiver/prune.py

fixes #6284
manifest, repo and cache are committed every checkpoint interval.
also, when ctrl-c is pressed, finish deleting the current archive, commit and then terminate.

prune/delete --checkpoint-interval=1800 and ctrl-c/SIGINT support

---

src/borg/archiver/rcreate.py
src/borg/crypto/key.py

default: create new, random authenticated encryption key.

rcreate --copy-ae-key: copy AE key from key of other repo, fixes #6710

---

src/borg/helpers/fs.py
src/borg/platform/base.py

hopefully this is the final fix.
after first fixing of #6400 (by using os.umask after mkstemp), there
was a new problem that chmod was not supported on some fs.
even after fixing that, there were other issues, see the ACLs issue
documented in #6933.
the root cause of all this is tempfile.mkstemp internally using a
very secure, but hardcoded and for our use case problematic mode
of 0o600.
mkstemp_mode (mosty copy&paste from python stdlib tempfile module +
"black" formatting applied) supports giving the mode via the api,
that is the only change needed.
slightly dirty due to the _xxx imports from tempfile, but hopefully
this will be supported in some future python version.

use a custom mkstemp with mode support, fixes #6933, fixes #6400

---

src/borg/repository.py

Forwardport: repository: add debug logging for issue (#6918)

---

setup.py

avoid triggering the pep8 checker.

_version.py: remove trailing blank, add LF at EOF

---

src/borg/archive.py
src/borg/testsuite/archiver.py
src/borg/xattr.py

xattrs / extended stat: improve exception handling (1.2-maint)

---

src/borg/archive.py
src/borg/testsuite/archiver.py
src/borg/xattr.py

forward port of #6990
The different quotes in both branches made some trouble but should be fine now.

xattrs / extended stat: improve exception handling (master)

---

setup.py

Avoid conflicting with shared libcrypto from the base OS pulled in via dependencies.

OpenBSD only - statically link OpenSSL (#6474)

---

src/borg/archive.py
src/borg/helpers/parseformat.py
src/borg/platform/darwin.pyx
src/borg/platform/freebsd.pyx
src/borg/platform/linux.pyx
src/borg/platform/posix.pyx
src/borg/upgrade.py

metadata: differentiate between empty/zero and unknown

---

src/borg/repository.py

start_offset (from state) is only valid for start_segment, otherwise we must use 0.

repository.scan: fix start_offset

---

src/borg/compress.pyx

fixes:
https://github.com/borgbackup/borg/discussions/7020#discussioncomment-3741024

avoid memoryview related TypeError in compressors

---

src/borg/archive.py
src/borg/testsuite/archiver/recreate_cmd.py

get_chunker: fix missing sparse=False argument, fixes #7056

---

src/borg/testsuite/archiver/create_cmd.py

I will fix test_chunking_time in this pr.
Since I can't see the test failing anywhere I don't really know what the error is. My guess is that the execution of the test is too fast, so I gave the test file more info.
I hope the CI here can clarify the issue.

Fix test_chunking_time

---

src/borg/crypto/file_integrity.py
src/borg/repository.py
src/borg/testsuite/repository.py

backport of #7141.
Not because we want to support windows here, but rather for more cleanly working with files.

Fix repository tests 1.2

---

.github/workflows/ci.yml
Vagrantfile

update python 3.9 and 3.11

---

src/borg/archive.py
src/borg/archiver.py

Fix nfiles 1.2

---

src/borg/archiver/create_cmd.py
src/borg/archiver/debug_cmd.py
src/borg/archiver/diff_cmd.py
src/borg/archiver/extract_cmd.py
src/borg/archiver/list_cmd.py
src/borg/archiver/recreate_cmd.py
src/borg/archiver/rename_cmd.py
src/borg/archiver/tar_cmds.py
src/borg/archiver/transfer_cmd.py
src/borg/helpers/__init__.py
src/borg/helpers/parseformat.py
src/borg/testsuite/helpers.py

also: simplify, reuse code from text_validator.

use archivename_validator everywhere

---

.github/workflows/ci.yml
.github/workflows/codeql-analysis.yml

GitHub actions updates (1.2-maint)

---

.github/workflows/black.yaml
.github/workflows/ci.yml
.github/workflows/codeql-analysis.yml

GitHub actions updates (master)

---

src/borg/archiver/rinfo_cmd.py

Added the `--iec` option and also a \n that I forgot to add in my previous pr.
Issue: #6606
Previous pr: #7121

Fix query quota

---

docs/usage/general/environment.rst.inc

the code now uses hashlib.blake2b from python stdlib.

remove BORG_LIBB2_PREFIX (not used any more)

---

scripts/shell_completions/bash/borg

The bash completion file references commands (e.g. init) and options (e.g. --prefix) that do no longer exist.
See #7011.

update bash completion script commands and options

---

src/borg/archiver/prune_cmd.py

guess this fixes issues like #5535.
i tested this with TZ=:
- UTC
- UTC+1 (my current local timezone)
- UTC+12
- UTC-12
- UTC+14

prune: compute pruning in utc timezone

---

src/borg/locking.py
src/borg/testsuite/locking.py

cherry-pick some not win32-related bug fixes from #7264.

Fix locking (1.2-maint)

---

src/borg/helpers/parseformat.py

hostname / username encoding

---

src/borg/manifest.py
src/borg/testsuite/archiver/rlist_cmd.py

Modified list_considering's call to list to support date based matching for #7296 
---
- Passing date-based matching args to list function
- Created a test function that utilizes rlist to test list_considering's support

Added date-matching support for list_considering

---

.coafile

it's not always happy with what black does.

coala: remove PEP8Bear

---

scripts/borg.exe.spec

pyinstaller: remove icon

---

src/borg/_hashindex.c

no critical fixes yet, one minor bugfix (guess we want to backport it to 1.2).

hashindex bugfix and refactoring (master)

---

src/borg/testsuite/archiver/extract_cmd.py

add test for extracted directory mtime (master)

---

src/borg/testsuite/__init__.py
src/borg/testsuite/archiver/create_cmd.py
src/borg/testsuite/archiver/extract_cmd.py
src/borg/testsuite/archiver/mount_cmds.py

relaxed timestamp comparisons (master)

---

src/borg/archive.py
src/borg/crypto/key.py

This makes borg2's new crypto do the same check as borg1's old crypto and makes sure that no chunks created by an evil borg client would go unnoticed.

assert_id: better be paranoid, fixes #7362

---

src/borg/testsuite/archiver.py

while that might be true for many cases, we can not assume it is always true, as proven by the failing test on S390.

"auto" compressor tests: do not assume zlib is better than lz4, fixes #7363

---

src/borg/archive.py
src/borg/testsuite/archive.py

Implements #7354
Added "Files changed while reading" stats to the Statistics class.

Add files changed while reading to Statistics class #7354

---

src/borg/testsuite/hashindex_stress.py

Add hashtable stress test (backport to 1.2-maint)

---

src/borg/_hashindex.c

Backport the commits from #7325

hashindex bugfix and refactoring (backport to 1.2-maint)

---

docs/installation.rst

docs: installation: add link to OS dependencies

---

src/borg/platform/freebsd.pyx

TODO:
- review by freebsd users / devs
- testing on freebsd
Fixes #6997.

xattrs: fix namespace processing on FreeBSD, fixes #6997

---

src/borg/archiver.py
src/borg/testsuite/archiver.py

Fixes #7432.
Backport of #7460.

Add --ignore-zeros flag to import-tar

---

.pre-commit-config.yaml
docs/development.rst
requirements.d/development.txt

Added pre-commit as a requirement and integrated black and flake8 lint scripts to execute before commits. Changed docs to notify fellow contributors to install the pre-commit hooks.

Added pre-commit for linting purposes. Fixes #7476

---

src/borg/archiver/__init__.py
src/borg/archiver/prune_cmd.py

use this to limit --list output to kept or pruned archives only.

prune --list-kept/--list-pruned, fixes #7511

---

src/borg/compress.pyx
src/borg/helpers/parseformat.py
src/borg/testsuite/compress.py
src/borg/testsuite/helpers.py

Fix argparse error messages

---

src/borg/testsuite/archiver/__init__.py
src/borg/testsuite/archiver/check_cmd.py
src/borg/testsuite/archiver/delete_cmd.py
src/borg/testsuite/archiver/mount_cmds.py

also: introduce src_file, which is a file in src_dir.

tests: use a smaller dir for src_dir, fixes #7518

---

docs/deployment/pull-backup.rst

I tried to use one of the described ways to perform "pull" backups, but all of them either failed or very rather complicated to be used and thus brittle in everyday use.
After some research I came up with simple ssh remote forwarding which for me is much easier to use than any of the currently described approaches.
Let me know if you would describe something differently or if there are security concerns which I did not see (I am just using this in a very small local/home environment, not a big corporate environment).

Describe performing pull-backups via ssh remote forwarding

---

src/borg/helpers/progress.py
src/borg/testsuite/helpers.py

ProgressIndicatorPercent: fix space computation for wide chars, fixes #3027

---

src/borg/archiver.py

doc markup fixes

---

src/borg/testsuite/compress.py

The compression tests had a lot of redundant code that was difficult to read. I went through each test using pytest parameterization to reduce the amount of duplicated code and generally clean things up. 
@m3nu @ThomasWaldmann

Parametrize compression tests

---

src/borg/archiver/help_cmd.py

I had hard time to understand how patterns are working, tried to improve this, making explanations more clear, and adding a useful sample for declarative includes

Improve patterns help

---

src/borg/archiver.py

See https://github.com/borgbackup/borg/pull/7635

Backport of improvements in patterns help

---

src/borg/testsuite/xattr.py

_Seemingly_ straightforward conversion with just a fixture to replace the setup/teardown and slight changes to the tests to make them work with fixture.

Xattr.py unittest to pytest conversion 

---

docs/usage/prune.rst.inc

Backport: Improve the documentation for `--keep-within`

---

setup.cfg
src/borg/item.pyx
src/borg/manifest.py
src/borg/testsuite/archiver/debug_cmds.py

also: manifest.version == 2 now

manifest: move item_keys into config dict, fixes #7710

---

src/borg/archiver.py

Backport of #7714 to `1.2-maint`

Backport: Docs: Rewrite `borg check` docs

---

src/borg/testsuite/__init__.py
src/borg/testsuite/archiver/benchmark_cmd.py
src/borg/testsuite/archiver/checks.py
src/borg/testsuite/archiver/disk_full.py
src/borg/testsuite/archiver/key_cmds.py
src/borg/testsuite/archiver/rcreate_cmd.py

rather use monkeypatch.setenv/delenv.

tests: remove usage of environment_variable context manager, fixes #1002

---

src/borg/testsuite/__init__.py

also: clean up imports / comments

remove unused methods of BaseTestCase

---

src/borg/testsuite/archiver/disk_full.py

- master branch has different free space requirements from 1.2-maint, so we now use a 700MB filesystem
- used pytest.mark.parametrize for the test passes, kind of a progress display
- fix bug in rcreate call, encryption arg is needed
- fix bug in lock file cleanup
- added repo space cleanup
- updated docstring with current linux instructions (ubuntu)
- stopped using the "reserved" files, the "input" files are good enough to get some space freed.

fix test_disk_full, fixes #7617

---

src/borg/archiver/create_cmd.py
src/borg/helpers/__init__.py
src/borg/helpers/fs.py
src/borg/testsuite/archiver/create_cmd.py

do not try to read parent dir of recursion root (master)

---

requirements.d/development.txt

also in requirements.d/development.txt.

require cython <3 for now

---

Vagrantfile

this also brings OpenSSL 3.0.x.

vagrant: add VM with debian bookworm

---

.github/workflows/ci.yml
pyproject.toml
src/borg/archiver/tar_cmds.py
src/borg/helpers/msgpack.py
tox.ini

some warnings still, but no major errors.

support / test on Python 3.12

---

.readthedocs.yaml

something is broken with these, build fails.

offline docs: remove epub, pdf. only build htlmzip.

---

src/borg/repository.py

this belongs to the fix-shadow-index-1.2 PR, but was forgotten.

shadow index: add more comments

---

docs/deployment/image-backup.rst

make SERIAL backup method compatible to borg2

---

docs/changes_1.x.rst

https://github.com/borgbackup/borg/pull/7946

CVE upgrade steps: remove period that could be interpreted as part of the command

---

docs/internals/frontends.rst

docs: Add "check.rebuild_refcounts" message

---

Vagrantfile
scripts/msys2-install-deps

this is the version we use in master branch since longer.

use pyinstaller==5.13.2

---

Vagrantfile
scripts/msys2-install-deps

use pyinstaller 6.3.0

---

requirements.d/development.lock.txt
requirements.d/development.txt
src/borg/testsuite/archiver.py

get rid of dateutil

---

docs/internals/frontends.rst
docs/usage/general/environment.rst.inc
docs/usage/general/return-codes.rst.inc
scripts/errorlist.py
src/borg/archive.py
src/borg/archiver.py
src/borg/cache.py
src/borg/constants.py
src/borg/crypto/file_integrity.py
src/borg/crypto/key.py
src/borg/crypto/keymanager.py
src/borg/helpers/__init__.py
src/borg/helpers/checks.py
src/borg/helpers/errors.py
src/borg/helpers/fs.py
src/borg/helpers/manifest.py
src/borg/helpers/parseformat.py
src/borg/locking.py
src/borg/remote.py
src/borg/repository.py
src/borg/testsuite/archiver.py
src/borg/testsuite/helpers.py

default behaviour is mostly unchanged, but user can enable this via an environment variable.
fixes #6756 and some other issues.

optional more specific return codes

---

.github/workflows/ci.yml
Vagrantfile
requirements.d/development.lock.txt
requirements.d/development.txt
scripts/msys2-install-deps
scripts/sdist-sign

use pip and build

---

src/borg/archiver/lock_cmds.py

Improve docs for borg with-lock as discussed in https://github.com/borgbackup/borg/issues/8022

improve docs for borg with-lock

---

src/borg/archiver.py

discussion in #8022
port of #8024

improve docs for borg with-lock, 1.4-maint backport

---

src/borg/archiver.py

discussion in #8022
port of #8024

improve docs for borg with-lock, 1.2-maint backport

---

Vagrantfile

Vagrant updates (master)

---

docs/development.rst

docs: how to run the testsuite using the dist package

---

src/borg/archiver/lock_cmds.py
src/borg/testsuite/archiver/lock_cmds.py

borg with-lock: catch exception, print error msg, fixes #8022

---

src/borg/archiver/key_cmds.py

this is a fwd port from 1.4-maint #8033 and most of it was already done in master, so only a minor change in here.

fix CommandError args, fixes 8029

---

docs/internals/frontends.rst
src/borg/crypto/key.py

better error msg for corrupted key data, fixes #8016

---

docs/internals/frontends.rst
src/borg/remote.py
src/borg/repository.py

more specific errors / msgids (master)

---

docs/usage/create.rst
src/borg/archive.py
src/borg/archiver/create_cmd.py
src/borg/helpers/__init__.py
src/borg/helpers/fs.py
src/borg/testsuite/archiver/create_cmd.py

slashdot hack (master)

---

.github/workflows/ci.yml
.github/workflows/codeql-analysis.yml
Brewfile
docs/global.rst.inc

github CI: misc updates (master)

---

.github/workflows/ci.yml
.github/workflows/codeql-analysis.yml
.github/workflows/windows.yml
docs/global.rst.inc

github CI: misc updates (1.2-maint)

---

src/borg/archiver.py

This PR fixes bug described in #8152 for 1.4 branch

 changed insufficiently reserved length for log message (copy of #8152 for 1.4)

---

docs/borg_theme/css/borg.css

We have this since quite a while and there were no major complaints.

recreate: remove experimental status

---

pyproject.toml
src/borg/helpers/msgpack.py

tests with 1.1.0rc1 were successful, thus I assume 1.1.0 will also work ok.

allow msgpack 1.1.0

---

Vagrantfile
scripts/fetch-binaries

- add fbsd13 VM
- change VM names
- update binaries fetching script

Vagrant machines (1.4-maint)

---

src/borg/cache.py
src/borg/testsuite/archiver.py

Backport of #8257 to 1.4-maint
Try to rebuild cache if an exception is raised, fixes #5213
For now, we catch FileNotFoundError and FileIntegrityError.
Write cache config without manifest to prevent override of manifest_id. This is needed in order to have an empty manifest_id. This empty id triggers the re-syncing of the chunks cache by calling sync() inside LocalCache.__init__()
Adapt and extend test_cache_chunks to new behaviour:
- a cache wipe is expected now.
- borg detects the corrupt cache and wipes/rebuilds the cache.
- check if the in-memory and on-disk cache is as expected (a rebuilt chunks cache).

Automatic rebuild cache on exception, fixes #5213 (#8257) - Backport to 1.4-maint

---

docs/faq.rst
docs/usage/general/environment.rst.inc
src/borg/cache.py
src/borg/testsuite/archiver/checks.py

Add BORG_USE_CHUNKS_ARCHIVE env var, fixes #8280

---

src/borg/cache.py

Related to #8282 
In case a file named chunks.archive.d, cache would not create a folder with that name to store cache chunks archive. We need to support both the new environment variable and the old "hacky" way of creating a file.

Fix backwards compatibility of old chunks.archive.d file behavior

---

src/borg/archiver/delete_cmd.py
src/borg/archiver/rcompress_cmd.py

Fix some issues related to Error and .print_error().

fix error handling (master)

---

docs/deployment/central-backup-server.rst
docs/faq.rst
docs/usage/general/repository-urls.rst.inc

Update repository URLs in docs to use new syntax

---

.github/workflows/ci.yml
scripts/msys2-install-deps
src/borg/archive.py
src/borg/testsuite/archiver/extract_cmd.py

Will currently upgrade PIP from the package 24.1.2 to 24.2 and solves #8264 
python-paramiko solves #8381

Fix for #8264 Windows CI broken and #8381 Windows build failing

---

src/borg/storelocking.py

- on explicit request, update .last_refresh_dt inside _create_lock / _delete_lock
- reset .last_refresh_dt if we kill our own lock
- be more precise, have exactly the datetime of the lock in .last_refresh_dt
- cosmetic: do refresh/stale time comparisons always in the same way

storelocking: fixes / cleanups

---

Vagrantfile

Vagrant updates 2

---

docs/binaries/00_README.txt
docs/usage/general/return-codes.rst.inc
src/borg/archiver.py

Doc updates (1.4-maint)

---

src/borg/archive.py
src/borg/archiver/check_cmd.py
src/borg/repository.py

Check improvements

---

docs/faq.rst
docs/quickstart.rst
docs/usage/serve.rst

docs/FAQ: Clean up entries regarding SSH settings

---

src/borg/archiver/mount_cmds.py

improve borg mount docs

---

scripts/shell_completions/zsh/_borg

I am not familiar with zsh completions, so I did only the easy stuff.
A lot of the more complex stuff is likely still broken, PRs welcome!

shell completions: adapt zsh for borg 2.0.0b13

---

src/borg/fuse.py

for archive series (duplicate names!), it is not just the archive name, but NAME-ARCHIVEID.

mount: fix check_pending_archive to give correct root dir, fixes #8528

---

docs/changes.rst

upgrade notes about files cache settings when NOT using archive series

---

.github/workflows/ci.yml
pyproject.toml
tox.ini

support and test on Python 3.13

---

docs/usage/prune.rst.inc

Update the prune doc to describe the new --keep-within intervals.

update prune documentation for new --keep-within intervals

---

docs/faq.rst

FAQ: Why are backups slow on a Linux server that is a member of a windows domain?

---

src/borg/testsuite/helpers.py

Fix hourly prune test failure due to local timezone  

---

src/borg/archiver/_common.py
src/borg/archiver/repo_create_cmd.py
src/borg/legacyremote.py
src/borg/legacyrepository.py
src/borg/remote.py
src/borg/repository.py

borgstore now does this automatically.

create: remove --make-parent-dirs option, #8619

---

docs/development.rst

Clearer language

---

docs/internals/data-structures.rst

work around sudden failure of sphinx ini lexer

---

docs/binaries/00_README.txt
docs/faq.rst

Docs about slow msgpack when using the binary (master)

---

docs/_templates/layout.html
docs/conf.py
requirements.d/docs.txt

docs: theme fixes (1.4-maint)

---

src/borg/crypto/keymanager.py

Just like #8747, only for 1.4-maint

Fix paper key import error message

---

src/borg/archiver.py
src/borg/compress.pyx
src/borg/testsuite/compress.py

implement padme chunk size obfuscation (SPEC 250), fixes #8705

---

pyproject.toml
requirements.d/development.txt

Also: raise setuptools version requirement appropriately.

pyproject.toml: SPDX expression for license, add license-files, see #8771

---

src/borg/archiver/__init__.py

forward port of #8685 to master branch.

quickfix to disallow running borg with assertions switched off, see #8649

---

src/borg/cache.py

chunks cache fixes (master)

---

Vagrantfile
docs/development.rst
docs/installation.rst
pyproject.toml

remove support for / testing on Python 3.9

---

src/borg/testsuite/archiver/repo_compress_cmd_test.py

very simple, mostly for coverage.

tests: add repo-compress --stats test

---

src/borg/archiver/list_cmd.py
src/borg/testsuite/archiver/list_cmd_test.py

IOW: if there are > N slashes in the path, it is not listed.

list --depth=N: list files up to N depth in path hierarchy, fixes #8268

---

src/borg/archiver/create_cmd.py
src/borg/helpers/fs.py
src/borg/testsuite/helpers_test.py

dir_is_tagged/_is_cachedir: add fd-based operations

---

.github/workflows/ci.yml
scripts/shell_completions/bash/borg
scripts/shell_completions/fish/borg.fish
scripts/shell_completions/zsh/_borg
src/borg/testsuite/shell_completions_test.py

add new commands and options to shell completions

---

setup.py

- remove outdated comment
- remove undef'ing of NDEBUG for chunkers

setup.py: cosmetic updates for chunkers

---

Vagrantfile
docs/binaries/00_README.txt
scripts/fetch-binaries

currently still known as "testing",
but soon to be released.

Vagrant: debian testing/trixie box (master)
