- docs/usage/notes.rst
See #4384. This was really easy; unexpectedly, the patch applied cleanly.
> Elaborate on append-only mode docs (1.1 backport)

- docs/internals/security.rst
some spelling fixes:
situation were -> situation where
kiB -> KiB (see https://en.wikipedia.org/wiki/Kibibyte)
posess -> possess
> docs: fix spelling errors

- scripts/shell_completions/bash/borg
- scripts/shell_completions/fish/borg.fish
- scripts/shell_completions/zsh/_borg
Added shell completions for
```borg diff repo::archive1 archive2```
Removed deprecated options.
Added new option ```--max-duration```
> Shell completions: removed deprecated, add new options; borg diff second archive

- src/borg/testsuite/xattr.py
- src/borg/xattr.py
i.e. prefix the keys with the namespace, so it is ns.key like on linux.
still only dealing with the "user" namespace, like before.
in the "system" namespaces there are ACLs (we deal with them via the acl
api, so no problem) and stuff from pnfsd (not sure what exactly).
this change is needed because FreeBSD's FUSE code expects the xattr
keys to be in that format.
it is also needed for cross-platform data exchange, so e.g. if one wants to:
- create archive on linux, extract on freebsd - with "user.xxx" xattrs.
- or vice versa.
archives made with older borg versions on freebsd will still extract correctly
on freebsd (not on linux though) even though they do not have the
namespace prefixes in the archived metadata (it will be interpreted in
same way as if they were prefixed by "user." as we …
> make freebsd xattr platform code api compatible with linux, fixes #3952 (1.1-maint bp)

- .travis/install.sh
- requirements.d/development.lock.txt
maybe slightly newer will also work, e.g. pip < 19.2, pytest < 5.0.
> lock travis-ci test env to py 3.4 compatible versions, fixes #4343

- src/borg/archiver.py
[TASK] #4471 – borg help should print list in sorted order: Fixed.
- Added a comment line `# borg <command>` above each subparser.
- Changed order of subparsers to get ordered output.
- Checked borg help output to see if something is broken.
Changes after last PR:
- Fixed wrong "borg debug xxx" commit messages.
- Split Step 5 into 5a and 5b.
Note: I forgot to add the `# borg help` line in step 1. I added that in step 15 where I moved the help section.
> Fix for #4471: Sorted commands help in multiple steps

- .travis/install.sh
- .travis/run.sh
pyenv recently gained the ability to use (and actually prefer) openssl
1.1 on mac OS.
we need to use python 3.5.3, older is not compatible with openssl 1.1.
with python 3.5.2, python was built without ssl support.
also, we need to set the right PKG_CONFIG_PATH, so borg also uses 1.1.
> travis: use openssl 1.1 for borg, use python 3.5.3 for 1.1 compat

- docs/usage/serve.rst
Add "SSH Configuration" section to "borg serve" documentation page. This new section documents the additional ssh configuration necessary to prevent the borg serve process from keeping a lock on a repo in the event the ssh connection is abnormally disconnected (leaving borg serve running until sshd times out, which can take upwards of an hour in some cases). This pull request is in response to issues #3988, #636 and #4485 (and probably others).
> Add "SSH Configuration" section

- docs/usage/serve.rst
Add "SSH Configuration" section to "borg serve" documentation, to outline ssh/sshd configuration to prevent borg serve keeping a lock on a repo in the event the ssh connection is abnormally disconnected.
In response to issues #3988, #636 and #4485 (and probably others).
Backport from master.
> Add "SSH Configuration" section to "borg serve" (backport from master)

- src/borg/archive.py
the second call was done in stat_attrs().
this increases backup with lots of unchanged files performance by ~ 5%.
> create: only run stat_simple_attrs() once

- src/borg/repository.py
this isn't much different than it was before 1.1.9,i think the simplest solution is to make it like before (as in 1.1.8).
> give invalid repo error msg if repo config not found, fixes #4411

- src/borg/archiver.py
- src/borg/cache.py
archives with borg 1.2 metadata: quick, we have precomputed size data
in archive metadata and just need to sum up for all archives.
archives without borg 1.2 metadata: expensive, need to read all
archives' items metadata streams and sum up for all items.
> fix "all archives" stats considering part files, fixes #4329

- Vagrantfile
we need to use py 3.5.3 to support openssl 1.1.
we also would need at least 3.6.7 to have pyenv switch to openssl 1.1,
but as we also use the latest 3.6 (3.6.8 currently) for building the
binary, we just use that for tests also.
> vagrant: build python and borg with openssl 1.1

- Vagrantfile
6.0 went out of support, the ftp server URL we used 404ed and we
already had the 6.4 box for master branch, so just use it for
1.1-maint also.
> vagrant: upgrade openbsd box to 6.4

- src/borg/archiver.py
- src/borg/helpers/parseformat.py
they are supported for --prefix already, so it totally makes sense to
also support them for the more powerful/generic --glob-archives.
> enable placeholder usage in --glob-archives, fixes #4495

- src/borg/archive.py
- src/borg/archiver.py
- src/borg/testsuite/archiver.py
also split the hardlink extraction test into 2 tests.
(cherry picked from commit f33f318d816505161d1449a02ddfdeb97d6fe80a)
> slave hardlinks extraction issue, see #4350 (1.1-maint)

- src/borg/archiver.py
for borgbackup's client/server mode security, it is essential that some stuff can be enforced server-side (e.g. quota, access only to specific repos).
the way this is done in the code should be resistant against "forgetting" to enforce if new stuff is added.
this was not the case until this PR, but should be fixed now.
please review / give feedback, see #4097.
a test for this (`test_get_args`) already existed before and still succeeds.
> use whitelist approach for borg serve, fixes #4097

- src/borg/archiver.py
the check checks whether follow_symlinks=False is supported, which
requires that the glibc is recent enough / python was compiled
for a recent enough glibc. follow_symlinks=False is only used for borg
create and extract, but not needed for borg serve.
thus, this makes it possible to run "borg serve" even on a bit older
servers. be careful, due to the presence of this check on the server
side until now, older server systems are not really tested.
> do not check python/libc for borg serve, fixes #4483

- src/borg/archiver.py
- src/borg/testsuite/archiver.py
- src/borg/testsuite/helpers.py
if the tests use a pure-python msgpack, 1 test which is specifically
made for that, will fail. esp. for linux distribution packages, this
will still point to the problem (that the msgpack package is not built
or installed correctly).
> pure-py msgpack warning shall not make a lot of tests fail, fixes #4558

- src/borg/testsuite/archiver.py
so both can be excluded by "not test_fuse"
(fedora does this for testing)
> rename test_mount_hardlinks to test_fuse_mount_hardlinks (master)

- docs/installation.rst
Previous URL was no longer functional and redirected to the Brew homepage.
> docs: update macOS Brew link

- src/borg/archiver.py
I haven't generated the new docs - I wasn't sure from the contributions section whether they should be generated here or wait for a release, so I kept it minimal.
There may be a better example to use, but this is one that came up in #borgbackup today.
> Add example of exclude-norecurse rule in help patterns

- setup.py
borgbackup's setup.py tries to display a meaningful error message if the user needs Cython but the library is not available. This pull request fixes the check (which was broken sometime in 1.2.x as it works in in 1.1.10.
> setup.py: fix detection of missing Cython

- src/borg/archive.py
note that "partial" even applied to giving an always matching condition.
"full" is only assumed if no conditions are given.
> extract: fix KeyError for "partial" extraction, fixes #4607 (master fwd port)

- src/borg/archiver.py
- src/borg/helpers/parseformat.py
This fixes the issue, that with `borg diff REPO::ARCHIVE1 ARCHIVE2`, placeholders only work in `ARCHIVE1`, not in `ARCHIVE2`.
The `REPO::ARCHIVE1` argument uses `location_validator` as its type, which does replace placeholders, the `ARCHIVE2` argument uses  `archivename_validator`, which prior to this change did not.
This other two commands using arguments of type `archivename_validator`, namely `rename` and `recreate`, did do replacing of placeholders in the extra archive arguments on their own. With the change to `archivename_validator()` this duplicate code could be removed.
> Enable placeholder usage in all extra archive arguments

- docs/installation.rst
It was broken because there's already a different reference named `github` in `docs/global.rst.inc`. Fixed by using an anonymous hyperlink reference, per https://stackoverflow.com/a/14067756/278488
> Fix osxfuse github link in installation docs

- src/borg/helpers/parseformat.py
Sopport xxh64 checksum in `borg list` besides the existing hashes provided by hashlib, using the built-in xxh64 implementation.
This e.g. allows to generate an archive listing that could be used with `xxh64sum` to quickly compare (verify) actual archive contents with existing files. While there may not be a noticeable speedup in borg's operation on a current system, it does lower CPU usage and may help  systems with slow CPUs.
It also gives people that happen to already have `xxh64sum` generated checksum files for their data another option.
> support xxh64 checksum in addition to the hashlib hashes in borg list

- src/borg/testsuite/hashindex.py
Fix broken test that relied on improper zlib assumptions
This test assumed that zlib would always produce the same output for a
given input, and that assumption has proven incorrect. It rested on
zlib never improving. The zlib shipped in Clear Linux has algorithm
improvements, which caused this test to break.
This patch instead decompresses the expected value and compares that.
> Fix broken test that relied on improper zlib assumptions

- src/borg/testsuite/hashindex.py
This is the cherry-pick of the fix in #4645 for 1.1-maint.
>     This test assumed that zlib would always produce the same output for a
>     given input, and that assumption has proven incorrect. It rested on
>     zlib never improving. The zlib shipped in Clear Linux has algorithm
>     improvements, which caused this test to break.
>     
>     This patch instead decompresses the expected value and compares that.
> Fiz zlib bad assumption

- src/borg/remote.py
if the remote server does not support the dict-based argument passing
yet (e.g. when accidentally using borg 0.29 on rsync.net), the GET rpc
call argument list failed to generate if the command currently being
processed was not a GET also.
note: rsync.net has a more recent borg as "borg1".
> fix preloading for old remote servers, fixes #4652

- src/borg/helpers/parseformat.py
I found this while trying to use the `--target` option on `borg recreate`.
> Fix invalid archive error message

- src/borg/helpers.py
Backporting #4656 to 1.1-maint
> 1.1-maint: Fix invalid archive error message

- src/borg/testsuite/__init__.py
this happened because the user had pytest5 installed somehow,
although it is incompatible with python 3.4:
```
File "/usr/local/lib/python3.4/dist-packages/borg/archiver.py", line 81, in <module>
from .selftest import selftest
File "/usr/local/lib/python3.4/dist-packages/borg/selftest.py", line 21, in <module>
from .testsuite.hashindex import HashIndexDataTestCase, HashIndexRefcountingTestCase, HashIndexTestCase
File "/usr/local/lib/python3.4/dist-packages/borg/testsuite/__init__.py", line 29, in <module>
from pytest import raises
File "/usr/local/lib/python3.4/dist-packages/pytest.py", line 6, in <module>
from _pytest.assertion import register_assert_rewrite
File "/usr/local/lib/python3.4/dist-packages/_pytest/assertion/__init__.py", line 6, in <module> …
```
> cope with ANY error when importing pytest into borg.testsuite, #4652

- docs/usage/create.rst
Documentation mentions the "default format borg will have in version 1.1" as if that were a future version.
> Update documentation of borg create

- docs/usage/benchmark_crud.rst.inc
> docs: benchmark crud: clarify that space is used until compact

- .travis.yml
- tox.ini
I think this is all that's required for python3.8-dev testing. Travis ran without errors pn python3.8
fixes #4682
> tox / travis: add testing on py38-dev

- src/borg/cache.py
Before this fix, because known() only checked the key-type file, the
location file could go missing without being automatically regenerated.
Now a save() is triggered if not all files are present.
> SecurityManager.known(): check all files, fixes #4614

- src/borg/archiver.py
the borg check --repair is needed to clean up all the orphaned chunks.
if the message is emitted on INFO log level, people likely do not see
it if they use default WARNING log level (they did not give -v).
> after double-force delete, warn about necessary repair, fixes #4704

- docs/man/borg-create.1
- docs/usage/create.rst
When I browsed the readthedocs and manpages while setting up Borg for myself for the first time, I saw multiple hints that pushing backups via SSH is supported (e.g. the existence of the `borg serve` command and the `--rsh` option), but I never found a clear example. I only found <https://borgbackup.readthedocs.io/en/stable/usage/general.html#repository-urls> after being pointed to it by @ThomasWaldmann.
Therefore, an explicit example in the `borg create` documentation seems appropriate. I put it next to the pull-style example using sshfs which serves a similar usecase.
> add a push-style example to borg-create(1)

- docs/usage_general.rst.inc
PR raised as per request in https://github.com/borgbackup/borg/issues/4540
Added some doco regarding use of temp directory on remote, in particular cases where default tmp directory is not appropriate for use.
> Updated doc to cover use of temp directory on remote

- docs/usage_general.rst.inc
- src/borg/helpers.py
- src/borg/platform/linux.pyx
remove WSL autodetection. if WSL still has this problem, you need to
set BORG_WORKAROUNDS=basesyncfile in the borg process environment to
work around it.
> new BORG_WORKAROUNDS mechanism, basesyncfile, fixes #4710

- src/borg/archive.py
if the file is not a regular file, but a hardlink slave with a not
extracted hardlink master, chunks will be None and we must not call
preload(chunks).
> fix partial extract for hardlinked contentless file types, fixes #4725

- docs/faq.rst
Drive home the point that relative source names does not save you from re-chunking if absolute pathnames change.
Since 'A' line reports relative filename, it is very easy to assume that this is the pathname used in files cache. Lets make cache entries that talk about this more verbose and re-iterate that files cache ALWAYS uses absolute pathnames
> Reiterate that 'file cache names are absolute' in FAQ

- docs/changes.rst
- src/borg/archiver.py
- src/borg/testsuite/archiver.py
also: add --atime option to enable storing files' atime.
> create: make --noatime the default, deprecate --noatime, fixes #4673

- src/borg/fuse.py
This PR fixes the `st_birthtime` (used e.g. in macOS) missing from the entries when using `borg mount` (note that `borg extract` does not exhibit this error).
> Add birthtime to FUSE entries

- src/borg/fuse.py
Same as #4763 in the 1.1-maint branch: this PR fixes the st_birthtime (used e.g. in macOS) missing from the entries when using borg mount (note that borg extract does not exhibit this error).
> Backport #4763 to 1.1-maint

- src/borg/archiver.py
The issue https://github.com/borgbackup/borg/issues/4471 solution
created many commands for borgfs which shouldn't exist in addition to
creating issue https://github.com/borgbackup/borg/issues/4752.
Fixes https://github.com/borgbackup/borg/issues/4752 .
> Fixes the man pages creation

- docs/faq.rst
Improve password FAQ (decrease pw length, add -w 0 option to base64 to prevent line wrap).
I thought about adding a note regarding why the -w option may be needed, but finally didn't do that to keep the FAQ short.
> [DOC] #4591 - Improve password FAQ

- docs/faq.rst
A new FAQ entry mentioning various ways to work around or prevent SSH timeout when extracting.
> [DOC] #3866 - Add FAQ for preventing SSH timeout in extract.

- src/borg/archiver.py
In my opinion the borg help pattern is already quite good in explaining the --exclude and --pattern features, so I just added a note that explicitly states the additional prefix in --pattern lines.
If you read this help carefully it should be sufficient.
> [DOC] #4118 - Explain difference between --exclude and --pattern.

- src/borg/repository.py
we create the hardlink to be able to secure erase the old config file.
if we can't do that because there is just a problem with hardlinks not
working, the old config will be just overwritten normally (not secure
erased). the user will get a warning in that case, but other than that,
the overall borg operation will succeed.
if there is a bigger problem (like a general lack of permissions or a
general issue with the underlying fs), subsequent operations will fail.
> ignore EACCES (errno 13) when hardlinking, fixes #4730

- src/borg/archiver.py
- src/borg/helpers/manifest.py
changes:
- changed --prefix default to None (was: ''), so we can check using "is not None" to determine when --prefix has been given.
- the previous check for --prefix being used was just for a truthy value, so using --prefix='' was not really supported, but happened to behave the same as the default processing anyway.
- argparse python stdlib code seems to have a bug when processing an option like --prefix='--', args.prefix will be [] in that case (should be '--'). With previous code this behaved like no prefix given ([] value is not truthy). Now, as we check for "is not None", it will try to process that value but blow up with a TypeError as it can't do [] + '*'.
This is a bit unpretty end, but at least borg prune won't delete all your archives and it will be a reminder that argparse is …
> --prefix / -P: fix processing, avoid argparse issue, fixes #4769

- .travis.yml
cf.
https://blog.travis-ci.com/2018-11-19-required-linux-infrastructure-migration
modified:   .travis.yml
> Remove deprecated keyword "sudo" from travis config.

- src/borg/remote.py
The RepositoryCache used `os.statvfs` which is not available on Windows.
`shutil.disk_usage` provides the same information but in a cross platform way.
> Replaced usage of os.statvfs with shutil.disk_usage

- src/borg/archiver.py
- src/borg/helpers/manifest.py
This way, if the archive does not exist, we print a pretty message and
abort.
Fixes #4793.
> Add a try catch when formatting the info string.

- src/borg/archive.py
The code used for error reporting crashes due to an invalid utf-8
sequence. Use errors='replace' to never crash there. Errors
are expected in input data when borg check is run.
> check: do not stumble over invalid item key, fixes #4845

- src/borg/repository.py
at least it does not crash now when committing.
the question why the compact map points to a missing segment file is not answered yet, there might be another problem...
> commit-time free space calc: ignore bad compact map entries, fixes #4796

- .travis.yml
- .travis/install.sh
macOS: to cover some rather old and some rather new python
(not 3.8 though, but 3.8.0 is tested on linux).
linux: to test on 3.7 releases also. stop testing 3.6-dev.
> travis: macOS: test on py35 and py37, linux: test on py37

- .travis.yml
- .travis/install.sh
- tox.ini
it seems that pyenv now depends on openssl 1.1, so use python versions
that work with openssl 1.1 for testing (same versions as currently
in master branch).
> travis: python upgrades

- src/borg/_chunker.c
- src/borg/testsuite/chunker_slow.py
I'm a bit late to the https://github.com/borgbackup/borg/issues/1021 party, buy here's a chunker speedup by rearranging the loop a bit. Testing throughput on my slow old laptop:
Before:
```(borg-env) lenovo_0$ borg-env/bin/python3  ~/borgbench
length   count      dt throughput chunks_count
1000000000       1 5.442 183.741    120
100000000      10 5.531 180.795     12
10000000     100 5.225 191.399      2
1000000    1000 2.764 361.778      1
100000   10000 0.172 5826.037      1
10000  100000 0.993 1006.679      1
1000 1000000 8.999 111.122      1
100 1000000 8.776 11.394      1
10 1000000 8.763 1.141      1
1 1000000 8.768 0.114      1
```
After:
```(borg-env) lenovo_0$ borg-env/bin/python3  ~/borgbench
length   count      dt throughput chunks_count
1000000000       1 3.891 256.990    120 …
```
> chunker speedup

- src/borg/testsuite/archiver.py
The test was failing due to localisation.
This is fixed by this commit.
> The test recreate_timestamp is fixed

- Vagrantfile
made an updated base VM for OS X 10.10, so it does not need to download
and install the OS updates.
installed brew on the base VM
updated osxfuse to 3.10.4
removed testing on python 3.4.0/3.5.0 (not openssl 1.1 compatible)
added testing on python 3.5.3, 3.7.0, 3.8.0 (still buggy, #4520)
binary building is on 3.5.9 now
> vagrant: darwin VM: testing/building updates

- src/borg/archiver.py
It actually took me several days to figure out that `--progress` was the culprit to Borg constantly being SIGKILL'd by the kernel, because Borg ate all of the memory, and because I enabled progress option. This elaborates on what's the calculation for.
This is not intended to be a "garbage" PR, but if you think this is useless you can close this.
> Elaborate on "Calculating size"

- docs/faq.rst
- docs/usage_general.rst.inc
I think it might be a good idea to add this information to the FAQs. While it has been answered on the mailing list, it was missing from the docs, as far as I can tell: If this assumption of "cache is at the same place as original files" is being made, it should be noted somewhere.
Could be extended further depending on #4899.
> Add paragraph regarding cache security assumptions

- .travis.yml
At this time, OSX builds don't seem to work well on Travis CI. This results in failed tests for each pull request or merge commit. Wouldn't it make sense to use `fast_finish` and `allow_failures` then to specifically allow those builds to fail if they're currently being ignored anyway? See https://docs.travis-ci.com/user/customizing-the-build/#jobs-that-are-allowed-to-fail for documentation. Then, if a justified failed test happens, it would show up faster and also wouldn't be disguised by the in any case failing OSX builds.
> Allow osx builds to fail

- src/borg/archiver.py
It was due to a wrong path given in the log output of --list.
> Fix #4934 : The path given by borg extract --strip-components --list is not confusing anymore

- src/borg/archiver.py
... but continue the operation just as if --stats was not given.
> ignore --stats when given with --dry-run, but continue, fixes #4373

- setup.py
- src/borg/platform/linux.pyx
- src/borg/platform/syncfilerange.pyx
Here is one way of addressing #4905. I moved the `cdef extern` import of `sync_file_range` into its own extension and imported it in a try block. If the import fails, borg falls back to using the BaseSyncFile class like it does with BORG_WORKAROUNDS=basesyncfile. This way BORG_WORKAROUNDS is not required when there is no sync_file_range support. An alternative would be to still require BORG_WORKAROUNDS.
> Move sync_file_range to its own extension

- src/borg/repository.py
if an old hints file gets converted to the new format and it
has entries referring to non-existent segment files, a crash
occurred.
with this code, the crash is avoided and the erroneous hints
entry is removed.
> fix crash when upgrading erroneous hints file, fixes #4922

- src/borg/_hashindex.c
the problem was that after a resize that was triggered by too few
empty buckets, the rebuilt new hash table had entries at different
positions than before, but the idx where to SET the entry was not
recomputed afterwards.
> fix bug in hashindex_set on resize, fixes #4829

- src/borg/archiver.py
> extract: fix confusing output of borg extract --list --strip-components (1.1-maint)

- src/borg/archive.py
- src/borg/archiver.py
- src/borg/repository.py
- src/borg/testsuite/__init__.py
- src/borg/testsuite/archiver.py
- src/borg/testsuite/upgrader.py
This is a port of #4903 addressing #4901 for the master branch. This cherry-picked cleanly from 1.1-maint except for a minor conflict with importing has_link into archiver.py.
> support platforms with no os.link (port to master)

- borg/_hashindex.c
the problem was that after a resize that was triggered by too few
empty buckets, the rebuilt new hash table had entries at different
positions than before, but the idx where to SET the entry was not
recomputed afterwards.
> fix bug in hashindex_set on resize, fixes #4829 (1.0-maint backport)

- src/borg/archiver.py
This should fix the flake8 issue noted in #4980. I checked locally and got the same flake8 errors on master.
After merging, this could be backported to 1.1-maint.
> Make flake8 happy about complex conditional

- .gitignore
Add syncfilerange.c to .gitignore like all the other intermediate Cython outputs. This was missed in #4965. It could be backported to 1.1-maint like #4970 backported #4965.
> Ignore syncfilerange.c

- setup_checksums.py
https://github.com/Cyan4973/xxHash/pull/324
As advertised, xxhash is picked up by py-pkgconfig.
> xxhash>=0.7.3 provides a pkgconfig file

- Vagrantfile
started as a forward port of #4990, but only the added VMs were left.
other changes were not needed / did not apply.
> add a debian buster and a ubuntu focal VM

- docs/internals/frontends.rst
Because some of the JSON blocks in frontends.rst included non-JSON contents (user replies, etc.) the blocks didn't parse/highlight and `make html` complained:
borg/docs/internals/frontends.rst:28: WARNING: Could not lex literal_block as "json".
There's no easy way to enable and disable highlighting just for specific lines, but individually unsetting the highlight language per block suppresses the warnings.
> Suppress Sphinx lexer warnings in frontends.rst

- docs/development.rst
> Add updating borgbackup.org/releases to release checklist (1.1 backport)

- docs/faq.rst
- docs/installation.rst
- docs/quickstart.rst
- docs/resources.rst
- docs/support.rst
I used `grep -Pnr '.{100}' *.rst` to find lines >100 characters long and reflowed them where reasonable (not in code snippets, otherwise well-formatted lists, etc.). Line length in the docs isn't too important (it doesn't matter once they're compiled), but it's nice not to have super-long lines in one's editor.
> Reflow some really long lines in the docs

- docs/internals/frontends.rst
Add a warning for --log-json option that parsing errors will always be printed as plain text.
> [DOCS] #4073 – PlaceholderError not printed as JSON

- src/borg/testsuite/archiver.py
Based on the comments in PR #4683, remove asserts that will always be true if the assert following on he next line is true as well.
> drop pointless asserts covered by other stricter asserts already

- docs/usage/general/environment.rst.inc
This prevents Sphinx WARNING: Bullet list ends without a blank line; unexpected unindent.
> Fix broken indent of a list item

- docs/deployment/pull-backup.rst
- docs/internals/data-structures.rst
- docs/usage/notes.rst
- scripts/shell_completions/bash/borg
- scripts/shell_completions/fish/borg.fish
- scripts/shell_completions/zsh/_borg
- src/borg/archive.py
- src/borg/archiver.py
- src/borg/testsuite/__init__.py
- src/borg/testsuite/archiver.py
Replaced by --noflags. In internal data structure the key 'bsdflags' is kept for backwards compatibility.
fixes #4489
> [FEATURE] #4489 – Deprecate --nobsdflags option

- .travis.yml
- .travis/install.sh
As suggested on IRC, simply going ahead and posting this as a pull request to make it easier to discuss possible improvements.
Intrigued by the exceeding timeouts of OS X builds and wanting to learn a little bit more about the build process, I've been playing around with the CI setup and made a few changes to `.travis.yml` and `.travis/install.sh`. Mostly tidying up, writing comments on what I learned, keeping it POSIX-compliant and verified with [ShellCheck](https://www.shellcheck.net/).
Turns out, OS X builds now consistently pass (within about half an hour), meeting the Travis CI maximum build time and not timing out. :tada:  (I hope I didn't break something without noticing.)
Possibly, the reasons for the previous timeouts have been some time-consuming remnants from using xcode6.4 …
> Adding comments and explanations to Travis config and install script, improving OS X builds

- setup.py
also:
add llfuse < 2.0 requirement also for python>=3.7.
maybe not really required because llfuse seems rather dead anyway,
but good for consistency.
> require recent enough llfuse for birthtime support, fixes #5064

- src/borg/fuse.py
e.g. ubuntu xenial has llfuse 0.41, which is older than llfuse 1.3, which introduced birthtime support.
guess this patch should be picked up by all maintainers offering a recent borg together with old llfuse < 1.3.0.
> fix crash on old llfuse without birthtime attrs, fixes #5064

- docs/faq.rst
- docs/internals/security.rst
- src/borg/archiver.py
Add new FAQ: A repo is corrupt and must be replaced with an older repo.
> [DOCS] #3428 –  Borg repo restore instructions needed

- src/borg/compress.pyx
> correctly calculate compression ratio, taking header size into account, too

- docs/deployment/hosting-repositories.rst
- docs/faq.rst
Article renamed to emphasize the security aspect and linked it in the FAQ.
If approved, I will backport it to 1.1-maint, too.
> docs: linked recommended restrictions to ssh public keys on borg servers in faq, fixes #4946

- Vagrantfile
This is tested after each commit so this test is quite useless on the
Vagrant VMs.
Fix #5020 .
> Remove the flake8 test for Vagrant VMs

- src/borg/archiver.py
Clean up the whole check usage paragraph, use consistent wording.
> [DOC] Document one cause of orphaned chunks in check command, #2295

- docs/usage/general.rst
- src/borg/archiver.py
- src/borg/repository.py
- src/borg/testsuite/__init__.py
- src/borg/testsuite/archiver.py
Linked to #1035. It makes sense wanting to mount read-only repos - and alternative solutions like copying to temp first or an overlay mount are unnecessarily tedious or complex.
Suggested explanation in the docs for `--bypass-lock`:
> Option ``--bypass-lock`` allows you to access the repository while bypassing borg's locking mechanism. This is necessary if your repository is on a read-only storage where you don't have write permissions or capabilities and therefore cannot acquire a lock. Examples are repositories stored on a Bluray disc or a read-only network storage. Avoid this option if you are able to use locks as it's the safer way; see the warning below.
> 
> **Note:** If you do use ``--bypass-lock``, you are responsible to ensure that no other borg instances have write access to the …
> Option to bypass locking to use sensible borg commands with read-only repositories

- docs/usage/general.rst
- src/borg/archiver.py
- src/borg/repository.py
- src/borg/testsuite/__init__.py
- src/borg/testsuite/archiver.py
> Backport of #5048 Option to bypass locking to use sensible borg commands with read-only repositories

- src/borg/fuse.py
setting it to 255 for now (as seen on Linux / ext4), better than the default 0.
the attribute is present since llfuse 1.3.0, which is the minimum requirement currently anyway.
> fuse: set f_namemax in statfs result, fixes #2684

- src/borg/testsuite/__init__.py
To simulate read-only repos, the repo folder was being rendered immutable. This doesn't work when running the tests as non-root users. See #5111
> Fix tests of read-only repos for non-root users

- src/borg/patterns.py
- src/borg/testsuite/patterns.py
Remove all leading slashes in patterns of all sorts but re: style.
This change will break some tests, but as far as I could determine it has no other side effects. I left out changing the re: patterns because removing the leading slash can invalidate all non-trivial patterns (like /?some/dir) or is complicated (like ^/some/dir).
I checked ``extract`` and ``mount`` to verify that all --exclude pattern styles work and the pathes args are recognized.
What's your opinion? Acceptable, or too esoteric?
> [FEATURE] Borg commands accept absolute pathes, #4029

- src/borg/helpers/parseformat.py
The parsing of windows path failed because a undefined variable
was referenced.
> Fixed windows path parsing

- src/borg/patterns.py
Strip leading path separator before trying to match a path.
I just found that I forgot this. In my tests I only checked if ``borg create ::archive relative/path`` works, but not with ``/absolute/path``.
> [BUGFIX] Borg commands accept absolute pathes, #4029

- src/borg/archiver.py
Add a section that explains why to use relative patterns and how this is changed in Borg 1.2.
This change is for the 1.1 branch. For the master branch I plan to add a different section.
> [DOCS] Add note about patterns and stored paths, #4160

- src/borg/compress.pyx
- src/borg/remote.py
- src/borg/testsuite/archiver.py
- src/borg/testsuite/compress.py
- src/borg/testsuite/key.py
- add decide() function to LZ4, LZMA and ZSTD classes that
falls back to NONE if the compressed data turns out bigger than
the original data
- leave ZLIB as is, as it does not use an ID header and compatibility
being the only reason to use it instead of above algorithms anyway
- adapt testsuite to cope with incompressible test data not being
compressed
- add tests to verify that incompressible data is not compressed to
larger size compressed data
Watching the progress output in one of my initial backups using borg I did notice compressed showing a larger number than original at some point. Unlike done in issues #4516 and #385, I actually tested with borg to verify that indeed compressed chunks being stored that were larger than an uncompressed chunk would have been.
Based on this I …
> only store compressed data if the result actually is smaller

- src/borg/archiver.py
- src/borg/testsuite/archiver.py
Add a for loop for "dynamic" config keys like last_segment_checked, skip printing if they are not found in the config.
Also allow last_segment_checked to be set with a int value.
Added tests.
fixes #5159
> [BUGFIX] Borg config --list does not show last_segment_checked, #5159

- src/borg/helpers/parseformat.py
Just a small cleanup to avoid unnecessary `self.used_call_keys = set(self.call_keys) & self.format_keys` calls. 
See the definition of add_keys() https://github.com/hrehfeld/borg/blob/19bfe21fa90fbcd4b2bb68c67d6f68af1ffbeaa8/src/borg/helpers/parseformat.py#L773
> parseformat: unnecessary calls removed

- .travis/install.sh
Fixes https://github.com/borgbackup/borg/issues/4982
Homebrew updated default openssl to 1.1 but not all versions of Python support that version (i.e. older versions of Python). It looks like the pyenv code assumes `openssl` formula is 1.0 and `openssl@1.1` is 1.1 when in fact they're now the same. This instructs pyenv to use `openssl@1.0` formula from rbenv tap
> Fix MacOS build for 1.0-maint

- src/borg/testsuite/archiver.py
the old test stumbled over files with an empty chunks list,
so I guess just having some empty file in src/borg could make
that test fail.
fixed this by deleting a chunk of some specific file (we use
this file / this construction at misc. other places in the
archiver tests).
> test_delete_force: avoid sporadic test setup issues, fixes #5196

- src/borg/archive.py
The locally defined preload() function overwrites the preload boolean keyword
argument, always evaluating to true, so preloading is done, even when not
requested by the caller, causing a memory leak.
Also move its definition outside of the loop.
This issue was found by Antonio Larrosa in borg issue #5202.
> rename local preload() function to not overwrite keyword argument of same name

- setup.cfg
Undeclared markers trigger a pytest warning:
PytestUnknownMarkWarning: Unknown pytest.mark.allow_cache_wipe - is this a typo?
You can see the warning in the current travis output:
=============================== warnings summary ===============================
.tox/py38/lib/python3.8/site-packages/borg/testsuite/archiver.py:1726
/home/travis/build/borgbackup/borg/.tox/py38/lib/python3.8/site-packages/borg/testsuite/archiver.py:1726: PytestUnknownMarkWarning: Unknown pytest.mark.allow_cache_wipe - is this a typo?  You can register custom marks to avoid this warning - for details, see https://docs.pytest.org/en/latest/mark.html
@pytest.mark.allow_cache_wipe
-- Docs: https://docs.pytest.org/en/latest/warnings.html
> declare "allow_cache_wipe" marker in pytest.ini to avoid pytest warning

- src/borg/archive.py
- src/borg/archiver.py
- src/borg/testsuite/archiver.py
In addition to allowing:
```
some-command --param value | borg create REPO::ARCH -
```
also allow:
```
borg create --content-from-command create REPO::ARCH -- some-command --param value
```
The difference is that the latter approach deals with errors properly.
In the former example, an archive is created no matter what. Even, if
`some-command` aborts and the output is truncated, Borg won't realize.
In the latter example, the status code is checked and archive creation
is aborted properly when appropriate.
> Allow creating archives using stdout of given command

- docs/usage/key.rst
- src/borg/archiver.py
- src/borg/crypto/key.py
- src/borg/crypto/keymanager.py
- src/borg/testsuite/archiver.py
Running 'borg key import' on a keyfile repository with the BORG_KEY_FILE environment variable set works correctly if the BORG_KEY_FILE file already exists. However, the command crashes if the BORG_KEY_FILE file does not exist:
$ BORG_KEY_FILE=newborgkey borg key import /home/strager/borg-backups/straglum borgkey
Local Exception
[snip]
File "[snip]/borg/crypto/key.py", line 713, in sanity_check
with open(filename, 'rb') as fd:
FileNotFoundError: [Errno 2] No such file or directory: '[snip]/newborgkey'
Platform: Linux straglum 5.0.0-25-generic #26~18.04.1-Ubuntu SMP Thu Aug 1 13:51:02 UTC 2019 x86_64
Linux: debian buster/sid
Borg: 1.1.11  Python: CPython 3.7.7 msgpack: 0.5.6
PID: 15306  CWD: /home/strager/Projects/borg
sys.argv: ['[snip]/borg', 'key', …
> allow key-import+BORG_KEY_FILE to create key files

- docs/conf.py
- docs/deployment/pull-backup.rst
I tried to document the socat pull mode described in https://github.com/borgbackup/borg/issues/900#issuecomment-499656737.
To keep it simple I did not include the systemd method. Should it be added?
> [DOCS] Add socat pull mode

- docs/usage/notes.rst
- src/borg/archiver.py
- src/borg/remote.py
- src/borg/testsuite/archiver.py
- src/borg/testsuite/repository.py
The umask value is NOT transmitted from client to server any more,
so the borg client can not influence the borg server umask any more.
If one wants to have a specific umask on the server side, one needs to
use a ssh forced command in .ssh/authorized_keys file.
OTOH, as the default value is 077 (in general, for client as well as for
the server) and the server does not take the value from the client any more,
there usually should be no need to give it on the server side, IF you are
happy with the default value.
> --umask is for the local borg process only, fixes #4947

- src/borg/archiver.py
- src/borg/constants.py
as documented:
https://borgbackup.readthedocs.io/en/stable/usage/general.html#return-codes
compatibility warning: in case you have scripts expecting rc == 2 for a
signal exit, you need to update them to check for >= 128.
> exit with 128 + signal number, fixes #5161

- docs/internals/frontends.rst
- docs/usage/general/environment.rst.inc
- src/borg/archiver.py
- src/borg/testsuite/archiver.py
borg check --repair and borg recreate are now present in the code
since rather long, so they are not experimental any more.
but, both bear some risk of data loss:
- there could be an undiscovered bug in the code
- the user might use them wrong (e.g. accidentally excluding everything /
not matching anything when recreating an archive)
- there might be kinds of corruption borg check --repair can not fix
and it might make things even worse while trying to fix.
so, if your repo / archive(s) are important, be careful.
> rephrase some warnings, fixes #5164

- src/borg/locking.py
OI rmdir gives errno 17 EEXIST when trying to remove a non-empty dir,
not ENOTEMPTY like other OSes.
Also: fix one error handler to also use a tuple-member check instead of "or".
> fix locking on openindiana, fixes #5271

- src/borg/testsuite/archiver.py
According to the manpage, `false` is only guaranteed to return with an exit code indicating an error. However, the manpage is silent on the exact code returned.
Likely fixes #5273.
> Stop relying on `false` exiting with status code 1

- src/borg/archiver.py
It seems that the item flags are only used in create and recreate --list, so there is no point in moving them out, and it's better to just link them in recrate.
> docs: point to borg create --list item flags in recreate usage, fixes #5165

- docs/faq.rst
Add a note about cache ballooning up on cache recreation, and that the workaround may be removed once cache is already in place.
> [Docs] Notes about borg cache workaround

- docs/faq.rst
and how the workaround applies to that.
https://github.com/borgbackup/borg/pull/5280 for `1.1-maint` branch
> Better description of how cache and rebuilds of it work

- docs/installation.rst
With the new Homebrew [formula](https://formulae.brew.sh/formula/borgbackup) merged, some minor updates to the install instructions were needed.
> Update Homebrew install instructions. See #5185

- src/borg/repository.py
We already have used SaveFile context manager since long at other places.
By using it, the original segment file stays in place until recovery of it
is completed (writing/syncing into *.tmp).
On successful completion, .tmp is renamed over original + dir syncing.
If aborted by some exception, including Ctrl-C, the original file is unmodified.
Fixes #5325.
> check --repair: fix potential data loss, fixes #5325

- Vagrantfile
- scripts/borg.exe.spec
Directory-style binaries avoid known PyInstaller issues with newer macOS versions: When using a single-file PyInstaller binary on macOS, the required libraries are extracted and individually checked by macOS. This can take 10 to 20 seconds.
A directory-style binary avoids these issues, but isn't as user-friendly, since the user gets to see all the additional library files.
This PR adjusts the PyInstaller spec file to build a dir-style bin for macOS and compresses it as tar file. Users would need to download this file and link `borg.exe` to their `PATH`.
Fixes #5185
> Build directory-based binary for macOS to avoid Gatekeeper delays.

- docs/deployment/pull-backup.rst
[DOCS] Add ssh-agent pull mode
Closes #5287 .
> Add ssh-agent pull backup method to doc

- setup.cfg
Undeclared markers trigger a pytest warning:
PytestUnknownMarkWarning: Unknown pytest.mark.allow_cache_wipe - is this a typo?
Backport of #5197
> declare "allow_cache_wipe" marker in setup.cfg to avoid pytest warning

- .travis.yml
- .travis/install.sh
- Vagrantfile
- docs/development.rst
- docs/installation.rst
- setup.py
py35 is EOL.
TODO: check if the openindiana vagrant box works as expected.
> drop python 3.5, fixes #5344

- scripts/shell_completions/zsh/_borg
Namely:
- add tags to all untagged contexts;
- don't leak $debug_commands;
- plus some cosmetic changes.
> Fix a few issues in zsh completion

- scripts/shell_completions/zsh/_borg
Turns out only zsh needed an update.
> Update shell completions

- src/borg/archiver.py
> docs: mention double --force in prune docs

- scripts/shell_completions/fish/borg.fish
As requested, the 1.1 backport. I used the squashed commit you performed in #5256 
```
git checkout 1.1-maint
git cherry-pick 8b30a76ae2e5c56e5cbf16ae3e389a29dd66be85
```
> Support repositories in fish tab completion (#5256)

- Vagrantfile
otherwise it does not find the C compiler.
also: add a note that we want to have python-37 package (in a comment,
because it is already preinstalled in our base VM image).
> vagrant: install gcc-7 on openindiana

- docs/deployment/pull-backup.rst
deployment docs: add ssh-agent pull backup method
Co-authored-by: Король Алексей <a.korol@npp-crts.ru> (main work)
Co-authored-by: Thomas Waldmann <tw@waldmann-edv.de>
(cherry picked from commit aef5e89126ffa3f0608d76eefaa1ecf6f0174632)
Includes changes from #5288
> Add ssh-agent pull backup method to doc (#5288)

- .travis.yml
- .travis/install.sh
- Vagrantfile
- setup.py
- tox.ini
Add python 3.9 support in `tox.ini`, `.travis.yml`, `Vagrantfile` and metadata in `setup.py`
> Enable Python3.9 env for test suite and VMs

- Vagrantfile
python 3.7 is the latest python release with good support by pyinstaller
4.0, so use latest 3.7.x to build the binary.
for testing borg on py36, use 3.6.1 because 3.6.0 breaks coverage-py.
also: upgrade 3.9.0rc2 to 3.9.0.
**no backport to 1.1-maint yet, maybe after 1.1.14 release**
> vagrant: use py37 for binary creation

- AUTHORS
I retired from this project in 2016, yet I still regularly get support requests by email. I rarely have time to answer those requests, which are better served by community infrastructure anyways.
I suspect other members of the borg "collective" are retired as well, but I do not want to make any claims in that regard.
> mark myself as retired

- setup.py
- setup_xxhash.py
- src/borg/algorithms/checksums.pyx
- src/borg/algorithms/xxhash-libselect.h
similar to the code we already have in master branch.
thanks to @LocutusOfBorg !
fixes #5400.
> enable using libxxhash (1.1-maint only)

- src/borg/archiver.py
This addresses #4009. The documentation now explicitly mentions
btrfs subvolumes.
I'm happy to change the wording if the PR is welcome but the exact wording is not.
> Clarify '--one-file-system' for btrfs

- src/borg/archiver.py
looks like the previous try to fix this was incomplete.
> fix --dry-run and --stats coexistence, fixes #5415

- src/borg/archiver.py
Python 3.8 changed the default format to PAX, but GNU format is documented for Borg.
Fixes #5274
> export-tar: set tar format to GNU_FORMAT explicitly

- tox.ini
tox.ini still had py35 in it's configuration while the setup.py [specifies](https://github.com/borgbackup/borg/blob/master/setup.py#L297) that the minimum supported version is py36.
This commits fixes this issue.
Fixes #5426
> Remove Python3.5 from tox.ini as it is not supported anymore

- docs/internals/data-structures.rst
We know use only "target chunk size" when speaking of the chunk size
that is expected to happen most of the time. This removes statistical
and mathematical inacurracies that could be troublesome for mathematical
people.
Fixes #5336
> Change documentation inaccuracy on chunk size.

- src/borg/archive.py
- src/borg/archiver.py
- src/borg/constants.py
--stdin-mode, --stdin-user and --stdin-group options added
File mode forces to regular file with other values from the option --stdin-mode. Default mode is 0o100660.
Error occurs if given user or group do not exists. Default user and group values are taken from system uid/gid 0
> create: implement --stdin-mode, --stdin-user and --stdin-group, #5333

- src/borg/repository.py
Hello! Thanks for Borg, it's great!
I ran into an `[Errno 5] Input/output error` when doing `borg init`. It occurs when Borg tries to hardlink `config` to `config.old`. Since the code already ignores (with warning) a few errors from `os.link`, I just added `EIO` (errno 5).
For some more context, I'm running Borg in Docker on Mac. Docker for Mac recently changed the default bind mount filesystem from `osxfs` to `gRPC-FUSE`. It's `gRPC-FUSE` that has this hardlink error. I can workaround by switching Docker back to `osxfs`, but that's slower. So it seems preferable to be able to run Borg on the newer filesystem.
> Allow EIO with warning when trying to hardlink

- src/borg/archive.py
- src/borg/archiver.py
- src/borg/constants.py
--stdin-mode, --stdin-user and --stdin-group options added
File mode forces to regular file with other values from the option --stdin-mode. Default mode is 0o100660.
Error occurs if given user or group do not exists. Default user and group values are taken from system uid/gid 0
> create: backport implementation --stdin-mode, --stdin-user and --stdin-group, #5462

- .travis.yml
- kill the macOS builds, way too expensive (and problematic anyway)
- kill the builds on python development versions, can't afford any more
> reduce testing on travis, no macOS, no py3x-dev, see #5467

- .travis.yml
- kill the macOS builds, way too expensive (and problematic anyway)
- kill the builds on python development versions, can't afford any more
> reduce testing on travis, no macOS, no py3x-dev, see #5467 (1.1-maint)

- src/borg/testsuite/archiver.py
Fixes #5438. The issue here was kind of funny. I ran the tests 1000 times, and they failed 4 - very close to 1/256th of the time. Then the problem became obvious: the corrupt() function wasn't corrupting the cache file if it did in fact originally end in "1".
> Fix spurious failure in test_cache_files

- src/borg/archiver.py
> Clarify '--one-file-system' for btrfs (1.1 backport)

- src/borg/testsuite/archiver.py
> Fix spurious failure in test_cache_files (1.1 backport)

- src/borg/archiver.py
- src/borg/helpers/parseformat.py
- src/borg/testsuite/helpers.py
Fixes #5189. `{now}` and `{utcnow}` will take the value of `--timestamp` if given. I also added a test for this functionality.
> Use --timestamp in placeholders if given

- src/borg/archiver.py
- src/borg/helpers.py
- src/borg/testsuite/helpers.py
> Use --timestamp in placeholders if given (1.1 backport)

- src/borg/helpers/parseformat.py
- src/borg/helpers/time.py
- src/borg/testsuite/helpers.py
This is a forward-port from my [back-port](https://github.com/borgbackup/borg/pull/5488) of #5472. Making the timestamp value timezone-aware makes `{now}` different from `{utcnow}`, which upon another look I think is what was [originally intended](https://github.com/borgbackup/borg/issues/5189#issuecomment-629865397).
Also, I got rid of a duplicate function that was accidentally added during a refactor.
> Timestamp fixes

- docs/deployment/central-backup-server.rst
I replaced the [pacman module](https://docs.ansible.com/ansible/latest/collections/community/general/pacman_module.html) with the [package module](https://docs.ansible.com/ansible/2.3/package_module.html), so the snippet work for most linuxes, and not only arch.
I also switched state from `latest` to `present` : it is meant to preserve idempotency. This is a [debattable change](https://github.com/ansible/ansible-lint/issues/479).
> Doc / Deployment with ansible: generic install

- docs/deployment/central-backup-server.rst
Backport of #5464 to 1.1-maint branch (documentation : ansible).
> Doc / Deployment with ansible: pacman -> package

- docs/deployment/pull-backup.rst
- docs/faq.rst
> Update the documentation on hacked backup client.

- src/borg/archive.py
- src/borg/archiver.py
As discussed on IRC, i'd like to do somewhat complex file matching rules (in particular contextual stuff like: "if directory contains `Cargo.toml` exclude `target`"). Other requests for complex matching are #4102 (stat-based filtering). The proposition is to add a lower-level mode for archive creation where borg would read on stdin for paths which it would add to the archive (still checking if stuff has changed but not recursing into directories). Then arbitrarily complex matching can then be scripted by the user as eg `find ... | borg create-nowalk`.
I'm starting the PR with only a single commit to gather comments, i intend to push more stuff before merge. I refactored `Archiver._process` into `Archiver._rec_walk` (which is functionally just a renaming of `Archiver._process`) and …
> Outsource recursive directory walking

- docs/faq.rst
Now the FAQ warns that a sleeping computer can lead to a broken pipe
when backing up over ssh.
Fixes #5301
> Add a hint on sleeping computer in the FAQ

- src/borg/helpers/fs.py
This patch introduces a new function that atomically checks if the given
directory exists or not, and if not, tries to fix it.
The error is reraised if necessary with a nice catching.
Fixes #5216.
> Fixes BORG_CACHE_DIR crashing borg if empty

- borg/testsuite/hashindex.py
for the bug, see #4829.
1.0-maint backport.
> add a test for the hashindex corruption bug, fixes #5531

- docs/internals/data-structures.rst
> Complements the documentation for pattern files and exclude files, fixes #5336 [1.1]

- README.rst
- docs/internals/security.rst
- src/borg/archiver.py
- src/borg/compress.pyx
- src/borg/helpers/checks.py
- src/borg/testsuite/compress.py
See #3687 for the problem discussion.
This PR would make a borg repo harder to attack using a known set of small file sizes fingerprinting attack.
Notes:
- borg client side will still store the real size (and overall csize) into client-side indexes
- borg server side segment files will only store overall csize (result of compression + obfuscation)
- plaintext size information in archive metadata is encrypted, attacker on repo side can't see it
- attacker does not know exact amount of obfuscation and can also only guess compression algo/level
- no problem adding just a random amount of zero bytes because encryption will make them look random
- but it is important to not compress these, because compressor could reduce a lot of zeros to just a few bytes e.g. due to run-length encoding (RLE), …
> Chunk size obfuscating "compressor"

- .github/workflows/ci.yml
sometimes they hung for 6h... (not our fault, seems like a infrastructure problem).
> add a timeout for the github CI jobs, fixes #5548

- docs/deployment/hosting-repositories.rst
- docs/faq.rst
I have updated both the FAQ and the https://github.com/borgbackup/borg/blob/master/docs/deployment/hosting-repositories.rst files.
Fixes #5497
> Complete documentation on append-only remote repos

- src/borg/archiver.py
- src/borg/helpers/misc.py
- src/borg/helpers/parseformat.py
- src/borg/testsuite/archiver.py
- src/borg/testsuite/helpers.py
WIP. Follow-up of #5492. Implement two switches which shortcut the filesystem-walking logic completely: borg will read the paths and backup without doing any recursion (directories can --and should-- be passed). Should honor any relevant option (common options and all filesystem option but --one-file-system).
Slight change from my earlier proposal: now if either `--paths-from-stdin` or `--paths-from-command` are given, then it won't process any normal path from `args.path`. In `--path-from-command` it wouldn't make sense anyway since `args.path` is being used for the command. Technically, for `--paths-from-stdin` we could still handle `args.path` as usual but it's probably safe to assume that a user don't want to mix both things. Besides it simplifies the code and the top-level behavior …
> create: implement --paths-from-stdin and --paths-from-command

- docs/deployment/hosting-repositories.rst
- docs/faq.rst
Backport the documentation changes to 1.1-maint.
> Complete documentation on append-only remote repos for 1.1-maint

- src/borg/archive.py
emit a warning message giving the path and the xattr key,
which is better than the previous output only refering to a
FD and not giving the xattr key.
also: continue trying to restore other xattrs and bsdflags afterwards
(it did not continue with this before this fix).
> extract: catch EPERM when setting xattrs, fixes #5092

- src/borg/testsuite/archiver.py
- src/borg/xattr.py
> extract: improve setxattr exception handling

- src/borg/archiver.py
- src/borg/testsuite/archiver.py
- do not archive duplicate roots (skip via inode)
- thus, it is also not extracted twice, avoiding issues
> do not recurse into duplicate roots, fixes #5603 (master)

- src/borg/archive.py
- src/borg/archiver.py
- src/borg/chunker.pyx
- src/borg/constants.py
- src/borg/testsuite/benchmark.py
- src/borg/testsuite/chunker.py
- src/borg/testsuite/chunker_pytest.py
- src/borg/testsuite/chunker_slow.py
fixes #5566 
the chunker now yields namedtuples (data, meta), so that sparse holes can be processed differently than normal data.
to avoid hashing the all-zero blocks again and again, a LRUcache for a few popular block sizes and their hashes is maintained.
this speeds up processing of sparse holes / all-zero blocks a lot.
additionally to all-zero sparse holes, the fixed-blocksize chunker now can also detect all-zero from-disk reads (allocation type CH_ALLOC).
also refactored all places that need to compare against `zeros` so that we only have one big all-zero-bytes object.
also added all-zeros detection for the buzhash chunker (here the results for a huge, completely sparse file).
Some stats:
- buzhash chunker, before this PR: Duration: 2 minutes 20.14 seconds
- buzhash chunker, after …
> Sparse file support (integration)

- docs/development.rst
- docs/installation.rst
See #5504 for motivation. The current installation instructions are confusing and result in failing tests on a typical setup, this adds a link back to an earlier section that's mentioned in the dev environment setup and changes the installation instructions to recommend only running the tests for installed versions of python.
> Update docs for dev environment installation instructions

- docs/usage/create.rst
Closes #5551
Added some examples for these options to the `borg create` documentation, one that showcases each of them.
> add examples for --paths-from-stdin, --paths-from-command, --paths-separator

- src/borg/repository.py
- src/borg/testsuite/repository.py
also:
- add test for removed empty shadowed_segments list
- add some comments
- add repo_dump test debug tool
> remove empty shadowed_segments lists, fixes #5275

- src/borg/repository.py
@timmc found:
"I notice that Repository.put doesn't add to shadow_index -- is that intentional? Not sure if there's an impact on this PR."
See commit comments.
> Fix "put updates shadow index"

- scripts/shell_completions/bash/borg
- scripts/shell_completions/fish/borg.fish
Bash and Fish tab completions now too support more than just one archive provided for 'borg delete'.
> Tab completion support for additional archives for 'borg delete'

- src/borg/archive.py
- src/borg/archiver.py
Ensure `Statistics()` instance used by `FilesystemObjectProcessors()` obeys `--log-json` argument. (needed for Vorta status logs)
See comment https://github.com/borgbackup/borg/issues/4360#issuecomment-774580052
> Pass args.log_json to FilesystemObjectProcessors/Statistics instance

- docs/installation.rst
- Add our in-house tap as alternative, if FUSE support is needed
- Add dependencies to install via Homebrew, when installing from source
- Add note about quarantine attribute when downloading binary release
Fixes #5522, fixes #5622
> Update macOS install instructions

- docs/deployment/automated-local.rst
- docs/quickstart.rst
This is generally a poor idea and shouldn't be promoted through examples.
Fixes #5625
> docs: remove /var/cache exclusion in example commands

- Vagrantfile
FreeBSD 10.x is not supported any more, the pkg sources are not
available any more, so our VM needed an upgrade.
so, we'll build borg 1.1.x binaries on FBSD 11.4 in future.
additionally, pyinstaller had some regression that is fixed by v4.2.
in v4.2-maint branch i added the FBSD bootloaders, which were missing
as usual.
> upgrade FreeBSD VM to 11.4, pyinstaller to v4.2, fixes #5688

- src/borg/helpers.py
backport of comment from a77db94b010bdec71637a6a73ca0788c1e78bae4
just to avoid future bugs.
> backport comment about archives.list() defaults

- src/borg/repository.py
- src/borg/testsuite/repository.py
This is a mostly cosmetic backport of master repository code changes (3 master PRs).
Due to the differences in 1.1-maint (always compact after commit, not persisting shadow_index), it is just to keep the code in sync and not strictly needed otherwise. There is also that code dedup part in put/delete, which is nice to have.
Fixes #5446.
> Repo changes backport to 1.1-maint

- .github/workflows/ci.yml
- setup.py
- src/borg/algorithms/msgpack/_unpacker.pyx
- src/borg/algorithms/msgpack/_version.py
- src/borg/helpers.py
- tox.ini
This is my attempt to solve #5683.
We should also update the msgpack version as [requested by @ThomasWaldmann](https://github.com/borgbackup/borg/issues/5683#issuecomment-777781315) and [@RonnyPfannschmidt](https://github.com/borgbackup/borg/issues/5683#issuecomment-777794854). The version is currently `version = (0, 5, 6)`.
Updating to 0.5.7 is easy though I also like the idea of using a more descriptive version number. As far as I can see nothing in borg uses the msgpack version number so we could also change to `version = (0, 5, 6, '+borg')` easily. Comments?
----
Commit message
The old buffer protocol was deprecated since Python 3.0 and will be removed entirely in Python 3.10.
This is a backport of
commit 9ae43709e42092c7f6a4e990d696d9005fa1623d
Author: Inada Naoki …
> msgpack: drop support for old buffer protocol

- src/borg/archive.py
- src/borg/archiver.py
- src/borg/fuse.py
- src/borg/testsuite/archive.py
this is different default behaviour than in borg < 1.2:
default (numeric_owner=False) is to use the user/group name from the archive,
look up the local uid / gid and then use that for the FUSE fs.
when --numeric-owner is given (numeric_owner=True), then the uid/gid
from the archive is directly used (as it was the default behaviour in
borg < 1.2).
this was implemented like this (changing the default behaviour) to make
borg mount and borg extract behave more similar considering usage of
user/group numeric archived ids or archived names mapped to corresponding
numeric local system ids.
also, both now use the same function to get the uid/gid from the item.
fixes #2377
> mount: implement --numeric-owner (default: False!)

- .github/workflows/ci.yml
it breaks everything due to issue #5729 - reenable after fixing that.
> don't test on py310 for now

- src/borg/archiver.py
Here is the backport from #5737, learned something new (`git cherry-pick`).
> docs: Add commas to pattern help section

- conftest.py
- scripts/errorlist.py
- setup.cfg
Update flake8 config to enforce desired 120 char line length and fix non-conforming files.
> cleanup code style checks

- conftest.py
- scripts/errorlist.py
- setup.cfg
@ThomasWaldmann, how about I start with this to grandfather in specific files that violate some checks. This will make sure that all other files meet the requirements and allow us to fix smaller sets of files, reducing conflicts for active PRs.
> 1.1-cleanup code style checks

- src/borg/archive.py
- src/borg/archiver.py
- src/borg/cache.py
- src/borg/helpers/parseformat.py
- src/borg/testsuite/helpers.py
A (minor) source of confusion for me are the sizes expressed in powers of 1000 instead of 1024 ([1KB = 1000B vs 1KiB = 1024B](https://en.wikipedia.org/wiki/Binary_prefix)), which is not consistent with the units used by many commands (`ls -h`, `df -h`, `du -h`, `dd`…).
To make it consistent,  add a common option (`--iec`).
For now, it's implemented for:
- info
- create --stats
> Add option to express sizes in powers of 1024 (KiB, MiB…)

- src/borg/archive.py
- src/borg/archiver.py
if we back up stdin / pipes / regular files (or devices with --read-special),
that may take longer, depending on the amount of content data (could be many GiBs).
usually borg announces file status AFTER backing up the file,
when the final status of the file is known.
with this change, borg announces a preliminary file status before
the content data is processed. if the file status changes afterwards,
e.g. due to an error, it will also announce that as final file status.
> print preliminary file status early, fixes #5417

- src/borg/item.pyx
- src/borg/testsuite/archiver.py
- tox.ini
the move of the function supports easier building of microbenchmarks against #5763 
the changes in tox.ini enabled running the tox command even when the system python is not ready,
it may be advisable to use pyproject.toml in future
> move chunk_equals to module level and modernize tox.ini

- src/borg/archiver.py
now both behave the same:
borg --iec info REPO
borg info --iec REPO
> fix --iec option when given after "borg"

- docs/changes.rst
fix typo from the latest release in `docs/changes.rst`
> Fix typo in changes.rst

- src/borg/archive.py
Depending on the number of archives in a repository, the archive check part
of the check operation can take some time, so it should have a progress
indicator as well.
1.1.x version of #5809, no changes needed.
> add progress indicator for archive check

- README.rst
The irc webchat link still pointed to Freenode while the IRC channel on the main page points to libera.chat.
> Fixed the Readme.rst irc webchat link.

- src/borg/locking.py
note: no port to master branch needed, locking code was already improved/fixed there by @alfredo08154711.
> handle crash due to kill stale lock race, fixes #5828

- src/borg/archive.py
- src/borg/archiver.py
- src/borg/helpers/misc.py
- src/borg/helpers/process.py
- src/borg/testsuite/archiver.py
based on #2234 - thanks to @enkore! fixes #2233.
rebased on / adapted to current master, also implemented my review feedback from back then.
TODO:
- Input I/O errors are always fatal, no matter what, Borg is not a tar-forensics-tool.
Decompressor runs in a separate process and can also be set via command line arg. That's not only more flexible than what the tarfile module does, but it also doesn't clog our process with compression I/O + CPU.
> implement simple import-tar

- src/borg/archive.py
This is a forward-port attempt of #5823. It is intended to be part of issue #5839.
> fix missing parameter in "did not consistently fail" msg, see #5822

- src/borg/archiver.py
This is a forward-port attempt of #5835. It is intended to be part of issue #5839.
> create --dry-run: fix display of kept tagfile, fixes #5834

- docs/faq.rst
This is a back-port attempt of #5519. It is intended to be part of issue #5838.
> Complete documentation on append-only remote repos (#5519)

- .github/workflows/ci.yml
- Vagrantfile
- setup.py
- src/borg/testsuite/archiver.py
- tox.ini
if you do not have python >= 3.7, you can still use borg 1.1.x or 1.0.x.
another option is to use the fat binary from github releases, which
includes python and all other stuff needed.
> drop support for py36, require py37+, fixes #5790

- docs/changes.rst
- docs/faq.rst
- docs/installation.rst
- docs/internals/data-structures.rst
- docs/internals/security.rst
- docs/usage/notes.rst
- scripts/shell_completions/fish/borg.fish
- scripts/shell_completions/zsh/_borg
- src/borg/__init__.py
- src/borg/archiver.py
- src/borg/helpers.py
- src/borg/locking.py
- src/borg/logger.py
- src/borg/paperkey.html
- src/borg/patterns.py
- src/borg/repository.py
- src/borg/testsuite/__init__.py
- src/borg/testsuite/archiver.py
- src/borg/testsuite/hashindex.py
This is a back-port attempt of #5597. It is intended to be part of issue #5837.
Note this is a manual revamp of the original merge commit due to the sheer number of differences. Notably some didn't apply because they were not present in this older version and some files were not present or were shuffled around.
`README_WINDOWS.rst` doesn't exist in this older release and appears to not exist anywhere else either.
`src/borg/compress.pyx` had no relevant typos in this release.
`src/borg/helpers/errors.py` and `src/borg/helpers/progress.py` didn't exist but their typos exist in this version under `src/borg/helpers.py`.
> Fix typos (backport of #5597)

- src/borg/archive.py
if the tar has no information about user/group name (empty string),
we must assign None to Item.user/group (not the empty string).
Fixup for #5650.
> import-tar: fix empty user/group name in TarInfo, fixes #5853

- src/borg/archiver.py
I noticed the changes I did were to the generated files and not the original source. This should correct that.
> add paragraph added in #5855 to utility documentation source

- docs/usage/check.rst.inc
- src/borg/archiver.py
This should close #5808 and count towards completion of #5129.
> resolve clarify borg check --verify-data (#5808)

- docs/usage/check.rst.inc
- src/borg/archiver.py
This is the back-port of #5855 for #5129.
> add notice about defective hardware to check documentation (#5753)

- docs/conf.py
the same change was done as part of 6a1f31bf2914d167e2f5051f1d531d5d4a19f54b for master. I would like to have this in `1.1-maint` because `.add_stylesheet()` was removed in Sphinx 4 and that version will be added to Fedora rawhide (aka Fedora 35) soon.
> docs: replace deprecated function ".add_stylesheet()" for Sphinx 4 compatibility

- src/borg/helpers/parseformat.py
I have changed the VALID_MODES in the FilesCacheMode function in parseformat.py and added 's' for size only mode.
Fixes #5686.
> Allow --files-cache=size

- docs/faq.rst
Hi!
I think that `tar --compare` is not very widely known, and it would be nice to mention this trick in the FAQ
> docs: mention tar --compare

- src/borg/xattr.py
this was a remainder from 1.1-maint, but is not used any more.
> remove unused libc_name

- src/borg/archiver.py
In issue #5630 it was specified that when `borg benchmark` is called with wrong arguments or with permission issues, the folder `borg-test-data` is not deleted.
During tests I have also discovered that the same happens when borg receives a `keyboard interrupt` while executing the benchmark.
To solve this problem, a `try/finally` block was added in method `test_files`, to make sure the command that removes the folder will be executed (in the `finally` statement) even if the code in the `try` statement fails.
In my tests, this have solved the issue on the specified test cases and in the case of the keyboard interrupt.
This PR resolves #5630
> Adding try/finally block to make sure cleanup happens

- src/borg/archiver.py
fwd port of #5905.
there was a similar phrasing already, but this commit gets messages in sync
with borg 1.1 again.
> docs: clarify "you will need key and passphrase" borg init warning, fixes #4622

- src/borg/helpers.py
"running under pyinstaller" detection is now as recommended by the pyinstaller docs.
> fix pyinstaller detection for dir-mode, fixes #5897

- docs/faq.rst
> docs: remove duplicate faq entries

- src/borg/fuse.py
we require >= 1.3 now anyway, see setup.py.
Looks like this was forgotten to backport to 1.1-maint and also was a remainder still requiring distutils.
Thanks to @LocutusOfBorg for pointing to the right changeset in master.
> fuse: remove unneeded version check and compat code

- docs/installation.rst
Fixes #5942, backports #5945
As requested, checked the Vagrantfile and the versions seem to be the same.
> docs: update referenced freebsd version (#5945)

- docs/usage/help.rst.inc
Fixes: #5300
This incorporates the comments from `patterns.py` into the documentation
to clarify the difference between `pp` and `pf`.
> docs: clarify pp pattern type

- src/borg/patterns.py
When exclude files are used, this can trigger a stack trace if the file
does not exist. Instead exit nicely without the stacktrace.
Fix #5734
> Use an exception catching to avoid a stack trace

- docs/usage/help.rst.inc
- docs/usage/list.rst
- src/borg/archiver.py
> docs: clarify pattern usage with commands

- Vagrantfile
note: no 1.1 backport of this (1.1 uses 3.9.0 for testing and 3.7 for binary builds)
> vagrant: use py 3.9.7 (incl. binary builds)

- src/borg/helpers/fs.py
fixes #5979.
but please note that this does not mean that "keys" and "security" are or will ever be the only subdirs below the borg config dir.
> do not require BORG_CONFIG_DIR if BORG_{SECURITY,KEYS}_DIR are set

- docs/usage/general/environment.rst.inc
- src/borg/archive.py
Fixes https://github.com/borgbackup/borg/issues/6024
src/borg/archive.py changed too much in master for this patch to apply. If master is affected by the same problem a different workaround will have to be used.
> Workaround for volume shadow copy in WSL1

- src/borg/repository.py
When an object is corrupted, the start position of the next object
will not be known as the size field belonging to the corrupted
object may be corrupted as well. In order to find the next object
within the segment, the remainder is scanned for the next valid
object, byte-by-byte. An object is considered valid if the CRC
checksum matches the content. However, doing so the scan accepted
any object size that fit within the remainder of the segment. As a
result, in particular when the corruption occurred near the start
of a segment, CRC checksums were calculated for large objects,
often hundreds of megabytes in size, despite the size being limited
to 20 MiB. This change makes it so that CRC calculation is skipped
when the object header indicates an impossible size, thereby,
greatly reducing …
> Speed up search for next valid object in segment in --repair mode

- src/borg/repository.py
Backport of #6022 as requested by @ThomasWaldmann.
> Backport of #6022: Speed up search for next valid object in segment in --repair mode

- scripts/shell_completions/zsh/_borg
BORG_LIBC was added in a4f7e69 to allow borg to work on systems where 
ctypes.util,find_library() fails. Since 9914968 borg no longer uses 
find_library(). This removes the need to forward port #6008
> Remove BORG_LIBC completion

- src/borg/archive.py
Submitted on `1.1-maint` because the code in question has been moved, removed, or refactored on `master`.
> avoid expanding path into LHS of formatting operation, see #6063

- src/borg/testsuite/archiver.py
- src/borg/xattr.py
Fixes #6063 (xattrs not supported warning during extract fails due to % in filename)
Forward port #6064 (avoid expanding path into LHS of formatting operation)
I took the liberty of adding tests that the original PR neglected. Once this is merged I'll backport the tests
> Forward port #6064: avoid expanding path into LHS of formatting operation

- src/borg/archiver.py
- src/borg/helpers.py
- src/borg/testsuite/archiver.py
- src/borg/testsuite/helpers.py
Backport #6023 (do not show archive name in error msgs referring to repository)
The original PR did not have a test to prove that the bug is fixed so I took the liberty of adding one. After this is merged I'll forward port the test to master.
> Backport #6023: do not show archive name in error msgs referring to repository

- src/borg/testsuite/archiver.py
This test was originally added in #6071
> Forward port: Test that the archive name is not mentioned

- src/borg/archiver.py
While reading the docs I noticed that in `borg list` the options --list-format and --format do the same thing. Using `git log -S` I have uncovered that --list-format used to be deprecated and was supposed to be removed in c87393cab736d30a3c138f5f694c8cc0c8ca6ccc, but you overlooked it and undeprecated it instead. *What should we do now? Just remove it or deprecate it again?*
> Remove --list-format from borg list

- src/borg/archiver.py
- src/borg/helpers/parseformat.py
Fixes #6061
I have added 3 examples of formatting usage and a link to the documentation for the full syntax.
See also  #6079
> Improve docs for `borg list` --format

- docs/usage/import-tar.rst
- src/borg/archiver.py
While doing some doc updates I needed a way to test them - to build
the documentation and inspect the output. I ran into an issue:
running python setup.py build_man was throwing exceptions:
1. The import-tar parser had a None description causing:
File "/home/user/borg/setup_docs.py", line 451, in write_heading
write(char * len(header))
TypeError: object of type 'NoneType' has no len()
2. There was no docs/usage/import-tar.rst causing an exception too
> Fix exceptions thrown by `setup.py build_man`

- docs/deployment/pull-backup.rst
Backport from master.
This is not improving the warnings etc. yet - just a fix for the broken menu indentation in 1.1-maint, which has been fixed already in master.
I will add more improvements in master branch, and finally backport them later.
> #5903 - Test/improve pull backup docs

- .github/workflows/ci.yml
test_fuse hangs (tried with osxfuse as well as with macfuse) for yet unknown reasons.
> macos ci: no fuse tests for now, fixes #6099

- src/borg/testsuite/archiver.py
the tests do object patching, this does not work when we call the external binary "borg.exe".
this made these tests fail IF the borg.exe was available (like in the debian stretch vagrant VM).
> fix new xattr tests for binary test runs

- scripts/shell_completions/fish/borg.fish
Fish 3.3.0 enabled stderr-nocaret flag by default which breaks stderr redirection with "^/dev/null". A posix-like "2>/dev/null" has to be used instead.
More details:
https://github.com/fish-shell/fish-shell/pull/7907
https://github.com/fish-shell/fish-shell/issues/7105
I wasn't enable to establish where "2>..." support had been added, but looking at https://github.com/fish-shell/fish-shell/issues/4394, I believe it was "long time ago". As a result, I propose to put it also in the next 1.1.x release (if any).
> Fix command & switch completion in Fish 3.3.0+

- docs/faq.rst
It was unclear that the user _only_ needs to have borg installed on a remote system to use client/server mode. Hopefully this change makes it apparent that the user doesn't start anything on the remote system themselves.
If the language is awkward or even more unclear, I'm happy to make changes
> clarify who starts the remote agent

- docs/usage/extract.rst.inc
- docs/usage/help.rst.inc
> docs: excluded parent dir's metadata can't restore.

- src/borg/archiver.py
- src/borg/crypto/keymanager.py
Implemented #6092. "borg key export [REPOSITORY]" now prints out the key
> key export: print key if path is '-' or not given, fixes #6092

- docs/usage/general/environment.rst.inc
thanks to @snsmac for the hint: there is no code implementing this any more. it was replaced by
BORG_HOST_ID (if needed).
> remove leftovers of BORG_HOSTNAME_IS_UNIQUE from docs

- src/borg/testsuite/archiver.py
> Backport: fix new xattr tests for binary test runs

- .github/workflows/ci.yml
This is a work around for #6099
This is a backport of #6125
> Downgrade to macOS 10.15 as macOS 11.x breaks fuse2 testing.
>
> On macOS 10.15, osxfuse and also macfuse works with borg's fuse2 tests.
>
> Upgrading to macOS 11.x based github CI breaks the tests, see #6099,
> even when using the more recent macfuse to provide fuse2 capability.
> Why did you switch from osxfuse to macfuse?
> strictly taken, the switch was not required, it also worked with osxfuse after the macos downgrade.
>
> but considering a later potential upgrade of macos to some more recent version again (after the hanging issue is analyzed and fixed), i wanted to switch to the more recent macfuse code to be prepared for that.
> Backport: CI: macOS: re-enable fuse2 testing

- setup.py
thanks to everybody who helped with this, esp. @th0ma7 and @methane.
> remove endianness macro, fixes #6105

- docs/quickstart.rst
Original wording was confusing
> Avoid to create a mixup of users and permissions in your repository (or cache).
It is not clear, what should be avoided?
> minor rewrite to make it less confusing (get rid of "Avoid to create a mixup")

- src/borg/archiver.py
What `borg prune` is mostly doing is also known as grandfather-father-son method (see link in code). I think it makes sense to put the words `rentention policy` and `backup rotation scheme` and most importantly, `GFS` to the docs. This increases the chance of stumbling upon borg when googling for these kinds of things. Do you agree?  For example, I was researching this a bit and found (and used) https://github.com/shello/gfs.py long before I knew borg was a thing.
This only makes sense if the change does not stay on master branch eternally. For example, the line above (`Important: Repository disk space is **not** freed until you run borg compact.`) has been commited three years ago but is still not present in the (stable, default) docs? That's a bit weird, not sure if I am …
> docs: add note about GFS

- src/borg/testsuite/archiver.py
In #6152 you have neglected to add a regression test for the bug you fixed. This is the test.
> Add test for: info: emit repo info even if repo has 0 archives

- src/borg/archiver.py
- src/borg/testsuite/archiver.py
Fixes #6120
This is a backport of https://github.com/borgbackup/borg/pull/6152
This also includes a backport of https://github.com/borgbackup/borg/pull/6155
> Backport: info: emit repo info even if repo has 0 archives

- src/borg/repository.py
- src/borg/testsuite/repository.py
see commit comments.
for master branch, these fixes are required, because we have delayed compaction (separate `borg compact` command).
for 1.1-maint, they could be also applied, but are not that important because compact_segments is always called after writing.
> repository: quota computation fixes for delayed compaction

- docs/usage/extract.rst.inc
- docs/usage/help.rst.inc
- src/borg/archiver.py
The PR #6062 made a mistake: it updated the generated files instead of the source. This is the fix
Refer to discussion in #5680.
> docs: excluded parent dir's metadata can't restore

- src/borg/archiver.py
- src/borg/crypto/keymanager.py
Backport of #6093
key export: print key if path is '-' or not given, fixes #6092
"borg key export [REPOSITORY]" now displays the key.
> Backport key export: print key if path is '-' or not given, fixes #6092 (#6093)

- .github/workflows/ci.yml
- Vagrantfile
Backport of #6116.
I did not port the lines from
https://github.com/borgbackup/borg/pull/6116/files#diff-1ea02434f746b6d1522cdef3d4a56e57cf2d5a72c5273927746a71eaf06d74fdR182-R183
because this branch still uses 3.7
> Backport upgrade pythons (#6116)

- setup.py
- setup_xxhash.py
- src/borg/algorithms/xxh64/xxhash.h
@LocutusOfBorg this is inspired by your debian patch.
https://salsa.debian.org/debian/borgbackup/-/blob/master/debian/patches/bundled-xxhash.patch
changes:
- the ".../xxh64" part of the path was missing in your patch.
- xxh64 belongs to checksums module (not crypto)
- getting it to compile (xxh64, zstd with bundled code or with system lib) was a bit of a pain, but I hope it works now
also, i gave xxh64 0.8.1 a try and it worked, so i updated the bundled code.
> fix xxh64 related build

- src/borg/archiver.py
Backport of #6165 which replaces #6062.
> Backport docs: excluded parent dir's metadata can't restore (#6165)

- src/borg/repository.py
- src/borg/testsuite/repository.py
Backport of #6119.
I adjusted the tests a little bit because the commit method is different.
> Backport repository: quota computation fixes for delayed compaction (#6119)

- docs/faq.rst
> Backport: Doc: ~/.config/borg/keys is not used w/ repokey

- docs/installation.rst
Per https://cygwin.com/packages/summary/openssl-devel.html, the Cygwin package "openssl-devel" has been obsoleted by the package "libssl-devel".
Also, if you install just the basic Cygwin package "python3", it now installs Python v3.8.
(There may be other Cygwin package names that need to be changed. I wasn't able to find the package "libopenssl". However, with the list that's given there, I was ultimately able to get everything working.)
> docs: fix/update cygwin package requirements

- src/borg/testsuite/__init__.py
- src/borg/testsuite/archive.py
- src/borg/testsuite/archiver.py
- src/borg/testsuite/hashindex.py
- src/borg/testsuite/repository.py
- src/borg/testsuite/xattr.py
Work toward https://github.com/borgbackup/borg/issues/28
This PR removes the usage of assert_true in the master branch
> Refactor: remove assert_true (master)

- src/borg/testsuite/__init__.py
- src/borg/testsuite/archive.py
- src/borg/testsuite/archiver.py
- src/borg/testsuite/hashindex.py
- src/borg/testsuite/repository.py
- src/borg/testsuite/xattr.py
Work toward #28
This PR removes the usage of assert_true in the 1.1 branch
> Refactor: remove assert_true (1.1)

- src/borg/archiver.py
- src/borg/helpers.py
- src/borg/remote.py
- src/borg/testsuite/helpers.py
- src/borg/testsuite/key.py
- src/borg/testsuite/repository.py
fixes #5826, fixes #5998.
- use expanded location for log output
- support placeholder expansion for BORG_REPO env var
- use Location.raw for the unprocessed, not expanded location string
> repo::archive location placeholder expansion fixes

- src/borg/helpers.py
previously, it just said PermissionDenied with giving the filename/path.
> if ensure_dir() fails, give more informative error message, fixes #5952

- src/borg/repository.py
compact_segments produced separate 17b files for intermediate commits, although they were intended to be end-of-segment-file commits.
this is because when the intermediate commit is triggered, we are already at an offset beyond the limit.
thus needed to add the no_new flag to indicate that we do not want a new segment file just for the commit IF it is an intermediate commit.
> fix intermediate commits, shall be at end of segment

- requirements.d/development.txt
see there: https://github.com/pypa/setuptools/issues/3063
> do not use broken setuptools version

- requirements.d/development.txt
setuptools>45 was added in 0e9befb53953af1ad4f8bd957dfc834fd1daebbe.
This constrint was never backported to 1.1.
My backport honors that.
This is a backport of #6223
Original commit message:
> see there: https://github.com/pypa/setuptools/issues/3063
> Backport: exclude buggy current setuptools release

- src/borg/archiver.py
https://github.com/borgbackup/borg/issues/6204#issuecomment-1027150308
The examples I provided should work in the next 1.2 release and
the next 1.1 release (see #6092 and #6177). Alternatively I could give
the following example that should work today:
```sh
borg key export --qr-html /path/to/repo encrypted-key-backup.html
```
@ThomasWaldmann, you have added "documentation" label after a comment by https://github.com/rolandu. Is this the fix you wanted/expected?
> Doc: borg key export: add examples

- src/borg/crypto/key.py
This commit aims to check to ensure that keys are not overwritten on keyfile repositories by the use of the BORG_KEY_FILE variable. Pretty basic, but I wasn't sure best practice to exit immediately, which is why it throws an exception. If Borg has a better way to handle that, let me know. Took inspiration from https://github.com/borgbackup/borg/blob/450ab38e4227773db83ad45edf5d5e8df7d4e1b8/src/borg/crypto/key.py#L112
Moved passphrase below so people don't put in a passphrase then get told the key is bad.
Issue that spawned this MR:
https://github.com/borgbackup/borg/issues/6036
> Disallow overwriting of existing keyfiles on init

- docs/faq.rst
- src/borg/testsuite/archiver.py
Fixes: #5858
In addition to explaining the consequences of deleting path/to/repo/nonce I have added tests to make sure that what the docs say is actually true.
> Doc: impact of deleting path/to/repo/nonce

- requirements.d/development.txt
This is a backport of https://github.com/borgbackup/borg/pull/6246
> Backport: setuptools 60.7.0 is breaks pyinstaller

- src/borg/crypto/key.py
- src/borg/testsuite/archiver.py
This is a backport of #6046 and #6243
> Backport: Disallow overwriting of existing keyfiles on init

- src/borg/archiver.py
This is a backport of #6242
This also fixes an indentation error in src/borg/archiver.py that caused
the HTML help to look bad (the tail end of the page ended up
*inside* of a code block instead of after it)
> Backport: Clarify usage of patternfile roots

- src/borg/archiver.py
The documentation for borg init was not structured logically:
1. The topic is switched from the general discussion of `borg init`
to the discussion of encryption modes without a title.
2. Obscure technical details (chunking, id generation etc) were
above the high-level overview and other key information.
> Doc: borg init: explain the encryption modes better

- src/borg/hashindex.pyx
- src/borg/testsuite/hashindex.py
the .get() like behaviour (== returning the value) was missing.
it's still not 100% like dict.setdefault, because there is no
default value None. but None doesn't make sense here, because we
usually need a N-tuple matching the hash table's value format.
note: this "bug" (or unusual implementation) was without consequences,
because hashindex.setdefault is not used anywhere in borg, so
it was also not used in a wrong way anywhere.
https://docs.python.org/3/library/stdtypes.html#dict.setdefault
> implement more standard hashindex.setdefault behaviour

- src/borg/archive.py
I was trying the `diff` command with somewhat big archives (60 GB of a Linux root filesystem) but with little differences (the second backup created right after the first one), and it used a lot of memory compared to `export-tar`.
Adding some prints in the code, I figured that `hardlink_masters` grew up to 300k items (the partition has only 10k hardlinks), but most of them were directories.
Compared to the other implementation of [item_is_hardlink_master](https://github.com/borgbackup/borg/blob/master/src/borg/archive.py#L2055), I conclude that storing the directories is a bug.
Comparing version 1.1.17 to `1.1-maint` with this change, it decreases the memory used (measured with `/usr/bin/time -f %M`) from 1.1 GB to 110 MB for the diff between the archives of the Linux partition.
> diff: reduce memory consumption, fix is_hardlink_master

- src/borg/cache.py
- src/borg/helpers/fs.py
- src/borg/platform/base.py
- src/borg/remote.py
- src/borg/repository.py
the previous implementation caused collateral damage on hardlink-copies of a repository,
see: https://github.com/borgbackup/borg/discussions/6286
> safe_unlink (was: truncate_and_unlink)

- src/borg/archiver.py
Resolves #6258: explains the difference between a path that ends with or without a slash.
In the doc I specifically mentioned the difference when used as an exclusion pattern, because if I'm not mistaken there's no difference for inclusion patterns (`some/path/` and `some/path` would result in the same backup set). But let me know if I should tweak this.
> docs: explain the difference between a path that ends with or without a slash

- src/borg/archiver.py
This is a backport of https://github.com/borgbackup/borg/pull/6297
> Backport: docs: explain the difference between a path that ends with or without a slash

- src/borg/cache.py
- src/borg/helpers.py
- src/borg/platform/base.py
- src/borg/remote.py
- src/borg/repository.py
- src/borg/testsuite/helpers.py
This is a backport of #6301 and #6311
> Backport:  safe_unlink (was: truncate_and_unlink)

- src/borg/repository.py
> Backport: compact segments: improve freeable / freed space log output

- docs/internals/data-structures.rst
This PR only contains a small patch to the internals docs.
The order of the fields of a log entry on disk is CRC32 first, the docs had the size first.
I tried to make this list similar to the HashIndex struct description.
> docs: Clarify on-disk order and size of log entry fields

- docs/internals/data-structures.rst
> docs: Clarify on-disk order and size of log entry fields (1.2)

- .github/workflows/codeql-analysis.yml
This is a backport of #6356
> WARNING: apt does not have a stable CLI interface. Use with caution in scripts.
> s/apt/apt-get/ (1.2)

- src/borg/crypto/low_level.pyx
The generated source code was producing a compiler warning due to
the pointers differing in constness. The called function expects
a non-const pointer while the generated code produces a const pointer
via a cast. This changes the cast to drop 'const' to make the compiler
happy.
> src/borg/crypto/low_level.pyx: fix compiler warning

- src/borg/crypto/low_level.pyx
The generated source code was producing a compiler warning due to
the pointers differing in constness. The called function expects
a non-const pointer while the generated code produces a const pointer
via a cast. This changes the cast to drop 'const' to make the compiler
happy.
Thank you for contributing code to Borg, your help is appreciated!
Please, before you submit a pull request, make sure it complies with the
guidelines given in our documentation:
https://borgbackup.readthedocs.io/en/latest/development.html#contributions
**Please remove all above text before submitting your pull request.**
> [1.2-maint] src/borg/crypto/low_level.pyx: fix compiler warning

- src/borg/compress.pyx
This resolves a compiler warning from the generated code that
resulted from a comparison of two local variables of different
signedness. The issue is resolved by changing the type of both
to int since this seems like the safest choice available.
> src/borg/compress.pyx: fix compiler warning, closes #6365

- docs/internals/data-structures.rst
* This is a backport of https://github.com/borgbackup/borg/pull/6357
> docs: Clarify on-disk order and size of log entry fields (1.1)

- src/borg/compress.pyx
This resolves a compiler warning from the generated code that
resulted from a comparison of two local variables of different
signedness. The issue is resolved by changing the type of both
to int since this seems like the safest choice available.
> [1.2-maint] src/borg/compress.pyx: fix compiler warning, closes #6365

- src/borg/crypto/_crypto_helpers.c
- src/borg/crypto/_crypto_helpers.h
- src/borg/crypto/low_level.pyx
- src/borg/testsuite/crypto.py
#6338 introduces regression when building with LibreSSL (3.5.0).
```
cc -Wno-unused-result -Wsign-compare -Wunreachable-code -DNDEBUG -O2 -pipe -g -fPIC -O2 -pipe -g -O2 -pipe -g -O2 -pipe -fPIC -Isrc/borg/crypto -I/usr/local/include/python3.9 -c src/borg/crypto/low_level.c -o /tmp/ports/pobj/borgbackup-1.2.1/borg-eec359cf228caf00d9c72bde07bf939872e9d3fa/temp.openbsd-7.1-amd64-3.9/src/borg/crypto/low_level.o
src/borg/crypto/low_level.c:12439:48: error: use of undeclared identifier 'EVP_chacha20_poly1305'; did you mean 'EVP_aead_chacha20_poly1305'?
__pyx_v_self->__pyx_base.__pyx_base.cipher = EVP_chacha20_poly1305;
^~~~~~~~~~~~~~~~~~~~~
EVP_aead_chacha20_poly1305
/usr/include/openssl/evp.h:1161:17: note: 'EVP_aead_chacha20_poly1305' declared here
const EVP_AEAD …
```
> Fix build with LibreSSL

- src/borg/_hashindex.c
- src/borg/cache_sync/unpack.h
This should close #6333 as it silences all the warnings. I put it in 2 commits because there were effectively 2 sets of warnings.
> fix multiple warnings related to _hashindex.c

- src/borg/cache_sync/unpack_template.h
These instances of implicit switch case fallthrough appear to be
intentional. Add comments that the compiler understands to suppress
the false positive warning.
> suppress -Wimplicit-fallthrough warning

- Vagrantfile
> vagrant: remove debian stretch VM, not supported any more

- src/borg/platform/posix.pyx
Fix compilation warnings:
```
gcc -pthread -Wno-unused-result -Wsign-compare -DNDEBUG -g -fwrapv -O3 -Wall -fPIC -I/opt/hostedtoolcache/Python/3.9.10/x64/include/python3.9 -c src/borg/platform/posix.c -o build/temp.linux-x86_64-3.9/src/borg/platform/posix.o
src/borg/platform/posix.c: In function ‘__pyx_pf_4borg_8platform_5posix_2swidth’:
src/borg/platform/posix.c:1572:3: warning: ‘PyUnicode_AsUnicode’ is deprecated [-Wdeprecated-declarations]
1572 |   __pyx_t_2 = __Pyx_PyUnicode_AsUnicode(__pyx_v_s); if (unlikely((!__pyx_t_2) && PyErr_Occurred())) __PYX_ERR(0, 19, __pyx_L1_error)
|   ^~~~~~~~~
In file included from /opt/hostedtoolcache/Python/3.9.10/x64/include/python3.9/unicodeobject.h:1026,
from /opt/hostedtoolcache/Python/3.9.10/x64/include/python3.9/Python.h:93,
from …
```
> Fix compilation warnings: ‘PyUnicode_AsUnicode’ is deprecated

- src/borg/platform/posix.pyx
* This is a backport of https://github.com/borgbackup/borg/pull/6416
> 1.2-maint: ‘PyUnicode_AsUnicode’ is deprecated

- src/borg/platform/posix.pyx
* This is a backport of https://github.com/borgbackup/borg/pull/6416
> 1.1-maint: ‘PyUnicode_AsUnicode’ is deprecated

- src/borg/algorithms/checksums.pyx
> fix "useless trailing comma" cython warnings

- src/borg/cache_sync/unpack_template.h
It turns out that explaining the comment actually breaks its
intended usage.
> properly suppress -Wimplicit-fallthrough

- setup.py
This is mainly intended for explicit warnings but it can be
used for other flags as well.
> Allow extra compiler flags for every extension build

- src/borg/helpers.py
- src/borg/platform/base.py
> respect umask for files / dirs (1.1)

- src/borg/algorithms/crc32_clmul.c
- src/borg/algorithms/msgpack/unpack_template.h
- src/borg/cache_sync/unpack_template.h
This includes a backport of https://github.com/borgbackup/borg/pull/6426
Testing:
```
git clean -e /.envrc -e /.direnv -fdx \
&& CFLAGS=-Werror=implicit-fallthrough pip -v install -e .
```
* This reduces compilation warnings introduced by https://github.com/borgbackup/borg/pull/6433
> 1.1: Make switch fallthrough explicit

- src/borg/algorithms/crc32_clmul.c
* This could be considered a forward port of https://github.com/borgbackup/borg/pull/6434
* Strictly speaking this is not a backport of  #6426 even though it serves the same purpose
Testing:
```
git clean -e /.envrc -e /.direnv -fdx \
&& CFLAGS=-Werror=implicit-fallthrough pip -v install -e .
```
> 1.2: Make switch fallthrough explicit

- src/borg/archiver.py
`borg benchmark cpu` fails on OpenBSD with the error below, which is
caused by LibreSSL currently not supporting AES256_OCB and
CHACHA20_POLY1305.
Work around this by checking if borg is used with LibreSSL. Tested on
OpenBSD.
```
Chunkers =======================================================
buzhash,19,23,21,4095    1GB        14.294s
fixed,1048576            1GB        0.244s
Non-cryptographic checksums / hashes ===========================
crc32 (libdeflate, used) 1GB        0.724s
crc32 (zlib)             1GB        1.953s
xxh64                    1GB        0.361s
Cryptographic hashes / MACs ====================================
hmac-sha256              1GB        7.039s
blake2b-256              1GB        9.845s
Encryption ===================================================== …
```
> `borg benchmark cpu` fails with libressl

- src/borg/crypto/_crypto_helpers.c
- src/borg/crypto/_crypto_helpers.h
- src/borg/crypto/low_level.pyx
- src/borg/selftest.py
- src/borg/testsuite/crypto.py
not used in 1.2.x, we'll start using them in 1.3.
> remove AEAD ciphers AES-OCB and CHACHA20-POLY1305, fixes #6472

- src/borg/crypto/_crypto_helpers.c
- src/borg/crypto/_crypto_helpers.h
- src/borg/crypto/low_level.pyx
#6473 Removed AEAD ciphers AES-OCB and CHACHA20-POLY1305 from 1.2. As a
result some additional code can be removed.
Passes regression tests.
> 1.2 - Remove unused code

- src/borg/archiver.py
This commit will change prompt of `borg delete` command from
```
You requested to completely DELETE the repository *including* all archives it contains:
host1.example.net-2022-03-14T14:55:31 Mon, 2022-03-14 15:55:31 [ecb4e323c38e5d560452192456073f284aa3acaf59b53e24f584ae33e3025519]
Type 'YES' if you understand this and want to continue: YES
```
to
```
You requested to completely DELETE the repository with ID 2c91b9eee2c718f766dcec336fa4c25af0568714110df36b5972b24a551a2310 located in ssh://username@borgbackup.example.net/path/to/repo *including* all archives it contains:
host1.example.net-2022-03-14T14:55:31 Mon, 2022-03-14 15:55:31 [ecb4e323c38e5d560452192456073f284aa3acaf59b53e24f584ae33e3025519]
Type 'YES' if you understand this and want to continue: 
```
> delete: add repository id and location to prompt

- docs/installation.rst
there was no change required due to argon2-cffi, because that will be automatically installed by pip.
> docs: add libdeflate requirement to install docs, fixes #6446

- src/borg/crypto/low_level.pyx
if we just have a pointer to a bytes object which might go out of scope, we can lose it.
also: cython can directly assign a bytes object into a same-size char array.
> avoid losing the key (old crypto)

- src/borg/crypto/key.py
- src/borg/helpers/manifest.py
but do not verify chunk-id for it (does not match because the ID is fixed at all-zero).
> bugfix: correctly give manifest id

- src/borg/archiver.py
Note: A KDF shall be expensive to compute to slow down attacks on your key encryption / your passphrase.
fixes #6443.
> borg benchmark cpu: add kdf timings

- docs/faq.rst
The previous sample for creating a ~/.borg-passphrase file creates it first and then chmod's it to 400 permissions. That's probably fine in practice, but means there's a tiny window where the passphrase file is sitting with default permissions (likely world readable, depending on the system umask).
It seems safer to first change the umask to remove all group & world bits (0077) _before_ creating the file. To be polite and avoid messing with the user's previous umask, we do this in a subshell. (Note that umask 0077 leads to a mode of 600 rather than the previous 400, because removing the owner write bit doesn't seem to buy much since the owner can just chmod the file anyway.)
> (docs) Recommend umask for passphrase file perms

- src/borg/helpers/parseformat.py
- src/borg/testsuite/helpers.py
added a negative lookahead/lookbehind to make sure an ipv6 addr
(enclosed in square brackets) does not get badly matched by the
regex part intended for hostnames and ipv4 addrs only.
the other part of that regex which is actually intended to match
ipv6 addrs only matches if they are enclosed in square brackets.
also added tests for ssh and scp style repo URLs with ipv6 addrs
in brackets.
also: made regex more readable, putting these 2 cases on separate lines.
> fix scp repo url parsing for ip v6 addrs, fixes #6526

- src/borg/archive.py
OpenBSD does not have `lchmod()` causing `os.lchmod` to be unavailable
on this platform. As a result ArchiverTestCase::test_basic_functionality
fails when run manually (#2055).
OpenBSD does have `fchmodat()`, which has a flag that makes it behave
like `lchmod()`. In Python this can be used via `os.chmod(path, mode,
follow_symlinks=False)`.
As of Python 3.3 `os.lchmod(path, mode)` is equivalent to
`os.chmod(path, mode, follow_symlinks=False)`. As such, switching to the
latter is preferred as it enables more platforms to do the right thing.
> 1.1 - Fix OpenBSD symlink mode test failure (#2055)

- conftest.py
- src/borg/archiver.py
- src/borg/constants.py
- src/borg/crypto/key.py
- src/borg/helpers/passphrase.py
- src/borg/item.pyx
- src/borg/testsuite/archiver.py
- src/borg/testsuite/crypto.py
- src/borg/testsuite/key.py
~~Note: this PR is not yet complete. I am submitting it to try running CI~~
This is the second part of https://github.com/borgbackup/borg/issues/747
~~ - [x] Add code in decrypt_key_file necessary to be able to decrypt v2 keys ~~
~~ - [x] Implement encryption of keys in the new format ~~
See [new TODO](https://github.com/borgbackup/borg/pull/6469#issuecomment-1079898226)
~~This PR includes #6468~~
> Argon2 the second part: implement key encryption / decryption

- src/borg/archive.py
also: fix percentage format for float value.
> escape % chars in archive name, fixes #6500

- pyproject.toml
- setup.py
Using pyproject.toml, we can avoid people running into issues when they did not install pkgconfig and cython first.
Also:
setup.py: add parent to sys.path
When using pyproject.toml the parent of setup.py is not on sys.path by default.
See <pypa/setuptools#3134>.
> add pyproject.toml, fix sys.path, fixes #6466

- src/borg/__init__.py
- src/borg/archiver.py
I have updated the cpu benchmark to use the same argon2 configuration as we use normally.
After this is merged I'll work on the last PR of #747 - the changelog and documentation updates
> Argon2 fourth part: borg benchmark cpu: use ARGON2_ARGS

- docs/usage/tar.rst
- src/borg/archive.py
- src/borg/archiver.py
- src/borg/testsuite/archiver.py
fixes #5830.
export-tar: just msgpack and b64encode all item metadata and put that into a BORG specific PAX header. this is *additional* to the standard tar metadata.
import-tar: when detecting the BORG specific PAX header, just get all metadata from there (and ignore the standard tar metadata).
> import/export-tar: --tar-format=BORG: roundtrip ALL item metadata

- src/borg/testsuite/crypto.py
- src/borg/testsuite/key.py
selftest imports testsuite.crypto
I did not realise this and imported pytest from testsuite.crypto
This broke the selftest.
Solution: move the tests that depend on pytest to testsuite.key.
All three affected tests are tests for the Key classes, so
this is probably a better plase for them anyway.
> Fix selftest

- src/borg/archiver.py
> docs: borg compact --cleanup-commits also runs a normal compaction

- src/borg/crypto/key.py
- src/borg/crypto/keymanager.py
- src/borg/repository.py
when migrating from repokey to keyfile, we just store an empty key into the repo config,
because we do not have a "delete key" RPC api. thus, empty key means "there is no key".
here we fix load_key, so that it does not behave differently for no key and empty key:
in both cases, it just returns an empty value.
additionally, we strip the value we get from the config, so whitespace does not matter.
All callers now check for the repokey not being empty, otherwise RepoKeyNotFoundError
is raised.
> load_key: no key is same as empty key, fixes #6441

- src/borg/archive.py
all-zero chunks are propagated as:
CH_ALLOC, data=None, size=len(zeros)
other chunks are:
CH_DATA, data=data, size=len(data)
also: remove the comment with the wrong assumption
> metadata stream can produce all-zero chunks, fixes #6587

- setup.cfg
readthedocs.org uses python setup.py install (not pip install).
fixes #6598.
> setup.cfg: setup_requires setuptools_scm

- src/borg/constants.py
- src/borg/crypto/key.py
- src/borg/testsuite/archiver.py
- src/borg/testsuite/crypto.py
fixes #6601
so we can completely get rid of aes-ctr some day.
> argon2 key: use chacha20-poly1305 instead of aes256-ctr+hmac-sha256

- pyproject.toml
we have this in setup_requires in setup.py, but i also added it to
pyproject.toml - so we can be sure it is installed no matter what.
**configuration** of setuptools_scm is done the old way in setup.py
here in 1.2-maint, in master we have switched that over to pyproject.toml.
> setuptools_scm: also require it via pyproject.toml

- src/borg/archiver.py
- src/borg/crypto/key.py
- src/borg/helpers/parseformat.py
- src/borg/testsuite/archiver.py
fixes #6554.
it potentially will ask for the passphrase for the key of OTHERREPO.
for the newly created repo, it will use the same passphrase.
it will copy: enc_key, enc_hmac_key, id_key, chunker_seed.
keeping the id_key (and id algorithm) and the chunker seed (and chunker
algorithm and parameters) is desirable for deduplication.
the id algorithm is usually either HMAC-SHA256 or BLAKE2b.
keeping the enc_key / enc_hmac_key must be implemented carefully:
A) AES-CTR -> AES-CTR is INSECURE due to nonce reuse, thus not allowed.
B) AES-CTR -> AEAD with session keys is secure.
C) AEAD with session keys -> AEAD with session keys is secure.
AEAD modes with session keys: AES-OCB and CHACHA20-POLY1305.
> init --other-location=OTHER_REPO: reuse key material from OTHER_REPO

- src/borg/archive.py
- src/borg/archiver.py
- src/borg/testsuite/archiver.py
the id must now always be given correctly because
the AEAD crypto modes authenticate the chunk id.
the special case when id == MANIFEST_ID is now handled
inside assert_id, so we never need to give a None id.
> fix key.decrypt calls

- src/borg/selftest.py
- src/borg/testsuite/chunker.py
- src/borg/testsuite/crypto.py
- src/borg/testsuite/hashindex.py
also: move the note about this to the very top of the affected modules.
> check that borg does not require pytest for normal usage, fixes #6563

- docs/faq.rst
Backport of #6659 to 1.2-maint
> Backport mention BORG_FILES_CACHE_SUFFIX as alternative to BORG_FILES_CACHE_TTL (#6659)

- src/borg/selftest.py
- src/borg/testsuite/chunker.py
- src/borg/testsuite/crypto.py
- src/borg/testsuite/hashindex.py
Backport of #6670 to 1.2-maint
> Backport check that borg does not require pytest for normal usage (#6670, 1.2)

- src/borg/selftest.py
- src/borg/testsuite/chunker.py
- src/borg/testsuite/crypto.py
- src/borg/testsuite/hashindex.py
Backport of #6670 to 1.1-maint
> Backport check that borg does not require pytest for normal usage (#6670, 1.1)

- src/borg/helpers/process.py
if cmd was falsy (e.g. None), there is no proc.
then, if "yield stream" raises an exception, the exception handler crashed at "proc.kill()".
> fix create_filter_process exception handler, fixes #6681

- src/borg/archive.py
- src/borg/testsuite/archive.py
fixes #6570
also:
- remove empty values from final json
- add test
> show_progress: add finished=true/false to archive_progress json

- src/borg/fuse.py
it does not make sense to request versions view if you only
look at 1 archive, but the code shall not crash in that case
as it did, but give a clear error msg.
> mount -o versions: give clear error msg instead of crashing

- docs/deployment/central-backup-server.rst
- docs/quickstart.rst
- docs/usage/general/repository-urls.rst.inc
- docs/usage/init.rst
- src/borg/helpers/parseformat.py
- src/borg/testsuite/archiver.py
- src/borg/testsuite/helpers.py
- src/borg/testsuite/repository.py
For #6691.
I have removed the scp part of the regex while keeping the local file part. Also removed the scp syntax from testsuite, docs.
Commits are not yet squashed for easier review.
> Remove scp syntax for locations

- docs/deployment/central-backup-server.rst
- docs/quickstart.rst
- docs/usage/general/repository-urls.rst.inc
- docs/usage/init.rst
- src/borg/helpers/parseformat.py
- src/borg/testsuite/archiver.py
- src/borg/testsuite/helpers.py
- src/borg/testsuite/repository.py
This reverts commit 1b4b84dfd8f1ec2a3aa156fb9cc2714ef6263143.
I will apply this to the new "borg2" branch.
> Revert "Remove scp syntax for locations (#6697)"

- docs/changes.rst
- docs/deployment/automated-local.rst
- docs/deployment/pull-backup.rst
- docs/faq.rst
- docs/quickstart.rst
- docs/usage/create.rst
- src/borg/archiver.py
Backport from master: Make clear that absolute paths always go into the matcher as if they are relative (without leading slash). Adapt all examples accordingly.
> #6407 - Document Borg 1.2 pattern behavior change

- src/borg/archiver.py
- src/borg/repository.py
the new options limit processing to segment S (and, optionally, also
to offset O), so you do not need to dump your complete repo to only
look at 1 segment (or 1 object).
notes:
- there is no rpc api for scan_low_level, so this only works locally.
- only works with --ghost
for #6687.
> borg debug dump-repo-objs --ghost: new --segment=S --offset=O options

- src/borg/archiver.py
- src/borg/helpers/checks.py
- src/borg/helpers/errors.py
- src/borg/platform/base.py
- src/borg/testsuite/helpers.py
Make unnecessary absolute imports relative instead, both to make code style more consistent and reduce the code parts a potential future module rename, e.g. for a breaking borg2, would have to touch.
> Use relative imports

- src/borg/archiver.py
- src/borg/cache.py
- src/borg/constants.py
Traditionally, DEFAULT_FILES_CACHE_MODE_UI and DEFAULT_FILES_CACHE_MODE
were - as the naming scheme implies - the same setting, one being the UI
representation as given to the --files-cache command line option and the
other being the same default value in the internal representation.
It happended that the actual value used in borg create always comes from
DEFAULT_FILES_CACHE_MODE_UI (because that does have the --files-cache
option) whereas for all other commands (that do not use the files cache) it
comes from DEFAULT_FILES_CACHE_MODE.
PR #5777 then abused this fact to implement the optimisation to skip loading
of the files cache in those other commands by changing the value of
DEFAULT_FILES_CACHE_MODE to disabled.
This however also changes the meaning of that variable and thus …
> make constants for files cache mode more clear

- src/borg/archiver.py
My first shot to improve the patterns help a bit. I tried to keep it short.
- Start with explaination where patterns can be used.
- Emphasize that leading separator is trimmed.
- List patterns file prefixes one by one to make it more readable.
- Add the tip for testing patterns.
- Keep examples short.
I haven't changed existing examples a lot, but I tested all aspects with different pattern styles.
fixes #5310
> [DOCS] #5310 - Overhaul borg help patterns

- docs/quickstart.rst
The line continuation is unnecessary for the last line of the command.
It could even be dangerous if a user modifies the script and puts something in the line directly below the command, not realizing that it will be mashed together with the previous command.
> [DOCS] Remove unnecessary/dangerous line continuation

- src/borg/helpers.py
- src/borg/repository.py
if a hardlink copy of a repo was made and a new repo config
shall be saved, do NOT fill in random garbage before deleting
the previous repo config, because that would damage the hardlink
copy.
> secure_erase: avoid collateral damage, fixes #6768

- docs/internals/frontends.rst
- src/borg/archive.py
- src/borg/archiver.py
- src/borg/cache.py
- src/borg/cache_sync/cache_sync.c
- src/borg/cache_sync/unpack.h
- src/borg/constants.py
- src/borg/fuse.py
- src/borg/hashindex.pyx
- src/borg/helpers/parseformat.py
- src/borg/item.pyx
- src/borg/testsuite/archive.py
- src/borg/testsuite/archiver.py
- src/borg/testsuite/cache.py
- src/borg/testsuite/hashindex.py
- src/borg/testsuite/item.py
"what would we lose/win if we would just not track csize (the compressed size of a chunk)", see #2357.
- do not have csize in the item.chunks list entries
- do not have csize in the ChunkIndex entries
- do not track csize in Statistics
- but: my other PR https://github.com/borgbackup/borg/pull/6705 would make borg track csize in the repo index
What we lose (some stuff could be just done differently):
- archive info: compressed size and deduplicated-compressed size stats (the latter is based on csize and refcount)
- archive list: placeholders for csize / dcsize
What we win:
- get rid of some ugly / complicated code
- repo-scope recompression would be easily doable, because there is no csize to "fix" in the archives (and in the chunks index)
- no super expensive `fetch_missing_csize` and no …
> borg2: there is no csize

- src/borg/testsuite/compress.py
This PR fixes the `test_obfuscate` length accounting for the `none` compression algorithm.
Specifically, it wasn't accounting for the 2 ID bytes that the `none` compression also adds.
This caused a test failure, where the "compressed" size was 2031 but the test expected a maximum of 2030, as you can see below:
<details>
<summary>Test output</summary>
```
============================= test session starts ==============================
platform linux -- Python 3.9.13, pytest-7.1.1, pluggy-1.0.0
benchmark: 3.4.1 (defaults: timer=time.perf_counter disable_gc=False min_rounds=5 min_time=0.000005 max_time=1.0 calibration_precision=10 warmup=False warmup_iterations=100000)
Tests enabled: BSD flags, fuse3, root, symlinks, hardlinks, atime/mtime, modes
Tests disabled: fuse2
rootdir: …
```
> fix test_obfuscate byte accounting

- src/borg/testsuite/compress.py
This PR backports #6773 to the `1.2-maint` branch.
>  fix test_obfuscate byte accounting (backport #6773 to 1.2-maint)

- src/borg/archiver.py
- src/borg/upgrade.py
- `From12To20`: upgrade from borg 1.2 repo/archive/item format to 2.0
- `NoOp`: do nothing (so `borg transfer` becomes a general purpose archive transfer method between related borg 2 repos)
> transfer: use an Upgrader class

- src/borg/repository.py
v2 is the default repo version for borg 2.0.
v1 repos must only be used in a read-only way, e.g. for --other-repo=V1_REPO with borg init and borg transfer!
> support repo version 1 also, fixes #6811

- src/borg/_hashindex.c
also: fix "off by one" comment
forward port to master.
> hashindex_compact: fix eval order (check idx before use), fixes #5899

- docs/internals/frontends.rst
in the finished == true message, these are missing:
- message
- current / total
- info
This is to be somewhat consistent with #6683 by only providing a minimal set of values for the finished case.
The finished messages is primarily intended for cleanup purposes, e.g. clearing the progress display.
> docs: json progress_percent: some values are optional, fixes #4074

- src/borg/archiver.py
- src/borg/remote.py
- src/borg/repository.py
old repos only accepted for `--other-repo` (for borg rcreate / borg transfer) so users can transfer their archives into related repos.
other than that, only accept new repos (version 2).
also, borg2 will reject talking to a borg < 2 repo server because that will not have the new `info` rpc call added in this PR. for the archives transfer, borg2 shall be used on the server (including for reading the old repo).
> check repo version / borg rinfo extended

- .github/workflows/ci.yml
- .github/workflows/codeql-analysis.yml
- Vagrantfile
- docs/installation.rst
- setup.py
- src/borg/archiver.py
- src/borg/checksums.pyx
- src/borg/testsuite/checksums.py
borg2's new repo format does not need computing crc32 over big amounts of
(content) data any more (we now use xxh64 for that).
thus, having a quick crc32 implementation via libdeflate is not important
enough any more to rectify having libdeflate as a requirement.
> stop using libdeflate

- src/borg/archive.py
- src/borg/archiver/recreate.py
- src/borg/constants.py
- src/borg/remote.py
- src/borg/repository.py
- src/borg/testsuite/crypto.py
- src/borg/upgrade.py
we expect that everybody has upgraded to borg
using borg 1.2.x or older, thus we do not need
to care about attic repos any more in borg2.
> remove remainders of attic legacy

- docs/usage/general/repository-urls.rst.inc
- src/borg/remote.py
- src/borg/testsuite/helpers.py
If you used this, just replace it by:
ssh://user@host:port/home/otheruser/
> ssh:// URLs: remove support for /~otheruser/, see #6855

- docs/internals/security.rst
- src/borg/archive.py
- src/borg/crypto/key.py
- src/borg/testsuite/key.py
See: https://github.com/borgbackup/borg/pull/6463#discussion_r925436156
> new crypto does not need to call ._assert_id()

- .github/workflows/ci.yml
too troublesome on github CI due to kernel extensions needed by macFUSE.
> CI: test on macOS 12 without fuse / fuse tests

- .github/workflows/ci.yml
too troublesome on github CI due to kernel extensions needed by macFUSE.
> CI: test on macOS 11 without fuse / fuse tests

- src/borg/archive.py
the old code did just 1 attempt to detect the repo decryption key.
if the first chunkid we got from the chunks hashtable iterator was accidentally
the id of the chunk we intentionally corrupted in test_delete_double_force,
setup of the key failed and that made the test crash.
in practice, this could of course also happen if chunks are corrupted, thus
we now do many retries with other chunks before giving up.
error handling was improved: do not return None (instead of a key), it just
leads to weird crashes elsewhere, but fail early with IntegrityError and a
reasonable error msg.
rename method to make_key to avoid confusion with borg.crypto.key.identify_key.
> check: try harder to create the key, fixes #5719

- src/borg/helpers/parseformat.py
item.bsdflags is either not present or an int, thus we default to 0 (== no flags) if not present.
> list: fix {flags:<WIDTH>} formatting, fixes #6081

- setup.cfg
- src/borg/archiver.py
manifest, repo and cache are committed every checkpoint interval.
also, when ctrl-c is pressed, finish deleting the current archive, commit and then terminate.
> prune/delete --checkpoint-interval=1800 and ctrl-c/SIGINT support, fixes #6284

- docs/internals/data-structures.rst
While writing my own out-of-band decoder, I had a hard time figuring out
how to unpack the manifest. From the description, I was only able to
read that the manifest is msgpack'd, but I had not been able to figure
out that it's also going through the same encryption+compression logic
as all other things do.
This should make it a little clearer and provide the necessary
information to understand how the compression works.
---
I also have the same change cherry-picked against master, but as master is now Borg 2.0, I'm not sure that it's correct. Any guidance appreciated (second PR with cherry-pick? PR against master only? ..?), my custom extractor is only tested against 1.2 :-).
> docs(1.2): provide more details on object layout

- src/borg/archiver/transfer.py
- src/borg/crypto/key.py
fixes #6893
also: add PlaintextKey and AuthenticatedKey support to uses_same_id_hash function.
> transfer: check whether ID hash method and chunker secret are same

- src/borg/archiver/delete.py
this option is only useful for deleting repos.
> delete: remove unused option --keep-security-info

- src/borg/helpers/fs.py
- src/borg/platform/base.py
hopefully this is the final fix.
after first fixing of #6400 (by using os.umask after mkstemp), there
was a new problem that chmod was not supported on some fs.
even after fixing that, there were other issues, see the ACLs issue
documented in #6933.
the root cause of all this is tempfile.mkstemp internally using a
very secure, but hardcoded and for our use case problematic mode
of 0o600.
mkstemp_mode (mosty copy&paste from python stdlib tempfile module +
"black" formatting applied) supports giving the mode via the api,
that is the only change needed.
slightly dirty due to the _xxx imports from tempfile, but hopefully
this will be supported in some future python version.
> use a custom mkstemp with mode support, fixes #6933, fixes #6400

- src/borg/repository.py
i suspect that compact_segments wrongly drops some DEL tags.
this could make already deleted chunks re-appear, leading to:
- suddenly more repo index entries than previously (check, repo part)
- suddenly orphaned chunks appearing (check, archives part)
if this is the case, the issue is harmless, but annoying/confusing.
to fix the issue, i need the complete log line "dropping DEL for id X".
the id X it mentions is one of the chunk ids borg check complains about.
> repository: add debug logging for issue #6687

- src/borg/remote.py
- src/borg/repository.py
- src/borg/testsuite/repository.py
- .list: only return IDs for objects where flags & mask == value.
- .flags(_many) (new) to set/query flags
> repository api: flags support, fixes #6982

- Vagrantfile
looks like rhel7 and co is still supported and needs the old glibc.
debian stretch is not supported any more by debian, so the binaries created on this are provided on a "use on your own risk" basis.
reverts fc67453bf3e17000da10ba3a4dfb691f39294633
> re-add stretch64 vm, fixes #7010

- src/borg/archiver/__init__.py
- src/borg/archiver/_common.py
- src/borg/archiver/create_cmd.py
- src/borg/archiver/recreate_cmd.py
- src/borg/helpers/__init__.py
- src/borg/helpers/parseformat.py
- src/borg/testsuite/archiver.py
- src/borg/testsuite/helpers.py
fix replacing placeholders in archive name, --comment and --glob-archives values (even if overridden by other options like --timestamp).
add test.
> refactor replace_placeholders, fixes #6966

- Vagrantfile
This reverts commit 7fec5ff0516be6950611c1df77ab5ee006994a01.
Does not work, we need libxxhash-dev and it is not available on debian stretch.
> Revert "re-add stretch64 vm, fixes #7010"

- setup.py
that would require setuptools_scm>=5.0.0 but some dists do not have that yet.
also, we do not use the version_tuple from _version.py, so it is not required anyway.
> do not use version_tuple placeholder in setuptools_scm template

- src/borg/archive.py
- src/borg/archiver/debug_cmd.py
- src/borg/repository.py
- src/borg/testsuite/repository.py
Luckily, we did not yet use `.scan()` in the way that would have caused problems.
> Fix repository.scan

- src/borg/archive.py
- src/borg/archiver/debug_cmd.py
- src/borg/remote.py
- src/borg/repository.py
- src/borg/testsuite/repository.py
achieved by putting it into the state that is now used instead of the marker.
> repository.scan: use same end_segment within same scan

- setup.cfg
- src/borg/archiver/__init__.py
- src/borg/archiver/rcompress_cmd.py
- src/borg/compress.pyi
- src/borg/compress.pyx
- src/borg/testsuite/archiver/rcompress_cmd.py
- src/borg/testsuite/compress.py
note: this can't be backported to borg 1.x because it uses some of the borg2-only features (like not having csize in archive metadata or elsewhere, like fetching the separate metadata **only** to check for the current compression type and level).
fixes #3631, fixes #5755
> rcompress: do a repo-wide (re)compression

- src/borg/archive.py
- src/borg/archiver/create_cmd.py
- src/borg/archiver/transfer_cmd.py
e.g. nfiles, size, etc.
fixes:
- checkpoint archives did not have this metadata yet
- borg import-tar did not have this metadata yet
> archive.save(): always use metadata from stats, fixes #7072

- src/borg/upgrade.py
after the cython code refactor in #7063, accessing the internal _dict is not possible any more.
but looks like we do not even need that.
> transfer/upgrade: do not access Item._dict, fixes #7077

- src/borg/upgrade.py
add the missing chunker_name as first element of the tuple.
> transfer/upgrade: fix borg < 1.2 chunker_params, fixes #7079

- src/borg/testsuite/hashindex.py
Pass the file descriptor instead of the file path
> Fix test_size_on_disk_accurate on Windows

- src/borg/archiver/create_cmd.py
argparse: the default action is "store" and that overwrote an already existing list in args.paths (e.g. from --pattern="R someroot") when it started to process the positional PATH args.
with "extend" it now extends the existing args.paths with the list of positional PATH arguments (which can be 0..N elements long, nargs="*").
note: "extend" is new since python 3.8, thus this can only be backported to 1.2-maint, but not to 1.1-maint.
> fix args.paths related argparsing, fixes #6994

- src/borg/helpers/fs.py
not supported any more in master and 1.2-maint branches.
> remove python < 3.7 compatibility code

- src/borg/testsuite/archiver/create_cmd.py
fast CPUs failed the test due to rounding down to 0.00s.
> fix failing hashing_time test

- src/borg/crypto/file_integrity.py
- src/borg/repository.py
- src/borg/testsuite/repository.py
`pytest -k "repository.py and not remote"`
Before: `==== 17 failed, 44 passed, 1521 deselected, 3 warnings, 2 errors in 4.27s =====`
With these changes `=============== 61 passed, 1521 deselected, 3 warnings in 2.96s ===============`
> Fix repository tests on Windows

- src/borg/algorithms/msgpack/_version.py
- src/borg/algorithms/msgpack/sysdep.h
- Fallback to compiler defines when __BYTE_ORDER is not available
- simplify the endianity handling
- additional cleanup
- Fix build error caused by ntohs, ntohl
Backport https://github.com/msgpack/msgpack-python/pull/513 (as discussed in
https://github.com/borgbackup/borg/pull/6149#issuecomment-1335745572) and https://github.com/msgpack/msgpack-python/pull/514.
Applied with
```
$ gh -R msgpack/msgpack-python pr diff --patch 513 |
git am --directory src/borg/algorithms/ -
$ gh -R msgpack/msgpack-python pr diff --patch 514 |
git am --directory src/borg/algorithms/ -
```
Tested on OpenBSD/sparc64 (big-endian) and OpenBSD/amd64 (little-endian).
> Fix msgpack runtime on big-endian OpenBSD/sparc64

- .github/workflows/ci.yml
- tox.ini
also: have a setting to disable fail-fast, in case something breaks again.
> fix tox4 issue on macOS CI (1.2-maint)

- src/borg/archiver.py
Without the status being set no output was generated in dry-run mode, confusing users about whether borg would back up directories (in non-dry-run mode).
"-" == item not backed up just because of dry-run mode
"x" == item excluded
> create: --list --dry-run output for directories, fixes #7209

- src/borg/archiver/create_cmd.py
- src/borg/archiver/list_cmd.py
- src/borg/archiver/recreate_cmd.py
- src/borg/archiver/rlist_cmd.py
- src/borg/archiver/tar_cmds.py
- src/borg/archiver/transfer_cmd.py
- src/borg/helpers/__init__.py
- src/borg/helpers/parseformat.py
- src/borg/testsuite/archiver/rlist_cmd.py
- src/borg/testsuite/archiver/transfer_cmd.py
- src/borg/testsuite/helpers.py
- archive names
- archive comments
also: kill the `b*` (bpath, barchive, bcomment) stuff.
- barchive and bcomment is not needed any more (validated plain text, nothing binary / strange inside)
- bpath will need to get solved otherwise later, maybe as base64-* element (for json, which allows only pure text)
> text attributes: validate more strictly, fixes #2290

- src/borg/archive.py
- src/borg/archiver/check_cmd.py
- src/borg/archiver/delete_cmd.py
- src/borg/archiver/prune_cmd.py
- src/borg/remote.py
- src/borg/repository.py
- src/borg/testsuite/archiver/prune_cmd.py
this option did not change behaviour since longer, we only had kept it for API compatibility.
as a borg2 repo server won't have old clients talking to it, we can safely remove this everywhere now.
> remove --save-space

- docs/usage/tar.rst
- src/borg/archiver/create_cmd.py
- src/borg/archiver/key_cmds.py
- src/borg/helpers/parseformat.py
- src/borg/helpers/process.py
- src/borg/platform/windows.pyx
- src/borg/testsuite/archiver/__init__.py
- src/borg/testsuite/archiver/check_cmd.py
- src/borg/testsuite/archiver/config_cmd.py
- src/borg/testsuite/archiver/corruption.py
- src/borg/testsuite/archiver/create_cmd.py
- src/borg/testsuite/archiver/debug_cmds.py
- src/borg/testsuite/archiver/diff_cmd.py
- src/borg/testsuite/archiver/extract_cmd.py
- src/borg/testsuite/archiver/info_cmd.py
- src/borg/testsuite/archiver/key_cmds.py
- src/borg/testsuite/archiver/recreate_cmd.py
- src/borg/testsuite/archiver/rlist_cmd.py
- src/borg/testsuite/archiver/transfer_cmd.py
`pytest -k "archiver and not binary and not remote"`
Before: `44 failed, 131 passed, 29 skipped, 1378 deselected in 74.48s (0:01:14)`
After: `173 passed, 33 skipped, 1382 deselected in 107.46s (0:01:47)`
Fixes #7172
> Fix archiver tests on Windows

- src/borg/testsuite/hashindex.py
python's io.BufferedWriter sizes its buffer based on st_blksize
If the write fits in this buffer, then it's possible none (or only some) of the data from idx.write() has been written through to fileno()
Note:1.2-maint counterpart of #7251.
I see that the contribution guidelines ask for PRs only against master (leaving backports up to you maintainers) but in this case I want to publicly post a commit based on 1.2-maint to this repo, so that @mweinelt can have the nixpkgs derivation cherry-pick that commit for testing. I think we understand what's going on, but the failure is being seen on nixos autobuilders that use ZFS for $TEMP, and I don't personally have anything with that configuration, or direct access to those build machines.
Fixes #7250
> [1.2-maint] Fix test_size_on_disk_accurate for large st_blksize, fixes #7250

- src/borg/testsuite/hashindex.py
python's io.BufferedWriter sizes its buffer based on st_blksize
If the write fits in this buffer, then it's possible none (or only some) of the data from idx.write() has been written through to fileno()
Fixes #7250
> Fix test_size_on_disk_accurate for large st_blksize, fixes #7250

- src/borg/archive.py
use case:
borg recreate -a src --target dst can be used to make a copy of an archive inside the same repository, see #7254.
> recreate: when --target is given, do not detect "nothing to do"

- docs/internals/frontends.rst
- src/borg/archive.py
- src/borg/archiver/tar_cmds.py
- src/borg/constants.py
- src/borg/fuse.py
- src/borg/helpers/parseformat.py
- src/borg/item.pyx
- src/borg/testsuite/archive.py
- src/borg/testsuite/archiver/transfer_cmd.py
- src/borg/upgrade.py
Also, in JSON:
- rename "linktarget" to "target" for symlinks
- remove "source" for symlinks
> Item: symlinks: rename .source to .target, fixes #7245

- src/borg/cache.py
As discussed in #7271, this makes borg2 less verbose when it is syncing the cache.  (This only happens if you access a repository from multiple hosts.)  Below is how the new output looks with `-v` and with `--debug`.  (With neither, there is no relevant output.)
```
(borg2-env) borg2-test$ export BORG_BASE_DIR=./borg2-base-dir
(borg2-env) borg2-test$ borg create -v host1test20 ./test-data/
Creating archive at "/t/borg2-test/test.repo"
Cached archive chunk indexes: 7 fresh, 0 stale, 2 need fetching.
Reading cached archive chunk index for host1test17
Reading cached archive chunk index for host1test18
Fetching and building archive index for host1test19
Reading cached archive chunk index for host1test2
Reading cached archive chunk index for host2test17
Fetching and building archive index for …
```
> cache.py: be less verbose during cache sync

- src/borg/archive.py
- src/borg/archiver/_common.py
- src/borg/archiver/check_cmd.py
- src/borg/helpers/__init__.py
- src/borg/helpers/parseformat.py
- src/borg/helpers/time.py
- src/borg/manifest.py
- src/borg/testsuite/archiver/__init__.py
- src/borg/testsuite/archiver/check_cmd.py
Support for date-matching during archive listing (fix for #7062)
---
- Added arguments --older --newer --newest --oldest to argparser
- Added parser to detect relative time markers i.e. 1d/1m
- Added an in-house month-offseter
- Edited manifest to initially filter by date if markers are present
- Added test cases to test date matching arguments
> Support for date-based matching during archive listing

- setup.py
note:
intentionally not undef'ing it for all the cython-only generated C code.
> undef NDEBUG for chunker and hashindex

- conftest.py
- scripts/msys2-install-deps
- setup.cfg
- src/borg/helpers/__init__.py
- src/borg/helpers/fs.py
- src/borg/testsuite/helpers.py
> use platformdirs

- src/borg/archive.py
- src/borg/archiver/create_cmd.py
- src/borg/testsuite/archiver/create_cmd.py
- src/borg/testsuite/archiver/recreate_cmd.py
more consistent now between dry-run and non-dry-run mode.
--filter=... users might need to update the status chars they filter for.
> better included/excluded status chars, docs, fixes #7321

- src/borg/archiver/recreate_cmd.py
- src/borg/testsuite/archiver/recreate_cmd.py
also add a test: recreate without --chunker-params shall not rechunk
before the fix, it triggered rechunking if an archive was created with non-default chunker params.
but it only should rechunk if borg recreate is invoked with explicitly giving --chunker-params=....
forward port of #7337.
> recreate: --chunker-params must default to None, fixes #7337

- src/borg/helpers/parseformat.py
This fixes the rest of the non-remote tests.
> parseformat: remove Windows-specific hack

- src/borg/_hashindex.c
- src/borg/testsuite/hashindex.py
- src/borg/testsuite/hashindex_pytest.py
The second commit adjusts the tests so that they no longer assume that `hashindex_compact` preserves the order of the entries.  Other early commits clean up some tests and add additional tests.  The change to hashindex_compact is in the second-last commit.  All tests pass after each commit including the two relevant tests run when `BORG_TESTS_SLOW=1`.  I also ran tests with extreme values of `HASH_MAX_LOAD` and `HASH_MAX_EFF_LOAD`.
Please check the new code carefully before merging.  Check for off-by-one errors.
I didn't test the speed.  I'm not sure if compacting takes enough time for it to be worth checking this.
I have a couple of other questions that I will ask at the relevant spot in the code.
> Make hashindex_compact simpler and probably faster

- src/borg/archive.py
I noticed that #7310 only solves part of the problem, because we incref chunks at other places, too, and we need to cleanup these also in case some exception happens.
Also, we might have exceptions between writing the chunks and writing the metadata item referencing them.
> avoid orphan content chunks (master)

- docs/installation.rst
This PR updates the link to the Fedora/RHEL package in docs/installation.rst. Fixes #7357.
> Installation: Update Fedora in distribution list

- .github/workflows/ci.yml
- src/borg/testsuite/archiver.py
- tox.ini
The tests assumed a specific compressed results size, which is bad, because it might vary depending on the zlib implementation.
Now the "auto" compressor tests just check if it is the same size as when unconditionally using the zlib compressor.
> "auto" compressor tests: don't assume a specific size, fixes #7363

- src/borg/archive.py
fixed #7355 
`Statistics.__add__()` now iterates over the keys of both dictionaries and adds their stats values in new defaultdict.
> fixed Statistics.__add__(), fixes #7355

- src/borg/cache.py
fixes #5963 
--debug output now:
```bash
➜  borg git:(master) ✗ ./borg-env/bin/borg -r /home/divyansh/Desktop/borg2 rlist --debug 
using builtin fallback logging configuration
38 self tests completed in 0.06 seconds
Verified integrity of /home/divyansh/Desktop/borg2/index.9
Enter passphrase for key /home/divyansh/Desktop/borg2: 
TAM-verified manifest
Using /home/divyansh/.cache/borg/496f0ecf408beb37acb21eac471aecaeae36e549fc70d1a49778e64413242cb9 as cache
security: read previous location '/home/divyansh/Desktop/borg2'
security: read manifest timestamp '2023-02-25T21:03:06.588359+00:00'
security: determined newest manifest timestamp as 2023-02-25T21:03:06.588359+00:00
security: repository checks ok, allowing access
Monday                               Sun, 2023-02-26 02:31:47 +0530 …
```
> feat: add cache dir to --debug

- setup_docs.py
Refer to https://reproducible-builds.org/docs/source-date-epoch/ for documentation on SOURCE_DATE_EPOCH.
> Make timestamps in manual pages reproducible

- src/borg/archiver.py
- src/borg/testsuite/archiver.py
this is an incompatible change:
before:
borg debug put-obj :: path1 path2 ...
(and borg computed all IDs automatically) (*)
after:
borg debug put-obj :: id path
(id must be given)
(*) the code just using sha256(data) was outdated and incorrect anyway.
also: fix error handling in get-obj.
(backport of #7405)
> fix borg debug get-obj/put-obj (1.2-maint)

- src/borg/testsuite/archiver.py
#7364 
#7372 
I'm not completely sure if it makes sense to backport 8916b5a7dac560b4a54953b53df9aa6bdcee5f38 as it is not directly related with the other commit
> "auto" compressor tests: don't assume a specific size (backport to 1.2-maint)

- src/borg/testsuite/compress.py
As the test structure got refactored in master and as far as i can see does not explicitly check against the output size of the different compression algorithms anymore,  i only adapted commit a6cd0fd2bfaa6f912a4930a4329166d9bde71e94
See:
#7372
#7364
> "auto" compressor tests: do not assume zlib is better than lz4, fixes #7363 (forwardport-master)

- .github/workflows/windows.yml
- scripts/msys2-build
Use the standard pip build command, and get rid of the build script.
> Windows: simplify building

- src/borg/archive.py
before, we only set this for regular files, but we better set this for block/char devices and fifos also, so we have it for all item types borg 1.x considers "hardlinkable".
this is important for sequential processing of items in an archive: if we encounter a hardlinkable item and .source is not set (that would make it a hardlink slave), it could be a hardlink master or not:
- hardlink_master == False  # this item is not part of a hl group
- hardlink_master == True  # this item is a hardlink master
This will also be important when items are converted to borg2.
> set .hardlink_master for hardlinkable items, fixes #7175

- docs/installation.rst
I've replayed the dev-installation on a fresh ubuntu 22.04 and fell into the same trap as the author of #7356, because my doc entry-point was:
* https://borgbackup.readthedocs.io/en/stable/development.html#
* https://borgbackup.readthedocs.io/en/stable/development.html#building-a-development-environment
Then..
The "Building a development environment" section links to the "Using git" section. This can result in developers overseeing the os dependencies necessity.
re #7356 (via #7398)
(dev environment setup can be further streamlined, if this is of interest)
> docs: add link to OS dependencies

- docs/installation.rst
- links did not work that way
- each OS has its own headline and can be discovered easily without that directory
> docs: remove OS directory from install docs

- .github/workflows/windows.yml
The Windows CI does not need to run when files such as docs are changed.
> Windows CI: only run when certain files are modified

- src/borg/archiver/debug_cmd.py
- src/borg/testsuite/archiver/debug_cmds.py
Forward-port of eb8ccd22d46f60896a66e1d6ce03b204489dba30 #7411
> debug id-hash: implement file content id-hash computation, see #7406 (forwardport-master)

- src/borg/archiver/delete_cmd.py
for deleting the cache only, use:
borg rdelete --cache-only
> delete: remove --cache-only option, fixes #7440

- src/borg/archiver/transfer_cmd.py
- src/borg/repoobj.py
- src/borg/testsuite/repoobj.py
this needs to decompress and to hash the chunk data, but better let's play safe.
at least we still can avoid the (re-)compression with borg transfer (which is often much more expensive
than decompression).
> transfer: verify chunks we get using assert_id, fixes #7383

- Vagrantfile
Fix #7010 #7459
This adds support to build the borg dependencies from source and re-adds the stretch64 VM.
* Libraries: LIBATTR=2.5.1, LIBACL=2.3.1, LIBFUSE=3.14.0, LIBLZ4=1.9.4, LIBZSTD=1.5.4, LIBXXHASH=0.8.1, OPENSSL=1.1.1t
* `pyenv` will detect the custom openssl version and use it. This is needed to build python >= 3.10 with openssl >= 1.1.1.
* The stretch64 VM is re-added.
The stretch64 `llfuse` tests seem okay, except 3 issues caused by fakeroot. This is likely unrelated.
The stretch64 `pyfuse3` tests show a few errors for the borg.exe, which is not built with pyfuse3. This seems due to how the FUSE_IMPL is detected.
```
borg mount not available: no FUSE support, BORG_FUSE_IMPL=pyfuse3. 
```
* A borg.exe built with llfuse, will fail the tests when called with …
> Add support to build dependencies from source to the Vagrantfile

- src/borg/archiver/debug_cmd.py
- src/borg/repoobj.py
- src/borg/testsuite/archiver/debug_cmds.py
Implements #7406 
Format of `parse-obj` and `format-obj` commands are:
```python
borg debug parse-obj --repo REPO_PATH INPUT_ID COMPRESSED_FILE OUTPUT_FILE OUTPUT_JSON 
borg debug format-obj --repo REPO_PATH INPUT_ID INPUT_FILE INPUT_JSON OUTPUT_FILE --compression="xyz,4"
```
The user is expected to use `borg debug get-obj` to get `COMPRESSED_FILE` for `parse-obj`.
Similarly, the user is expected to use `borg debug id-hash` to get `INPUT_ID` for `format-obj`.
> Add parse-obj and format-obj debug commands

- src/borg/helpers/fs.py
- src/borg/testsuite/helpers.py
> fix config/cache dir compatibility issues, fixes #7445

- src/borg/helpers/progress.py
- src/borg/testsuite/helpers.py
needs to use swidth() in case there are wide chars (like CJK) in the left part of the msg (e.g. an archive name).
> ProgressIndicatorPercent: fix space computation for wide chars, fixes #3027

- src/borg/archiver/mount_cmds.py
saying "must be a writable directory" can distract from the real root cause as seen in #7496.
so we better first check if the mountpoint is an
existing directory and if not, just tell that.
after that, we check permissions and if they are not like required, tell that.
> mount: improve mountpoint error msgs, see #7496

- src/borg/helpers/parseformat.py
- src/borg/testsuite/archiver/rlist_cmd.py
```
$ borg rlist --format '{name} {size} {nfiles}{NL}' 
docs 20150956 436
```
> rlist: size and nfiles format keys

- docs/usage/general/environment.rst.inc
- src/borg/archiver/list_cmd.py
- src/borg/archiver/prune_cmd.py
- src/borg/archiver/rlist_cmd.py
for now for: prune, list, rlist.
> implement BORG_<CMD>_FORMAT env vars, fixes #5166

- src/borg/archiver/__init__.py
as a first step, i moved all the traceback formatting to format_tb.
also, it **first** prints the error and then the traceback as additional information for a bug report, as suggested by @jimparis in that ticket.
> refactor toplevel exception handling, see #6018

- src/borg/archiver/_common.py
- src/borg/testsuite/archiver/argparsing.py
Ensure that cli options specified with action=Highlander can only be set once, even if the set value is a default value. Add tests for action=Highlander. 
Closes #7500
> Ensure that cli options specified with action=Highlander can only be set once.

- src/borg/archiver.py
> improve --one-file-system help /docs

- src/borg/archiver.py
Should we still bother with 1.2, or is v2 imminent?
> incl./excl. options, path-from-stdin exclusiveness

- docs/faq.rst
- docs/quickstart_example.rst.inc
- docs/usage/delete.rst
- docs/usage/mount.rst
- docs/usage/prune.rst
at some places, the docs were not updated yet.
for borg 1.x, -a (aka --glob-archives) expected
sh: style glob patterns ONLY (but one must not
give sh: explicitly).
for borg 2, -a (aka --match-archives) defaults
to id: style (identical match), so one must give
sh: if one wants shell-style globbing.
> docs: fix some -a / --match-archives issues

- src/borg/testsuite/archive.py
- src/borg/testsuite/archiver/help_cmd.py
- src/borg/testsuite/cache.py
- src/borg/testsuite/key.py
sometimes the automatically computed IDs are just too long, so rather give IDs directly or avoid them otherwise.
> tests: avoid long ids in pytest output

- SECURITY.md
At 1.2.4 release, this update was added to 1.2-maint branch, but not to master branch.
Also tell that 2.0.x is not released yet and thus there is also no security support for it yet.
> Security support docs (master)

- src/borg/constants.py
- src/borg/repository.py
+ os.scandir instead of os.listdir: Improved speed and added flexibility with attributes (name, path, is_dir(), is_file())
+ use is_dir / is_file to make sure we're reading only dirs / files respectively
+ Filtering to particular start, end index range built in
+ Have separate generators to avoid unnecessary less_than / greater_than checking for every dir/file when not required
Resolves #7597
> unify scanning and listing of segment dirs, files and apply good practices

- src/borg/repository.py
With this commit, empty directories are cleared after segments compacting.
Fixes https://github.com/borgbackup/borg/issues/6823
> clear empty directories at end of compact process, fixes #6823

- src/borg/constants.py
- src/borg/repository.py
+ os.scandir instead of os.listdir Improved speed and added flexibility with attributes (name, path, is_dir(), is_file())
+ use is_dir / is_file to make sure  we're reading only dirs / files respectively
+ Filtering to particular start, end index range built in
+ Move value bounds of segment (index) into constants module and use them instead
Resolves #7597
(forward port from commits c9f35a16e9bf9e7073c486553177cef79ff1cb06^..edb5e749f512b7737b6933e13b7e61fefcd17bcb)
> unify scanning and listing of segment dirs / segment files and apply good practices

- src/borg/repository.py
Compact moves data to new segments, and then removes the old segments. When enough segments are moved, directories holding the now cleared segments may thus become empty.
With this commit any empty directories are cleared after segments compacting. Fixes #6823
> Add function to clear empty directories at end of compact process.

- src/borg/testsuite/item.py
- src/borg/testsuite/version.py
Continued parameterization efforts in the the test suite. This draft PR focuses on the `version` and `item` tests.
> Parameterize version and item tests

- src/borg/testsuite/chunker_pytest.py
the last chunk can be smaller than 2**min_exp.
> fix test_buzhash_chunksize_distribution

- docs/usage/general/environment.rst.inc
- src/borg/archiver/_common.py
- src/borg/archiver/serve_cmd.py
- src/borg/helpers/__init__.py
- src/borg/helpers/fs.py
- src/borg/helpers/parseformat.py
- src/borg/logger.py
- src/borg/remote.py
- src/borg/testsuite/archiver/__init__.py
- src/borg/testsuite/archiver/serve_cmd.py
- src/borg/testsuite/helpers.py
Server side (listening side):
```
borg serve --socket=/path/to/socket
or
borg serve --socket  # finds socket at `get_runtime_dir()/borg.sock`
```
Client:
```
borg --socket=/path/to/socket --repo=socket:///path/to/repo rcreate ...
or
borg [--socket] --repo socket:///path/to/repo create ...  # finds socket at `get_runtime_dir()/borg.sock`
```
`BORG_RUNTIME_DIR` env var can be used to override `BORG_BASE_DIR` and `platformdirs.user_runtime_dir`, as usual.
fixes #6183.
> implement unix domain socket support

- src/borg/archive.py
- src/borg/fuse.py
- src/borg/helpers/lrucache.py
- src/borg/repository.py
- src/borg/testsuite/lrucache.py
Hello,
while looking trough the code I noticed that `LRUCache` is using custom logic to keep track of ordering which handles the `list` operations not very efficiently.
Since `OrderedDict` is implemented in C it should provide a speedup and allow for a simpler implementation.
I tried to run the tests on my machine but `conftest.py` fails to parse the version made up by setuptools-scm.
> replace `LRUCache` internals with `OrderedDict`

- src/borg/testsuite/archiver/extract_cmd.py
about 10-50% of the github windows CI runs fail due to this - root cause unknown.
Example failure:
```
sparse_support = is_sparse(filename, total_size, hole_size)
if sparse_support:
self.cmd(f"--repo={self.repository_location}", "rcreate", RK_ENCRYPTION)
self.cmd(f"--repo={self.repository_location}", "create", "test", "input")
with changedir(self.output_path):
self.cmd(f"--repo={self.repository_location}", "extract", "test", "--sparse")
self.assert_dirs_equal("input", "output/input")
filename = os.path.join(self.output_path, "input", "sparse")
with open(filename, "rb") as fd:
>               self.assert_equal(fd.read(hole_size), b"\0" * hole_size)
E               AssertionError: b'\x0[8388602 chars]x00\xf0Y\xb5\xe3\xee\xf3\x1f\xe3L\xcf\xae\x92\[159253621 chars]\x00' != b'\x0[8388602 …
```
> test_sparse_file: skip test on win32

- docs/usage/list.rst
- pattern needs to start with + - !
- first match wins
- the default is to list everything, thus a 2nd pattern is needed to exclude everything not matched by 1st pattern.
> list: fix --pattern examples, fixes #7611

- src/borg/crypto/key.py
check key file structure, make sure the binary key is not way too short (or zero) length.
if key file looks strange, emit warnings.
> keyfile: improve key sanity check, fixes #7561

- src/borg/fuse.py
macFUSE supports a volname mount option to give what finder displays on desktop / in directory list.
if the user did not specify it, we make something up, because otherwise it would be "macFUSE Volume 0 (Python)".
> mount: make up volname if not given (macOS), fixes #7690

- docs/usage/prune.rst.inc
Move the explanation below the general explanation of the `--keep-*` option
behavior rephrase the last sentence to make it clear that it works like the
other options that were explained in the previous paragraph.
Resolves #7687
> Improve the documentation for `--keep-within`

- src/borg/archive.py
- src/borg/archiver.py
- src/borg/helpers/manifest.py
- src/borg/helpers/time.py
- src/borg/repository.py
- src/borg/testsuite/archiver.py
`datetime.utcnow()` is deprecated since Python 3.12. This causes additional lines of output and thus breaks the test suite. I was not sure if all borg internals are ready to deal with timezone-aware datetime instances so tried to keep the changes minimal.
This error was detected during the Python 3.12 mass rebuild for the upcoming Fedora 39.
> add `utcnow()` helper function to avoid `datetime.utcnow()`

- setup_docs.py
- src/borg/testsuite/helpers.py
`datetime.utcfromtimestamp` is deprecated in Python 3.12:
```
src/borg/testsuite/helpers.py:1218: DeprecationWarning: datetime.utcfromtimestamp() is deprecated and scheduled for removal in a future version. Use timezone-aware objects to represent datetimes in UTC: datetime.fromtimestamp(timestamp, datetime.UTC).
assert datetime.utcfromtimestamp(safe_ns(beyond_y10k) / 1000000000) > datetime(2038, 1, 1)
```
I added a custom helper with emulates the behavior of `datetime.utcnow` to avoid the deprecation warning. My idea was that creating tz-aware datetime instances creates longer code lines and reduces readability.
> replace "datetime.utcfromtimestamp" to avoid deprecation warnings with Python 3.12

- src/borg/helpers/fs.py
- src/borg/testsuite/archiver/create_cmd.py
> Properly normalise paths on Windows

- src/borg/testsuite/helpers.py
A borgbackup-2.0.0b6 test fails on OpenBSD with the message below.
```
=================================== FAILURES ===================================
_____________________________ test_get_runtime_dir _____________________________
path = '/run/user/55/borg', mode = 511, pretty_deadly = True
def ensure_dir(path, mode=stat.S_IRWXU | stat.S_IRWXG | stat.S_IRWXO, pretty_deadly=True):
"""
Ensures that the dir exists with the right permissions.
1) Make sure the directory exists in a race-free operation
2) If mode is not None and the directory has been created, give the right
permissions to the leaf directory. The current umask value is masked out first.
3) If pretty_deadly is True, catch exceptions, reraise them with a pretty
message.
Returns if the directory has been created and has the …
```
> Fix failing test on OpenBSD

- src/borg/archiver/check_cmd.py
The current `borg check` docs have a very tech-centered focus. Some rather important bits for users are just small notes in subordinate clauses and the docs didn't really focus on what the user needs to know and what he's supposed to do (see e.g. #7578). Therefore I rewrote the docs. It appears like a rewrite from scratch, but in reality heavily relies on what was there before.
**Important!** I rewrote the docs based on what I understood from the old docs. Since the old docs were a bit ambiguous sometimes, I might got some things wrong. Thus it's very important that someone with actual code insight checks this.
Some open questions:
- ~~I was a bit confused about what `--max-duration` is lacking compared to a full repo check. Does only a full repo check include the repo index check, or …
> Docs: Rewrite `borg check` docs

- src/borg/crypto/key.py
This is an emergency workaround for authenticated repos if the user has lost the borg key.
We can't compute the TAM key without the borg key, so just skip all the TAM stuff.
> bugfix: skip TAM check with BORG_WORKAROUNDS=authenticated_no_key

- docs/usage/general/environment.rst.inc
- src/borg/archiver/rcreate_cmd.py
- src/borg/crypto/key.py
- src/borg/repoobj.py
> BORG_WORKAROUNDS=authenticated_no_key to extract from authenticated repos without key, fixes #7700

- src/borg/testsuite/archiver/__init__.py
- src/borg/testsuite/archiver/argparsing.py
- src/borg/testsuite/archiver/benchmark_cmd.py
- src/borg/testsuite/archiver/bypass_lock_option.py
- src/borg/testsuite/archiver/check_cmd.py
- src/borg/testsuite/archiver/checks.py
- src/borg/testsuite/archiver/config_cmd.py
- src/borg/testsuite/archiver/corruption.py
- src/borg/testsuite/archiver/create_cmd.py
- src/borg/testsuite/archiver/debug_cmds.py
- src/borg/testsuite/archiver/delete_cmd.py
- src/borg/testsuite/archiver/diff_cmd.py
- src/borg/testsuite/archiver/extract_cmd.py
- src/borg/testsuite/archiver/info_cmd.py
- src/borg/testsuite/archiver/key_cmds.py
- src/borg/testsuite/archiver/list_cmd.py
- src/borg/testsuite/archiver/lock_cmds.py
- src/borg/testsuite/archiver/mount_cmds.py
- src/borg/testsuite/archiver/prune_cmd.py
- src/borg/testsuite/archiver/rcompress_cmd.py
- src/borg/testsuite/archiver/rcreate_cmd.py
- src/borg/testsuite/archiver/rdelete_cmd.py
- src/borg/testsuite/archiver/recreate_cmd.py
- src/borg/testsuite/archiver/rename_cmd.py
- src/borg/testsuite/archiver/rinfo_cmd.py
- src/borg/testsuite/archiver/rlist_cmd.py
- src/borg/testsuite/archiver/tar_cmds.py
- src/borg/testsuite/archiver/transfer_cmd.py
Solves [this comment](https://github.com/borgbackup/borg/pull/7722#issuecomment-1646961750).
Currently, every cmd in `testsuite/archiver/` tests are passing `f"repo={archiver.repository_location}"` as an argument, in addition to the `archiver` itself. @ThomasWaldmann suggested just creating this argument in the function itself, thus removing a lot of redundant and messy code. That is what I have done here.
> `cmd` function now creates repo_location argument

- src/borg/testsuite/platform.py
- src/borg/testsuite/platform_darwin.py
- src/borg/testsuite/platform_linux.py
- src/borg/testsuite/platform_posix.py
This is one of the last remaining files in the test suite to have quite a bit of unittest and `BaseTestCase` usages, so I split it into its own PR. Will convert all unittest to pytest, remove `BaseTestCase` entirely, and rename some tests to follow the naming conventions of the classes they are being pull from.
> PR: `testsuite/platform.py` conversion to pytest + remove `BaseTestCase`

- src/borg/testsuite/archive.py
- src/borg/testsuite/chunker_slow.py
- src/borg/testsuite/helpers.py
Now that the `ArchiverBaseTestCase` has been removed from `testsuite/archiver/__init__.py`, I would now like to remove `BaseTestCase` from the `testsuite/__init__.py`. After @ThomasWaldmann's recent update to the `BaseTestCase`[here](https://github.com/borgbackup/borg/pull/7736), all that remains are a few assert methods that seem superfluous and could be replaced with the built-in python asserts.
> PR: Remove BaseTestCase from `testsuite/`

- src/borg/testsuite/platform.py
- src/borg/testsuite/platform_freebsd.py
Creates a dummy file for ACL testing FreeBSD. Relates to issue #7745.
> `platform_freebsd.py` dummy test file

- docs/usage/general/environment.rst.inc
It mentioned borg rcreate due to a bad backport from master. Must be borg init in borg 1.2.x.
> docs: fix borg init command in environment.rst.inc

- src/borg/archiver/help_cmd.py
borg2 repos are not compatible with borg1 anyway,
so no need to mention that.
> docs: remove zstd compat hint

- docs/changes.rst
while the main issue in the code has been fixed since 1.2.5, let's better refer to 1.2.6, which has fixes in upgrade docs and code.
> docs: minor fix to CVE-2023-36811 related upgrade instructions

- src/borg/archive.py
- src/borg/archiver/key_cmds.py
- src/borg/archiver/rcreate_cmd.py
- src/borg/cache.py
- src/borg/crypto/key.py
- src/borg/helpers/parseformat.py
- src/borg/item.pyx
- src/borg/manifest.py
- src/borg/testsuite/archiver/checks.py
- src/borg/testsuite/key.py
remove a lot of complexity from the code that was just there to
support legacy borg versions.
borg < 1.0.9 which did not TAM authenticate the manifest nor the archives.
borg < 1.2.6 did not always (correctly) TAM authenticate the archives.
The upgrade procedure to 1.2.6+ includes enabling TAM authentication for manifest and all archives, including existing archives.
> TAM: always generate and verify

- requirements.d/development.lock.txt
- requirements.d/development.txt
twine is only needed at release time, no need
for all developers or all test runs to install
this.
also, some requirement of twine needs a rust
compiler, so if there is no rust compiler,
automated runs will abort due to that.
> remove twine from requirements

- Vagrantfile
- setup.py
OpenSSL-1.1.1 reached EOL status. Switch building on OpenBSD to OpenSSL-3.0 (LTS version).
> OpenBSD only: switch to OpenSSL-3.0

- docs/internals/data-structures.rst
- docs/internals/security.rst
- src/borg/archive.py
- src/borg/archiver/debug_cmd.py
- src/borg/archiver/rcompress_cmd.py
- src/borg/archiver/tar_cmds.py
- src/borg/archiver/transfer_cmd.py
- src/borg/cache.py
- src/borg/constants.py
- src/borg/crypto/key.py
- src/borg/fuse.py
- src/borg/helpers/misc.py
- src/borg/helpers/parseformat.py
- src/borg/manifest.py
- src/borg/remote.py
- src/borg/repoobj.py
- src/borg/testsuite/archive.py
- src/borg/testsuite/archiver/check_cmd.py
- src/borg/testsuite/archiver/checks.py
- src/borg/testsuite/archiver/rcompress_cmd.py
- src/borg/testsuite/key.py
- src/borg/testsuite/remote.py
- src/borg/testsuite/repoobj.py
writing: put type into repoobj metadata
reading: check wanted type against type we got
repoobj metadata is encrypted and authenticated.
repoobj data is encrypted and authenticated, also (separately). encryption and decryption of both metadata and data get the same "chunk ID" as AAD, so both are "bound" to that (same) ID.
a repo-side attacker can neither see cleartext metadata/data, nor successfully tamper with it (AEAD decryption would fail).
also, a repo-side attacker could not replace a repoobj A with a differently typed repoobj B without borg noticing:
- the metadata/data is cryptographically bound to its ID. authentication/decryption would fail on mismatch.
- the type check would fail.
thus, the problem (see CVEs in changelog) solved in borg 1 by the manifest and archive TAMs is now …
> replace TAMs by typed repo objects, fixes #7670

- scripts/glibc_check.py
Hi y'all,
There's a small issue in `scripts/glibc_check.py`: it uses `shell=True` with untrusted input leading to some problems. Given that it's a completely separate script mentioned at the bottom of the FAQ meant for developers it's not in a practical sense a security issue, but still.
Before:
```
$ python3 scripts/glibc_check.py 2.11 '/bin/date; touch /tmp/ohno'
The binaries do not work with the given glibc 2.11. Minimum is: 2.34
$ ls -al /tmp/ohno 
-rw-r--r-- 1 quinox development 0 Oct  6 14:40 /tmp/ohno
```
After:
```
$ python3 scripts/glibc_check.py 2.11 '/bin/date; touch /tmp/ohno'
/bin/date; touch /tmp/ohno errored.
File "/tmp/borg/scripts/glibc_check.py", line 61, in <module>
ok = main()
File "/tmp/borg/scripts/glibc_check.py", line 46, in main …
```
> Prevent CLI argument issues in scripts/glibc_check.py

- src/borg/archiver.py
The -a option for borg prune accepts only glob pattern (i.e. sh:) but not the actual prefix sh: which can be confusing especially for people who don't actually know what a glob pattern is. Also added a warning for the change in behaviour in borg v2.
fixes #7868
> Clarify borg prune -a option description

- docs/usage/general/environment.rst.inc
- setup.py
Using pkgconfig gives a more meaningful error message in case libacl development files are missing.
> linux: use pkgconfig to find libacl

- docs/deployment/automated-local.rst
> automated-local.rst: use GPT UUID for consistent udev rule (1.2-maint)

- .github/workflows/ci.yml
esp. the macOS CI jobs are sometimes rather slow,
so 40min were not enough.
> CI: increase timeout to 90min

- src/borg/repository.py
- src/borg/testsuite/repository.py
This is a fix to `borg check --repair` so it will recreate a complete shadow_index inside the hints file.
Doing that should fix **past** issues caused by the double-put bug (see #7896) and by the persistence of the shadow index, which is new since borg 1.2.
When running borg in client/server mode (with a remote repo), the fix needs to get applied repo/server-side.
> check --repair fixes shadow_index (1.2-maint)

- src/borg/repository.py
- src/borg/testsuite/repository.py
This is to avoid **future** issues when borg issues a double-put (a put to a chunk id that already exists in the repo - AFAIK it only does that for borg recreate when changing compression and also for each manifest update - but in case of the manifest this maybe never triggered an issue because the manifest was usually written into an own small segment file).
When running borg in client/server mode (with a remote repo), the fix needs to get applied repo/server-side.
> fix shadow index update for double-put (1.2-maint)

- src/borg/_chunker.c
With Python 3.13, Python.h no longer includes the `<unistd.h>` standard header file: https://docs.python.org/3.13/whatsnew/3.13.html#id8
Disclaimer: I only tested this with borg 1.2 as I failed to create a Python 3.13 virtualenv with borg 2. However the fix
> Python 3.13: include `unistd.h` in `_chunker.c`

- docs/changes.rst
The traceback seen there came from borg not showing a .checkpoint archive that didn't have a valid TAM and thus the user not see it / fix it:
https://github.com/borgbackup/borg/issues/7802#issuecomment-1793860606
> CVE-2023-36811 upgrade docs: consider checkpoint archives, fixes #7802

- src/borg/archiver/create_cmd.py
When borg invokes a system command, it needs to prepare the environment for that. This is especially important when using a pyinstaller-made borg fat binary that works with a modified env var LD_LIBRARY_PATH - system commands may crash with that.
borg already had calls to prepare_subprocess_env at some places (e.g. when invoking ssh for the remote repo connection), but they were missing for:
borg create --content-from-command ...
borg create --paths-from-command ...
> create --*-from-command: run subcommands with a clean environment, fixes #7916

- docs/deployment/image-backup.rst
> Add backup by SERIAL method documentation

- src/borg/locking.py
- src/borg/testsuite/locking.py
The intention of LockRoster.modify(key, REMOVE) is to remove self.id.
Using set.discard will just ignore it if self.id is not present there anymore.
Previously, using set.remove triggered a KeyError that has been frequently seen in tracebacks of teardowns involving Repository.__del__ and Repository.__exit__.
I added a REMOVE2 op to serve one caller that needs to get the KeyError if self.id was not present.
Thanks to @herrmanntom for the workaround!
> LockRoster.modify: no KeyError if element was already gone, fixes #7937

- docs/changes.rst
https://github.com/borgbackup/borg/issues/7802#issuecomment-1823651979
> Remove period that could be interpreted as part of the command

- src/borg/_chunker.c
With Python 3.13, Python.h no longer includes the <unistd.h> standard header file: https://docs.python.org/3.13/whatsnew/3.13.html#id8
(backport from master)
> include unistd.h in _chunker.c

- docs/changes.rst
- docs/usage/notes.rst
I forked a new maintenance branch `1.4-maint` at borg 1.2.7.
This brings it in sync with updates that were done in 1.2-maint after 1.2.7.
> sync with 1.2-maint

- setup.py
drop support for Cython 0.29.x, use Cython 3.0.x from now on.
> cython: use 3str language level (default in cython3), fixes #7978

- src/borg/crypto/low_level.pyx
These were deprecated in OpenSSL 3.0.
Instead, use hmac.digest from Python stdlib.
> crypto: get rid of deprecated HMAC_* functions

- src/borg/archiver/create_cmd.py
- src/borg/archiver/diff_cmd.py
- src/borg/archiver/extract_cmd.py
- src/borg/archiver/key_cmds.py
- src/borg/archiver/list_cmd.py
- src/borg/archiver/mount_cmds.py
- src/borg/archiver/recreate_cmd.py
- src/borg/archiver/tar_cmds.py
- src/borg/helpers/__init__.py
- src/borg/helpers/parseformat.py
> PATH: do not accept empty strings, fixes #4221

- pyproject.toml
- setup.py
> use and require cython3

- src/borg/archiver.py
- src/borg/testsuite/archiver.py
Add exception handling. Prints error message instead of exception if binary run with `with-lock` does not exist:
```bash
(venv) kmille@linbox:borg venv/bin/borg with-lock ~/tmp/borgrepo noo
Could not execute 'noo': [Errno 2] No such file or directory: 'noo'
```
I only handle `FileNotFoundException`. Here are the [subprocess docs about exceptions](https://docs.python.org/3/library/subprocess.html#exceptions). We could also catch [SubprocessError](https://docs.python.org/3/library/subprocess.html#subprocess.SubprocessError), [OSError](https://docs.python.org/3/library/exceptions.html#OSError) and [ValueError](https://docs.python.org/3/library/exceptions.html#ValueError) but then I'm still not sure if that's all. I really like python but to find out which exceptions can be raised is... …
> catch FileNotFoundError in `borg with-lock`, fixes #8022

- src/borg/logger.py
this is for better compatibility with python's Logger methods which we wrap here:
- have a first param `msg` for the usual logging calls (which is either a simple string or a format string if args are also given)
- use `kwargs`, not `kw`
- fix `.setLevel` params
- fix `.exception` params
This shouldn't change the behaviour of existing correct calls, just catch incorrect calls and be prettier in IDEs.
> logger method params (1.4-maint)

- src/borg/archiver.py
Since long, we have borg --version to display the borg (client) version string in its very detailed form provided by setuptools_scm, e.g.:
borg 1.4.0.dev119+gc7cef548.d20240119
Now there is an additional new command "borg version <REPO>", which shows the client / server version, e.g.:
1.4.0a / 1.2.7
If a local repo is given, the client code directly accesses the repository, thus we show the client version also as the server version.
If a remote repo is given (e.g. ssh:), the remote borg is queried and its version is displayed as the server version.
Due to the version tuple format used in borg client/server negotiation, only a simplified version is displayed (as provided by borg.version.format_version).
> implement "borg version", fixes #7829

- src/borg/repository.py
Also: use ERROR loglevel for these (not WARNING).
A different amount of index entries was already logged as error and led to "error_found = True" in repository.check.
Different values in the rebuilt index vs. the on-disk index were only logged on warning level, but did not lead to error_found = True.
Guess there is no reason why these should not be errors and lead to error_found = True, so this was fixed in this commit.
Minor related change: change report_error function args, so it can be called like logger.error - including giving a format AND args.
> check: fix return code for index entry value discrepancies

- .github/workflows/ci.yml
especially the macos workers are sometimes extremely slow.
> gh actions: increase timeout

- pyproject.toml
The long_desc_from_readme() was not called, it just read the whole README.rst until "readme" was declared dynamic.
> sdist: dynamically compute readme (long_description)

- src/borg/helpers/__init__.py
- src/borg/helpers/parseformat.py
- src/borg/remote.py
this is a fwd port from 1.4-maint #8047.
as we don't have nonce files any more in master, only the generally useful stuff has been ported.
- add Error / ErrorWithTraceback exception classes to RPC layer.
- add hex_to_bin helper
> give clean error msg for invalid nonce file, see #7967

- src/borg/archiver/config_cmd.py
- src/borg/archiver/debug_cmd.py
- src/borg/cache.py
- src/borg/crypto/key.py
- src/borg/crypto/keymanager.py
- src/borg/repository.py
- src/borg/testsuite/archiver/key_cmds.py
- src/borg/testsuite/archiver/rcompress_cmd.py
- src/borg/testsuite/checksums.py
- src/borg/testsuite/chunker_slow.py
- src/borg/testsuite/crypto.py
- src/borg/testsuite/key.py
our own hex_to_bin / bin_to_hex is more comfortable to use.
also: optimize remaining binascii usage / imports.
> refactor: use less binascii

- src/borg/archiver.py
(backport from master, only thing todo here was that one place)
> fix: Error/CommandError have a output format for 1 argument

- docs/deployment.rst
- docs/deployment/non-root-user.rst
Add a deployment strategy describing how to run borg as a non-root user and still be able to access/backup all files on the system.
I was not sure if I should include more about how/where to create the systemd service and timer files. I feel like this would not be the place to explain basic systemd, so I kept it short. If someone feels different, I could add more detail.
> add non-root deployment strategy

- src/borg/archive.py
I put it into same class as EPERM and EACCES:
BackupPermissionError: borg is not permitted to access the file.
> create: deal with EBUSY, fixes #8123

- .pre-commit-config.yaml
- docs/changes.rst
- src/borg/archiver.py
- src/borg/crypto/key.py
- src/borg/helpers/__init__.py
Some new `borg upgrade` options to simplify the CVE-related borg > 1.2.4 upgrade procedure.
> repo upgrade helpers (1.2-maint)

- src/borg/archive.py
- src/borg/platform/darwin.pyx
- src/borg/platform/freebsd.pyx
- src/borg/platform/linux.pyx
- src/borg/testsuite/platform.py
This definitely will need some review and practical testing.
Fixes #4049.
Fixes #8139.
> improve acl_get / acl_set error handling (1.4-maint)

- src/borg/archiver.py
This PR fixes bug described in https://github.com/borgbackup/borg/pull/8152 for 1.2 branch
> changed insufficiently reserved length for log message (copy of #8152 for 1.2)

- src/borg/archive.py
- src/borg/platform/darwin.pyx
- src/borg/platform/freebsd.pyx
- src/borg/platform/linux.pyx
- src/borg/testsuite/platform.py
- src/borg/testsuite/platform_darwin.py
- src/borg/testsuite/platform_freebsd.py
> improve acl_get / acl_set error handling (master)

- src/borg/helpers/time.py
- src/borg/testsuite/archive.py
- src/borg/testsuite/helpers.py
maybe this fixes the frequently failing test.
also, giving ms makes more sense than 10ms granularity.
> format_timedelta: use 3 decimal digits (ms)

- src/borg/archiver/prune_cmd.py
During `borg prune` I've encountered a minor issue -- output was not properly aligned.
```
Keeping archive (rule: hourly #3):       2024-02-20-23:13:36                  Tue, 2024-02-20 23:13:38 [53dbb412a3d28b8d788cee0fe189d1ceefd4affd27866d23ffaee7cd45af5971]
Keeping archive (rule: hourly[oldest] #4): 2024-02-20-23:09:22                  Tue, 2024-02-20 23:09:24 [66392999b4cb3a71262f1bdff4ecd05bcb6b74c6dc1ae6a2c9903bcf4a8137b3]
```
This PR fixes this issue. Full command with output can be viewed [here](https://gist.github.com/galqiwi/4402da1a7eb46546c2973f574a261112).
> changed insufficiently reserved length for log message 

- setup.py
Looks like borg's setup.py has hidden the real cause of a cythonize ImportError.
There are basically 2 cases:
- either there is no Cython installed, then the import fails because the module can not be found, or
- there is some issue within Cython and the import fails due to that.
It's important not to hide the real cause, especially if we run into case 2.
case 1 is kind of expected and frequent, case 2 is rare.
> setup.py: fix import error reporting for cythonize import, see #8208

- setup.py
- src/borg/helpers/msgpack.py
tests with 1.1.0rc1 were successful, thus I assume 1.1.0 will also work ok.
> allow msgpack 1.1.0

- Vagrantfile
- scripts/fetch-binaries
RHEL8 and clones are on this glibc version.
Fixes #8171.
> revive the buster64 box (1.4-maint)

- docs/installation.rst
Installing Borg from `pip` requires a few dependencies. Unfortunately, zypper can't find a few of those listed. Here's the fix.
> Fixed openSUSE dependencies in installation.rst

- docs/usage/mount.rst
Simply omitting the first positional argument (REPO) does not work because borg then gets confused.
> docs: add examples using :: positional argument, fixes #8255

- src/borg/cache.py
- src/borg/testsuite/archiver/corruption.py
Here is a fix for #5213 by calling wipe_cache() if an exception is raised on LocalCache.open().
> Automatic rebuild cache on exception, fixes #5213

- docs/faq.rst
- docs/usage/general/environment.rst.inc
- src/borg/cache.py
- src/borg/testsuite/archiver.py
This is the backport of the pull request #8281 to fix #8280 on 1.4-maint
> Backport BORG_USE_CHUNKS_ARCHIVE env var to 1.4-maint

- src/borg/archive.py
- src/borg/testsuite/archiver/check_cmd.py
test the healing more thoroughly:
- preservation of correct chunks list in .chunks_healthy
- check that .chunks_healthy is removed after healing
- check that doing another borg check --repair run does not find something to heal, again.
also did a datatype consistency fix for item.chunks_healthy list members: they are now post processed in the same way as item.chunks, so they have type ChunkListEntry rather than simple tuple.
> improve borg check --repair healing tests, see #8302

- docs/usage/general/date-time.rst.inc
- Closes borgbackup/borg#8310
Is this acceptable, or you had something different in mind?
> Add TIMESPAN to doc

- docs/deployment/automated-local.rst
Hey there!
This small documentation fix aligns all `/etc/backups` path references in the Automated Backups to a Local Hard Drive deployment guide. Previously, there were some references to `/etc/backup` instead of `/etc/backups`, which caused confusion.
> docs: align /etc/backups path references in automated backups deployment guide

- docs/deployment/automated-local.rst
Backport (cherrypick) from master to 1.4-maint of #8314 
This small documentation fix aligns all /etc/backups path references in the Automated Backups to a Local Hard Drive deployment guide. Previously, there were some references to /etc/backup instead of /etc/backups, which caused confusion.
> docs: align /etc/backups path references in automated backups deployment guide (1.4-maint)

- src/borg/archiver.py
- src/borg/testsuite/__init__.py
- src/borg/testsuite/archiver.py
Right now, if `borg diff` is run with the `--json-lines` parameter (and without `--content-only`, files whose content have _not_ been modified will still be given a `modified` entry of `{"added": 0, "removed": 0, "type": "modified"}`, e.g.:
```
{"changes": [{"added": 0, "removed": 0, "type": "modified"}, {"new_ctime": "2024-07-22T20:13:59.352959", "old_ctime": "2020-01-06T02:21:13.955255", "type": "ctime"}], "path": ".areca/workspace/.log/areca.12-06-24.log"}
```
Per IRC discussion, this is considered a bug, as the file's content was not actually _changed_, and thus shouldn't be in the `changes` JSON array. This PR fixes the behavior so that JSON entries no longer get a `"type": "modified"` object for files whose contents weren't changed, but `ctime`, `mtime`, etc _were_ changed. E.g.: …
> Suppress modified changes for files which weren't actually modified in JSON output.

- docs/misc/prune-example.txt
- src/borg/archiver.py
- src/borg/helpers/misc.py
- src/borg/testsuite/archiver.py
This implements and would close #4750 as described. It works for my use case, but is not ready to be merged due to no tests and docs, and there are subtleties to be addressed wrt [what a quarter year actually means](https://en.wikipedia.org/wiki/Calendar_year#Quarter_year).
To do:
> Add quarterly pruning strategy.

- pyproject.toml
so we can do borgstore releases:
0.0.x == compatible fixes, would match
0.1.0 could be incompatible changes, would not match
> require borgstore~=0.0.1

- docs/deployment/central-backup-server.rst
- docs/faq.rst
> Update repository URLs in docs to use new syntax

- docs/usage/general/repository-urls.rst.inc
> docs: user@ and :port are optional in sftp and ssh URLs

- src/borg/testsuite/archiver/create_cmd.py
frequently failing on fast machines.
> remove the hashing/chunking time tests

- src/borg/archiver/compact_cmd.py
- src/borg/archiver/diff_cmd.py
- src/borg/archiver/transfer_cmd.py
- src/borg/fuse.py
- src/borg/helpers/parseformat.py
- src/borg/testsuite/archiver/__init__.py
For Archive(), always use the archive id, not the archive name!
> fixes for non-unique archive names

- src/borg/repository.py
under all circumstances, we must avoid that the lock gets stale due to not being refreshed in time.
there is some internal rate limiting in _lock_refresh, so calling it often should be no problem.
fixes #8390.
> repository.list: refresh lock more frequently

- .github/workflows/ci.yml
- docs/installation.rst
The msys2 changelog says it is only needed for setuptools < 70.2.0:
https://www.msys2.org/docs/python/#known-issues
https://setuptools.pypa.io/en/stable/history.html#v70-2-0
See also TODO in #8381.
> msys2: disable SETUPTOOLS_USE_DISTUTILS=stdlib hack

- src/borg/archiver/repo_compress_cmd.py
repository.list is slow, so rather use the chunkindex, which might be cached in future. 
currently, it also uses repository.list, but at least we can solve the problem at one place then.
> repo-compress: use chunkindex rather than repository.list()

- docs/faq.rst
- docs/internals/data-structures.rst
- docs/usage/general/environment.rst.inc
- src/borg/archive.py
- src/borg/archiver/__init__.py
- src/borg/archiver/_common.py
- src/borg/archiver/create_cmd.py
- src/borg/archiver/list_cmd.py
- src/borg/archiver/prune_cmd.py
- src/borg/cache.py
- src/borg/constants.py
- src/borg/helpers/parseformat.py
- src/borg/testsuite/archiver/corruption.py
- src/borg/testsuite/archiver/create_cmd.py
- src/borg/testsuite/cache.py
- src/borg/testsuite/conftest.py
> files cache improvements

- docs/quickstart.rst
- docs/usage/general/file-systems.rst.inc
- docs/usage/general/repository-urls.rst.inc
- pyproject.toml
- src/borg/archiver/_common.py
- src/borg/helpers/parseformat.py
- src/borg/testsuite/helpers.py
Thanks to @ncw for adding an rclone backend to borgstore!
Not much to do here, except supporting rclone://... URLs.
Fixes #5324.
Fixes #1070.
Fixes #102 (fuse not needed, rclone talks to s3 directly).
Fixes #4101 (rclone mount not needed anymore, borg talks to rclone directly).
Related to #2177 (offers a lot of new storage provider options).
> add support for rclone:// repositories (via borgstore)

- src/borg/archive.py
- src/borg/archiver/compact_cmd.py
- src/borg/cache.py
borg compact uses ChunkIndex (a specialized, memory-efficient data structure), so it needs less memory now. Also, it saves that chunks index to cache/chunks in the repository.
When the chunks index is needed, it is first tried to get it from cache/chunks and only fall back to building the chunks index via repository.list() (which can be rather slow).
borg check --repair currently just invalidates the chunks cache.
borg create updates the chunks cache.
> chunks index caching

- docs/usage/repo-list.rst
- src/borg/archiver/repo_list_cmd.py
- src/borg/testsuite/archiver/create_cmd.py
- src/borg/testsuite/archiver/repo_list_cmd.py
- src/borg/testsuite/archiver/transfer_cmd.py
Looks like this now:
```
(borg-env) tw@MacBook-Pro borg % borg repo-list                    
60e521ba  Mon, 2024-09-23 22:57:11 +0200  docs             tw          MacBook-Pro  a comment
211b5d10  Thu, 2024-09-26 09:07:07 +0200  scripts          tw          MacBook-Pro
d7ceb3f1  Thu, 2024-09-26 10:05:23 +0200  scripts          tw          MacBook-Pro
bc8d1d7a  Thu, 2024-09-26 10:12:45 +0200  src              tw          MacBook-Pro
cee1c7e5  Thu, 2024-09-26 10:15:07 +0200  scripts          tw          MacBook-Pro
a07b7cd7  Thu, 2024-09-26 10:15:17 +0200  docs             tw          MacBook-Pro
```
```
(borg-env) tw@MacBook-Pro borg % borg repo-list --short
60e521ba5d44d6fed6aa984ded9301821e85d594971986097f96dc5b55597ef2
211b5d10d61558d8d85eb25c5f5c3c2f14c694c240f206c84bc007c39c4890cd …
```
> List more archive metadata

- src/borg/archive.py
- src/borg/archiver/info_cmd.py
- src/borg/constants.py
- src/borg/item.pyx
- src/borg/testsuite/archiver/info_cmd.py
Read or modify this set, only add validated str to it:
Archive.tags: Optional[set[str]]
borg info [--json] <archive> displays a list of comma-separated archive tags (currently always empty).
> tags: low-level infrastructure for archive tags

- src/borg/archiver/__init__.py
- src/borg/archiver/_common.py
- src/borg/archiver/debug_cmd.py
- src/borg/archiver/delete_cmd.py
- src/borg/archiver/diff_cmd.py
- src/borg/archiver/help_cmd.py
- src/borg/archiver/info_cmd.py
- src/borg/archiver/list_cmd.py
- src/borg/cache.py
- src/borg/manifest.py
- src/borg/testsuite/archiver/__init__.py
> AND-matching also on host, user, tags

- src/borg/repository.py
- src/borg/testsuite/conftest.py
- src/borg/testsuite/storelocking.py
also:
- add BORG_STORE_DATA_LEVELS=2 env var
- use BORG_STORE_DATA_LEVELS=0 to speed up tests
> give borgstore.Store a complete levels configuration, fixes #8432

- src/borg/helpers/msgpack.py
as borg now uses repository.store_load and .store_save to load and save the chunks cache, we need a rather high limit here.
this is a quick fix, the real fix might be using chunks of the data (preferably <= MAX_OBJECT_SIZE), so there is less to unpack at once.
see #8440.
> msgpack: increase max_buffer_size to ~4GiB

- src/borg/helpers/parseformat.py
1st commit: just fixing the protocol part:
```
% borg repo-info
Location: rclone://None/./pcloud:justtesting
```
2nd commit: do not display None, but rather empty host:
```
% borg repo-info    
Location: rclone:///./pcloud:justtesting
```
> Location.canonical_path: some fixes, see #8446

- src/borg/archive.py
- src/borg/archiver.py
- src/borg/testsuite/archiver.py
Per IRC, `borg diff` will assert if a multiply-linked file is selected for compare, but its hard link source was _not_ selected for compare. Print a warning and allow the diff to continue.
Example failure:
```
william@xubuntu-dtrain:/shares/wjones/work/browser-hist$ borg diff --content-only ::WD3200BEVT-userprofile-2021-10-17-120019 WD3200BEVT-userprofile-2021-10-24-120006 --pattern="+ pf:" --pattern="+ pp:Downloads" --pattern="! **/" > /dev/null
Local Exception
File "/home/william/Projects/borg/borg/src/borg/archiver.py", line 5412, in main
exit_code = archiver.run(args)
File "/home/william/Projects/borg/borg/src/borg/archiver.py", line 5330, in run
rc = func(args)
File "/home/william/Projects/borg/borg/src/borg/archiver.py", line 191, in wrapper
return …
```
> Do not assert on diff if hard link sources are not found due to exclusions

- src/borg/archiver/delete_cmd.py
- src/borg/archiver/prune_cmd.py
- src/borg/archiver/recreate_cmd.py
- src/borg/archiver/tag_cmd.py
- src/borg/constants.py
- src/borg/testsuite/archiver/delete_cmd_test.py
- src/borg/testsuite/archiver/prune_cmd_test.py
- src/borg/testsuite/archiver/recreate_cmd_test.py
- src/borg/testsuite/archiver/tag_cmd_test.py
Fixes #953. Fixes #8205. Fixes #4758.
> implement special tags, @PROT for protecting archives

- .github/workflows/ci.yml
- docs/usage/general/repository-urls.rst.inc
- pyproject.toml
- scripts/msys2-install-deps
- src/borg/archiver/repo_create_cmd.py
- src/borg/conftest.py
- src/borg/helpers/parseformat.py
- src/borg/remote.py
- src/borg/repository.py
- src/borg/testsuite/archiver/checks_test.py
- src/borg/testsuite/helpers_test.py
- src/borg/testsuite/legacyrepository_test.py
- src/borg/testsuite/repository_test.py
- clean up URLs / URL parsing (esp. how absolute and relative paths work)
- pre-create store directories
> changes needed for borgstore 0.1.0

- src/borg/repository.py
do not show a traceback for this (expected) case.
> simple error msg for non-existing repo, fixes #8475

- Vagrantfile
- requirements.d/development.txt
- it is broken on old macOS
- python 3.12.5/6/7 has bundled pip 24.2
Fixes #8415.
> avoid broken pip 24.2

- src/borg/archiver/mount_cmds.py
"clean" as adverb does not have suffix -ly.
Source: https://dict.leo.org/grammatik/englisch/adjv_usage_flat.php?lang=de#id=5.3.1.b
> docs: Fix grammar in borg mount docs

- src/borg/cache.py
- src/borg/hashindex.pyx
- refactor packing/unpacking of fc entries into separate functions
- instead of a chunks list entry being a tuple of 256bit id [bytes] and 32bit size [int],
only store a stable 32bit index into kv array of ChunkIndex (where we also have id and
size [and refcount]).
- only done in memory, the on-disk format has (id, size) tuples.
memory consumption (N = entry.chunks list element count, X = overhead for rest of entry):
- previously:
- packed = packb(dict(..., chunks=[(id1, size1), (id2, size2), ...]))
- packed size ~= X + N * (1 + (34 + 5)) Bytes
- now:
- packed = packb(dict(..., chunks=[ix1, ix2, ...]))
- packed size ~= X + N * 5 Bytes
> reduce memory consumption of files cache, fixes #5756

- src/borg/cache.py
If we have an entry for a chunk id in the ChunkIndex, it means that this chunk exists in the repository.
The code was a bit over-complicated and used entry.refcount only to detect whether .get(id, default) actually got something from the ChunkIndex or used the provided default value.
The code does the same now, but in a simpler way.
Additionally, it checks for size consistency if a size is provided by the caller and a size is already present in the entry.
> seen_chunk: do not use .refcount

- src/borg/archive.py
- src/borg/archiver/compact_cmd.py
- src/borg/cache.py
- src/borg/hashindex.pyi
- src/borg/hashindex.pyx
- src/borg/repository.py
- src/borg/testsuite/hashindex_test.py
Make better use of these 32bits.
> ChunkIndexEntry.refcount -> .flags

- src/borg/cache.py
if the size is not known yet in the chunks index, we must update the value there.
> compress_entry: fix assertion failure

- docs/changes.rst
- src/borg/archive.py
- src/borg/archiver/_common.py
- src/borg/archiver/check_cmd.py
- src/borg/archiver/compact_cmd.py
- src/borg/archiver/delete_cmd.py
- src/borg/archiver/prune_cmd.py
- src/borg/archiver/undelete_cmd.py
Follow-up to #8515
Refer to https://github.com/borgbackup/borg/pull/8515#pullrequestreview-2417746853 for details.
> Update docs to better incorporate new undelete command

- src/borg/archive.py
- src/borg/archiver/compact_cmd.py
- src/borg/cache.py
- src/borg/repository.py
this should fix the cache coherency issue when running (and finishing normally) multiple backups in parallel. if another backup then starts at any time, it will merge all already cached chunk indexes before beginning to process files.
Improvements:
- doesn't need a separate file for the hash
- multiple borg running in parallel don't overwrite the other's chunk indexes
- when loading the chunk index from the cache, just merge all we have there
- we can later write multiple partial chunkindexes to the cache
> chunk index cache: use cache/chunks.<HASH>, see #8503

- docs/faq.rst
- docs/quickstart.rst
- docs/usage/serve.rst
- src/borg/archiver.py
Includes changes from #8483 #8484
> Backport doc changes

- src/borg/archiver/repo_compress_cmd.py
- src/borg/hashindex.pyi
- src/borg/hashindex.pyx
Worst (but frequent) case here is that all or most of the chunks in the repo need to get recompressed, thus storing all chunk ids in a python list would need significant amounts of memory for large repositories.
We already have all chunk ids stored in cache.chunks, so we now just flag the ones needing re-compression by setting the F_COMPRESS flag (that does not need any additional memory).
> repo-compress: reduce memory consumption

- Vagrantfile
- src/borg/logger.py
Fixes #8506.
#8506 is likely caused by the Vagrant box having a mirror in its `etc/installurl`, which does not offer 7.4 packages. There are other mirrors out there who do, e.g., https://ftp.openbsd.org/pub/OpenBSD/.
> Fix OpenBSD Vagrant

- docs/usage/create.rst.inc
Rewording of the "flags" description in the docs of borg 1.4. https://github.com/borgbackup/borg/issues/8556
> Clarify  excluded and included flags for dry-run in borg the docs

- docs/usage/create.rst.inc
Rewording of the "flags" description in the docs of borg 1.2. #8556
>  Clarify excluded and included flags for dry-run in borg the docs #8563

- Vagrantfile
- docs/man/borg.1
- docs/usage/general/environment.rst.inc
- setup.py
`setup.py` hardcoded crypto library paths for OpenBSD, causing build issue when OpenBSD drops specific OpenSSL version. Solution is to make paths configurable.
Addresses #8553.
> borg2 - Support other OpenSSL versions on OpenBSD (#8553)

- .github/workflows/ci.yml
- Brewfile
- Vagrantfile
it looks like in brew they removed pkg-config formula and added an alias to the pkgconf formula (which also provides a pkg-config cli command).
the transition was not seamless:
Installing pkg-config
==> Downloading https://ghcr.io/v2/homebrew/core/pkgconf/manifests/2.3.0_1 ==> Fetching pkgconf
==> Downloading https://ghcr.io/v2/homebrew/core/pkgconf/blobs/sha256:5f83615f295e78e593c767d84f3eddf61bfb0b849a1e6a5ea343506b30b2c620 ==> Pouring pkgconf--2.3.0_1.arm64_sonoma.bottle.tar.gz Error: The `brew link` step did not complete successfully The formula built, but is not symlinked into /opt/homebrew Could not symlink bin/pkg-config
Target /opt/homebrew/bin/pkg-config
is a symlink belonging to pkg-config@0.29.2. You can unlink it:
brew unlink pkg-config@0.29.2
To force the link and overwrite …
> macos: fix broken brew pkg-config -> pkgconf transition

- src/borg/archiver/compact_cmd.py
- src/borg/testsuite/archiver/compact_cmd_test.py
with --stats it will be as slow as before, listing all repo objs.
without --stats, it will be faster by using the cached chunks index.
> compact: add --stats option

- docs/installation.rst
I was installing borg2 (`pip install borgbackup==2.0.0b14`) on Debian 12 (bookworm) armv7l and found the libffi header missing.
Was following along the instructions in that section (python virtual env), but libffi was not pulled in as a dependency so I had to install it manually.
I did a quick lookup on the corresponding packages for Fedora/OpenSuse, but I'm not quite sure about the right packages for MacOS/FreeBSD/Windows.
Maybe it's not needed at all?
> doc(installation): add libffi-dev dependency

- docs/global.rst.inc
- docs/installation.rst
borg 1.2.x used to bundle some source code for lz4, zstd and xxhash, but borg 1.4.x got rid of that - all that is meanwhile available as a library in all OSes we support.
also, the python package pkgconfig does not need to be "preinstalled" anymore, because our pyproject.toml cares for that. otoh, the cli tool pkg-config must be preinstalled so that libs and headers can be found automagically.
Also be a bit more clear about the FUSE stuff.
> docs: update install docs, nothing bundled anymore! fixes #8342.

- src/borg/archiver.py
We don't want to accept very small quota limits < 10M, but 0 (quota disabled) is acceptable.
> config: fix acceptance of storage_quota 0, fixes #8499

- src/borg/archiver.py
Sole purpose of this is to simplify scripting.
> compact: support --dry-run (do nothing), fixes #8300

- src/borg/archiver.py
Doesn't mean that 10M is very helpful in out of space conditions, but avoids wrong unit assumptions as in #6066.
> config: reject additional_free_space < 10M, fixes #6066

- src/borg/helpers/yes.py
if retry is True, it will just retry to get a valid answer. if retry is False, it will return the default.
the code can be tested by entering "error" (without the quotes).
> yes: deal with UnicodeDecodeError in input(), fixes #6984

- docs/global.rst.inc
- docs/installation.rst
the python package pkgconfig does not need to be "preinstalled" anymore, because our pyproject.toml cares for that. otoh, the cli tool pkg-config must be preinstalled so that libs and headers can be found automagically.
Also be a bit more clear about the FUSE stuff.
> docs: update install docs, fixes #8342.

- docs/usage/serve.rst
see https://github.com/borgbackup/borg/issues/8318
As a short summary of issue 8318:
openssh executes the user's configured shell with the whole command (either remote-command or forced-command) as a single argument like so: `"$SHELL" -c "$COMMAND"`.
This entails a larger attack surface, when a complex and feature-rich shell is configured for the user.
Because in the example configuration of a push backup server a complex and feature-rich shell is not needed, recommending the usage of a simple shell like /bin/sh will reduce the opportunity of yet-undiscovered security vulnerabilities to arise in the future.
> docs: borg serve: recommend using a simple shell (closes #3818)

- docs/internals/data-structures.rst
/Users/tw/w/borg/docs/internals/data-structures.rst:971: WARNING: Lexing literal_block
'
[cache]
version = 1
repository = 3c4...e59
manifest = 10e...21c
timestamp = 2017-06-01T21:31:39.699514
key_type = 2
previous_location = /path/to/repo
[integrity]
manifest = 10e...21c
files = {"algorithm": "XXH64", "digests": {"HashHeader": "eab...39e3", "final": "e2a...b24"}} '
as "ini" resulted in an error at token: '}'.
Retrying in relaxed mode. [misc.highlighting_failure]
Note: this part of the docs didn't change for a long time, so I guess the sudden warning comes from a change in sphinx' lexers.
Main problem is that rc != 0 will abort our CI pipeline.
> work around sudden failure of sphinx ini lexer

- src/borg/crypto/key.py
- src/borg/helpers/passphrase.py
- src/borg/testsuite/helpers_test.py
This pull request improves the handling of passphrases and adds comprehensive debug information. The main changes include:
- Displaying hex bytes for passphrases in all cases, including ASCII and non-ASCII characters.
- Adding an option to display the hex bytes when the password is used and found incorrect.
- Showing which environment variables were used during passphrase operations.
- Preventing sensitive passphrase information from being logged unintentionally by directing it to sys.stderr.
- Adding tests to verify:
- Handling of incorrect passphrases.
- Passphrase verification logic.
- Debug information display for passphrases.
> Enhance passphrase handling (Fixes #8496)

- docs/usage/general/date-time.rst.inc
- src/borg/archiver/prune_cmd.py
- src/borg/helpers/parseformat.py
- src/borg/helpers/time.py
- src/borg/testsuite/archiver/check_cmd_test.py
- src/borg/testsuite/archiver/repo_list_cmd_test.py
- src/borg/testsuite/helpers_test.py
https://github.com/borgbackup/borg/issues/8624
> Allow timespan to be specified with common time units

- src/borg/archiver/help_cmd.py
Clarify docs: 
Within a shell, command line options with special characters require adjustments, such as quotation marks.  
https://github.com/borgbackup/borg/issues/8578
> docs: clarify requirements when using command line options with special characters within a shell

- src/borg/archiver.py
docs: clarify requirements when using command line options with special characters within a shell #8628 
backport to the 1.4-maint branch 
as suggested in https://github.com/borgbackup/borg/pull/8628#issuecomment-2585895924
> docs: clarify requirements when using command line options with special characters within a shell #8628

- docs/deployment/automated-local.rst
fixes #8639
The priority of 40 for the udev rules as stated in to documentation applies the rule too early on some systems, which prevents the rule from matching. This commit changes the priority to 80.
> docs: fix udev rule priority in automated-local.rst

- docs/deployment/automated-local.rst
fixes #8641
In the example, setting SYSTEMD_WANTS instead of appending may prevent other autostart services attached by earlier udev rules from launching. This commit changes = to += to fix this behavior.
> docs: modify docs for automated backup to append to SYSTEMD_WANTS

- src/borg/archiver.py
> quickfix :  borg exits when assertions are disabled with Python optimizations

- src/borg/testsuite/helpers.py
> Fix hourly prune test failure due to non-full-hour timezone 

- src/borg/testsuite/helpers.py
Reverts #8686 (to maintain consistency with master branch test code )
> Revert "Fix hourly prune test failure due to non-full-hour timezone "

- docs/development.rst
Note that there are exceptions to this rule. Assuming this is correct and what is meant by the branching paragraph below.
> Clearer language

- docs/deployment/image-backup.rst
- docs/deployment/pull-backup.rst
- docs/usage/create.rst
- docs/usage/create.rst.inc
- docs/usage/general/environment.rst.inc
- docs/usage/general/logging.rst.inc
- src/borg/archiver/create_cmd.py
- src/borg/archiver/help_cmd.py
REPO::ARCHIVE formatting has been replaced in the documentation with --repo 
Only python files have been updated 
All modified commands have been tested
This should replaces the initial PR
> docs: borg commands updated with --repo option

- src/borg/archiver/help_cmd.py
- src/borg/compress.pyx
- src/borg/testsuite/compress_test.py
- src/borg/testsuite/xattr_test.py
Added Padmé padding as a new obfuscation option with SPEC=250.
> implement padme chunk size obfuscation (SPEC 250), fixes #8705

- src/borg/testsuite/xattr_test.py
Reference: #8718 
com.apple.provenance is an extended attribute that macOS assigns to files downloaded from the internet, mainly to track their origin.
> tests: ignore 'com.apple.provenance' xattr (macOS specific)

- docs/conf.py
- requirements.d/docs.txt
- tox.ini
The html generated uses jquery ($(...)),
but sphinx does not include it anymore since a while.
also: correctly add guzzle_sphinx_theme to extensions.
> docs: add sphinxcontrib.jquery

- docs/internals/frontends.rst
- src/borg/archive.py
- src/borg/archiver/check_cmd.py
- src/borg/archiver/compact_cmd.py
- src/borg/archiver/mount_cmds.py
- src/borg/archiver/recreate_cmd.py
- src/borg/archiver/tar_cmds.py
- src/borg/archiver/transfer_cmd.py
- src/borg/fuse.py
- src/borg/helpers/fs.py
- src/borg/helpers/misc.py
- src/borg/helpers/parseformat.py
- src/borg/legacyrepository.py
- src/borg/remote.py
- src/borg/repository.py
- src/borg/testsuite/archiver/check_cmd_test.py
- src/borg/testsuite/archiver/extract_cmd_test.py
- src/borg/testsuite/archiver/mount_cmds_test.py
- src/borg/testsuite/archiver/transfer_cmd_test.py
- src/borg/upgrade.py
Well, it's not totally removed, some code in `Item`, `archive` and `borg transfer --from-borg1` needs to stay in place, so that we can pick the CORRECT chunks list that is in `.chunks_healthy` for all-zero-replacement-chunk-patched items when transferring archives from borg1 to borg2 repos.
FUSE fs read: IOError or all-zero result (depending on allow_damaged_files option)
extract, diff, ...: fetch_many() will on-the-fly create all-zero replacement chunks (of correct size, if size is known) if it gets a None result (not: bytes chunk cdata) from repo.get() because a chunk is missing. it will also emit an ERROR about the missing chunk, with chunk id and size.
Also fixes: #8562
> Item: remove .chunks_healthy, fixes #8559

- src/borg/archive.py
- src/borg/platform/__init__.py
- src/borg/platform/darwin.pyx
- src/borg/testsuite/archiver/extract_cmd_test.py
> fix: retrieve `birthtime` in nanosecond precision via system call

- src/borg/crypto/keymanager.py
I just experimented a bit with printable key ex/import and noticed the error message checking the number of slashes in the `id`  line being wrong.
This also applies to at least the 1.4 and 1.2 versions
> Fix paper key import error message

- src/borg/archive.py
- src/borg/platform/__init__.py
- src/borg/platform/darwin.pyx
- src/borg/testsuite/archiver.py
> fix: retrieve `birthtime` in nanosecond precision via system call (1.4-maint)

- src/borg/platform/freebsd.pyx
This only happened when:
- using borg extract --numeric-ids
- processing NFS4 ACLs
It didn't affect POSIX ACL processing.
This is rather old code, so it looks like nobody used that code or the bug was not reported.
The bug was discovered by PyCharm's "Junie" AI. \o/
> freebsd: fix nfs4 acl processing, fixes #8756 (master)

- src/borg/platform/freebsd.pyx
This only happened when:
- using borg extract --numeric-ids
- processing NFS4 ACLs
It didn't affect POSIX ACL processing.
This is rather old code, so it looks like nobody used that code or the bug was not reported.
The bug was discovered by PyCharm's "Junie" AI. \o/
> freebsd: fix nfs4 acl processing, fixes #8756 (1.4-maint)

- src/borg/platform/freebsd.pyx
This only happened when:
- using borg extract --numeric-ids
- processing NFS4 ACLs
It didn't affect POSIX ACL processing.
This is rather old code, so it looks like nobody used that code or the bug was not reported.
The bug was discovered by PyCharm's "Junie" AI. \o/
> freebsd: fix nfs4 acl processing, fixes #8756 (1.2-maint)

- src/borg/compress.pyx
It's easy enough to verify exhaustively for any plausible chunker params that Padmé always produces at most a 12% overhead. Checking that again at runtime is pointless.
A self-contained script to confirm the above for all data lengths between 2 bytes and 100 megabytes (takes about 2 minutes to run):
```python
#%%
import math
from math import floor
def log(x):                           # we use log in base 2
return math.log(x, 2)
def padme(L):
"""
Pads the length L using the Padmé algorithm
Args:
L (int): unpadded object length
Returns:
int: the padded object length
"""
E = floor(log(L))
S = floor(log(E))+1
lastBits = E-S                    # we want those bits to be 0
bitMask = (2 ** lastBits - 1)     # create a bitmask of 1's
return (L + bitMask) & ~bitMask   # round up if necessary
def …
```
> Remove unnecessary check that Padmé overhead is at most 12%

- .github/workflows/ci.yml
- pyproject.toml
- tox.ini
Python 3.9 will run out of upstream support 2025-10 anyway. So we can also drop it right now and have faster CI testing.
Fixes #8723.
> remove support for / testing on Python 3.9

- src/borg/archiver/compact_cmd.py
The issue was due to using an outdated chunkindex that had entries for chunks that did not exist in the repo anymore.
> compact: always write updated chunkindex to repo, fixes #8791

- src/borg/cache.py
guess we better invalidate the old repo-side cache of the chunk index and rebuild it with the current borg and borghash code.
> chunks cache: invalidate old chunk index cache

- pyproject.toml
- requirements.d/development.txt
This is a workaround for #8828.
> require Cython < 3.1 for now

- .github/workflows/codeql-analysis.yml
this just updates the pin to the latest version
should i investigate enabling something like renovate or dependabot for those as followup?
> update codeql to v3 due to deprecation

- pyproject.toml
- requirements.d/development.txt
- src/borg/item.pyx
uses the correct invocations for __set_name__ as cython now supports it
the code for manually calling is left in place to ensure support for older cython where needed
closes #8828
> fix #6858: correct the signature of __set_name__ as cython 3.1 added support

- src/borg/archive.py
- src/borg/cache.py
- src/borg/manifest.py
- src/borg/repository.py
- src/borg/testsuite/archiver/restricted_permissions_test.py
Also: moved name length check to Archive.__init__, so it doesn't read all other archives main metadata when creating a new archive.
In write-only mode, the files cache can't be built from the repo from the latest archive of same series, we are not allowed to read that!
fixes #1165 
fixes #4071
> repository: add write-only permissions mode, fixes #1165

- src/borg/testsuite/archiver/diff_cmd_test.py
If we touch too quickly after file creation, it would not noticably update the timestamp.
> tests: fix diff cmd test on macOS HFS+, fixes #8860

- src/borg/testsuite/archiver/extract_cmd_test.py
- src/borg/testsuite/archiver/list_cmd_test.py
- src/borg/testsuite/archiver/repo_space_cmd_test.py
- src/borg/testsuite/archiver/transfer_cmd_test.py
- src/borg/testsuite/legacyrepository_test.py
- src/borg/testsuite/repository_test.py
pytest likes to keep the temp files from the test for a while (the last 3 test runs).
if we want to be able to use a ramdisk of reasonable size for the temp files, we need to be a bit more careful about how much data we create there.
after this PR, we need ~500MB space per test run, so a ramdisk of 1.5-2.0GB works.
> Tests: save temp space

- tox.ini
- consistent indentation with spaces
- use pytest, not py.test
- consistent empty lines between sections
- remove empty changedir lines
> minor tox.ini improvements

- .github/workflows/ci.yml
The file:// repo URLs are still broken on windows.
> CI: disable windows for now

- src/borg/testsuite/chunker_slow.py
we want to get rid of legacy stuff(*) one day and sha256 is as good for this purpose (and might be even hw accelerated).
(*) considered legacy due to the way it gives the key to the blake2b function (just padding and prepending it to the data, instead of using the key parameter, see #8867 ).
> test_chunkpoints_unchanged: do not use blake2b_256

- docs/usage/serve.rst
see #8318
so long as it can be assumed that the user has configured a POSIX compliant login shell, using a simple command [1] looks cleaner, as no ``export`` or ``;`` are used.
[1] Section "2.9.1 Simple Commands" in volume "Shell & Utilities" of POSIX.1-2024
> docs: borg-serve: simplify example of env in authorized_keys

- src/borg/testsuite/repository.py
This is a backport of eaca4a6c4a07bffb412588c8bf602fb29553dc16 (#8913) to 1.4-maint. I added this patch to Fedora to get borg 1.4 building for the upcoming Fedora 43 which will use Python 3.14.
> tests: fix ZeroDivisionError msg test for py314 (for borg 1.4)

- src/borg/helpers/parseformat.py
it used to be 100, but that caused test failures on some systems with deep build directories.
> to_key_filename: raise length limit to 120, fixes #8966

- src/borg/archive.py
- src/borg/archiver/create_cmd.py
control how borg detects whether a file has changed while it was backed up, valid modes are ctime, mtime or disabled.
ctime is the safest mode and the default.
mtime can be useful if ctime does not work correctly for some reason (e.g. OneDrive files change their ctime without the user changing the file).
disabled (= disabling change detection) is not recommended as it could lead to inconsistent backups. Only use if you know what you are doing.
> create --files-changed=MODE option

- src/borg/archive.py
- src/borg/archiver/tar_cmds.py
- src/borg/constants.py
- src/borg/testsuite/archiver/tar_cmds_test.py
Implemented handling of POSIX access and default ACLs in tar files. New keys, `SCHILY.acl.access` and `SCHILY.acl.default`, are used to store these ACLs in the tar PAX headers.
See #2521.
> export-tar/import-tar: support for POSIX ACLs

- pyproject.toml
- requirements.d/development.txt
Also: raise setuptools version requirement appropriately.
In case the setuptools requirement turns out to be a problem when packaging borg for some OS distribution and an older setuptools must be used, just do a reverse patch when packaging borg - there should be no problem as long as you use some older setuptools.
> pyproject.toml: SPDX expression for license, add license-files, see #8771

- docs/installation.rst
Note that Arch Linux usually has no separate `-dev` packages, but ships development headers with the normal package.
> Add Arch Linux to installing from source docs

- docs/installation.rst
Backport of #9018
By the way: There are GitHub actions (e.g. [here](https://github.com/marketplace/actions/backporting) and [here](https://github.com/marketplace/actions/backport-action)) that can automate this. Didn't use any myself before, so I can't really make a recommendation, but I've seen them in other projects, so might be worth a look :+1:
> Add Arch Linux to installing from source docs (v1.4 backport)

- docs/installation.rst
Backport of #9015
[465937f](https://github.com/borgbackup/borg/pull/9020/commits/465937f5a3f8ea45ff65f00f23fe361011af1887) unifies the paragraph order with `master` (it caused a merge conflict).
> Update install docs to include `SETUPTOOLS_SCM_PRETEND_VERSION` (v1.4 backport)

- src/borg/testsuite/archiver/diff_cmd_test.py
This is a follow-up to #8344. After mulling it over, I generally think `borg` is doing the right thing when diffing with hard links, as the changes reported [match POSIX semantics](https://pubs.opengroup.org/onlinepubs/9799919799/functions/unlink.html) for unlinking:
```
Upon successful completion, unlink() shall mark for update the last data modification and last file status change timestamps of the parent directory. Also, if the file's link count is not 0, the last file status change timestamp of the file shall be marked for update.
```
An `mtime` and `ctime` change with no content modification or permission change between the same file in two repos is probably a reasonable hint that a hard link was broken. Similarly, a `ctime` change with no permission change is probably a reasonable …
> Add tests for diff output of archives with hard links.
