docs/quickstart.rst, docs/update_usage.sh, docs/usage.rst
Thanks to @lfam (attic PR #277 )!
Note: As I already had refactored a lot of these pathes you changed, it was easier
to just cherry pick the hunks with the other changes and apply them manually.
=> Documentation for 'attic serve'

borg/repository.py
=> Loggedio exceptions

borg/archive.py, borg/cache.py, borg/fuse.py, borg/remote.py, borg/xattr.py
also: remove some unused temp dir. code
=> use borg-tmp as prefix for temporary files / directories

borg/archiver.py, borg/key.py, borg/remote.py, borg/repository.py, borg/testsuite/archive.py, docs/usage.rst
see usage.rst change for a description and why this is needed
=> repo key mode (and deprecate passphrase mode), fixes #85

requirements.d/development.txt, tox.ini
Added requirements file enabling:
pip install -r requirements.d/development.txt
=> add development.txt and modify tox.ini

borg/archiver.py, borg/remote.py, borg/testsuite/archiver.py
also: add test, automate YES confirmation for testing
=> repo delete: add destroy to allowed rpc methods, fixes issue #114

borg/archive.py
see the comments on the individual commits
=> Fix restore xattrs

borg/cache.py
added a check that compares the size of the new chunk with the stored size of the
already existing chunk in storage that has the same id_hash value.
raise an exception if there is a size mismatch.
this could happen if:
- the stored size is somehow incorrect (corruption or software bug)
- we found a hash collision for the id_hash (for sha256, this is very unlikely)
=> detect inconsistency / corruption / hash collision, closes #170

borg/archiver.py, borg/helpers.py, borg/testsuite/helpers.py, docs/usage.rst
sets the default repository to use, e.g. like:
export BORG_REPO=/mnt/backup/repo
borg init
borg create ::archive
borg list
borg mount :: /mnt
fusermount -u /mnt
borg delete ::archive
=> BORG_REPO env var support

borg/archive.py, borg/archiver.py, borg/testsuite/archiver.py
also: fix verbose mode display of stdin backup
=> implement borg create --dry-run, attic issue #267

borg/cache.py
seems to work for me. some brave soul could give it additional testing.
=> Faster cache sync

borg/archiver.py, borg/helpers.py, borg/support/__init__.py, borg/support/argparse.py, setup.py
also: remove previois attempt to fix this, installing pypi argparse into virtualenv does not work.
=> add a argparse.py (from py 3.2.6) that is not broken

borg/cache.py
for @anarcat as a temporary solution.
=> temporary hack to avoid using lots of disk space for chunks.archive.d

borg/cache.py
- issue #234: handle exception when config file is empty is really not a borg cache config
- there was a unused %s in the Exception string
- error msg was wrong when version check failed - this IS a borg cache, but not of expected version
=> fix multiple issues with the cache config version check, fixes #234

borg/archiver.py
it deletes just the local cache for the given repository, not the repo itself.
=> implement borg delete --cache-only repo, attic #123

borg/helpers.py, borg/testsuite/helpers.py
=> respect XDG_CACHE_HOME

README.rst, docs/Makefile, docs/development.rst, setup.py
this should fix the API build on the main website.
=> API doc fixes

docs/installation.rst, docs/quickstart.rst, docs/usage.rst, setup.py
The commit messages are hopefully descriptive enough.
=> docs: Some small fixes

borg/archiver.py
it should also probably be --one-file-system for coherence with du(1)
=> add -x flag, common to GNU utilities

AUTHORS, docs/global.rst.inc, docs/installation.rst
Same as #278 before the carnage
=> docs: restructure installation.rst + add OS X install instructions

docs/usage.rst, setup.py
it's not pretty yet, but better than nothing.
=> include the help offered by borg help <topic> in the usage docs, fixes #293

borg/testsuite/archiver.py, borg/testsuite/benchmark.py
=> Test binary, fixes #215

borg/helpers.py, borg/platform_darwin.pyx, borg/platform_freebsd.pyx, borg/platform_linux.pyx, borg/testsuite/platform.py
Just for review, one TODO left.
=> Non ascii acls

borg/archive.py
code copied & adapted from Archive.load()
=> implement cmdline metadata value decoding

README.rst, docs/changes.rst, docs/conf.py, docs/development.rst, docs/faq.rst, docs/quickstart.rst
i noticed a few warnings in the docs generation this morning... this takes care of most of them (apart from #312), but also does title cleanups in the changelog and the FAQ.
=> various docs fixes

docs/usage.rst
this should finally close #289
=> explicitely commit to the units standard

Vagrantfile, borg/archiver.py, borg/helpers.py, borg/testsuite/archiver.py
this is especially useful for automated log analysis (e.g. borgweb).
if there is a definite rc 0 or rc 1 in the log, the tool can easily find out whether backup succeeded or not and indicate green or red status.
=> Final status

borg/archive.py, borg/fuse.py, borg/helpers.py, borg/testsuite/archiver.py
restore: mtime and atime
FUSE: support ctime and atime additionally to mtime
=> backup atime and ctime additionally to mtime, fixes #317

borg/archiver.py, borg/cache.py, borg/helpers.py, borg/testsuite/__init__.py, borg/testsuite/archiver.py, borg/testsuite/helpers.py
yes() is quite a functionality monster, but at least this avoids duplications and having different bugs/features at different places.
=> Cleanup confirmations

borg/testsuite/archiver.py
See there for 3 corrupt repos produced by the new test:
https://paste.thinkmo.de/bqyrsTv6#borg-corrupt-repos.tgz
=> add a test to find disk-full issues, #327

borg/archiver.py, borg/testsuite/archiver.py
lists only archives with names starting with the given prefix.
=> borg list --prefix=thishostname- REPO, fixes #205

README.rst
Fixed the link to "The Borg collective".
=> Fix for link to "The Borg collective"

borg/repository.py
I'ld appreciate if somebody could do some codereview on this.
=> Fix borg check crashing on some repos, issue #364

docs/installation.rst
i had a few annoyances with the install page for a while. a lot of those were fixed thanks to #295 but i found that headings were still a bit off...
=> Install docs nitpick

borg/archiver.py, borg/logger.py, borg/testsuite/logger.py, docs/usage.rst
=> configure logging via env var

borg/archiver.py, borg/cache.py, borg/locking.py, borg/remote.py, borg/repository.py, borg/testsuite/locking.py, borg/testsuite/repository.py
also: simplify exceptions / exception handling
=> Max lock wait, fixes #210

borg/archiver.py, borg/cache.py, borg/locking.py, borg/remote.py, borg/repository.py, borg/testsuite/archiver.py, borg/testsuite/locking.py, borg/testsuite/repository.py
this is based on the other 2 locking PRs.
=> Break lock

borg/archiver.py, borg/testsuite/archiver.py
this adds unit tests for, and fixes #436.
=> fix --no-progress

borg/archiver.py
=> fix format of umask in help pages

borg/archive.py, borg/archiver.py, borg/testsuite/archiver.py, docs/changes.rst, docs/development.rst, docs/usage.rst
plus some more stuff, read the commit comments / changes.
=> refactor --verbose and silence borg by default (supercedes PR 444)

Vagrantfile
filed some bug reports, added some notes to Vagrantfile.
=> results of some llfuse experiments

borg/archiver.py, borg/testsuite/archiver.py, borg/testsuite/benchmark.py, docs/usage.rst
added: BORG_DELETE_I_KNOW_WHAT_I_AM_DOING for the check in "borg delete"
=> fix badly named environment variable, fixes #503

borg/archive.py, borg/helpers.py
- so it shows progress while it backups a bigger file
- so it announces the filename earlier
also: move rate limiting code to show_progress()
=> output progress indication from inner loop, fixes #500

docs/deployment.rst, docs/index.rst
This is just a example how a borg backup server could be configured and used.
As this is just and idea, I keep it is open for discussion. Other people will also need to solve the centralised/offsite backup server problem.
=> Docs: deployment example

borg/archiver.py, borg/testsuite/archiver.py
like --stats enables statistics output, --list enables the file/dirs list output.
=> add --list option for borg create

docs/installation.rst
=> Move to my ppa and add Trusty/Vivid packages

borg/archiver.py, borg/cache.py
also: make check in Lock.close more precise, check for "is not None".
note: a lot of blocks were just indented to be under the "with" statement,
in one case a block had to be moved into a function.
=> implement and use context manager for Cache, partial fix for #285

docs/installation.rst
=> add netbsd install instructions

README.rst
Could also link to LICENSE file in repo.
=> Fix dead link to license

borg/archiver.py
=> Reformat commands list

docs/quickstart.rst
=> Fix for Issue #604

borg/archiver.py, borg/helpers.py, borg/testsuite/helpers.py, borg/upgrader.py, docs/internals.rst, docs/quickstart.rst, docs/usage.rst
~/.borg/keys -> ~/.config/borg/keys
=> use xdg base dir for keys

docs/deployment.rst, docs/quickstart.rst, docs/usage.rst
I have updated and verified the examples in docs/, as described in issue #644
=> Updated and verified examples in docs/

borg/fuse.py, setup.py
did some testing (automated as well as manual). seems to work for <0.42 as well as for 0.42.1.
Thanks to Nikratio for helping with the needed changes.
=> Fuse compat fixes

borg/archive.py
(not tested by me for the #657 scenario, but at least all our unit tests, including the atime test, worked)
=> fix _open_rb noatime handling, fixes #657

README.rst, docs/faq.rst, docs/installation.rst, docs/quickstart.rst, docs/usage.rst
use the travis status image as png as svg does not show an image in firefox.
=> update and improve docs

docs/faq.rst
Example to faq documentation how bandwidth limiting can be done with pipeviewer.
see #661 for discussion
=> Faq: how to limit bandwidth

README.rst
Update README.rst to new changelog location in docs/changes.rst
=> Update README.rst to new changelog location

borg/fuse.py
The file stats are packed with 'int_to_bigint' before storing in the archive. Extracting from the archive correctly unpacks these, but not on fuse. This results in a byte string being passed to llfuse if any of the atime/mtime/ctime are unexpectedly large.
=> Unpack file stats before passing to fuse

borg/_chunker.c
- Postulated as fix in https://github.com/borgbackup/borg/issues/748#issuecomment-196485116
- @seambeat confirmed fix in https://github.com/borgbackup/borg/issues/748#issuecomment-196586665
=> fix to silently skipping EIO and the like #748

borg/archiver.py
It logs at INFO level, so add -v to see actually see it.
=> implement --show-version: shows/logs the borg version, fixes #725

AUTHORS, borg/archiver.py, borg/helpers.py, docs/installation.rst, docs/usage.rst, docs/usage/mount.rst.inc, setup.py
- add archiver.main_mount()
- update usage of mount subcommand
- run build_usage
- add entry point in setup.py
=> provide wrapper for borg mount, fixes #743

docs/installation.rst
docs/installation.rst: Add Gentoo package to list of distribution packages.
=> Installation: Mention Gentoo package

docs/installation.rst
* docs/installation.rst: Add GNU Guix package to list of distribution packages.
=> Installation: Mention GNU Guix package.

Vagrantfile
this box has still some issues, but hopefully they will be fixed soon.
=> vagrant: add ubuntu/xenial 64bit

borg/repository.py, borg/testsuite/repository.py, docs/usage.rst
=> Feature append only

borg/_chunker.c, borg/testsuite/chunker.py
This is a slightly modified version of the fix, it now uses a loop instead.
=> Chunker: fix wrong EOF assumption, check for return type

borg/fuse.py
Copy/paste error, shouldn't have used the _ns variables here.
=> fix incorrect _ns variables

docs/installation.rst
seems like no one else noticed this... see #105
=> add jessie-backports to supported platforms

borg/archive.py
Fixes #826 
Let's see if it works this time ;D
=> ArchiveChecker: move "orphaned objects check skipped" to INFO log level

borg/testsuite/archiver.py
=> Test suite: Reset exit code of persistent archiver

borg/archiver.py, borg/testsuite/archiver.py
=> init: clean up partial repo if passphrase input is aborted

docs/installation.rst
=> add link to OpenBSD port and OpenSUSE

docs/installation.rst
=> added package link to docs for fedora

borg/archiver.py
bug: c[1] was not the size, but the byte at index 1 of the id bytestring!
=> compare_content: fix wrong added/removed file size

borg/_chunker.c
Despite what the man page says, Linux does not discard the initial
partial page only. The ending page would be truncated no matter if
it is partial or not.
Page-align the fadvise size to take care of this.
Also while we are at it, roll back initial fadvise offset to the
previous page boundary to actually throw away that page as we
no longer need it having read the second part now and the first
time in the previous call.
This patch has a noticeable impact in my Linux testing when the file
is on the rotating media. The total test runtime decreased by a bit
over 10%, but since over half of that time was actually cpu time,
the actual iowait time decreased around 20%.
=> Workround a bug in Linux fadvise FADV_DONTNEED, fixes #907

borg/archiver.py, borg/helpers.py, borg/testsuite/archiver.py
=> create: Visit files in inode order

docs/installation.rst
https://svnweb.freebsd.org/ports?view=revision&revision=413469
It is not yet in "pkg"; that will automatically happen in the next quarterly period.
=> docs/installation: Add FreeBSD Ports tree

.gitignore, borg/_hashindex.c, borg/archive.py, borg/archiver.py, borg/helpers.py, borg/remote.py, borg/testsuite/__init__.py, buildwin32.py, docs/development.rst, docs/installation.rst, setup.py
Initial native windows support.
Original PR #935 
Tested and working commands:
- init
- create, With all compressions
- list
- info
- delete
- diff
- extract
=> Add Windows support

.gitignore, borg/_hashindex.c, borg/archive.py, borg/archiver.py, borg/helpers.py, borg/remote.py, borg/testsuite/__init__.py, buildwin32.py, docs/development.rst, docs/installation.rst, setup.py
Rebased and squashed all the commits from  #947 as requested @ThomasWaldmann
=> Add initial native Windows support.

borg/key.py, borg/testsuite/key.py, docs/usage.rst
collapsed all commits into 1, rebased on current master, added tests.
thanks to @legrostdg for implementing this.
=> add BORG_KEY_FILE

borg/archiver.py, borg/testsuite/archiver.py
=> borg prune: ignore checkpoints, fixes #997

borg/archiver.py, borg/testsuite/archiver.py, docs/usage.rst, docs/usage/with-lock.rst.inc
Guess this is ready now for merging. After review, I'll collapse the commits.
manual usage:
```
(borg-env)tw@tux:~/w/borg$ borg with-lock repo ls -d repo/lock.exclusive
repo/lock.exclusive
```
=> borg with-lock REPO CMD ARGS

.travis/install.sh, borg/archiver.py, borg/helpers.py, borg/testsuite/archiver.py
also: add some tests that invoke all supported compression algorithms
=> compression heuristics based on lz4, fixes #1006

borg/archiver.py, docs/usage.rst
docs: rephrased, more useful examples
=> borg create help: document format tags, fixes #894

borg/archiver.py, borg/testsuite/archiver.py
prune: only keep latest checkpoint if not superceded by a successful backup
=> prune: kill all checkpoints except the latest

docs/faq.rst, docs/usage.rst
also: fix append-only mode description - "multiple machines" and "central server" are over-specific and not required for this scenario.
=> FAQ: add entries about compromised machines and other troubles, fixes #1011

setup.py
thanks to @weakish for finding this!
=> seek /opt/pkg (pkgsrc OS X) for openssl and lz4

borg/key.py
=> When probing key files, do binary reads

borg/archive.py, borg/archiver.py, borg/helpers.py, borg/platform.py, borg/platform_base.py, borg/platform_darwin.pyx, borg/platform_freebsd.pyx, borg/platform_linux.pyx, borg/platform_posix.pyx, borg/testsuite/archive.py, borg/testsuite/helpers.py, borg/testsuite/platform.py, setup.py
on posix platforms, this is a small wrapper around wcswidth(3).
on non-supported platforms, it just uses len(s), as before.
=> add swidth call, fixes #1051

borg/_chunker.c
currently, ALL linux kernels are affected.
=> clarify comment about linux kernel versions, fixes #1024

borg/platform_linux.pyx, borg/testsuite/archiver.py
=> Fix crash regression for UDS introduced in 805f631

borg/archiver.py, borg/platform_linux.pyx, borg/testsuite/archiver.py
=> List files excluded via UF_NODUMP

borg/repository.py, borg/testsuite/repository.py
- Track free space information for each ~~un-compact~~ fragmented segment
- Don't compact large segments with little free space
- Don't read deleted data when compacting
Consider this a WIP, it has not been tested since the last rebase. I will also probably split this into two+ commits for clarity. (Splitting it from #985 and moving it around as a single commit was simply easier)
TODO: 
Terms:
- Compact segment: contiguous, no holes / deleted data
- Fragmented|Sparse segment: has deleted data in it
- Segment compaction: making fragmented segments compact
- ... and how the heck can we give "deleted data" a better name?! (*terminated data* does not count)
- "superseded entry"?
- PUT x, PUT x: first PUT superseded by newer PUT
- PUT x, DELETE x: first PUT is superseded by DELETE
- (assuming …
=> Repository: compact v2

borg/remote.py
Here's a fix for #940, where borg will busy-wait writing to a high latency remote repository.  This happens because it does not remove stdin_fd from w_fds when it reaches its self-imposed maximum of 100 inflight requests.  I will add reproduction steps to the #940 shortly.
=> RemoteRepository: Fix busy wait in call_many, fixes #940

.gitignore, borg/archive.py, borg/archiver.py, borg/constants.py, borg/platform.py, borg/platform_windows.pyx, setup.py
Get and set DACL and owner for files and folders.
Setting owner seems to require administrator.
=> Windows file permissions

src/borg/archive.py, src/borg/archiver.py, src/borg/cache.py, src/borg/constants.py, src/borg/fuse.py, src/borg/helpers.py, src/borg/item.py, src/borg/platform/darwin.pyx, src/borg/platform/freebsd.pyx, src/borg/platform/linux.pyx, src/borg/testsuite/archive.py, src/borg/testsuite/archiver.py, src/borg/testsuite/item.py, src/borg/testsuite/platform.py
=> refactor to use Item class

borg/archive.py, borg/archiver.py, borg/helpers.py
can happen for not correctly initialized repos or corrupted repos.
here: borg list failing more pretty
=> better error handling for missing repo manifest, fixes #1043

borg/archive.py, borg/testsuite/archive.py
when trying to resync and skip invalid data, borg tries to qualify a byte sequence as
valid-looking msgpacked item metadata dict (or not) before even invoking msgpack's unpack.
besides previously hard to understand code, there were 2 issues:
- a missing check for map16 - this type is what msgpack uses if the dict has more than
15 items (could happen in future, not for 1.0.x).
- missing checks for str8/16/32 - str16 is what msgpack uses if the bytestring has more than 31 bytes
(borg does not have that long key names, thus this wasn't causing any harm)
this misqualification (valid data considered invalid) could lead to a wrong resync, skipping valid items.
added more comments and tests.
=> fix resync and msgpacked item qualifier, fixes #1135

docs/resources.rst
atticmatic wrapper script has been renamed to borgmatic!
=> Update resources.rst to rename atticmatic to borgmatic

borg/testsuite/archiver.py
found out that xfs is doing stuff behind the scenes: it is pre-allocating 16MB
to prevent fragmentation (in my case, value depends on misc factors).
fixed the test so it just checks that the extracted sparse file uses less (not
necessary much less) space than a non-sparse file would use.
another problem showed up when i tried to verify the holes in the sparse file
via SEEK_HOLE, SEEK_DATA:
after the few bytes of real data in the file, there was another 16MB
preallocated space.
So I ended up checking just the hole at the start of the file.
tested on: ext4, xfs, zfs, btrfs
=> fix sparse file test, fixes #1170

borg/archiver.py, borg/helpers.py, borg/testsuite/archiver.py, borg/testsuite/helpers.py, docs/quickstart.rst, docs/usage.rst
also fixes some other issues, see the commit comments.
=> add placeholder support at missing places, add missing help

borg/repository.py
For 1.0.4 or later.
d513cfd was already fixed in master with the v2 code.
=> Repository: Read v2 hints files

borg/archive.py, borg/archiver.py, docs/usage.rst
please review if the semantics is now right.
=> fixes for --read-special mode

borg/archive.py, borg/archiver.py
=> WIP: Forced archive delete

README.rst, docs/support.rst
less items in frontpage link list
add IRC chat link
minor other changes
=> update frontpage / support docs

borg/repository.py, docs/internals.rst, docs/quickstart.rst
This automates what one would have to do otherwise (find last committed segment, delete everything after that)
Fixes #1262 #1114
=> Repository: cleanup on ENOSPC

borg/fuse.py
=> Fix FUSE crash in xattr code on Linux

src/borg/archive.py, src/borg/archiver.py
Also small merge fixup.
Fixes #1222
=> wrap get_flags with backup_io

src/borg/helpers.py, src/borg/repository.py, src/borg/testsuite/repository.py
obsoleted by 5b453856ec23 and e96905c6b
Fixes #1269
=> Remove InternalOSError

src/borg/platform/base.py
=> sync_dir: silence fsync() failing with EINVAL

borg/archive.py
before 1.0.4/1.0.5 we had no means to tell if a file has been "repaired" with all-zero
chunks, but now we can see it if chunks_healthy key is present.
=> warn if a file with damaged chunks is extracted, fixes #1299

borg/archive.py, borg/archiver.py, borg/testsuite/archiver.py
also: improve logging for archive check
https://paste.thinkmo.de/MMXNxFUh#borg-healing.txt
=> heal items

borg/archiver.py, borg/fuse.py, borg/testsuite/__init__.py, borg/testsuite/archiver.py
=> fuse: EIO on damaged files unless told not to (-o allow_damaged_files)

borg/testsuite/archiver.py
removed the pointless platform check.
just first test the input file with the same checks we expect succeeding
on the extracted file. skip sparse archiving / extraction testing if the input
file checks fail - likely we have a problem with the OS or the FS then.
=> more compatible sparse file testing, fixes #1310

borg/xattr.py
Fixes error handling observed in #1314, root cause not known yet.
=> xattr: don't log before logging is set up

borg/xattr.py
Backport of #1188, to fix #1314
=> Correctly handle multiple LD_PRELOAD entries

borg/testsuite/archiver.py
=> test_atime: try to open with O_NOATIME to determine support

borg/archiver.py
=> Fix borg break-lock ignoring BORG_REPO env var

src/borg/archiver.py, src/borg/helpers.py
=> recreate: fix hogged signal handlers

Vagrantfile
A fix for absence of 'vagrant' user on ubuntu/xenial64  vm machine.
=> Fixed the issue of absense of vagrant user on xenial64

appveyor.yml, src/borg/archive.py, src/borg/helpers.py, src/borg/platform/windows.pyx, src/borg/testsuite/archiver.py, src/borg/testsuite/helpers.py, src/borg/testsuite/repository.py, src/borg/testsuite/shellpattern.py
Most of them is just marked as skipif on windows as the paths aren't valid windows paths.
Also got appveyor to run the tests without failing the build.
=> Windows: Fix lot of tests

Vagrantfile
-Fetch all that is needed for building borg.
-Build windows standalone exe.
-~~Todo: try to use inno setup automatically~~
-~~Make base box~~ Used one from atlas
It expires in 90 days. You can allways load a snapshot or download new.
=> vagrantfile for windows

borg/archiver.py
=> Use an OrderedDict for helptext, making the build reproducible

.gitignore
Seems like every time I make a PR I notice some other autogenerated files that aren't gitignored. At least I didn't commit them this time :smile:.
=> Ignore generated platform C files

src/borg/testsuite/archiver.py
Part of #1363 
Thanks to @enkore for the code: https://github.com/borgbackup/borg/issues/1363#issuecomment-234726334
=> Fixed noatime detection

src/borg/testsuite/platform.py
Fixes https://github.com/borgbackup/borg/pull/1365#issuecomment-234734212 as specified here: https://github.com/borgbackup/borg/pull/1365#discussion_r71976549
=> Catch a ValueError when checking if a user exists

borg/archiver.py, borg/helpers.py
Redo of #1375 for 1.0-maint
Fixes #1116
=> Ignore stdout/stderr broken pipe errors

docs/development.rst, docs/faq.rst, docs/installation.rst
=> Platform feature matrix

borg/archiver.py, borg/remote.py, borg/repository.py
=> Add --append-only to borg init (1.0-maint)

docs/changes.rst, docs/deployment.rst, src/borg/platform/posix.pyx
=> Remove trailing whitespace (master)

src/borg/archive.py, src/borg/repository.py
=> Fix some issues in --verify-data

borg/archiver.py, borg/fuse.py
Cherry-pick of bfb00df from master to 1.0-maint
Fixes #1398
=> borg mount: cache partially read data chunks

borg/fuse.py
also: refactor / deduplicate directory creation
=> FUSE: always create a root dir, fixes #1125

docs/usage.rst, src/borg/archiver.py
=> docs: remove borg list example, be more specific about compression heuristics

borg/archiver.py, borg/helpers.py, borg/remote.py
PR for #1392 against 1.0-maint branch
=> borgversion placeholder 1.0-maint

docs/faq.rst
Simplified https://github.com/borgbackup/borg/pull/1432 using an existing related question and following previous recommendations
=> Add backup using stable filesystem names recommendation

borg/archiver.py, borg/testsuite/archiver.py
dump all objects stored in the repository (decrypted and decompressed)
=> borg debug-dump-repo-objs

borg/cache.py
thanks much to e477 for diagnosing this and finding the right fix.
=> fix unintended file cache eviction, fixes #1430

borg/testsuite/archiver.py
NOATIME support needed checking and the flagfile was UF_NODUMP and thus not there in the backup archive.
Note: i have just duplicated the has_noatime function instead of refactoring it to be global,
to avoid merge conflicts in case we cherry-pick the test improvements from master.
=> fix fuse tests on OS X, fixes #1433

src/borg/archive.py
doesn't merge conflict with #1420
=> minor recreate refactor

borg/compress.pyx, borg/helpers.py, borg/testsuite/helpers.py, borg/testsuite/xattr.py, borg/xattr.py
=> lz4 reusing helpers.Buffer

src/borg/archive.py, src/borg/archiver.py, src/borg/compress.pyx, src/borg/helpers.py, src/borg/key.py, src/borg/testsuite/archiver.py, src/borg/testsuite/key.py
=> recreate goals for 1.1rc1

src/borg/archiver.py, src/borg/testsuite/archiver.py
=> Fix borg-list --list-format

borg/cache.py
=> Cache: release lock if cache is invalid

borg/locking.py, borg/repository.py, borg/testsuite/locking.py
=> Fix cosmetics + file leftover for "not a valid borg repository"

docs/usage.rst
Fixes #900 
This method requires sshfs which mounts the remote filesystem over ssh.
=> added doc for "pull" type backup over sshfs

src/borg/repository.py, src/borg/testsuite/archiver.py
Simple, segment based, so depending on max_segment_size more or less granular.
Fixes #1115
=> Repository: add compact_segments progress

docs/borg_theme/css/borg.css
Addjust border color, same as https://github.com/borgbackup/borg/pull/1528 but for https://github.com/borgbackup/borg/tree/1.0-maint
=> Addjust border color

Vagrantfile
hopefully there will be a release of pyinstaller that has these changes.
=> Vagrant: pyinstaller: use pre-built linux bootloaders, fixes #1506

borg/testsuite/archiver.py
fakeroot >= 1.20.2 "supports" xattrs, but this support somehow leads to the fuse tests not seeing
the xattrs in fuse, because the file visible in the fuse mount was not created via fakeroot.
=> work around fuse xattr test issue with recent fakeroot

docs/changes.rst, docs/usage.rst, src/borg/archiver.py, src/borg/fuse.py, src/borg/testsuite/archiver.py
for mixed repos, --prefix would make sense here.
also, not mounting all archives, but just last N would also make sense.
we'll do that after the first/last PR is merged.
=> FUSE versions view

src/borg/fuse.py
some small optimizations and refactorings
=> Improve fuse

README.rst, borg/archiver.py, docs/faq.rst, docs/usage.rst
=> misc docs improvements

borg/archiver.py
If the connections hangs up, the borg server needs to clean
up, especially unlock the repository, so a later try will
work again.
=> Handle SIGHUP for proper unlock on lost connection, fixes #1593

Vagrantfile
7.9 is not available any more.
=> update wheezy vagrant box to 7.11

README.rst, Vagrantfile, docs/development.rst, docs/faq.rst, docs/usage.rst, src/borg/archive.py, src/borg/archiver.py, src/borg/hashindex.pyx, src/borg/testsuite/archiver.py, src/borg/testsuite/hashindex.py
Also: add SIGHUP handling for borg recreate.
=> Merge 1.0 maint

src/borg/archive.py, src/borg/testsuite/archiver.py
so they can be "repaired" immediately and maybe healed later.
=> borg check: delete chunks with integrity errors, fixes #1575

borg/archiver.py, borg/helpers.py
Note: to ease the first review, I did not indent the blocks into the context manager scopes, but just left a TODO there.
=> Improve signal handling

src/borg/archiver.py
=> Re-Indent borg help helptexts, again.

src/borg/archive.py, src/borg/helpers.py, src/borg/testsuite/helpers.py
=> Fix broken --progress for double-cell paths

src/borg/archive.py, src/borg/helpers.py, src/borg/testsuite/helpers.py
=> borg check --verify-data tuning

docs/usage.rst
=> add more specific warning about write-access debug commands

docs/faq.rst
=> Clarify FAQ regarding backup of virtual machines

borg/archive.py, borg/archiver.py, borg/cache.py, borg/helpers.py, borg/key.py, borg/keymanager.py, borg/repository.py, borg/testsuite/archiver.py, borg/upgrader.py
simplifies code and also porting and merging between 1.0 and 1.1/master.
=> backport bin_to_hex and use it

Vagrantfile
debian711* is 404.
fixes #1686.
=> vagrant: update image name of boxcutter debian7 boxes

src/borg/repository.py
the old way had a bad O(N^2) runtime behaviour. for small segments and large objects, it didn't matter much (small N), but for the 500MB large segments and small objects, N^2 can be huge.
btw, the high cpu usage @enkore has seen can not come from crc checks - we do not have a header crc (unfortunately), we just have a header+data crc - and we can't use that if we just read the header and seek over the data.
@enkore can you please repeat your perf test?
Fixes #1610
=> Repository.scan(): avoid re-reading same repo object headers repeatedly

borg/key.py
this is a backport of bcdce91dfb2883c139011322a9e8086059fbe5c2 improvements on the exception msgs.
fixes #1571.
=> borg.key: include chunk id in exception msgs

.travis.yml
nightly points to python 3.7 now.
=> travis: use 3.6-dev

borg/testsuite/benchmark.py, borg/testsuite/helpers.py, borg/testsuite/upgrader.py, conftest.py
fix related to #1714 (same issue, for cache dir).
also: refactor some env var setting to use monkeypatch (if pytest based).
=> Clean env in 1.0

borg/helpers.py, borg/remote.py, borg/testsuite/helpers.py
Fixes #1655 
TODO:
- remove "WIP" from commit comment
Please help reviewing this so that we have no unexpected effects in stable release update.
=> implement /./relpath hack

Vagrantfile
self-made basic openbsd box includes pre-installed rsync as vagrant is unable to install rsync.
as the self-made box now has enough space on /, remove workaround for low space.
delete line from tox.ini with sed so it does not try to install llfuse (which is broken on openbsd).
=> vagrant / openbsd: use own box, fixes #1695

borg/archiver.py
=> fix debug get-obj / delete-obj crash if object not found and remote repo 

borg/archiver.py
=> add borg debug refcount-obj ID subcommand

src/borg/archive.py, src/borg/archiver.py, src/borg/fuse.py, src/borg/helpers.py, src/borg/testsuite/archiver.py
also:
- use consider_part_files when dealing with multiple archives / whole repo mount
- refactor / dedup code
=> borg mount --first / --last / --sort / --prefix, fixes #1542

src/borg/archive.py, src/borg/archiver.py, src/borg/testsuite/archiver.py
=> borg check --first / --last / --sort / --prefix, fixes #1663

src/borg/_hashindex.c
Performance improvement extracted from the Robin Hood hashing work #1429 
When inserting a new key `hashindex_set` is basically a lookup for existing key to update followed by a lookup for the address to insert at. By having `hashindex_lookup` provide info about where the lookup stopped we can avoid re-examining the same buckets for an appropriate location to insert at.
=> shortcut hashindex_set by having hashindex_lookup hint about address

Vagrantfile
=> vagrant: do not try to install llfuse on centos6

docs/conf.py
otherwise code examples overflow
=> restore normal size

src/borg/cache.py, src/borg/constants.py, src/borg/repository.py, src/borg/upgrader.py
=> Clarify cache/repository README file

src/borg/repository.py, src/borg/testsuite/repository.py
=> borg init: fix free space check crashing if disk is full

borg/xattr.py
=> at xattr module import time, loggers are not initialized yet

borg/cache.py
bug:
if no files were added/modified, _newest_mtime stayed at its initial 0 value.
when saving the files cache, this killed all age 0 entries.
Now using None as initial value, so we can spot that circumstance.
The 2 ** 63 - 1 value is just so it is MAX_INT on a 64bit platform, for better performance.
It can be easily increased when y2262 is coming.
=> fix determination of newest mtime, fixes #1860

src/borg/cache.py
=> Add begin_txn progress message

docs/internals.rst, docs/usage.rst
not sure how to write these formulas better, right now they maybe look worse than what's usually happening in practice.
=> add more details about resource usage

src/borg/archiver.py, src/borg/cache.py
=> Add cache.sync progress display

borg/key.py
note: the duplication is intentional, i did not want to spend addtl. time for the usual case, rather have addtl. code for the exception case.
=> fix TypeError in errorhandler, fixes #1903

src/borg/key.py, src/borg/testsuite/key.py
=> blake2b key modes: use B2B as MAC; longer keys.

src/borg/archiver.py
Issue #1914 fixed.
Ran all the tests, everything seems allright.
Probably the same problem in 1.0-maint.
=> Fixed borg info

conftest.py
@ronny thanks, your hint helped. :)
=> get back pytest's pretty assertion failures, fixes #1938

docs/changes.rst, docs/faq.rst
Accidentally destroyed PR #1944
=> Update 1.1 changes

README.rst, docs/installation.rst
also add note about remote repos being broken on cygwin.
=> document windows 10 linux subsystem install

borg/archiver.py
This works around http://bugs.python.org/issue9351
Since Debian and Ubuntu ship 3.4.2 and 3.4.0 respectively.
=> Fix subsubparsers for Python <3.4.3

src/borg/remote.py
Seems to work now both with ssh://.../~user/ and someone@host:~user (and also someone@host:/~user/) and with plain ~.
Fixes #1759
=> Fix processing of remote ~/ and ~user/ paths

borg/archive.py, borg/archiver.py, borg/crypto.pyx, borg/helpers.py, borg/key.py, borg/testsuite/archiver.py, borg/testsuite/crypto.py, borg/testsuite/helpers.py, borg/testsuite/key.py, docs/changes.rst, docs/quickstart.rst, docs/usage.rst, docs/usage/upgrade.rst.inc
=> Release 1.0.9

src/borg/archiver.py
=> Add prune progress display

README.rst
Information about security contact seems to have moved.
=> Update link to security contact

borg/archiver.py
to make figuring stuff like #1982 out easier.
=> dump trace on signal

LICENSE, docs/conf.py, src/borg/shellpattern.py
The previous year had alot of bugs.
<sup>Also, I'm sorry if this may seem childish but can you please tell me what to do to close issue #1721. I really want the bounty before the Steam winter sale ends. k thx bye.</sup>
=> Happy new year!

borg/xattr.py, docs/changes.rst
=> fix xattrs on ObjectiveFS

.travis.yml, Vagrantfile, setup.py, tox.ini
=> tox / travis: also test on Python 3.6

.travis/install.sh
somehow just the path of the osxfuse package changed. also added py 3.6.
=> travis: fix OS X based testing

docs/changes.rst
=> update CHANGES (1.0-maint)

borg/remote.py
this problem was found on cygwin/windows due to its small pipe buffer size of 64kiB.
due to that, bigger (like >64kiB) writes are always only partially done and os.write() returns
the amount of data that was actually sent. the code previously did not use that return value
and assumed that always all is sent, which led to a loss of the remainder of transmission data
and usually some "unexpected RPC data format" error on the client side.
On all other operating systems (Linux, *BSD, OS X), this error was not seen.
=> borg serve: fix transmission data loss of pipe writes, fixes #1268

Vagrantfile
=> vagrant: fix openbsd repo, fixes #2042

setup.py
=> setup.py: add crc32.c to sdist

Vagrantfile
finally it was released! \o/
thanks to @htgoebel!
=> upgrade pyinstaller from 3.1.1+ to 3.2.1

Vagrantfile
also: tests / binaries with osxfuse 3.5.4
=> Binaries with py353

borg/helpers.py, borg/testsuite/helpers.py
this was like whack-a-mole: fix one regex -> another issue pops up.
review carefully.
=> fix bad parsing of wrong syntax

borg/archive.py, borg/fuse.py
Fixes #2092 
Does not fix #1297 (it's a different race but a race nonetheless)
=> Fix invalid hard links

docs/changes.rst
=> docs: add CVE numbers for issues fixed in 1.0.9

borg/archiver.py, borg/fuse.py
=> mount: umount on SIGINT/^C when in foreground

src/borg/_hashindex.c
hashindex_lookup would always hint at skipping whatever it's probe
length had been with no regard for tombstones it had encountered. This
meant new keys would not overwrite first tombstones, but would always
land on empty buckets. 
Ran the benchmarks I used for the Robin Hood hashing so you can 
compare the impact of this patch:
https://cdn.rawgit.com/rciorba/d8990a54be8b778bb3322ac40364de90/raw/90d05773cc377b061f400d3833166bbce4243ba1/results.html
That is a regression I introduced myself as part of: #1748
=> fix wrong skip_hint on hashindex_set when encountering tombstones

docs/changes.rst, src/borg/archive.py, src/borg/archiver.py, src/borg/helpers.py, src/borg/testsuite/archiver.py
Very small commit to make tagging accept folders as tags and allow things like
`--exclude-if-present .git`.
This is being discussed in #1999
=> change dir_is_tagged to use os.path.exists()

MANIFEST.in, Vagrantfile, docs/changes.rst, docs/usage/mount.rst.inc, src/borg/_hashindex.c, src/borg/archive.py, src/borg/archiver.py, src/borg/fuse.py, src/borg/helpers.py, src/borg/platform/__init__.py, src/borg/platform/base.py, src/borg/platform/linux.pyx, src/borg/repository.py, src/borg/testsuite/helpers.py
also: refactored posix_fadvise checks / calls into safe_fadvise calls to avoid code duplication.
=> Merge 1.0-maint

borg/helpers.py
Computer clocks are often not set very accurately set, but borg
assumes manifest timestamps are never going back in time.
Ensure that this is actually the case.
Commands to reproduce:
```
borg init -e repokey /tmp/borg-repo2
borg create /tmp/borg-repo2::test1 tox.ini
borg info /tmp/borg-repo2::test1
faketime -f "+1y" borg create /tmp/borg-repo2::test2 tox.ini
BORG_CACHE_DIR=/tmp/foo BORG_SECURITY_DIR=/tmp/bar borg create /tmp/borg-repo2::test3 tox.ini
borg info /tmp/borg-repo2::test1
```
=> Manifest: Make sure manifest timestamp is strictly monotonically increasing.

src/borg/archiver.py
Fixes #2158 
Have to review it myself. So just the structure / idea.
=> create: handle BackupOSError on a per-path level in one spot

docs/borg_theme/css/borg.css, setup.py, src/borg/archiver.py
=> fix build_xxx

src/borg/archiver.py, src/borg/key.py, src/borg/testsuite/archiver.py
Fixes #2165 and also showed some minor test issues (missing --encryption, handling of argparse errors "if not FORK_DEFAULT").
=> init: mandatory --encryption arg

src/borg/archive.py
see #2180 - the problem was we only checked for all chunks from the healthy list, but not for the already existing replacement chunks.
=> archive check: detect and fix missing replacement chunks, fixes #2180

src/borg/helpers.py, src/borg/testsuite/helpers.py
fixes #2186.
file:////servername/share/path (does not work without file:// - there would be some failures at other places)
=> Location: accept //servername/share/path

src/borg/archive.py, src/borg/archiver.py, src/borg/helpers.py, src/borg/logger.py
=> Add --log-json option for structured logging output

docs/faq.rst, src/borg/archiver.py
=> document snapshot usage #2178

docs/usage.rst, src/borg/archiver.py
=> Document relative path usage #1868

src/borg/testsuite/archiver.py
based on #2184, apply after #2184.
=> Test delete --force

src/borg/cache.py
backport to 1.0-maint as it is a small change, but huge performance/usability impact.
=> files cache: update inode number, fixes #2226

borg/cache.py
=> files cache: update inode number, backport fix for #2226

docs/usage_general.rst.inc, src/borg/archiver.py
(ported bebehei's 1.0-maint change to master)
(originally wanted to rebase the changesets, but that was more painful than just redoing them)
=> [docs] improve remote-path description

docs/internals/frontends.rst, scripts/errorlist.py, src/borg/archive.py, src/borg/archiver.py, src/borg/cache.py, src/borg/helpers.py, src/borg/logger.py, src/borg/remote.py, src/borg/repository.py, src/borg/testsuite/archiver.py
This should pretty much kill that area off.
Last area I see left is to handle yes()
=> JSON progress indicators

docs/quickstart.rst
(missing line after :: from #2235 made rST not recognize the code block; also aligned the indentation, but that was not the issue)
=> quickstart: fix rst issue

src/borg/_hashindex.c
if there are too many deleted buckets (tombstones), hashtable performance goes down the drain.
in the worst case of 0 empty buckets and lots of tombstones, this results in full table scans for
new / unknown keys.
thus we make sure we always have a good amount of empty buckets.
same as #2248, for master branch.
=> hashindex: rebuild hashtable if we have too little empty buckets, fixes #2246

src/borg/archiver.py, src/borg/helpers.py, src/borg/testsuite/archiver.py
=> Add return code functions

src/borg/archiver.py
This is to address issue #2268
=> docs:  improve --exclude-if-present and --keep-exclude-tags

docs/internals/frontends.rst, docs/usage_general.rst.inc, src/borg/archive.py, src/borg/helpers.py, src/borg/logger.py
Fixes #654 
Although some minor / not overly important bits and pieces are still missing, I'd have to make a survey to find them all. Thinking recreate might not do the stats or file list right (or does it?), perhaps adding a few more tests, and working a more general intro / summary into the docs and more [comprehensive] reference material.
Also, feedback if someone wants to make a test drive would be valuable, before we freeze this interface and define compatibility policies etc.
=> json: yes()

docs/usage.rst
cherry pick of #2270 to master
=> Address SSH batch mode in docs (fixes #2202) (#2270)

docs/internals/security.rst
Copied from #2266, fixes #2266
=> docs/security: counter tracking

docs/installation.rst
=> fix caskroom link, fixes #2299

src/borg/archive.py
=> Archive: allocate zeros when needed

src/borg/archive.py, src/borg/cache.py, src/borg/helpers.py, src/borg/testsuite/helpers.py
filesystem -> clamp -> archive (create)
=> clamp (nano)second values to unproblematic range, fixes #2304

src/borg/archiver.py, src/borg/helpers.py, src/borg/testsuite/helpers.py
=> support setting the pattern style default in patterns file

docs/faq.rst
Added a small note in the FAQ about backing up the root partition.
=> Added FAQ section about backing up root partition

setup.py, src/borg/constants.py, src/borg/item.py, src/borg/platform/windows.pyx
Retrieve effective permissions inherited from parent folders.  #1341 
Check for privileges to get/set SACL and backup/restore them.  #983
=> Improved handling of Windows permissions

src/borg/helpers.py
this is some refactoring / optimization intended to get applied before PR #2334:
- rather use function than decorator - less and less complex code, more flexible usage.
- only normalize once before doing all the matching.
=> optimize / simplify path normalization

src/borg/archive.py, src/borg/cache.py, src/borg/remote.py, src/borg/repository.py, src/borg/testsuite/archive.py, src/borg/testsuite/archiver.py
supercedes #2238, fixes #2225.
=> async exception processing

docs/changes.rst
=> update CHANGES (master / 1.1.0b4)

src/borg/archive.py
2 little refactors / fixes.
todo: check if fixes apply to 1.0-maint.
=> Refactor extract

.travis.yml, .travis/install.sh, requirements.d/development.txt
* add setuptools_scm to the development requirements
* print the own version at install time
* unshallow the repo and fetch all tags
=> enhance travis setuptools_scm situation

src/borg/archiver.py, src/borg/testsuite/archiver.py
=> serve: fix forced command lines containing BORG_ env vars

borg/archiver.py, borg/helpers.py, borg/testsuite/archiver.py
=> 1.0-maint backports

docs/changes.rst, docs/usage.rst, docs/usage_general.rst.inc, src/borg/cache.py, src/borg/helpers.py, src/borg/remote.py, src/borg/repository.py
=> BORG_HOSTNAME_IS_UNIQUE=yes by default.

docs/installation.rst, src/borg/archive.py, src/borg/archiver.py, src/borg/fuse.py, src/borg/helpers.py
see #2324.
maybe rather review the changesets than the overall change (displayed badly on github diff view).
=> Generic hardlinks

src/borg/repository.py
=> hardlink issue

src/borg/testsuite/hashindex.py
Insert a few keys, delete some of them, check we still have
the values we expect, check the deleted ones aren't there.
=> add extra test for the hashindex

borg/testsuite/archiver.py
(cherry picked from commit 2ad5f903fe0755e4141a9a676e31340c0dc6600b)
=> add test for borg delete --force

borg/archiver.py, borg/helpers.py, borg/testsuite/helpers.py
(cherry picked from commit 42371181fcd296dad404c6b6e92e3108fb1793c7)
=> support switching the pattern style default in patterns file

borg/archiver.py
(cherry picked from commit c7256abd84bf5a067f9941d9289e837f673977dc)
=> borg rename: expand placeholders, fixes #2386

docs/faq.rst, docs/installation.rst, docs/internals/data-structures.rst, docs/usage_general.rst.inc
=> docs fixes

borg/repository.py
(cherry picked from commit 697942cd01bd46adae6523c0338c7a6f00fe442a)
=> be more clear that this is a "beyond repair" case, fixes #2427

src/borg/testsuite/benchmark.py
=> fix invalid param issue in benchmarks

src/borg/helpers.py, src/borg/testsuite/archiver.py, src/borg/testsuite/helpers.py
=> embrace y2038 issue to support 32bit platforms

borg/helpers.py, borg/testsuite/archiver.py, borg/testsuite/helpers.py
(cherry picked from commit de76a6b8218bf0f20aa31e92ca92edab37483f34)
=> embrace y2038 issue to support 32bit platforms (1.0-maint)

src/borg/patterns.py
Fixes #2469 for now. Patterns still needs some more rework, see other issues.
=> fix --exclude and --exclude-from recursing into directories

docs/internals/frontends.rst, src/borg/archiver.py, src/borg/helpers.py, src/borg/testsuite/archiver.py
=> list: --json-lines for archive contents

docs/changes.rst, src/borg/cache.py, src/borg/crypto/key.py, src/borg/testsuite/archiver.py
=> consider repokey w/o passphrase == unencrypted

docs/changes.rst, docs/usage.rst, src/borg/remote.py
=> serve: ignore --append-only when creating a repository

src/borg/crypto/file_integrity.py, src/borg/testsuite/file_integrity.py
This is based on much earlier work from October 2016 by me, but is
overall simplified and changed terminology (from "signing" to
hashing and integrity checking).
See #1688 for the full history.
=> Implement IntegrityCheckedFile

borg/archiver.py, borg/helpers.py, borg/testsuite/archiver.py, borg/testsuite/helpers.py
Fixes #2463 
TODO: After merge, remove pending backport labels if any.
=> Remove patterns from 1.0-maint branch

docs/man_intro.rst, docs/usage.rst, setup.py, src/borg/archiver.py, src/borg/testsuite/archiver.py
=> Support common options on the main command

src/borg/remote.py
=> serve: fix incorrect type of exception_short for Errors

src/borg/archiver.py, src/borg/cache.py, src/borg/testsuite/archiver.py
Fixes #2487 
TODO: Check if some corner case(s) were overlooked. Some functions are now separated and can now be covered with additional tests (the reconanlinzlianoztion thing).
=> Verify most operations against securitymanager

src/borg/fuse.py, src/borg/testsuite/archiver.py, src/borg/xattr.py
=> fuse: fix crash if empty (None) xattr is read

src/borg/archiver.py
=> mount: check llfuse is installed before asking for passphrase

borg/archiver.py
This is fixed in 1.1.
Fixes #2542
=> note -v/--verbose requirement on affected options

docs/usage/help.rst.inc, src/borg/archiver.py
Fixes #2543 
Normally I wouldn't add this, but systemd really makes life hard here.
=> docs: add systemd warning regarding placeholders

src/borg/archiver.py
=> mount: do pre-mount checks before opening repository

docs/changes.rst, docs/faq.rst
unmerged branch (2.3.17)
Don't remember any more whether this was already discussed.
=> faq: I get an IntegrityError or similar - what now?

src/borg/helpers.py, src/borg/testsuite/helpers.py
also: Location: more informative exception when parsing fails
continuation of #2264, fixes #2256.
=> WIP ipv6 address support

README.rst, borg/archiver.py, borg/fuse.py, borg/helpers.py, borg/testsuite/archiver.py, borg/testsuite/helpers.py
- #2541
- #2549
- #2536
- #2551 
- #2555
=> Backports for 1.0.11

src/borg/repository.py, src/borg/testsuite/archiver.py
=> init: don't allow creating nested repositories

src/borg/helpers.py, src/borg/testsuite/helpers.py
=> Restrict key file names

README.rst
=> Add bountysource badge

docs/internals/data-structures.rst, src/borg/archiver.py, src/borg/remote.py, src/borg/testsuite/archiver.py, src/borg/testsuite/repository.py
=> serve: add --restrict-to-repository

docs/internals/data-structures.rst
Part of my series to realize #1101 (#1688 #2496 #2502 #2568 #2580 #2584)
=> docs: file integrity

.travis/run.sh, Vagrantfile, scripts/faked-debug.sh
Reverts borgbackup/borg#2478
See #2594
=> Revert "Start fakeroot faked in debug mode - fixes EISDIR issues"

src/borg/archive.py, src/borg/archiver.py
=> recreate: if single archive is not processed, exit 2

docs/faq.rst, docs/quickstart.rst
=> docs: don't suggest to leak BORG_PASSPHRASE

src/borg/helpers.py, src/borg/platform/base.py, src/borg/repository.py
Fixes #2557 
I'd just make similar changes to chunks.archive.d writeout, but that's still locked.
=> repository: truncate segments before unlinking

docs/changes.rst, docs/faq.rst
=> docs: faq: Can I use Borg on SMR hard drives?

src/borg/_hashindex.c
=> hashindex: Cython defines PY_SSIZE_T_CLEAN

src/borg/cache_sync/unpack_template.h
=> cache sync: move assert() behind declarations

docs/internals/data-structures.rst, docs/internals/security.rst
=> internals: rewrite manifest & feature flags

src/borg/archive.py, src/borg/archiver.py, src/borg/helpers.py, src/borg/testsuite/archiver.py
=> implement --glob-archives/-a

docs/borg_theme/css/borg.css, docs/deployment.rst, docs/deployment/automated-local.rst, docs/deployment/hosting-repositories.rst, docs/usage/general.rst
This is based on my gist from early 2016: https://gist.github.com/enkore/a977f21f6d94f3db4891
=> docs: deployment: Automated backups to a local hard drive

scripts/fuzz-cache-sync/main.c, src/borg/_hashindex.c, src/borg/cache_sync/unpack.h, src/borg/remote.py, src/borg/testsuite/remote.py
- https://github.com/borgbackup/borg/pull/2572#discussion_r121285579
- https://github.com/borgbackup/borg/pull/2572#discussion_r121283265
- https://github.com/borgbackup/borg/pull/2572#discussion_r121256431 (fun-fact: all code generated by Cython is wrapped in a #ifdef Py_PYTHON_H ;)
=> cache sync changes

Vagrantfile
See the comments, rsync has troubles and breaks "vagrant up".
After fixing it and starting the provisioning steps manually, tests work ok.
There is no specific platform support for OI yet, though.
Also, FUSE support on OI is too old for llfuse.
```
==> openindiana64: Rsyncing folder: /home/tw/w/borg/ => /vagrant/borg/borg
There was an error when attempting to rsync a synced folder.
Please inspect the error message below for more info.
Host path: /home/tw/w/borg/
Guest path: /vagrant/borg/borg
Command: "rsync" "--verbose" "--archive" "--delete" "-z" "--no-owner" "--no-group"
"-e" "ssh -p 2222 -o LogLevel=FATAL  -o ControlMaster=auto
-o ControlPath=/tmp/ssh.950 -o ControlPersist=10m
-o IdentitiesOnly=yes -o StrictHostKeyChecking=no
-o UserKnownHostsFile=/dev/null
-i …
```
=> vagrant: add OpenIndiana

src/borg/cache.py, src/borg/testsuite/archiver.py
=> cache sync: check Operation.READ compatibility with manifest

src/borg/archiver.py
=> document pattern denial of service

docs/borg_theme/css/borg.css, src/borg/archiver.py, src/borg/nanorst.py
=> init: note possible denial of service with "none" mode

src/borg/archiver.py
Doesn't seem warranted to me to have this.
=> remove short options for rarely used options / commands

Vagrantfile
==> stretch64:   py35: commands succeeded
=> vagrant: add Debian 9 "stretch" 64bit

src/borg/archiver.py
- action='store_true' implies default=False
- missing metavars added
- minor code formatting
=> argparse cleanup

.travis/install.sh
they removed it from the preinstalled sw stack.
=> travis: install fakeroot for Linux

borg/_chunker.c, borg/archive.py, borg/archiver.py, borg/chunker.pyx, borg/helpers.py, borg/testsuite/__init__.py, docs/installation.rst
fixes #2720 
@enkore can you do the bounty with the remaining backports (but not #2255 for now)?
=> even more backports

docs/usage/prune.rst
Fixes https://github.com/borgbackup/borg/issues/2735
I also moved it to the bottom as the main examples are more important and this is a large file.
Not tested practically (could not find an easy way to parse these files), I just hope the instructions were correct. :smile:
=> Include prune example in doc

Vagrantfile
=> Vagrantfile: Fix set-up of cygwin and it's sshd.

conftest.py, setup.py
todo: after fixing this, another issue with the attic tar not being found surfaced.
=> fix borg import issue, add comment, fixes #2718

borg/archiver.py, borg/helpers.py, borg/key.py, borg/remote.py, borg/repository.py, borg/testsuite/key.py, docs/faq.rst, docs/quickstart.rst, docs/usage.rst
=> Backports (6)

Vagrantfile
openbsd works now.
fixed memory issues.
the tests on stretch64 also worked.
=> Vagrant fixes and updates

src/borg/archiver.py, src/borg/crypto/keymanager.py, src/borg/helpers.py, src/borg/nanorst.py, src/borg/testsuite/helpers.py
=> key import: allow reading from stdin

docs/usage/info.rst
=> docs: info: update and add examples

docs/usage/mount.rst
=> docs: mount: add repository example

src/borg/archiver.py, src/borg/helpers.py
=> fix reversed archive ordering with --last

.editorconfig
just the usual stuff, can be extended later.
=> add a basic .editorconfig, fixes #2734

docs/usage/create.rst.inc, src/borg/archiver.py
See #2800 for explanation and discussion.
=> #2800 - Better explanation of the --ignore-inode option relevance

requirements.d/coala.txt
Put each package on a separate line.
Error was:
Invalid requirement: 'coala coala-bears'
=> Fix coala requirements

docs/installation.rst
=> Update source-install about doc dependencies

src/borg/archiver.py
=> Reference list of status chars in borg recreate --filter description

borg/helpers.py, borg/key.py, borg/keymanager.py, borg/testsuite/archiver.py, borg/testsuite/xattr.py, docs/installation.rst
First time doing backports, hopefully I did them right 🤞
Fixes #2799
=> Backports (7)

src/borg/fuse.py
This is already stored in the `ArchiveInfo` from the manifest so it can still lazy-load the archive itself.
=> Use archive creation time as mtime for FUSE mount (fixes #2834)

docs/usage/recreate.rst
=> docs: recreate: fix wrong "remove unwanted files" example

setup.py, src/borg/archive.py, src/borg/constants.py, src/borg/repository.py
https://lgtm.com/projects/g/borgbackup/borg/alerts/
just fixed the easy stuff. any ideas about the rest?
=> lgtm fixes

src/borg/archiver.py, src/borg/helpers.py, src/borg/platform/__init__.py, src/borg/platform/base.py, src/borg/platform/darwin.pyx, src/borg/platform/freebsd.pyx, src/borg/platform/linux.pyx, src/borg/platform/posix.pyx, src/borg/testsuite/__init__.py
=> umount: try fusermount, then try umount

src/borg/cache.py
=> cache: write_archive_index: truncate_and_unlink on error

docs/global.rst.inc, docs/installation.rst, setup.py, src/borg/_chunker.c
The GIL change actually was one of the last changes I made on the prototype, but it's rather straightforward, and with some GIL stuff already scattered across the code base I don't see a good reason to not just add it.
=> multithreading: add pyzmq dep, chunker GIL

src/borg/_item.c, src/borg/helpers.py, src/borg/item.pyx, src/borg/testsuite/item.py
Attached to Item() because that's the only expected usage for now.
=> multithreading: item.to_optr(), Item.from_optr()

.gitignore, .travis.yml, .travis/install.sh, MANIFEST.in, Vagrantfile, docs/changes.rst, docs/development.rst, docs/installation.rst, docs/usage_general.rst.inc, setup.py, src/borg/archiver.py, src/borg/helpers.py, src/borg/remote.py, tox.ini
fixes #2891 
also: drop testing on 3.4
=> increase Python minimum requirement to 3.5.0

src/borg/archive.py, src/borg/archiver.py
This momentarily bricks the stats display.
=> archive: create FilesystemObjectProcessors class

borg/_hashindex.c
=> replace modulo with if to check for wraparound in hashmap

Vagrantfile
=> backported vagrant-fixes for 1.0-maint

Vagrantfile
has python 3.6, openssl 1.1.
and most of the stuff we need is preinstalled on this box. \o/
=> vagrant: add archlinux VM

src/borg/archiver.py, src/borg/testsuite/archiver.py
See issue #2899 for a description of the problem.
=> Only compare contents when chunker params match (fixes #2899)

src/borg/helpers.py, src/borg/testsuite/archiver.py
a first step for #2376, see commit comments.
=> json: use isoformat

src/borg/helpers.py, src/borg/testsuite/archiver.py
=> json isoformat

docs/development.rst
* Fix a couple of grammar mistakes and improve wording.
* Use proper Git terminology for operations on patches.
* Unify capitalization of "GitHub".
* Add proper formatting to branch names.
=> development.rst: Miscellaneous improvements

src/borg/archiver.py
=> create: document exclusion through nodump

src/borg/archive.py, src/borg/archiver.py, src/borg/item.pyx, src/borg/testsuite/archiver.py
This is the first step for #2475. It dos not change any functionality, it just moves logic around and provides a way to get changes between two archives in a "programmatically reusable" form.
Do you usually squash merge or do I need to rebase instead of merging master?
=> Refactor diff functionality

docs/changes.rst, docs/internals/frontends.rst, src/borg/archive.py, src/borg/archiver.py, src/borg/helpers/parseformat.py, src/borg/helpers/time.py, src/borg/testsuite/archiver.py
=> Datetime formatting

docs/internals/data-structures.rst
=> docs/internals: note segment size limitation

src/borg/archive.py
(cherry picked from commit 8a299ae24ced26dbb53517e594634ea676779bc3)
=> borg create --timestamp: set start time, fixes #2957

src/borg/crypto/keymanager.py
=> keymanager: don't depend on optional readline module

borg/keymanager.py
=> 1.0 backport #2980 keymanager: don't depend on optional readline module

src/borg/crypto/keymanager.py
=> 1.1 backport #2980 keymanager: don't depend on optional readline module

src/borg/repository.py
(cherry picked from commit 9fc4d00bf6b8cae85246bff508e490498279e737)
=> recover_segment: use mmap(), fixes #2982

Vagrantfile
- deduplicated .bash_profile creation
- now we always have XDISTN=... and LANG=... (not just for pyenv)
- username is just given where needed ("ubuntu" vs "vagrant")
- override for cygwin not needed as init is not global any more
also: fixes #2977 
this is maintained in 1.1, port to master later.
=> vagrant: clean up shell profile init, user name

Vagrantfile
- deduplicated .bash_profile creation
- now we always have XDISTN=... and LANG=... (not just for pyenv)
- username is just given where needed ("ubuntu" vs "vagrant")
- override for cygwin not needed as init is not global any more
=> vagrant: clean up shell profile init, user name (master)

src/borg/repository.py, src/borg/testsuite/repository.py
even an empty trailing file was enough to blow it up.
guess this fixes #2982.
There are 2 hard problems in computer science: cache invalidation, naming things, and off-by-1 errors.
=> FD cache invalidation

docs/faq.rst
=> Improve macos faq entry (1.1-maint)

src/borg/archive.py, src/borg/constants.py, src/borg/helpers/manifest.py, src/borg/helpers/parseformat.py, src/borg/helpers/time.py, src/borg/repository.py, src/borg/testsuite/archiver.py
=> fix .isoformat() issues

README.rst
(cherry picked from commit 7c9561afa2260383b47dc03e2645ae661c495736)
=> show/link new screencasts in README, fixes #2936

docs/internals/frontends.rst
(cherry picked from commit 133e847f8ee42a2bf6da3f4b6a14d98a27c01be8)
=> document utf-8 locale requirement for json mode, #2273 (#3009)

src/borg/archiver.py, src/borg/testsuite/archiver.py
=> delete: support naming multiple archives

src/borg/remote.py
the client_supports_log_v3 flag was added to differentiate 1.1.0 beta3
to beta5 clients (which did not support parsing json log format from
server) from >= 1.1.0beta6 clients (which support it).
for clients older than 1.1.0b3, no json log format will be negotiated
anyway.
by removing the client_supports_log_v3 flag support, we drop support for
clients using 1.1.0beta3..5.
thus, a client is now expected to either support old log format (like
borg 1.0.x) or new json format (like borg 1.1.0 >= beta6).
client     server comment
===========================================
any        0.29+  uses $LOG plain remote log format
any        1.0.x  uses $LOG plain remote log format
1.0.x      1.1.0  uses $LOG plain remote log format
1.1.0b1/b2 1.1.0  (uses $LOG plain remote log format)
1.1.0b3-b5 …
=> remove client_supports_log_v3 flag (1.1-maint)

src/borg/archiver.py, src/borg/crypto/key.py, src/borg/helpers/fs.py, src/borg/helpers/process.py, src/borg/remote.py, src/borg/xattr.py
=> fix subprocess environments

src/borg/helpers.py
(cherry picked from commit b5069770b7d4eb454cd429a0e4e7b2347994add0)
=> fix LDLP restoration for subprocesses, fixes #3077

docs/faq.rst
(cherry picked from commit fe0843733767432d8af40423fd207231f4805ce1)
=> faq: we do not implement futile attempts of ETA / progress displays

setup.py
(cherry picked from commit bf3f8e567283f43f297670554d158588df38bf78)
=> implement simple "issue" role for manpage generation, fixes #3075

src/borg/archiver.py, src/borg/crypto/key.py
=> init: fix wrong encryption choices in command line parser

Vagrantfile
(cherry picked from commit c995797640c86c976c26e85529a917ad091a9939)
=> vagrant: use self-made FreeBSD 10.3 box, fixes #3022

src/borg/logger.py
(cherry picked from commit afba813706e3f0db2688086fd553b40c770f4136)
=> logging with fileConfig: set json attr on "borg" logger, fixes #3114

src/borg/archive.py
(cherry picked from commit 9d3daebd5fa6a7929fc3a1e556a2b7931c97b354)
=> recreate: don't crash on attic archives w/o time_end, fixes #3109

README.rst
(cherry picked from commit c8441b5b3da4413e63c9b856b2816a6758dae2f3)
=> readme: -e is required in borg 1.1

.travis/install.sh
(cherry picked from commit 6049a07b74b55856d5be999bac4b4d49a5317d35)
=> don't brew update, hopefully fixes #2532

src/borg/platform/linux.pyx
opening a device file for a non-existing device can be very slow.
also: lstat -> stat(..., follow_symlinks=False) like everywhere else.
=> bsdflags support: skip blk/chr/lnk file type, fixes #3130

src/borg/platform/linux.pyx
opening a device file for a non-existing device can be very slow.
symlinks will make the open() call fail as it is using O_NOFOLLOW.
also: lstat -> stat(..., follow_symlinks=False) like everywhere else.
(cherry picked from commit a6ee4e9aedd2eb124c3a486f12131215661f77e1)
=> bsdflags support: do not open BLK/CHR/LNK files, fixes #3130

src/borg/archive.py, src/borg/archiver.py, src/borg/testsuite/archiver.py
see #3160 
could be also `--no-bsdflags`, but we already have `--noatime` (similar for names in the code).
=> implement --nobsdflags and --exclude-nodump

docs/faq.rst, src/borg/archive.py
=> remove hardlinked symlink warning, update docs

borg/archive.py, docs/faq.rst
(cherry picked from commit d535c6a25d7c43723979e0924fca4f6babb01377)
=> update docs about hardlinked symlinks limitation

src/borg/archiver.py
(cherry picked from commit 93de42bb256833b441a58afab674b911baf1573b)
=> show excluded dir with "x" for tagged dirs / caches, fixes #3189

src/borg/helpers/fs.py, src/borg/testsuite/helpers.py
Fixes #3083
For more details info, see PR: https://github.com/borgbackup/borg/pull/3206
=> add BORG_CONFIG_DIR env (#3083)

setup.cfg
(cherry picked from commit bb1c7a7f57ddbd3e046524a0de8c161ba807a1fd)
=> flake8: add some ignores

scripts/shell_completions/bash/borg, scripts/shell_completions/fish/borg.fish
As mentioned in #2862, this PR adds bash and fish shell completions. Zsh will be added separately by @mrkmg. This PR fixes #3086.
=> Add bash and fish shell auto-completions.

scripts/shell_completions/zsh/_borg
Added directly from upstream source at https://github.com/mrkmg/borgbackup-zsh-completion
Per request in Issue #2862
=> Added ZSH Shell Completion Script

scripts/shell_completions/zsh/_borg
Added ZSH Shell Completion from upstream. https://github.com/mrkmg/borgbackup-zsh-completion
=> Added ZSH Shell Completion

src/borg/archive.py, src/borg/archiver.py
master branch only, not present in 1.1-maint.
=> borg create: fix stats

src/borg/archive.py
(cherry picked from commit 2c6f9634bc970eefd46fdc66642b8998f3c3fa1b)
=> set bsdflags last (include immutable flag), fixes #3263

src/borg/archiver.py
always use sys.stdout.write as in main() we have replaced that with a
handler that deals with BrokenPipe exceptions.
all the encode / decode dance was just to remove surrogates,
but that is not needed as format_item already does remove surrogates.
(cherry picked from commit 726ef118bc3a86b1d2c91101149a3fc1149dec27)
=> borg list: fix broken pipe handling, fixes #3245

docs/development.rst
(cherry picked from commit 818b61935bba264cb6f3be8beb54c49ccbc67e92)
=> update release checklist about security fixes

src/borg/archiver.py
=> Clarify encryption of key for borg key export (1.1-maint)

docs/usage/borgfs.rst, setup.py, src/borg/archiver.py, src/borg/testsuite/archiver.py
=> Generate usage & man page for borgfs (1.1-maint)

docs/faq.rst
This has been asked twice already this year:
https://mail.python.org/pipermail/borgbackup/2017q3/000796.html
https://mail.python.org/pipermail/borgbackup/2017q4/000891.html
... and I was asked again privately today, so this qualifies as FAQ to
me.
=> add FAQ about removing old files and policies

docs/faq.rst
=> add FAQ about removing old files and policies (1.1 backport)

docs/faq.rst
Fixes #3328, also streamlined some of the language for the rest of the paragraph
=> Mention break-lock in checkpointing FAQ entry

docs/faq.rst
=> Mention break-lock in checkpointing FAQ entry (1.1 backport)

src/borg/cache.py
=> Highlight that information is obtained from security dir (1.1 backport)

docs/faq.rst
=> Document sshfs rename workaround (1.0 backport)

src/borg/helpers/parseformat.py
=> Clarify key aliases for borg list --format

src/borg/helpers.py
=> Clarify key aliases for borg list --format (1.1 backport)

src/borg/archiver.py, src/borg/fuse.py, src/borg/testsuite/archiver.py
=> borg mount options (1.1 backport)

MANIFEST.in, setup.py
=> clean up and simplify packaging

src/borg/archiver.py
(cherry picked from commit 520a6a2ef116331964a57e857d32ff217b14fb5d)
=> docs: point out tuning options for borg create, fixes #3239

docs/faq.rst, docs/quickstart.rst, docs/usage.rst, docs/usage/config.rst, docs/usage/notes.rst, setup.cfg, src/borg/archiver.py, src/borg/helpers.py, src/borg/testsuite/archiver.py
=> Add borg config command (1.1 backport)

docs/faq.rst, docs/usage/create.rst, docs/usage/mount.rst, docs/usage/notes.rst, docs/usage/tar.rst, docs/usage_general.rst.inc, src/borg/archiver.py
=> docs fixes / updates (1.1-maint)

setup.py, src/borg/archiver.py
=> Fix build_man issues (1.1 backport)

README.rst, docs/development.rst
Fixed support links as seen in a comment here: https://github.com/borgbackup/borg/pull/3361
=> fixed support links

docs/support.rst
otherwise people ONLY reading the docs (and not coming from the
homepage) will miss these options.
Thank you for contributing code to Borg, your help is appreciated!
Please, before you submit a pull request, make sure it complies with the
guidelines given in our documentation:
https://borgbackup.readthedocs.io/en/latest/development.html#contributions
**Please remove all above text before submitting your pull request.**
=> link to the homepage for support/service (1.1-maint)

docs/development.rst, docs/support.rst
(cherry picked from commit c7994b598b696d7fb585c21e5a8c489af30a37e4)
=> docs: fix broken links

requirements.d/development.txt
https://github.com/pytest-dev/pytest/issues/2957
=> exclude broken pytest 3.3.0 release

.travis.yml, .travis/install.sh, Vagrantfile, borg/archiver.py
I went through the 1.1 changesets, looking for stuff that should get backported.
=> 1.0 Backports

borg/archive.py, docs/usage.rst
=> 1.0 Backports 2

src/borg/archive.py, src/borg/testsuite/archiver.py
=> fix for borg check --repair malfunction, #3444 (master)

src/borg/archiver.py, src/borg/cache.py
(cherry picked from commit 8f772437f21c0a979e5eb922ead9efcb952d878c)
see #3450
=> also delete security dir when deleting a repo, fixes #3427 (1.1)

docs/3rd_party/lz4/LICENSE, docs/installation.rst, docs/usage_general.rst.inc, setup.py, setup_lz4.py, src/borg/algorithms/lz4-libselect.h, src/borg/algorithms/lz4/lib/lz4.c, src/borg/algorithms/lz4/lib/lz4.h, src/borg/compress.pyx, src/borg/helpers.py
=> compress ext building (lz4 part, 1.1)

scripts/shell_completions/bash/borg, scripts/shell_completions/fish/borg.fish
=> zstd compression method added to fish/bash completions

docs/usage_general.rst.inc, src/borg/helpers/fs.py, src/borg/remote.py, src/borg/testsuite/helpers.py, src/borg/upgrader.py
also: sorted env var docs by level
=> added BORG_BASE_DIR, s/get_home_dir/get_base_dir/g, docs, fixes #3338

src/borg/archiver.py
(cherry picked from commit d1cdc1451ff9f4bad73de4d60f2f75051133489e)
=> borg init: use given --storage-quota for local repo, fixes #3470 (1.1)

src/borg/repository.py
init: more clear exception messages for borg create, fixes #3465
also: refactor
(cherry picked from commit 9f400633f29e8de1a5e447e30ae143a525cfee1c)
=> Correct some confusing error messages from `borg init` (#3485)

LICENSE, docs/conf.py, src/borg/shellpattern.py
=> Celebrate the new year with 1.1-maint

LICENSE, docs/conf.py
=> Celebrate the new year with 1.0-maint

scripts/shell_completions/zsh/_borg
Since @mrkmg seems to be absent nowadays, I took the courage and updated zsh completions to be on-par with bash/fish completions.
=> Updated zsh completions for borg 1.1.4

src/borg/helpers.py
=> remove unneeded sort from scandir_generic()

src/borg/helpers/fs.py
This is the PR against master that fixes #3545.
=> ignore exceptions in scandir_inorder() caused by an implicit stat() (PR against master)

docs/internals/frontends.rst, src/borg/archive.py
=> add chunker_params to archive info (at least to json output) (PR against master)

docs/internals/frontends.rst, src/borg/archive.py
=> add chunker_params to borg archive info (--json)

scripts/shell_completions/bash/borg, scripts/shell_completions/fish/borg.fish
... in bash and fish completions. Zsh was already using spaces.
=> Using spaces instead of tabs for indentation

.travis/install.sh
This reverts commit e4828078bbc6ceba34a1b923b4c50a31b10b4f08.
=> Revert "travis osx: run brew update first, fixes #3527"

README.rst, docs/usage_general.rst.inc
This pull request fixes issues https://github.com/borgbackup/borg/issues/3502 and https://github.com/borgbackup/borg/issues/3554 .
This also closes https://github.com/borgbackup/borg/issues/3426 if the two commits are sufficient. If not, I can add some more documentation for these two issues.
=> A few documentation fixes for Documentation issue 19

docs/quickstart.rst
=> [Docs] Update quickstart.rst to fix typo

setup.py, setup_b2.py, setup_lz4.py, setup_zstd.py
This backports #3580 to 1.1-maint as requested in #3644.
=> Backport 3580 to 1.1-maint

scripts/shell_completions/bash/borg, scripts/shell_completions/fish/borg.fish
This backports #3596 and #3600 to 1.1-maint as requested in #3645.
I've combined these two into one PR as the second one was a clean-up commit dependant on the first.
=> Backport 3596 and 3600 to 1.1-maint

setup.py
This backports #3580 to 1.0-maint as requested in #3647.
I've did a cherry-pick to apply the parts that could be done & applied the change to the lz4 check in setup.py instead of setup_lz4.py.
=> Backport #3580 to 1.0-maint

docs/support.rst
Short howto on using gpg to verify a signed binary release.
Fixes #3634
=> Add docs on how to verify a signed release

src/borg/archiver.py, src/borg/constants.py, src/borg/repository.py, src/borg/testsuite/archiver.py
only a few basic checks, it does not prevent all stupidities.
=> borg config: add some validation, fixes #3566

src/borg/archive.py
fixup for cb7887836aa1fb45912a10c298ab688b6dce06a9
=> fix borg recreate --progress (broken by previous commit)

docs/internals/security.rst
fixes #1040.
@textshell @enkore ^^^
=> security docs: add about combining compression and encryption

docs/quickstart.rst
I took a shot at this description as well, sorry for kind of stealing this one @bhaveshpoddar94!
=> Add quickstart introduction to repositories & archives (fixes #3620)

src/borg/crypto/key.py
=> improve getpass user experience (1.1 backport)

docs/internals/security.rst
@enkore @nadalle is this ok for a short doc about it? i didn't want to get too much into the details...
=> security: describe chunk size / proximity issue, see #331

docs/internals/security.rst
(cherry picked from commit 8ac272f35f9c3ee51bbe42c32616b54f05911233)
=> security: describe chunk size / proximity issue, see #3687

docs/quickstart.rst
(cherry picked from commit 09beb64f344c4b21f8a212f49ab6998ff4fbdc22)
=> Add quickstart introduction to repositories & archives (fixes #3620) 1.1-maint port

src/borg/archive.py
=> fix Archive's checkpoint_interval arg default (1.2 forward-port)

src/borg/archiver.py
(cherry picked from commit 01d2f728131e3f3eb6e1722c69482d969a570347)
=> create: implement --stdin-name, fixes #3533 (1.1 backport)

src/borg/archive.py, src/borg/archiver.py, src/borg/cache.py, src/borg/testsuite/cache.py
=> non-lazy files cache (1.2 forward-port)

src/borg/archive.py, src/borg/archiver.py
=> set rc=1 when extracting damaged files (1.1 backport)

docs/usage/with-lock.rst.inc
* move note about repo copy to FAQ
* add link to FAQ
=> docs: Improve borg with-lock

docs/faq.rst
I think this will more helpful to have all info about copy repo in one section
=> Add note from borg with-lock about copy repo

src/borg/archive.py
only output msgs if there is actually something to delete.
be more precise, show count of orphaned / superseded objects.
=> borg check: fixup for "deleting orphaned objs" msgs, fixes #3795

docs/usage_general.rst.inc
(cherry picked from commit 1ba0e8562127e2bbf286f5d1188226a5b864f14b)
=> docs: describe what BORG_LIBZSTD_PREFIX does

borg/archive.py
(cherry picked from commit 959beb867ba3cc6b6fb522d57d8ecd31b443e9f0)
=> xattrs: fix borg exception handling on ENOSPC error, fixes #3808

Vagrantfile
=> Vagrant changes (master)
