docs/faq.rst

UNIX domain sockets: explain why not, see attic issue #259
Symlinks: say that they are backed up as is and not followed, replacement for attic PR #294
Sparse files: explain what the "simple" in simple sparse file support means.
Plus some other explanations / mentions that were missing.

improve docs about what is preserved and what not

---

docs/usage.rst

--monthly is old/deprecated, --keep-monthly is new way.

fix small doc bug in prune examples, fix attic #306

---

docs/quickstart.rst
docs/usage.rst

do not hide useful information

toplevel error handler: show tracebacks

---

borg/archive.py
borg/archiver.py
borg/helpers.py

a lot of speedup (esp. for slow connections to remote repositories) for:
```
list <repo>
delete <repo> (shows list of all archives in query)
prune
```
the previous method used metadata from the archive itself, which is (in total) rather large.
so if you had many archives and a slow (remote) connection, it was very slow.
but there is a lot easier way: just use the archives list from the repository manifest - we already
have it anyway and it also has name, id and timestamp for all archives - and that's all we need.
I defined a ArchiveInfo namedtuple that has same element names as seen as attribute names
of the Archive object, so as long as name, id, ts is enough, it can be used in its place.

efficient archive list from manifest, fixes attic #167

---

borg/_hashindex.c
borg/hashindex.pyx
borg/helpers.py

borg info repo::archive now reports unique chunks count, total chunks count
it's useful to see how they change in response to different CHUNK_MASK values.
also: use index->key_size instead of hardcoded value

determine and report chunk counts in chunks index

---

borg/archiver.py

always use archiver.print_error, so it goes to sys.stderr
always say "Error: ..." for errors
for rc != 0 always say "Exiting with failure status ..."
catch all exceptions subclassing Exception, so we can log them in same way and set exit_code=1

improve at-end error logging

---

borg/archive.py
borg/cache.py
borg/fuse.py
borg/helpers.py
borg/key.py
borg/lrucache.py
borg/remote.py
borg/testsuite/__init__.py
borg/testsuite/archiver.py
borg/testsuite/helpers.py
borg/testsuite/platform.py
setup.cfg
setup.py

use simpler super() syntax of python 3.x
remove fixed errors/warnings' codes from setup.cfg flake8 configuration
fix file exclusion list for flake8

style and cosmetic fixes, no semantic changes

---

scripts/borg
setup.py

also kills the dist-utils fallback

use entrypoints instead of scripts, for better use of the wheel format and modern installs

---

borg/archive.py
borg/cache.py

This fix is maybe not perfect yet, but maybe better than nothing.
A comment by Ernest0x (see https://github.com/jborg/attic/issues/232 ):
@ThomasWaldmann your patch did the job.
attic check --repair did the repairing and attic delete deleted the archive.
Thanks.
That said, however, I am not sure if the best place to put the check is where
you put it in the patch. For example, the check operation uses a custom msgpack
unpacker class named "RobustUnpacker", which it does try to check for correct
format (see the comment: "Abort early if the data does not look like a
serialized dict"), but it seems it does not catch my case. The relevant code
in 'cache.py', on the other hand, uses msgpack's Unpacker class.

fix Traceback when running check --repair, attic issue #232

---

docs/installation.rst

Fixed formatting issue in installation.rst where packages were listed all on one line.

Fix format issue in installation.rst for Cygwin

---

borg/archiver.py
borg/helpers.py
borg/remote.py
borg/testsuite/archiver.py

affects local and remote umask, secure by default M == 077
fixes issue #117

implement --umask M

---

borg/archiver.py
borg/cache.py
docs/usage.rst

do not use the files cache for such special files
Note: if one lists an archive with special files, their metadata will look like ... a special file (mode, size of 0, ...). But differently from the usual way of dealing with them, they WILL have all the content read from that special file.

read special files as if they were regular files, update docs, closes #79

---

borg/repository.py

the daemonize code changes the cwd, thus a relative repo path can't work.
borg mount repo mnt  # did not work
borg mount --foreground repo mnt  # did work
borg mount /abs/path/repo mnt  # did work

use absolute path, attic issue #200, attic issue #137

---

borg/helpers.py
borg/testsuite/helpers.py

The OS X file system HFS+ stores path names as Unicode, and converts
them to a variant of Unicode NFD for storage.  Because path names will
always be in this canonical form, it's not friendly to require users to
match this form exactly.  Convert paths from the repository and patterns
from the command line to NFD before comparing them.
Unix (and Windows, I think) file systems don't convert path names into a
canonical form, so users will continue to have to exactly match the path
name they want, because there could be two paths with the same character
visually that are actually composed of different byte sequences.
*Changes since last PR*
- rebased on upstream master
- fixed test error
- removed 'normalize' parameter in favor of sys.platform testing
- reorganized tests into OSX/non-OSX …

Normalize paths before pattern matching on OS X

---

borg/archiver.py
borg/helpers.py
borg/testsuite/helpers.py

for borg mount's FUSE filesystem, we use the archive name as a directory name,
thus slashes are not allowed.

archive names with slashes are invalid, attic issue #180

---

docs/Makefile
docs/conf.py
docs/index.rst

this is a crude hack for now, and could use a better table of contents
but at least we have some way of linking and showing the different
internal functions
the next phase here is obviously to document that API through the
addition of docstrings. a static api.rst could also be easier to read,
but maybe that could go through some docstrings as well, to be tested

add automatically generated API

---

borg/archiver.py
borg/remote.py
borg/testsuite/repository.py
docs/usage.rst

while SSH options can be specified through `~/.ssh/config`, some users
may want to use a completely different SSH command for their backups,
without overriding their $PATH variable. it may also be easier to do
ad-hoc configuration and tests that way.
plus, the POLA tells us that users expects something like this to be
supported by commands that talk to ssh. it is supported by rsync, git
and so on.
see https://github.com/jborg/attic/issues/99
a significant amount of code reshuffling was necessary for unit tests to be implemented here, so please bear with me...

add support for arbitrary SSH commands

---

docs/development.rst
docs/installation.rst

we stop supporting them, because there are better alternatives:
- use a distribution package (from your linux distribution), if available
- use a pyinstaller binary provided by us (they include all you need in 1 file and
thus have better compatibility properties and are easier to install than a wheel)
- install from source (pypi or git) if everything else fails

remove docs about binary wheels

---

docs/development.rst

link to the locations of different tools when I know them. i marked
the ones I don't know about specially so we can document those as
well.
point to the Github releases for the standalone binaries upload
this is in progress, a continuation of the discussion in #214.

some fixes to the release engineering docs

---

.gitignore

the current instructions create a dirty tree that `git add .` would
commit into git. this is error prone and somewhat unclean.
i found it preferable to change the `.gitignore` than to change the instructions, since there are probably `borg-env` environments lying around everywhere already.

fix virtualenv path in .gitignore

---

borg/archive.py
borg/archiver.py
borg/helpers.py
borg/key.py
borg/repository.py
docs/Makefile
docs/_themes/local/sidebarusefullinks.html
docs/usage.rst
setup.py

this should close #155, minus changes to point all "homepage" urls to RTD. turns out i simply had to disable all C code building and a few other checks in order to make that work. A magic `READTHEDOCS` environment variable is available for that (found *that* sucker in https://github.com/andsor/pypercolate/blob/master/setup.py#L30).
it required rewriting the makefile code into hairy Python code, with an unfortunate cleanroom reimplementation of the code mentionned in #208 - which will need to be rewritten once we switch to click - ouch! (#251) the code is not very pretty, and setup.py is growing like crazy now, maybe it would be worth moving some of that code into a borg.documenation module.
anyways, the usage build is *much* faster than it was in the makefile, so that's good, and now the …

fix build on readthedocs.org

---

borg/archiver.py
borg/testsuite/upgrader.py
borg/upgrader.py

instead, we perform the equivalent of `cp -al` on the repository to
keep a backup, and then rewrite the files, breaking the hardlinks as
necessary.
it has to be confirmed that the rest of Borg will also break hardlinks
when operating on files in the repository. if Borg operates in place
on any files of the repository, it could jeoperdize the backup, so
this needs to be verified. I believe that most files are written to a
temporary file and moved into place, however, so the backup should be
safe.
the rationale behind the backup copy is that we want to be extra
careful with user's data by default. the old behavior is retained
through the `--inplace`/`-i` commandline flag. plus, this way we don't
need to tell users to go through extra steps (`cp -a`, in particular)
before running the …

do not upgrade repositories in place by default

---

borg/upgrader.py

this resolves bug #269 where the index file could not be
converted, completely breaking conversion.
it seems that, during some refactoring, the index conversion code was
completely dropped. this was missed by the unit tests because the repo
can still be opened by the constructor even though the index is
invalid, so tests need improvements there.

fix cascading failure with the index conversion code

---

borg/archiver.py

it should also probably be --one-file-system for coherence with du(1)
this is a reroll of #282.

add -x flag, common to GNU utilities

---

borg/archiver.py

the old name still works, but emits a deprecation warning suggesting the new name.
this is a followup to 4fd06e2634e9583762606eae0f27a6a569afcd60, which added "-x" (as seen in "du").

use --one-file-system (as "du" tool does) instead of --do-not-cross-mountpoints

---

borg/testsuite/logger.py
borg/testsuite/upgrader.py
docs/development.rst
setup.cfg

followup for #4: we configure flake8 to be a little more strict so that new contributions are cleaner. i also fix errors i introduced in recent pull requests, to try to play catchup at *least* with the new stuff i submitted.
finally, i added a blurb to the development docs about flake8, because i had forgotten about it...
before this PR:
```
1       E121 continuation line indentation is not a multiple of four
1       E125 continuation line does not distinguish itself from next logical line
25      E127 continuation line over-indented for visual indent
1       E128 continuation line under-indented for visual indent
1       E202 whitespace before ']'
1       E203 whitespace before ','
1       E221 multiple spaces before operator
1       E222 multiple spaces after operator
1       E225 …
```

small flake8 changes

---

borg/archiver.py

this way the version can be discovered by scripts without having to
part the output of 'help'.
it is removed from the 'help' output itself because it is prettier
without the complete version number, and then the description can be
reused elsewhere as well without needing the version number. this is especially important for #208

add standard --version argument

---

borg/archiver.py
borg/locking.py

there were 2 issues:
lock used another pid and tid than release because daemonize() made it different processes/threads.
solved by just determining PID only once and not using TID any more.
the other issue was that the repo needed and explicit closing.

fuse mount: fix unlocking of repository at umount time, fixes #331

---

borg/archiver.py
borg/logger.py
borg/testsuite/archiver.py
borg/testsuite/logger.py

All normal informational output is now logged at INFO level.
To actually see normal output, the logger is configured to level INFO also.
Log levels:
WARNING is for warnings, ERROR is for (fatal) errors, DEBUG is for debugging.
logging levels must only be used according to this semantics and must not be
(ab)used to let something show up (although the logger would usually hide it)
or hide something (although the logger would usually show it).
Controlling the amount of output shown on INFO level:
--verbose, --progress, --stats are currently used for this.
more such flags might be added later as needed.
if they are set, more output is logged (at INFO level).
also: change strange setup_logging return value

fix logging levels, issue #321

---

borg/cache.py
borg/repository.py
borg/testsuite/archiver.py

this is a recommended thing since direct use of RawConfigParser
is not recommended and deprecated according to python docs.

move away from RawConfigParser to ConfigParser

---

borg/archiver.py
borg/helpers.py
borg/testsuite/helpers.py

the reason for a slow msgpack can be:
- pip install: missing compiler (gcc)
- pip install: missing compiler parts (e.g. gcc-c++)
- pip install: cached wheel package that was built while the compiler wasn't present
- distribution package: badly built msgpack package

emit a warning if we have a slow msgpack installed

---

borg/archiver.py
borg/cache.py
borg/helpers.py
borg/key.py
borg/locking.py
borg/remote.py
borg/repository.py

subclasses of "Error": do not show traceback
(this is used when a failure is expected and has rather trivial reasons and usually
does not need debugging)
subclasses of "ErrorWithTraceback": show a traceback
(this is for severe and rather unexpected stuff, like consistency / corruption issues
or stuff that might need debugging)
I reviewed all the Error subclasses whether they fit into the one or other class.
Also: fixed docstring typo, docstring formatting

prettier error messages, fixes #57

---

.coveragerc
borg/platform.py
borg/xattr.py
tox.ini

seems like they need a */ prefix
also: exclude everything below support/ - this is 3rd party stuff.

fix .coverragerc omits, fixes #319

---

borg/archive.py

This solves:
File
"/storage/8899fc1454db04de.a/home/code/ports/pobj/borgbackup-0.28.0/borgbackup-0.28.0/borg/archive.py",
line 605, in <listcomp>
item_keys = [msgpack.packb(name) for name in ITEM_KEYS]
NameError: name 'msgpack' is not defined

Catch msgpack error in archive.py

---

setup.py

it requires "mock" (and later also sphinx) and we do not (want to) have that in setup_requires.
I removed the build.sub_commands.append(...) because that made setup.py install run build_api
and build_usage automatically for production installs. the comment said it does not work on
readthedocs anyway.
build_api and build_usage can still be run manually.

do not try to build api / usage docs for production install

---

Vagrantfile
borg/logger.py
docs/development.rst

this fixes #218 in an easier way so one doesn't have to type
--hidden-import=logging.config all the time when using pyinstaller.

avoid hidden import, make it easy for pyinstaller

---

borg/archiver.py

--progress isn't a "toggle" anymore, in that it will never disable progress information: always enable it.
example:
$ borg create ~/test/borg2::test$(date +%s) . ; echo ^shows progress
reading files cache
processing files
^shows progress
$ borg create ~/test/borg2::test$(date +%s) . < /dev/null; echo ^no progress
reading files cache
processing files
^no progress
$ borg create --progress ~/test/borg2::test$(date +%s) . < /dev/null; echo ^progress forced
reading files cache
processing files
^progress forced
$ borg create --no-progress ~/test/borg2::test$(date +%s) . ; echo ^no progress
reading files cache
processing files
^no progress
we introduce a ToggleAction that can be used for other options, but
right now is just slapped in there near the code, which isn't that
elegant. inspired by: …

add a --no-progress flag to forcibly disable progress info

---

borg/archiver.py
borg/cache.py
borg/locking.py
borg/remote.py
borg/repository.py
borg/testsuite/locking.py
borg/testsuite/repository.py

based on PR#438.
one small fix to avoid orphan locks at a specific place.
but: it will still happen, as the exclusive lock is held over a long time (e.g. while a backup is running) and the current method to release it relies on `__del__` methods in Cache and Repository, which is maybe not the most reliable thing.

Avoid orphan locks, see #285

---

borg/testsuite/archiver.py
docs/faq.rst
docs/usage.rst

this tests the behaviour found in #403 and documented in #418, but doesn't fail on the unexpected A
this also clarifies the documentation on this issue to hilight that the reason this is okay is because we only look at the files cache for status. also link in the usage.

add test for the weird unchanged file status

---

borg/_hashindex.c
borg/testsuite/hashindex.py

BUCKET_UPPER_LIMIT: 90% load degrades hash table performance severely,
so I lowered that to 75% (which is a usual value - java uses 75%, python uses 66%).
I chose the higher value of both because we also should not consume too much
memory, considering the RAM usage already is rather high.
MIN_BUCKETS: I can't explain why, but benchmarks showed that choosing 2^N as
table size severely degrades performance (by 3 orders of magnitude!). So a prime
start value improves this a lot, even if we later still use the grow-by-2x algorithm.
hashindex_resize: removed the hashindex_get() call as we already know that the values
come at key + key_size address.
hashindex_init: do not calloc X*Y elements of size 1, but rather X elements of size Y.
Makes the code simpler, not sure if it affects performance. …

misc. hash table tuning

---

borg/remote.py

this is needed because due to the locking improvements, some rpc calls' signature changed slightly.

increase rpc protocol version to 2, fixes #458

---

borg/helpers.py
borg/repository.py

The read_msgpack and write_msgpack functions were only used in one place
each.  Since msgpack is read and written in lots of places, having
functions with these generic names is confusing. Also, the helpers
module is quite a mess, so reducing its size seems to be a good idea.

helpers: remove functions that are only used once

---

borg/_hashindex.c
borg/cache.py
borg/hashindex.pyx

this was also the loop contents of hashindex_merge, but we also need it callable from Cython/Python code.
this saves some cycles, esp. if the key is already present in the index.

hashindex_add C implementation

---

docs/installation.rst

On arch I don't want to perform a full system upgrade when installing a new package; so let's drop the "yu" part.

Fix wrong installation instructions for archlinux

---

borg/archive.py
borg/archiver.py
borg/remote.py
borg/repository.py
borg/testsuite/archiver.py
borg/testsuite/repository.py
docs/quickstart.rst

please review this as alternative to #423 (fixing #239)
as soon as one target segment is full, it is a good time to commit it and remove the source segments
that are already completely unused (because they were transferred to the target segment).
so, for compact_segments(save_space=True), the additional space needed should be about 1 segment size.
note: we can't just do that at the end of one source segment as this might create very small
target segments and that is not what we want.

compact_segments: save_space -> free unused segments quickly

---

borg/fuse.py

Single-shot unpacker read buffer decreased from (default) 1Mb to 512b.
"ls -alR" on ~100k files backup mounted with fuse went from ~7min to 30 seconds.

Optimized fuse inode cache

---

borg/archiver.py
borg/testsuite/archiver.py

For 0.29 we worked towards a "silent by default" behaviour, so interactive usage will include -v more frequently in future.
But I noticed that this conflicts with the progress display. This would be no problem if users willingly decide which one
of --verbose or --progress they want to see, but before this fix, the progress display was activated magically when
a tty was detected. So, to counteract this magic, users would need to use --no-progress.
That's backwards imho, so I removed the magic again and users have to give --progress when they want
to see a progress indicator. Or (alternatively) they give --verbose when they want to see the long file list.

remove --progress magic, fixes #476

---

docs/installation.rst

Documentation: Standalone binary / pyinstaller extracts dependencies into /tmp. Currently /tmp requires about ~28MB of free space. It also needs exec permissions. Closes #499

docs: standalone binary needs exec on temp

---

docs/usage.rst

* docs/usage.rst: Replace "|project_name|" with "borg" because the
abstraction doesn't work in usage examples.
Currently, this displays as "|project_name|" in the docs. This patch
updates it to display "borg".
I don't know rst so I don't know if there is a better way to do this.

docs: Give project name in usage example.

---

borg/helpers.py
borg/testsuite/helpers.py

The parsing code for exclude files (given via `--exclude-from`) was not tested.
The core is factorized into its own function to facilitate an easier test.

Factorize and test loading of excludes from file

---

borg/archiver.py

The help text describing patterns should be dedented like other multi-paragraph text blocks.

Dedent pattern help text

---

docs/installation.rst

we have new OS supported, as per #105. this adds Debian stretch and Ubuntu Wily to the list, along with NixOS. i also reorder the table so that it's sorted alphabetically - i originally kept OSX in the end as a separate distribution, but let's drop that distinction, since this will also cover *BSDs, which are not Linux derived either.

expand install docs table

---

borg/archiver.py
borg/helpers.py
borg/testsuite/archiver.py
borg/testsuite/helpers.py
docs/usage.rst

The existing option to exclude files and directories, “--exclude”, is
implemented using fnmatch[1]. fnmatch matches the slash (“/”) with “*”
and thus makes it impossible to write patterns where a directory with
a given name should be excluded at a given location in the directory
hierarchy, but not at any other place. Consider this structure:
home/
home/aaa
home/aaa/.thumbnails
home/user
home/user/img
home/user/img/.thumbnails
The intention is to exclude “.thumbnails” in all home directories while
retaining directories with the same name in all other locations. With
fnmatch the pattern “home/*/.thumbnails” matches
“home/user/img/.thumbnails” too.
The desired exclusion can be implemented using the “--exclude-regex”
option introduced with this change:
--exclude-regex …

Implement exclusions using regular expressions

---

borg/archiver.py
borg/helpers.py

prune and create now both require --verbose --stats to show stats.
it was implemented in this way (and not with print) so you can feed the stats data
into the logging system, too.
delete now says "Archive deleted" in verbose mode (for consistency,
it already said "Repository deleted" when deleting a repo).
also: add helpers.log_multi to comfortably and prettily output a block of log lines

log stats consistently, fixes #526

---

docs/conf.py

relates to issue #541 
now that we can build a simple man page with sphinx, shall we bundle it with borg?
like in docs/_build/man/borg.1?
shall we also bundle rendered html docs in docs/_build/html/* then?

sphinx configuration: fix to create a simple man page from usage docs

---

docs/changes.rst
docs/usage.rst

I've come across these while working on the debian package (they were actually detected by lintian (a Debian QA tool) because they got copied into the manpage) and I've dropped one "are" in the usage.rst sentence.

docs: Correct small typos in changes and usage

---

README.rst
docs/deployment.rst

docs/deployment.rst: Fixes on some incorrect restructuredtext usage.
README.md: add shield for readthedocs, add screencast in seperated section
After some discussion of the previous PR: https://github.com/borgbackup/borg/pull/529#issuecomment-171566027

Docs/deployment: Fixes on incorrect markup

---

borg/archive.py
docs/internals.rst

the items metadata stream is usually not that big (compared to the file content data) -
it is just file and dir names and other metadata.
if we use too rough granularity there (and big minimum chunk size), we usually will get no deduplication.

finer chunker granularity for items metadata stream, fixes #547, fixes #487

---

borg/locking.py

the problem was that the borg process removed its own shared lock when upgrading it to an exclusive lock.
this is fine if we get the exclusive lock, but if we don't, we must re-add our shared lock.
this fixes the KeyError in locking.py:217

fix locking, partial fix for #502

---

README.rst
borg/archiver.py
borg/testsuite/archiver.py
docs/deployment.rst
docs/faq.rst
docs/global.rst.inc
docs/internals.rst
docs/quickstart.rst
docs/usage.rst

* Fixed RST warning markup.
* `borg prune` only knows "--keep-within" and not "--within".
* Use HTTPS everywhere. Especially when the website already redirects to HTTPS.
* Fixed spelling.
* Make note that AES-256 is used.
* Use ``--option`` in RST to not render "--" as "–".
``--options`` should probably also be used for help texts which are shown on the command line help.
https://github.com/borgbackup/borg/blob/master/borg/archiver.py
This also looks good in the manpage.
Thanks so much for your work!

Docs fixes.

---

README.rst

Github generated wrong markup, because of a few whitespace errors.
This patch fixes the rst markup of the README.rst file.

Fix markup in README.rst

---

AUTHORS
borg/archiver.py
borg/helpers.py
borg/testsuite/archiver.py
borg/testsuite/helpers.py

Implement the request for pattern support on file extraction from issue #361.

Extract pattern support

---

borg/upgrader.py

fixes #576 
Maybe a different error should be output? atm it’s:
no key file found for repository
Maybe something like:
No key folder found, assuming no keys exist
Or even an error, prompting for folder generation? Although that might be a bit much.

Fix upgrade without ~/attic/keys existing.

---

borg/archiver.py

we now use -P for --prefix and -p for --progress. previously, the
result of -p depended on the command: some were using it for
--progress, some for --prefix. this was confusing and was making it
impossible to both --progress and --prefix with on-letter options
--progress is likely used more often and interactively, so it get the
keystroke shortcut (lower "-p")
--prefix is used more rarely / in scripts, but important/dangerous for
prune, so it get the extra keystroke (higher "-P")
If somebody used -p someprefix and does not fix that to -P, it will
result in "no archive specified" or "unrecognized argument". So it
will neither cause pruning to remove wrong data nor go unnoticed.
Closes: #563

disambiguate -p versus -P

---

docs/installation.rst

Ubuntu Vivid is not supported anymore.

Delete Ubuntu Vivid, EOL

---

borg/helpers.py

this does NOT fix absolute vs. relative path usage,
but as this also deals with remote paths, this can't be done in general.

use os.path.normpath on repository paths, fixes #606

---

docs/usage.rst

I couldn't figure out how to specify a custom private key for SSH communication until I read one of the tests covering `BORG_RSH`. The original documentation wasn't clear to me at the time. This pull request adds to the documentation so that other's may not waste the same time as I. :smile:

Added example to BORG_RSH documentation.

---

docs/usage.rst

also: do not use /dev/sda in case someone stupidly tries out the examples.
/dev/sdx should be safe for people who do not understand what they do.

docs: add example how to restore a raw device, fixes #671

---

borg/helpers.py
borg/testsuite/helpers.py
docs/usage.rst

Format tags available for archive name:
`{now}, {utcnow}, {fqdn}, {hostname}, {user}, {pid}
`
Example:
add short hostname, backup username and current unixtime (seconds from epoch)
`$ borg create  /mnt/backup::{hostname}-{user}-{now:%s} ~`
See issue #650 for discussion of this feature

Archive name formatting on create

---

borg/archiver.py
borg/helpers.py

If remote home is readonly for the user, using borg will fail on permission
problem to create cache and keys directories. borg --server does not use nor need
them so drop mkdirs from run()
see #701 for discussion

Remote end does not need cache nor keys directories, do not make them.

---

docs/borg_theme/css/borg.css

I know !important is generally discouraged, but it's the easiest solution by far here, and I can't see it causing much harm.

CSS !important overwrite. Fix borgbackup/borg#727

---

docs/faq.rst

if the filesystem issue can't be reproduced with a known-good,
local fs like ext4 on linux, the issue is likely not borg's fault.

document how to debug / file filesystem issues, fixes #664

---

borg/helpers.py

platform.libc_ver() is broken, it uses string comparison to compare version numbers.

remove useless/misleading libc version display, fixes #738

---

borg/helpers.py

Building the API docs for these functions capture the build host's I/O charset, making the build unreproducible.
This PR follows the style of #736, moving the evaluation of `sys.stderr` from the parameter list to the constructor.

Build api.html reproducibly for ProgressIndicatorEndless/Percent

---

borg/helpers.py

used by borg list, prune, delete.
before: ```<name> <datetime>```
now:    ```<name> <datetime> [<id>]```
it's a bit less pretty now, but better for automation as the id always stays same while the name can be changed.

format_archive: also output archive id, fixes #731

---

borg/archive.py
borg/archiver.py
borg/cache.py

Solves the issue with pull backups taking ages, because sshfs does not forward inode numbers from the server[1].
[1] I have not researched why, I guess it is a fundamental problem of sorts - if it were a simple "fix" they would just do it, I suppose.

Feature --ignore--inode

---

AUTHORS
borg/archive.py
borg/archiver.py
borg/testsuite/archiver.py

borg diff: find different files between archives

---

borg/archiver.py
borg/helpers.py
borg/testsuite/archiver.py
borg/testsuite/helpers.py

Current state:
- compatible except for {formatkeys}, which is gone
- available keys now right in --help, with additional per-key help if deemed necessary
- supports -e, exclude-from, paths like the others
(code should/will be shared, see feature-diff branch)
- supports guaranteed_available hashlib hashes
(to avoid varying functionality depending on environment)
(also, the other hashes are really obscure, like MD-4)
The two profiles [formerly linked here](https://github.com/borgbackup/borg/issues/735#issuecomment-196355903) were actually a mistake ; I wasn't running the second command inside the current environment and hence still used the old version (which is the reason why these are so similar -- should've been suspicious). The first approach was actually a **lot** slower, due to the …

ItemFormatter for printing items, borg list redo.

---

borg/archive.py
borg/archiver.py
borg/helpers.py
borg/testsuite/archiver.py

**Issue summary:**
When extracting subtrees ("partial_extract") by using any of (excludes, PATH, strip-components) hard links might fail, because Borg tried to link to non-existing files, if the first appearance of a (inode, device) tuple (which uniquely identifies files and is identical across hard links) was not extracted.
**Implementation:**
* creating a mapping that stores *all* file paths so far and their chunk list or link source. (We need to store all seen files, because we can't tell if a file is hard-linked)
* when extracting a hard link: resolving whether an instance of the link was extracted
* if it was not, the file contents will be extracted
* and the entry in our "master file mapping" will be changed to point to this file
* if it was, a hard link is created
**Drawbacks:**
* …

Issue #761: Links fail for extracting subtrees

---

borg/archiver.py
borg/helpers.py
docs/usage.rst
docs/usage/diff.rst.inc
docs/usage/list.rst.inc

- Note in borg diff help explaining --same-chunker-params
- Corrected "PATH" description for borg list saying that it's about extracting
- Ran "setup.py build_usage"
- Added an example for borg diff (we should remember to update that when/if we change the output format)

Update usage docs (diff and list)

---

borg/archiver.py
borg/remote.py
borg/repository.py
borg/testsuite/__init__.py
borg/testsuite/archiver.py
borg/testsuite/repository.py
borg/testsuite/upgrader.py
borg/upgrader.py

From https://github.com/borgbackup/borg/issues/562#issuecomment-198576577
Not sure if we should do `@drop_unused_args`, avoids some repetition, but could be a bit "opaque".
Looks good to me. I don't see any ignored (raised in __del__) exceptions in ArchiverTestCase anymore, and only one in RemoteArchiver (test_remote_repo_restrict_to_path, I think it might have something to do with that monkey patching). This should essentially eliminate stale locks in practice. (Except for SIGTERM).

Feature ctxmng: Repository context manager

---

AUTHORS
borg/archiver.py
borg/helpers.py
borg/testsuite/archiver.py
borg/testsuite/helpers.py
docs/usage.rst

This is an implementation for #757. I have tested the implementation with my real snapshots, and I like to use this output format myself. The format is similar to what I described in #757, but I made some changes. I'd like to hear any comments and ideas about this format and implementation details.
The main design goals of the new format:
- One file takes exactly one line of output
- The format is easy to read with typical, long list of changes
- Metadata changes are visible and easy to examine
- Unuseful information is not shown
~~There are many possible special cases where regular files are replaced with links, or where hard links are replaced by symbolic links etc. In this output format, these modifications are indicated on the file mode. For convenience, I introduce a new file mode …

Improved diff format

---

borg/archiver.py
borg/testsuite/archiver.py
docs/usage.rst

Makes it easy to see paths excluded by --exclude* options for testing of
regexes, and for ongoing monitoring that files desired for backup aren't
getting excluded accidentally.

Add 'x' status for excluded paths (#814)

---

borg/archiver.py
borg/testsuite/archiver.py
docs/usage/diff.rst.inc

This is a solution to #797. The commit is quite trivial and should be easy to review.
Previously, on `borg diff`, the output always had first the modifications, then additions, and finally removals. Output may be easier to follow if the various kinds of changes are interleaved. This commit is a simple solution that first collects the output lines and sorts them by file path before printing. This new behavior is optional and disabled by default. It can be enabled with `--sort` command line option.
This option will be especially useful after the planned multi-threading changes arrive. Multi-threading may shuffle the archive order of files making diff output hard to follow without sorting.

Add '--sort' option for sorting diff command output

---

borg/crypto.pyx
borg/key.py
borg/testsuite/crypto.py

AESKeyBase.decrypt makes less copies of the data, specifically data[41:],
which copies the payload, is gone. This is possible since this commit
makes our lil' crypto API compatible with simple buffers.
In Cython there is a syntax for creating memoryviews from buffer-enabled
objects, however, it doesn't support read-only buffers. ro_buffer gets
this job done, though, and also does the proper type checking
(by PyBUF_SIMPLE).
Note: msgpack doesn't support memoryviews. Otherwise we could avoid
copying the en/de-crypted output with the final "return out[:ctl]"
This commit leads to a solid 10-15 % increase in performance of hash-lists
and extract.
--
We could also avoid the outgoing copy in AES, but memoryviews are not handled by msgpack. See msgpack/msgpack-python#126
(Technically the HMAC of …

Replace stdlib hmac, zero-copy decrypt

---

borg/archiver.py
borg/remote.py
borg/repository.py
borg/testsuite/__init__.py
borg/testsuite/archiver.py
borg/testsuite/repository.py
borg/testsuite/upgrader.py
borg/upgrader.py

Backported from #777 to 1.0-maint

Make Repository a context manager, use decorators for wrapping withs

---

borg/archiver.py
borg/remote.py
docs/usage.rst

it's not recommended to suppress warnings or errors,
but the user may decide this on his own.
note: --warning is not given to borg serve so a <= 1.0.0 borg
will still work as server. it is not needed as it is the default.

add --warning, --error, --critical for completeness, fixes #826

---

borg/remote.py

(GH wanted to put this into master before)

Remote: don't print tracebacks for Error exceptions handled downstream

---

borg/archiver.py

`borg info` command shows the command line that was used to create the archive. If the command line has arguments with spaces in them the printed command will not work. This commit will escape these arguments by enclosing it to quotation marks. This is a minor thing.

Escape cmdline arguments that have spaces in them

---

borg/archive.py
borg/archiver.py
borg/cache.py

#852 This is mainly meant for use with network file systems like sshfs and
possibly CIFS, which don't convey proper inode numbers.
Backported from master for inclusion into 1.0.1

1.0-maint, borg create: add --ignore-inode option [to fix sshfs performance]

---

borg/archive.py
borg/archiver.py
borg/testsuite/archiver.py
docs/usage.rst
docs/usage/comment.rst.inc
docs/usage/create.rst.inc

This is an implementation for #842. Tests and better documentation will follow.
- Archives now have a new metadata field `comment`
- `borg info` command shows the comment if it's present
- `borg create` command now has option `--comment` for adding comments to archives.
- A new command `borg comment` is added for modifying the comments on existing archives.

Add archive comments

---

docs/installation.rst

ubuntu was showing up twice in the list of supported OSes... it seems it was because the line was getting too long, so I removed the "names" and kept only the numbers to keep the line short.

cleanup ubuntu in install list

---

borg/archiver.py
docs/borg_theme/css/borg.css
docs/usage.rst
docs/usage/break-lock.rst.inc
docs/usage/change-passphrase.rst.inc
docs/usage/check.rst.inc
docs/usage/comment.rst.inc
docs/usage/common-options.rst.inc
docs/usage/create.rst.inc
docs/usage/debug-delete-obj.rst.inc
docs/usage/debug-dump-archive-items.rst.inc
docs/usage/debug-get-obj.rst.inc
docs/usage/debug-put-obj.rst.inc
docs/usage/delete.rst.inc
docs/usage/diff.rst.inc
docs/usage/extract.rst.inc
docs/usage/info.rst.inc
docs/usage/init.rst.inc
docs/usage/list.rst.inc
docs/usage/migrate-to-repokey.rst.inc
docs/usage/mount.rst.inc
docs/usage/prune.rst.inc
docs/usage/rename.rst.inc
docs/usage/serve.rst.inc
docs/usage/upgrade.rst.inc
setup.py

- Group options
- Nicer list of options in Sphinx
This is how the help looks like with the patch:
Sphinx: https://pstore.enkore.de/borg/usage.html#borg-create (this also works very nicely with RTFD's responsive theme, try making the browser window narrow :)
And on the console:
```
$ borg create --help                                   
usage: borg create [-h] [-v] [--debug] [--lock-wait N] [--show-version]
[--show-rc] [--no-files-cache] [--umask M]
[--remote-path PATH] [-n] [-s] [-p] [--list]
[--filter STATUSCHARS] [-e PATTERN]
[--exclude-from EXCLUDEFILE] [--exclude-caches]
[--exclude-if-present FILENAME] [--keep-tag-files] [-x]
[--numeric-owner] [--ignore-inode] [--read-special]
[--comment COMMENT] [--timestamp yyyy-mm-ddThh:mm:ss]
[-c SECONDS]
[--chunker-params …
```

better help texts and sphinx reproduction of the help

---

borg/archiver.py

This fixes issue #873. Discussed in #borgbackup. Solution by nachtgeist/rts/ThomasWaldmann:
OpenBSD uses st_dev=0 for '/' on OpenBSD. Code below evaluates to false as '/' has st_dev=0:
if restrict_dev and st.st>_dev != restrict_dev:

fix issue #873 - running borg with --one-file-system traverses in excluded filesystems

---

borg/archiver.py
borg/testsuite/archiver.py

Previously on some cases where symlink replaced something else or was replaced by something else, `borg diff` failed with `KeyError: b'source'`. This commit fixes the issue. There are now also tests that catch this issue.
(I remember testing this case when developing the feature, but I guess I dropped it when refactoring the hardlink behavior.)

Fix 'borg diff' when symlink is replacing or being replaced

---

docs/installation.rst

Let me note, that repositories below home: aren't official in any way, but I just submitted it to the  openSUSE Archiving:Backup repo now. That's the first step for getting really official on openSUSE, too.

Fix package naming for openSUSE

---

borg/archiver.py
borg/cache.py

This also makes --cache-only idempotent: it won't fail if the cache
is already deleted.
Fixes #874

borg delete: fix --cache-only for broken caches

---

borg/_hashindex.c

hashindex_summarize: fix missing byte-order conversion

---

borg/helpers.py

building the API docs captured sys.stderr's IO charset, making the build
unreproducible.

reproducible doc for ProgressIndicator*

---

borg/_hashindex.c
borg/archive.py
borg/cache.py
borg/hashindex.pyx
borg/testsuite/hashindex.py

(This changeset does not include #890, since that one is already for 1.0-maint. It supersedes merged #887, and unmerged #888 for master)

Add overflow checks to refcounting, port stuff to Cython etc

---

borg/cache.py
borg/hashindex.pyx
borg/testsuite/hashindex.py

Also fixes a small cosmetic bug (would only affect recreate) where with add_chunk(overwrite=True) chunks that aren't unique would count towards the unique/deduplicated size.

Cache: update add_chunk to use ChunkIndex.add

---

borg/archiver.py

fix spelling, as shown on 
https://lintian.debian.org/full/debian@danny-edel.de.html#borgbackup_1.0.1-1
( and I have a typo in commit-message.. haha)

fix spelling, as of lintian.debian.org

---

borg/archive.py
borg/testsuite/archiver.py
borg/xattr.py

They are extracted correctly, for a little while at least, since chown()
resets call capabilities on the chowned file[1]. Which I find curious,
since chown() is a privileged syscall. Probably a safeguard for
sysadmins who are unaware of capabilities.
The solution is to set the xattrs last, after chowing
[1] Even though I know this now I cannot find **any** documentation indicating this behaviour.

Fix capabilities extraction on Linux

---

borg/archive.py
borg/archiver.py
borg/cache.py
borg/fuse.py
borg/helpers.py
borg/key.py
borg/testsuite/archive.py
borg/testsuite/archiver.py
borg/testsuite/helpers.py
borg/testsuite/key.py

Chunk is a namedtuple of (meta, data), create chunks using mkchunk(data, **meta).
This does not yet have any visible functionality, meta is always empty dict right now.

pass meta-data around, fixes #765

---

borg/archiver.py

assuming that there is not more than 1 backup archive made in 1s,
--keep-last N and --keep-secondly N are equivalent.

implement --keep-last N via --keep-secondly N, also --keep-minutely, fixes #537

---

docs/installation.rst

Update installation instructions so that the following error won't occur:
gcc: error: /usr/lib/rpm/redhat/redhat-hardened-cc1: No such file or directory
error: command 'gcc' failed with exit status 1

Fix Fedora installation instructions

---

borg/archiver.py
borg/fuse.py

This fixes performance issues of FUSE mounted archives with programs that do small reads.
An extreme case are the shaXXXsum family of programs which read 32 kB blocks. This leads to chunks being decrypted and decompressed excessively often, the slowdown for these approaches a factor 60. This patch caches partially read chunks in a bounded cache with LRU-eviction (LRUCache), which brings md5sum and the like to the speed of the native "borg list" functionality.

borg mount: cache partially read data chunks

---

docs/deployment.rst

It has more or less the same functionality as the Ansible example, though isn't a line-by-line translation.
It's also tested on a Debian system, but if you want I can rewrite it for Arch; the only real change will be the install lines.

Added Salt example to documentation

---

borg/archive.py
borg/archiver.py
borg/helpers.py
borg/key.py
borg/testsuite/helpers.py
docs/misc/compression.conf

current state:
- --compression-from reads a file with a list compression-spec:matching-pattern that is used to set up CompressionDecider1
- docs/misc/compression.conf example file (currently used to disable compression)
- if no match, compresses like given by --compression
- CompressionDecider2 operates on chunks - it does not do much yet (out of scope of this PR), just either gets the desired compression from Chunk meta or returns the default compression (set by --compression) if there is no meta entry.
- debug log tells filenames and compression
- clean_lines() can be used later to deduplicate similar code at other places
TODO:

Flexible compression - pattern matching on path/filename

---

borg/archiver.py
borg/crypto.pyx
borg/helpers.py
borg/selftest.py
borg/testsuite/__init__.py
borg/testsuite/archiver.py
borg/testsuite/chunker.py
borg/testsuite/conftest.py
borg/testsuite/crypto.py
borg/testsuite/hashindex.py

These run in ~100 ms here, so even on much slower machines (where also
Python setup will be slower) it shouldn't be noticeable at all. (starting Borg takes ~1.5-2 s)
On the QEMU-emulated ppc machine they take ~3.5 s while starting Borg takes ~15 s.
An explicit SELFTEST_COUNT is kept around to make sure that all the tests were properly discovered. With some of the bugs we have been seeing lately I'm starting to become paranoid :D 
~~--debug is maybe a bit too verbose about this. Yeah, let's make it less verbose; that the successful tests were successful and discovered are asserted in other ways.~~ (done)
Check: does it run for every cmd() in the testsuite? if so, patch that out for the testsuite; don't need to waste time in CI/tests.

Add power-on self-test

---

borg/_chunker.c

always use 4 spaces for indenting.

_chunker.c: remove tab characters

---

borg/archiver.py

if giving --prefix resulted in an empty archives_checkpoints list, it crashed with an IndexError.

prune: fix IndexError

---

borg/crypto.pyx

was forgotten there and not used any more since a while.
also removed the hint about PyCrypto being an alternative to crypto.pyx,
it was not updated since 2014, looks pretty stale.

remove openssl RAND_bytes from crypto.pyx

---

borg/testsuite/__init__.py
borg/testsuite/archiver.py
borg/testsuite/key.py

test_symlink_extract doesn't do anything for the coverage, but verifies symlink extraction where there was no test previously.
test_decrypt_integrity tests the various kinds of integrity errors AESKeyBase.decrypt can/should raise; was not covered previously.
These commits are a bit older. Oops.
---
WIP. I'll make this a collective PR for some other tests I want to write. I.e. changeset constrained to borg/testsuite/ _only_.
TODO

decrypt integrity test + some other tests

---

borg/constants.py
borg/helpers.py
borg/platform.py
borg/platform_base.py
borg/platform_darwin.pyx
borg/platform_freebsd.pyx
borg/platform_linux.pyx
borg/repository.py
docs/usage.rst

Note: the original idea in this PR does not work (well it does, but not the way I wanted it ;). ~~Alternatives are being developed.~~ Alternative developed, needs testing.
Also see https://github.com/borgbackup/borg/issues/45#issuecomment-213715080
Summary
Test set:
*  images + XMP metadata (for some folders)
* average file size ~3.5 MB
* 5388 files
* 19.49 GB
```
Throughput     %CPU      total CPU time
1.0.2 / master ........ 24 MB/s ...... 33 % .... 280 s
fastlio none .......... 52 MB/s ...... 62 % .... 237 s
fastlio none64 ........ 54 MB/s ...... 55 % .... 205 s
```
All are I/O-bound, but fastlio is less so. free(1) shows that master branch doesn't
let the kernel use it's buffers (due to fsync after each segment) efficiently, while
fastlio does. Profiling shows that for fastlio fsync() …

Improved LoggedIO write performance

---

borg/archiver.py
docs/usage.rst

Also tell which algos are used and that HW accel is supported.
online manual (`borg xyz --help` and `borg help xxx`) has some other spots. Ha, just collect'em here and get that out for 1.1 as well.

init: move epilogue from docs/usage into help output

---

borg/archiver.py

kill <pid> is now a clean exit instead of a crashit.
Also, don't print a big and scary traceback for KeyboardInterrupts.
SIGTERM exists everywhere, even on Windows.

Handle SIGTERM

---

borg/archive.py
borg/archiver.py
borg/helpers.py
borg/platform.py
borg/platform_base.py
borg/platform_linux.pyx
borg/testsuite/__init__.py
borg/testsuite/archiver.py
borg/testsuite/conftest.py
conftest.py

Another leftover from weeks ago.
This also adds some output in the py.test header about the test platform, we have quite a few possibilities there and it is not immediately obvious.
Implements the popular flags from  #618. Many flags are read-only (informational) or generally not very useful or unsupported. The selection made here is relatively portable and useful. Linux-specific flags should not be ORed into bsdflags.

Translate Linux fsflags to BSD flags and vice versa

---

borg/repository.py
borg/testsuite/repository.py

I have a slightly different fix for master that doesn't destroy performance with larger segments (i.e. put commits in their own segment)
Problem description: is_committed_segment() seeked to the end of a segment file and checked whether there is a COMMIT_TAG there. This can also be the case when a PUT ends with a structure that is a COMMIT_TAG and is thus no valid way to check for the commit state of a segment.
This is a luck-based bug. You'll need to back something up where a chunk ends with a commit tag (another borg repo) and then that has to end up at the end of a segment file and *then* you'll need a kill/crash and *then* you *can theoretically* get an inconsistent repo (with some other conditions applying as well).
Now:
- Early segment magic check by iterator setup in iter_objects
- …

Repository: fix commit tags being seen in data

---

borg/remote.py

RepositoryCache: don't cache large objects

---

borg/archiver.py
borg/helpers.py
borg/logger.py
borg/remote.py
borg/testsuite/archiver.py
borg/testsuite/helpers.py
borg/testsuite/repository.py
docs/changes.rst
docs/development.rst
docs/quickstart.rst
docs/usage.rst

There are persistent questions why --list output doesn't show up, and borg currently isn't able to show *just* the list output.  The solution is to use a more granular child logger, so that list output only goes to the borg.archiver.list child logger.  That logger can then be configured separately from the parent loggers.
The .list child logger can also be used as a hook in a BORG_LOGGING_CONF config file to log the list output to a separate file (this is my main motivation), or send it to a network socket where some daemon could analyze it.
What I did:
- add an accessor to LazyLogger to call the real logger's getChild()
- log --list output using child logger .list
- if --list is passed, change child logger .list (only) to log at INFO level
This is a proof of concept for adding similar …

Print --list output (only) without requiring --info

---

borg/helpers.py
borg/item.py
borg/testsuite/item.py

Item class + tests for now, WIP.
This is just the isolated item class + tests for now.
When this is merged, there needs to be a widespread refactoring to actually use this.

Items refactoring

---

borg/_chunker.c
borg/chunker.pyx
borg/testsuite/archiver.py

please review thoroughly!
cases (before this change):
- A) remaining <= window_size
- would do 2 chunker_fill calls (both line 253) and trigger eof with the 2nd call
- no buzhashing
- result is 1 len(remaining) chunk
- B) window_size < remaining <= min_size:
- the chunker would do 1 chunker_fill call (line 253) that would read the entire remaining file (but not trigger eof yet)
- would compute all possible remaining - window_size + 1 buzhashes, but without a chance for a cut,
because there is also the n < min_size condition
- would do another chunker_fill call (line 282), but not get more data, so loop ends
- result is 1 len(remaining) chunk
- C) file > min_size:
- normal chunking
cases (after this change):
- A) similar to above A), but up to remaining <= min_size,
so it does not buzhash …

chunker: speed up remainder <= min_size case

---

borg/repository.py
borg/testsuite/archiver.py
borg/testsuite/repository.py

Forces commit tags into their own micro-segment, which can be checked
quickly by is_committed_segment
Follow-up to #1052 for master.

Repository: avoid reading large segments for commit state check

---

borg/archiver.py
conftest.py
setup.py

Actually two, but the second one by far eclipses the first :)
With "-k 'not remote'" (<-- a bit overeager matching) it runs in 26 seconds vs. 73 seconds for me. Without any -k (but still with --benchmark-skip) I get 200 seconds vs. 290 seconds. (All numbers without xdist).
(xdist: without benchmark, without remote, they run in ~8 seconds @ 9 processes - and still have good coverage)
While *overall* it doesn't make a large difference for Travis (since a lot of time is spent on installing and compiling stuff):
```
#1818: ============= 532 passed, 142 skipped, 2 xpassed in 382.75 seconds =============
#1820: ============= 532 passed, 142 skipped, 2 xpassed in 298.44 seconds =============
```

Travis workers hate him: improve testing speed with one simple trick

---

borg/platform_linux.pyx

obtain ioctl from sys/ioctl.h as per manpage

---

borg/hashindex.pyx
borg/helpers.py
borg/repository.py
borg/testsuite/repository.py

> And don't swallow all OSErrors when creating archives. We need to work on
> that on a more general level....
[One approach](/enkore/borg/tree/map_internal_oserror) (which I don't particularly like. I think it'd be better to carefully inspect all FS operations and add appropriate error handling - but this could also be a lot of additional code). --- I'll open another ticket for discussion about that issue.

Auto-recover from corrupted index/hints file(s)

---

borg/remote.py
borg/testsuite/repository.py

May fix issue 1081, but that issue is hard to reproduce at will, so I can't be sure.  It does remove some needlessly tricky test code.

Break out remote log and stderr handling code to simplify testing

---

docs/installation.rst

fedora was out of order, EPEL was missing, BSD ports were named weirdly, and openindiana and mageia were missing.
i also changed the warning about borg being too young for being in all distros: it's really *everywhere* now, and the problem will quickly reverse, as the versions from the distros will be out of date from the upstream releases.

update install docs table again

---

setup.py

as the requirement string is a AND operation, I used the rough "<2.0" requirement
and then excluded the non-working versions.

llfuse: update version requirement for freebsd

---

src/borg/platform/base.py

This doesn't avoid "any and all issues", but can limit the damage.
A "backport" (the SyncFile abstraction is new, cherry-picking does not apply) to 1.0-maint makes sense.
Works with sshfs. Linux manpage says it shouldn't work with NFSv3.

SyncFile: open with O_EXCL (or equivalent)

---

borg/archive.py
borg/helpers.py
borg/testsuite/archive.py

we need a list of valid item metadata keys. using a list stored in the repo manifest
is more future-proof than the hardcoded ITEM_KEYS in the source code.
keys that are in union(item_keys_from_repo, item_keys_from_source) are considered valid.
the 2nd changeset uses the valid item keys set (and a new required keys set) to validate item dicts within borg check.

item_keys in manifest, validate item keys

---

docs/usage/create.rst.inc
src/borg/archiver.py
src/borg/helpers.py

Create time is already stored as meta data. Hence, it often makes more sense to use random names that are potentially globally unique. Other names could lead to confusion if different backup systems exist in parallel etc.

Adds uuid to archive format tags

---

deployment/windows/buildwin32.py
deployment/windows/installer.iss
src/borg/helpers.py

Mainly moved all the stdlib .py-files into one zip. (#983)
.dll-files can not be in the zip, moved them in ´bin´. Exe and all necessary dlls in main folder.

Windows: clean up building and installer

---

borg/helpers.py
setup.cfg

We know that star imports have their issues and we only have one of them,
for good reasons. Thus, we switch off that new F405 test/message.

flake8: ignore F405, fixes #1185

---

src/borg/xattr.py

Issue #1111 is caused by the fact that the entire contents of LD_PRELOAD is used for libc_name. When eatmydata is used, LD_PRELOAD looks something like `libfakeroot-sysv.so:libeatmydata.so`, but if any other library instead of libeatmydata was preloaded, it would also cause this issue. Thus LD_PRELOAD should be properly parsed by splitting it on `[ :]` (both of which are valid separators) and iterating over it to find a libfakeroot entry.

Correctly handle multiple LD_PRELOAD entries; fixes #1111

---

borg/crypto.pyx
borg/testsuite/crypto.py
requirements.d/attic.txt
tox.ini

for testing on openssl 1.1 one needs this so it does not try to install attic (which does not work with openssl 1.1):
```
echo "# nope" > requirements.d/attic.txt
```
about the code:
I took it from the crypto-aead PR - I had trouble there with reading back ctx.iv in aes-gcm mode and replaced it by just computing the next iv in our code.

OpenSSL 1.0 and 1.1 compatibility

---

borg/repository.py

Empty index file is most likely a result from an unclean
shutdown in the middle of write, e.g. on ext4 with delayed
allocation enabled (default).
Ignoring such a file would get it recreated by other parts of code,
where as not ignoring it leads to an exception about
not being able to read enough bytes from the index.
Signed-off-by: Oleg Drokin <green@linuxhacker.ru>

Ignore empty index file.

---

docs/usage/list.rst.inc
src/borg/archiver.py
src/borg/helpers.py
src/borg/testsuite/archiver.py

This would give custom formatting when running `borg list /path/to/repo` with `--format`. The current `{keys}` for the formatting are:
- `{name}`: name of the archive
- `{time}`: time of creation of the archive
- `{id}`: the ID of the archive
This would also fix #1166 as weird names can be displayed with the correct formatting, for example:
```bash
$ borg create "/path/to/repo::archive " /files/to/backup
$ borg create "/path/to/repo::archive    " /files/to/backup
$ borg list /path/to/repo
archive                              Tue, 2016-06-14 03:20:01
archive                              Tue, 2016-06-14 03:24:06
$ borg list /path/to/repo --format="{name}/"
archive /archive    /
```
The slash can now be used a seperator as it is not allowed in archive names. This makes the trialing …

Apply --format when listing repository archives, fixes #1166

---

src/borg/item.py

this saves some encoding / decoding dance compared to having a str interface.

use bytes type for ACL attributes, fixes #1205

---

Vagrantfile

machine already has python3.4.
rsync works now.
fuse does not work on openbsd (and breaks borg install, if tried).

Vagrantfile: use openbsd 5.9, fixes #716

---

borg/archive.py
borg/archiver.py
borg/remote.py
borg/testsuite/archive.py

Pulling a thumbdrive during a backup now produces the correct result:
```
File "/home/mabe/Projekte/_oss/borg/borg/archiver.py", line 81, in wrapper
return method(self, args, repository=repository, **kwargs)
File "/home/mabe/Projekte/_oss/borg/borg/archiver.py", line 247, in do_create
create_inner(archive, cache)
File "/home/mabe/Projekte/_oss/borg/borg/archiver.py", line 219, in create_inner
read_special=args.read_special, dry_run=dry_run)
File "/home/mabe/Projekte/_oss/borg/borg/archiver.py", line 275, in _process
status = archive.process_file(path, st, cache, self.ignore_inode)
File "/home/mabe/Projekte/_oss/borg/borg/archive.py", line 594, in process_file
chunks.append(cache.add_chunk(self.key.id_hash(chunk), chunk, self.stats))
File …
```

Fix incorrect propagation of OSErrors in create code

---

src/borg/archiver.py

doing a checkpoint can be expensive, if the repo connection is slow and/or
accessed via a network filesystem and/or the repo is large.
thus: don't do it too often.

increase checkpoint-interval default from 300 to 1800s, fixes #896

---

borg/archiver.py
borg/remote.py
borg/repository.py
borg/testsuite/repository.py
docs/usage.rst

Fixes #1168
Replaces #1229 in which I accidentally committed `.eggs`.

Add --append-only to borg serve (1.0-maint)

---

borg/archiver.py
docs/usage/create.rst.inc
docs/usage/help.rst.inc
docs/usage/prune.rst.inc
docs/usage/serve.rst.inc

This fixes #1247. It also regenerates the usage documentation, so that
styling fixex in that section (as well as other existing changes) make
it into the files in docs/.

Documentation: Explicate that Fnmatch is default

---

borg/archive.py
borg/archiver.py
borg/testsuite/archive.py

Note that this isn't nearly as critical as the other error handling bug,
since nothing is written. So it's "merely" misleading error reporting.
Fixes #1231

Implement fail-safe error handling for borg-extract 

---

docs/usage/create.rst.inc

lzma compression levels above 6 do not increase compression ratio but waste a lot of cpu cycles

Update docs about lzma compression levels above 6

---

borg/testsuite/archiver.py

use the same condition for the input file as also later for the extracted file.
the test preparation sparseness assertion failed on cygwin / ntfs, because the
input file uses ~40MB in blocks vs. total_len ~80MB.

sparse test: fix sparseness assertion in test prep, fixes #1264

---

borg/testsuite/archiver.py

obviously cygwin (windows) does not like the made-up uid 100 gid 200
and raises "invalid argument" OSError.

catch "invalid argument" on cygwin, fixes #257

---

.travis.yml
.travis/install.sh

this is based on PR #1073.
note: uses python 3.5.2 as python 3.5(.0) has no lzma support (on the NON-container ubuntu trusty travis-ci.org infrastructure)

Travis using ubuntu trusty

---

borg/archive.py

if we do not lose the original chunk ids list when "repairing" a file (replacing missing
chunks with all-zero chunks), we have a chance to heal the file back into its original
state later, in case the chunks re-appear (e.g. in a fresh backup).
this prepares for #148, so we do not lose information until that is implemented.

repair: remember the good chunks

---

borg/fuse.py

The problem was that OS X Finder queried some OS X specific xattrs
and if they were not present, the wrong errno (ENODATA) was included
in the raised FUSEError exception. According to the llfuse docs, the
errno must be ENOATTR for this case.
Obviously, Finder didn't handle this well and denied access to the
file. Also, file size was displayed as "zero bytes" although we
return the correct value.

fuse: getxattr fail must use errno.ENOATTR, fixes #1126

---

docs/installation.rst

cython is installed with pip later.
liblz4 is available from normal cygwin packages now.
creation of virtualenv worked now without issues.

update cygwin installation docs

---

Vagrantfile

it even breaks the whole build / installation.

do not install llfuse on netbsd (broken)

---

borg/platform.py

Some network filesystems don't support this.
Fixes #1287

sync_dir: silence fsync() failing with EINVAL

---

borg/_hashindex.c
borg/hashindex.pyx

hashindex_set may resize the hashtable, failing to recognize the return code

Fix missing return code check in ChunkIndex._add

---

borg/testsuite/archiver.py

this is not pretty, but I couldn't precisely find out the failure reason, but there is strong evidence that this is not a real bug in borg, but some side-effect of fakeroot usage.
silencing these always failing tests makes vagrant testing easier as "all succeeding" tests is easier to check than having always to check the same 3 failing tests.

binary test issues

---

README.rst
docs/api.rst
docs/deployment.rst
docs/development.rst
docs/faq.rst
docs/installation.rst
docs/internals.rst
docs/quickstart.rst
docs/usage.rst

default is "python", that's why some help fragments and bash scripts looked strange.

docs: fix the highlighting

---

.gitignore

These files are generated during the execution of `tox` and are cleaned up if not interrupted with Ctrl+C.

gitignore .coverage.*

---

src/borg/testsuite/platform.py

Not too much too it. Allows running tests with `sudo tox` instead of vagrant or `fakeroot -u tox`. Resolves #1361.

Allow running tests outside of Vagrant

---

docs/quickstart.rst

continues from chat in IRC
for quick reference, here's a direct link to this branch's rendered view (github-rendered): https://github.com/jzacsh/borg/blob/document-envvars-pitfalls/docs/quickstart.rst#pitfalls-with-shell-variables-and-environment-variables

doc: quickstart on shell pitfalls for env. vars

---

docs/quickstart.rst
src/borg/_hashindex.c
src/borg/hashindex.pyx
src/borg/helpers.py
src/borg/repository.py
src/borg/testsuite/hashindex.py
src/borg/testsuite/helpers.py
src/borg/testsuite/repository.py

A failed check looks like this:
> Insufficient free space to complete transaction (required: 1.10 TB, available: 47.58 GB).
> zsh: exit 2     borg create ...
Also logs some --debug output:
> check_free_space: required bytes 26549600, free bytes 47584997376
(in this case: 5 MiB + 20 MiB + 4× some dozen KiB index size)
The check uses f_bavail, which does *not* include root's block reserve. Therefore the block reserve is not written full, even when running as root (yay). For the same reason additional_free_space is around. It can also be used to defeat the check (with a negative value) in desperate situations.
Fixes #1272 #1273

Check free space before committing

---

src/borg/cache.py
src/borg/key.py
src/borg/platform/__init__.py
src/borg/platform/base.py
src/borg/platform/linux.pyx
src/borg/repository.py

Renders the issues [described here](https://github.com/borgbackup/borg/issues/1060#issuecomment-229622961) unreproducible for me. Naturally the transaction may be a bit botched and needs recovery (e.g. "hints.tmp", index missing etc), but since the segments are solid so is the transaction.
Fixes #1060

Use atomic file writing and updating for configuration and key files

---

borg/remote.py

This fixes the cosmetic issue that the cleanup happened in `__del__` and caused an AssertionError there.

RemoteRepository init: always call close on exceptions, fixes #1370

---

borg/cache.py
docs/faq.rst
docs/usage.rst

raise default ttl to 20 (previously: 10).
fixes #1338 and #1391.

implement BORG_FILES_CACHE_TTL, update FAQ

---

src/borg/archive.py
src/borg/archiver.py
src/borg/testsuite/archive.py
src/borg/testsuite/archiver.py

fixes #1326 
there is currently a bit overlap:
borg info archive: archive info +  archive stats + repo stats
borg info repo: repo stats only
So, remove repo stats from "borg info ARCHIVE"?

borg info REPO

---

conftest.py
src/borg/archive.py
src/borg/testsuite/__init__.py
src/borg/testsuite/archiver.py
src/borg/testsuite/platform.py
src/borg/testsuite/upgrader.py

So much for the easy tag on #1362.
Resolves all of #1362, and the ACL part of #1363. The rest of ntfs-3g will be fixed using an env variable as described [here](https://github.com/borgbackup/borg/issues/1362#issuecomment-234728068) (will be done in a separate PR).
The only non-testing change here is a try-catch around `os.utime`, as that throws an OSError on SSHFS when used on a symlink. However, if the utime block fails, it's not a big deal and we're fine to just skip over the issue.

Filesystem feature detection and test skipping

---

docs/development.rst

real story: users that are also developpers expect to find out where to submit issues and pull requests in the development section, but couldn't. add some meat there and point to the support section for everything else.

mention where code, issues and support is

---

Vagrantfile

Note: "FUSE for OS X" was renamed to "FUSE for macOS".

Vagrantfile: use FUSE for macOS 3.4.1

---

borg/archiver.py
borg/cache.py
borg/locking.py
borg/remote.py
borg/repository.py
borg/testsuite/archiver.py
borg/testsuite/locking.py
borg/testsuite/repository.py
borg/testsuite/upgrader.py
borg/upgrader.py

see #1220 + commit comments.
The deadlock is fixed already.
But: needed a RPC API change to add the exclusive param. :-(
Also: Thinking about whether we maybe rather want a safe default for exclusive.
Currently it is usually False and you need to give exclusive=True - guess the opposite way would be safer, so one does not forget requesting an exclusive lock.
Nothing really bad would happen if one forgets though, the code has an automatic lock upgrade to an exclusive lock.
The lock upgrade/downgrade code was kept to support old clients.
Current code shall not use it, it is deprecated.

fix deadlock

---

borg/repository.py
borg/testsuite/repository.py
docs/changes.rst

we will not get() objects that have a segment entry larger than MAX_OBJECT_SIZE.
thus we should never produce such entries.
also: introduce repository.MAX_DATA_SIZE that gives the max payload size.

repo: do not put objects that we won't get, fixes #1451

---

borg/archiver.py
borg/compress.pyx
borg/helpers.py
borg/key.py
borg/testsuite/compress.py

the statically allocated COMPR_BUFFER was right size for chunks,
but not for the archive item which could get larger if you have
many millions of files/dirs.

LZ4: dynamically enlarge the (de)compression buffer, fixes #1453

---

src/borg/archive.py
src/borg/archiver.py
src/borg/helpers.py
src/borg/logger.py

- --debug-topic sets any logger to DEBUG level, has predefined shortcuts
- Silences some very verbose debug information by default (e.g. which compression for what file)
- Some minor refactors
- borg-extract gains --progress

Debugging topics and some other minor stuff

---

borg/archive.py

increasing the mask (target chunk size) from 14 (16kiB) to 17 (128kiB).
this should reduce the amount of item metadata chunks an archive has to reference to 1/8.
this does not completely fix #1452, but at least enables a 8x larger item metadata stream.

larger item metadata stream chunks, fixes #1452

---

borg/repository.py

an acd_cli (amazon cloud drive fuse filesystem) user had "borg init" crash in the line below.
by adding the assertion we tell that we do not expect the transaction_id to be None there,
so it is easier to differentiate from a random coding error.

add transaction_id assertion

---

borg/helpers.py
borg/testsuite/helpers.py

Fixes #1467 
Warning: The repository at location /... was previously located at /somewherelese
Do you want to continue? [yN] yes (from BORG_RELOCATED_REPO_ACCESS_IS_OK)
Previously:
Warning: The repository at location /... was previously located at /somewherelese
Do you want to continue? [yN]
*(is that doing something?)*

Print active env var override by default

---

borg/testsuite/xattr.py
borg/xattr.py
docs/changes.rst

this also fixes the race condition seen in #1462 because there is only 1 call now.
either it succeeds, then we get the correct length as result and truncate the result value to that length.
or it fails with ERANGE, then we grow the buffer to double size and repeat.
or it fails with some other error, then we throw OSError.

xattr: dynamically grow result buffer until it fits, fixes #1462

---

borg/repository.py
borg/testsuite/repository.py

Fixes #1442
(note that the segments _still_ get generated, see the comment, they
should be collected now on the next compaction run)

Fix untracked segments made by moved DELETEs

---

borg/testsuite/archiver.py

GNU Hurd needs to fix their O_NOATIME, after that we can
re-enable the test on that platform.
They already know, see link in the src.

skip the O_NOATIME test on GNU Hurd, fixes #1315

---

borg/archiver.py

In tracebacks we have it already, but with the command,
you can have it without a traceback also.

implement borg debug-info, fixes #1122

---

src/borg/repository.py
src/borg/testsuite/repository.py

Fixes #1396 
Note that for append-only repos with unmaterialized DELETEs this makes it behave a bit like #1442 when compaction is run (non-append-only), ie. the unmaterialized DELETEs won't really go away, because they're not in the index. Reinforcing the suggestion to do pruning without append-only.

Track shadowing of log entries

---

Vagrantfile
src/borg/remote.py

fixes #1416, see also: https://github.com/pyinstaller/pyinstaller/pull/2148
also: use waf --no-lsb (the bootloader does not build without it on our wheezy vagrant VM)
This fixes the fakeroot issues, when fakeroot can't find its libs.
Also it fixes a lot of tests that get disturbed by the stderr message fakeroot emits due to that.

use patched LDLP-preserving pyinstaller

---

docs/internals.rst

PR #1509 applied to 1.0-maint.

internals.rst: fix typos

---

src/borg/archiver.py
src/borg/remote.py

archiver: split traceback and msg, have separate log level for traceback, log LockTimeout at debug level, for "Error" exceptions: always log the traceback, either at ERROR or DEBUG level.
remote: if we have an "Error" typed exception instance, we can use its traceback flag and .get_message() as we do locally.

improve error logging, fixes #1440

---

borg/testsuite/archiver.py

at some time they had deadlock issues, but it worked for me now.

re-enable fuse tests for RemoteArchiver

---

docs/borg_theme/css/borg.css

This changes the border-color of the search to match with the background-color.

Addjust border color

---

borg/remote.py

While checking if my ssh forced command worked i started an ssh session to the backup server manually and got the following stacktrace:
```
$ echo -n | borg serve
$LOG ERROR borg.archiver Remote: Local Exception.
File "/home/martin/sw-dev/borg/src/borg/archiver.py", line 2395, in main
exit_code = archiver.run(args)
File "/home/martin/sw-dev/borg/src/borg/archiver.py", line 2328, in run
return args.func(args)
File "/home/martin/sw-dev/borg/src/borg/archiver.py", line 175, in do_serve
return RepositoryServer(restrict_to_paths=args.restrict_to_paths, append_only=args.append_only).serve()
File "/home/martin/sw-dev/borg/src/borg/remote.py", line 91, in serve
self.repository.close()
AttributeError: 'NoneType' object has no attribute 'close'
Platform: Linux …
```

borg serve throws exception while trying to close when it gets eof at start

---

src/borg/archive.py
src/borg/archiver.py
src/borg/item.py
src/borg/testsuite/archiver.py

extract: When doing a partial restore don't leak prefetched chunks.
The filter function passed to iter_items (with preload=True) may never return True for items that
are not really extracted later because that would leak prefetched items.
For restoring hard linked files the item containing the actual chunks might not be matched
or implicitly removed from the restore by strip_components. For this reason the chunk list or all
items that can potentially be used as hardlink target needs to be stored.
To achive both requirements at the same time the filter function needs to store the needed information
for the hardlinks while not returning True just because it could be a hardlink target.
Also contains fixes by encore to fix miscalculation of progress wrt hardlinks and reduces memory usage  by …

extract: When doing a partial restore don't leak prefetched chunks.

---

src/borg/archiver.py
src/borg/helpers.py

Instead of
```
Calculating Size
Extracting files xx %
```
now
(short) `Calculating Size`, then `Extracting files xx %` in the same line, if no other output was requested, then after successful completion the output collapses completely ie.
```
$ borg extract ...
$
```

ProgressIndicatorPercent / extract minor cosmetic enhancement

---

src/borg/helpers.py
src/borg/key.py
src/borg/nonces.py
src/borg/remote.py
src/borg/repository.py
src/borg/testsuite/archiver.py
src/borg/testsuite/helpers.py
src/borg/testsuite/key.py
src/borg/testsuite/nonces.py
src/borg/testsuite/repository.py

Questions:
Reserve nonce space for AES-CTR before using it.
Reusing the nonce totally breaks AES-CTR confidentiality.
This code uses a reservation of nonce space and stores the next nonce available for
a future reservation on the client and in the repository.
Local storage is needed to protect about evil repositories that try to gain access to
encrypted data by not saving nonce reservations and aborting the connection or otherwise
forcing a rollback.
Storage in the repository is needed to protect against another client writing to the
repository after a transaction was aborted and thus not seeing the last used nonce from
the manifest.
With a real counter mode cipher protection for the multiple client case with an actively 
evil repository is not possible. But this still protects against …

Fix AES-CTR nonce reusage

---

README.rst

Fix second block in "Easy to use" section not showing on GitHub

---

borg/archive.py
borg/archiver.py
borg/testsuite/archiver.py

also correctly processes broken symlinks. before this regressed to a crash
(5b45385) a broken symlink would've been skipped.
Fixes #1584

create --read-special fix crash on broken symlink

---

borg/archive.py
borg/hashindex.pyx
borg/testsuite/hashindex.py

hashindex: export max load factor to Python-space

---

Vagrantfile

... until pyinstaller team catches up, merges the fixes and recompiles the bootloader.

Vagrantfile: use TW's fresh-bootloader branch

---

docs/faq.rst

The script in the FAQ is named pv-wrapper. But in the variable export pv-wrapper.sh was used.

Fix inconsistency in FAQ

---

src/borg/archiver.py
src/borg/remote.py
src/borg/testsuite/remote.py

The --remote-ratelimit option adds a very simple rate limit for the
sending data to the remote.
Currently implemented by sleeping if the transmission speed is greater
than the limit.

Add --remote-ratelimit

---

borg/helpers.py

when screen width was too narrow, the {space} placeholder could get negative,
which crashes as it is a width specification.
now we simplify progress output if screen is narrow.
we stop output completely if screen is ridiculously narrow.

adapt formatting to narrow screens, do not crash, fixes #1628

---

src/borg/archiver.py
src/borg/helpers.py
src/borg/testsuite/helpers.py

This changes both `{now}` and `utcnow` to use the ISO-8601 format with the default `T` separator.
Example:
2016-09-22T11:11:43
Closes #1606

Change {utcnow} and {now} to ISO-8601 format

---

borg/archiver.py
borg/keymanager.py
borg/testsuite/archiver.py

We recommed that users backup their keys, this adds simple to use commands
to do so.
Supported formats are the keyfile format used by borg internally and
a special format with by line checksums for printed backups.
For this format the import is an interactive process which checks
each line as soon as it is input.
Fixes #1555

Implement key import / export

---

docs/development.rst

It’s used by default, so install it as well.

development.rst: Add sphinx_rtd_theme to the sphinx install command

---

borg/archiver.py
borg/cache.py
borg/helpers.py
borg/key.py

except for the passphrase display as we can only display it as long as we have it in memory,
here: retry, telling the user if he entered something invalid and needs to enter again.

yes(): abort on wrong answers, saying so

---

borg/archiver.py
borg/keymanager.py
borg/testsuite/archiver.py
setup.py

This moves the key-export and key-import commands to subcommands of the key command.
For the existing debug-* commands it adds a debug command with subcommands but doesn‘t remove the debug-* commands. This should be done later for 1.1.

Use subcommands for debug-* and key-*

---

setup.py

The original code meant to skip processing commands with subcommands as notmal commands. But instead it also skipped all other commands with the same parent. As the order of commands is not static this build a different subset of documentation includes each time.

setup.py: Fix build_usage to always process all commands.

---

borg/hashindex.pyx
borg/testsuite/hashindex.py

NSKeyIterator and ChunkKeyIterator raised StopIteration once only when they reached their end.
But they did not raise StopIteration if one called next() again after they were exhausted,
so they did not comply to the standard iterator protocol.
AFAIK, this did not cause actual problems due to the way these iterators are used,
but when I tried to use itertools.islice() to get n-long sequences from these iterators,
it failed / went into an endless loop.

hashindex: fix iterator implementation

---

borg/hashindex.pyx
borg/helpers.py

API_VERSION is used to check whether the compiled binaries are up-to-date.
the tests for the recent iterator fixes of course need updated (fixed) binaries,
so we bump api_version, so not-up-to-date binaries will get identified.

Hashindex api version bump

---

src/borg/archiver.py
src/borg/helpers.py
src/borg/testsuite/archiver.py

follow-up of #1369
this adds the arguments `--first`, `--last` and `--sort-by`, and groups them with `--prefix` as archives filters that can be applied on repository targets.
usable with `check`, `delete`, `info` and `list`.
use-case in a script:
```bash
while used_space_exceeds_pcent; do
log 'Used space exceeds ${MAX_DISK_USAGE}%, deleting oldest backup archive.'
borg delete --first 1 --force $BORG_REPOSITORY & wait
done
```

Archives filters

---

src/borg/hashindex.pyx
src/borg/helpers.py

note:
merging the respective changeset from 1.0-maint was not effective
as we already had version 3, so there was no increase.

hashindex: bump api_version

---

Vagrantfile
scripts/borg.exe.spec

also: exclude osxfuse dylib on Mac OS X

pyinstaller: use a spec file to build borg.exe binary

---

src/borg/archiver.py
src/borg/key.py

```
Repository ID: 6cb322e51621ca7a805692788869fb0cf1556cc250d73b4274cd1dd96fb973ad
Encrypted: Yes (key file)
Key file: /home/mabe/.config/borg/keys/tr_keyfile
Cache: /home/mabe/.cache/borg/6cb322e51621ca7a805692788869fb0cf1556cc250d73b4274cd1dd96fb973ad
------------------------------------------------------------------------------
Original size      Compressed size    Deduplicated size
All archives:                    0 B                  0 B                  0 B
Unique chunks         Total chunks
Chunk index:                       0                    0
```
I think this covers the most important questions:
- What's the repo ID
- Where is that cache
- Where is the key file I need to back up
- Is this stuff even encrypted?
Another interesting question would be "how large is the cache", …

borg info <repo>: print general repo information

---

src/borg/archiver.py
src/borg/platform/__init__.py
src/borg/platform/windows.pyx

Backup and extract Windows alternate data steams (#1342 #983 )
ADS are saved as separate items and extracted as such on non-windows.

Windows: alternate data steams

---

src/borg/archive.py
src/borg/remote.py
src/borg/repository.py
src/borg/testsuite/repository.py

Issue #1610.
I kept repo.list as is and just added a new method repo.scan.

WIP: repo.scan - list keys in disk-order

---

borg/helpers.py

So that the message we give appears not only in the traceback, but also in the (short) error message.

IntegrityError: add placeholder for message, fixes #1572

---

src/borg/remote.py

The preloading code pretends to be more general than it is (and is used)
This clarifies what the code can actually do. It also decouples the cache data structure from rpc protocol details opening the way to use something else than tuples as rpc argument encoding.
scaled back version that only changes indexing of the cache and makes sure preload is only used with 'get' method.

Cleanup prefetch code in RemoteRepository

---

borg/cache.py

fixes #1524
before, if a longer backup got interrupted before commit(),
it asked same question again.

update changed repo location immediately after acceptance

---

docs/usage.rst
src/borg/archive.py
src/borg/archiver.py
src/borg/testsuite/archiver.py

we use "debug xxx" subcommands now. docs updated.
also makes "borg help" shorter as not all debug-xxx commands
show up, but just 1 main "debug" command.

remove debug-xxx commands, fixes #1627

---

borg/helpers.py
borg/testsuite/helpers.py

also:
- refactor / deduplicate the location parsing regexes
- add comments
- add more tests for Location parsing
https://regex101.com/ <- useful for testing semi-manually

allow pathes with colons, fixes #1705

---

borg/testsuite/__init__.py
borg/testsuite/archiver.py

not just the -o mount_options, but any options borg mount would take.
simpler, more flexible.
Applying against 1.0-maint to keep the tests better in sync.

fuse_mount contextmanager: accept any options

---

conftest.py
src/borg/testsuite/helpers.py
src/borg/testsuite/key.py
src/borg/testsuite/nonces.py

otherwise it spoils the user's nonces and cache dirs with lots of files.
also: remove all BORG_* env vars from the outer environment
TODO: check whether some of this should be applied to 1.0-maint first.

point XDG_*_HOME to temp dirs for tests, fixes #1714

---

Vagrantfile

self-made basic netbsd box includes pre-installed rsync as vagrant is unable to install rsync.
delete line from tox.ini with sed so it does not try to install llfuse (which is broken on netbsd).

vagrant / netbsd: use own box, fixes #1671, fixes #1728

---

Vagrantfile

it tries to do chown -R vagrant.vagrant, but some boxes do not
have a vagrant group and break there. also, we do our own chown
in the provisioning scripts.

vagrant: no chown when rsyncing

---

borg/testsuite/__init__.py
borg/testsuite/archiver.py

they fail the FUSE tests on centos7.

ignore security.selinux xattrs, fixes #1735

---

docs/deployment.rst

This PR is filed to the `1.0-maint` branch, as requested in #1757.

docs/deployment.rst: do not use bare variables in ansible snippet

---

borg/cache.py

due to the changed canonicalization for relative pathes in PR #1711 (implement /./ relpath hack),
there would be a changed repo location warning and the user would be asked if this is ok.
this would break automation and require manual intervention, which is unwanted.
thus, we introduce a new cache config version and when automatically upgrading to this
new version, we also fix the previous_location config entry, if it only changed in the
expected way, but still means the same location.

avoid previous_location mismatch, fixes #1741

---

borg/remote.py

Cherry-pick commit 731f6241faa254c379a9bc25dd21133d3604d32a from master to fix issue #940 in 1.0-maint.

RemoteRepository: Fix busy wait in call_many, fixes #940

---

docs/quickstart.rst
docs/usage.rst

We only mentioned the remote repo URL format in quickstart, there was nothing in the "usage" (reference) section.

repo url / archive location docs + typo fix

---

Vagrantfile

EdgeOnWindows10 is an official Microsoft Image with Microsoft Edge configured as the default browser. See [official](https://atlas.hashicorp.com/Microsoft/boxes/EdgeOnWindows10) vagrant image page.
Requirements:
`vagrant-reload` plugin.
Usage:
- Initial `vagrant up` command fails because of missing `/vagrant/borg/` path.
- Run `vagrant provision` after that, it will automatically install required packages and synchronize folders.
Caveats:
- ~~I was not able to make it working with [x86_64 cygwin version](https://www.cygwin.com/setup-x86_64.exe)~~ Works both for x86_64/x86. X86_84 is by default - see https://www.cygwin.com/faq.html section **4.45. How do I fix fork() failures?** why x86_64 is preferred
- One has to enter password when required
- `llfuse` python module is not available on …

add windows virtual machine

---

borg/testsuite/archiver.py

otherwise the "input" dir is root.wheel -rwx------ and gives a PermissionError when trying to access it.

vagrant: fix fuse test for darwin, fixes #1546

---

docs/quickstart.rst

move the note about free space after the step by step example. it is
unlikely that users will hit out of space conditions on their first
run, and at the end of the example, they will see the not anyways.
this is to make the documentation less scary for new users and easier
to use.

faster quickstart

---

README.rst
docs/faq.rst

it seems now that the fork is more of historical value than a current
thing. people interested in the differences between borg and attic can
look in the FAQ, but I do not see why this is present in the README.
a new section regarding compatibility is created to keep that warning
in place.

move fork differences to FAQ

---

README.rst
docs/book.rst
docs/conf.py
docs/index.rst
docs/introduction.rst

the changes here add a logo to the PDF document, use a more readable font (12 instead of 10pt), make URLs work and unbreak the table of contents of the PDF docs.
this is a reroll of #1796 against 1.0-maint.

improvements to the PDF version of the documentation

---

README.rst
docs/faq.rst
docs/installation.rst
docs/support.rst

the rationale is to simplify the README file to the bare
minimum. security researchers will be able to find the contact
information if they look minimally and people installing the software
will find a link where relevant (in binary releases only, since all
the others have other trust paths)
reroll of #1798 against 1.0-maint

move security verification to support section

---

AUTHORS
docs/authors.rst
docs/book.rst
docs/faq.rst

as agreed on IRC:
```
21:05:45 <ThomasWaldmann> anarcat: about the toc in the pdf:
21:06:04 <ThomasWaldmann> the x.y.z level in usage seems unwanted
21:06:49 <ThomasWaldmann> same for changelog (attic versions)
21:07:03 <anarcat> right, we could stick that to 2 levels
21:07:09 <anarcat> there's also a level error in the FAQ
21:07:57 <ThomasWaldmann> in "borg collective" it seems strange that 2nd and 3rd level only talks about attic
21:08:11 <ThomasWaldmann> so guess there is a borg headline missing
21:08:31 <ThomasWaldmann> also could drop 3rd level
21:08:38 <anarcat> ThomasWaldmann: maybe that should be just "Authors"
21:08:43 <anarcat> or "Credits"
21:09:18 <anarcat> i'll whip up something
21:09:39 <ThomasWaldmann> yes 12 Authors, 12.1 Borg Authors ("The Borg Collective") 12.2 Attic …
```

fix more issues with the PDF

---

borg/testsuite/archiver.py
borg/testsuite/repository.py

remote is broken and hangs infinitely on cygwin.
https://github.com/borgbackup/borg/issues/1268

skip remote tests on cygwin

---

src/borg/cache.py
src/borg/helpers.py
src/borg/locking.py
src/borg/platform/__init__.py
src/borg/platform/base.py
src/borg/platform/darwin.pyx
src/borg/platform/freebsd.pyx
src/borg/platform/linux.pyx
src/borg/platform/posix.pyx
src/borg/remote.py
src/borg/repository.py
src/borg/testsuite/locking.py
src/borg/testsuite/platform.py

Supersedes #1246
Fixes #562 
Edit [travis #3000](https://travis-ci.org/borgbackup/borg/builds/164401648) :)

Automatically remove stale locks

---

.gitattributes

Some tools like gitk need this for sensible word diffs.

.gitattributes: Set python diff mode for all *.py files.

---

src/borg/repository.py

The rollback‘s cleanup parameter should not be exposed externally, esp. not via rpc.
Thus remove cleanup from public rollback method and have that one call a internal version that allows finer control and is used internally in Repository when needed.

Repository: rollback's cleanup parameter is internal.

---

borg/archiver.py

In the online help, explain that archives with different contents need to be
separated via the prefix when pruning to achieve a desired retention policy per
archive set.
Relates to #1824.

Clarify prune behavior for different archive contents

---

docs/global.rst.inc
docs/installation.rst
docs/usage.rst
scripts/py36-blake2.py
setup.py
src/borg/archiver.py
src/borg/blake2-libselect.h
src/borg/blake2/COPYING
src/borg/blake2/README.md
src/borg/blake2/blake2-impl.h
src/borg/blake2/blake2.h
src/borg/blake2/blake2b-ref.c
src/borg/crypto.pyx
src/borg/key.py
src/borg/selftest.py
src/borg/testsuite/crypto.py
src/borg/testsuite/key.py

The BLAKE2b implementation is triple licensed under the CC0, OpenSSL and Apache 2.0 licenses, all of which are compatible with our BSD 3 clause.
The BLAKE2b implementation files are copied verbatim from git sha1 https://github.com/BLAKE2/BLAKE2/commit/d4418edab4b9e7595973f876f82d9fecf54b9d19 , completely unmodified to make maintenance as easy as possible.
This actually adds very little new code, since almost everything is reused. Note that the encrypt/decrypt code in AuthenticatedKey is copied from PlaintextKey (enc_key, mac_key are unused but still there, no harm done).
#1034 does not apply perfectly cleanly, but all merge conflicts are the simple kind (import lines in two files, one hunk in the crypto tests where git makes up a conflict where both branches added separate tests, the …

Add BLAKE2b key types

---

src/borg/archiver.py

A small merge mishap in 2a864be8; 1.0-maint has it correctly.

debug, key: enable --help

---

conftest.py

Fixes #1801 
Cherry pick of 4f1157c into 1.0-maint due to f3efcdb
TODO removed since we already did that after 1.0-maint, but 1.0-maint
will never receive the change.

Fix tox/pybuild in 1.0-maint

---

borg/archive.py
borg/repository.py
borg/testsuite/archiver.py

64a3fa8: no segments, no index. (or no committed segments and no index, if we'd have no committed segments but an index we can usually recover, the stick-a-commit-on-it technique).
2261709: no objects
Fixes #1815

check: catch two kinds of different repos

---

borg/archive.py
borg/testsuite/archiver.py

Fix check incorrectly reporting attic 0.13 and earlier archives as corrupt

---

src/borg/archive.py
src/borg/archiver.py
src/borg/helpers.py
src/borg/testsuite/archiver.py
src/borg/testsuite/helpers.py

This changes the extract progress output to include the current file being extracted.
```bash
$ borg extract rep::archive -p
42.0% Extracting: /answer/to/life/...verse/and/everything
```
This is made possible by making `ProgressIndicator` more flexible, it can take as many arguments for it's message format.
As suggested in #1721.

Improve extract progress display, for #1721

---

setup.py
src/borg/helpers.py
src/borg/platform/base.py
tox.ini

our setup.py seems to trigger a false positive in flake8, so apart from applying one fix I also excluded it for now.
```
setup.py:143:1: E305 expected 2 blank lines after class or function definition, found 0
138 
139 
140 include_dirs = []
141 library_dirs = []
142 define_macros = []
143 crypto_libraries = ['crypto']
144 
145 possible_openssl_prefixes = ['/usr', '/usr/local', '/usr/local/opt/openssl', '/usr/local/ssl', '/usr/local/openssl',
146                              '/usr/local/borg', '/opt/local', '/opt/pkg', ]
```

fixes for flake 3.1.1

---

src/borg/archiver.py
src/borg/remote.py
src/borg/repository.py
src/borg/testsuite/repository.py
src/borg/version.py

The current RPC model does not allow to add new parameters to methods without compatibility hacks.
This introduces a new RPC protocol based on named parameters. The clients still starts with the RPC protocol used since 0.29.0 and only upgrades to the new protocol when the server supports it. When in the future this compatibility is no longer needed this use of the old protocol can be removed while still beeing compatible with all versions containing this PR (this can be done by settings RemoteRepository.dictFormat = True in the constructor)
The amount of compatibility code for the old protocol is fairly small. Consisting of a dict which for each method describes the order of the positional arguments in the old protocol, 2 methods 4 lines long each for argument format conversation and 7 if …

RFC: Make rpc protocol more extensible

---

borg/archiver.py
borg/helpers.py
borg/platform.py
borg/platform_darwin.pyx
borg/platform_freebsd.pyx
borg/platform_linux.pyx
borg/testsuite/__init__.py
docs/usage.rst
docs/usage/umount.rst.inc

this refactors umount code we already used for the testsuite into the platform module's namespace.
also, it exposes that functionality via the cli api, so users can use it via "borg umount <mountpoint>",
which is more consistent than using borg to mount and fusermount -u (or umount) to un-mount.

borg umount, fixes #1855

---

README.rst
setup.py

I have discovered that PyPI is way more sensitive to RST warnings than
other platforms: warnings and errors will make the document not show
up correctly, which is currently the case here:
https://pypi.python.org/pypi/borgbackup/
the suggested changes remove Sphinx-specific markup from the output,
namely the badges and `|replacement|` patterns, but also the
`higlight` directive. this also requires adding tags to the README to
mark the badges to remove and removal of the `none` argument for the
`.. code-block::` element which was not having any significant in
Sphinx anyways.

display README correctly on PyPI

---

src/borg/testsuite/archiver.py

they are not there any more in the base class, so there is nothing to override.
@enkore ^^^

remove some unneeded test overriding methods

---

src/borg/cache.py
src/borg/helpers.py

I'm not sure if this is the correct implementation, or if that's really what you want, so I'm waiting for feedback.
Since compact_segments shows progress even if the `-p` argument is not active, I wasn't sure if this was intentional, so commit progress will also be shown even if `-p` isn't active.
This is for #1721

Add progress display for cache commit

---

docs/quickstart.rst

I'm still hoping that a destination switch can be added (requested long ago in https://github.com/jborg/attic/issues/195), but in the meantime this may help. I'm guessing this clobbers any existing files.

Clarify extract is relative to current directory

---

docs/usage.rst
src/borg/archiver.py
src/borg/cache.py
src/borg/helpers.py
src/borg/nonces.py
src/borg/testsuite/archiver.py
src/borg/testsuite/helpers.py
src/borg/testsuite/key.py
src/borg/testsuite/nonces.py

Since BORG_NONCES_DIR was only part of beta releases so far I'd say we need no migration in borg itself but can just provide a shell snippet in the changelog that moves the files.

Rename BORG_NONCES_DIR to BORG_SECURITY_DIR and then some

---

borg/testsuite/helpers.py

make sure the BORG_(CACHE|KEYS)_DIR env var is not set initially.

test_get_(cache|keys)_dir: clean env state, fixes #1897

---

.travis/install.sh
requirements.d/development.txt

Is needed only for python 3.2 support.
For normal development, we expect you have py34+ for borg 1.1.
For vagrant, it is still needed because of older VMs like wheezy (py32).
Not needed for Travis-CI any more, we moved to trusty VMs (py34) there.

partially remove virtualenv/pip version requirement, fixes #1738

---

src/borg/archive.py
src/borg/archiver.py
src/borg/testsuite/archiver.py

Fixes #1920 #1919 #1913
#1920 was introduced in 93b03ea2310. Previously the function always returned an iterator (a3ee9d2c). In 93b03ea I rewrote it to *be* the iterator, without also modifying the second code path to conform. This was not noticed because the test for this code path was broken, and because I did not take a closer look at the resulting archives during manual testing. Just using `recreate ... --stats` would have already shown that something was amiss.
#1919 was overlooked when removing the signal processing stuff. Archiver.do_recreate used the return value to exit should a signal be received; these returns where removed, but the if in do_recreate was not updated.

recreate fixes

---

setup.py
src/borg/archive.py
src/borg/archiver.py
src/borg/cache.py
src/borg/helpers.py
src/borg/item.pyx
src/borg/key.py
src/borg/testsuite/archive.py
src/borg/testsuite/helpers.py
src/borg/testsuite/item.py

I tested this mostly on a very artificial test case: no data at all in the files, but many files and deep directory structures. So comparisons put a spotlight on how fast Borg processes metadata and ex-aggregates per-file overheads.
There are four changes:
1. Compile borg.item with Cython. Item.update is a very hot function that is called multiple times per file and tends to take a couple percent overall runtime even in more realistic conditions.
I suspect the slightly increased maintenance burden (have to recompile after code change) is mostly irrelevant, since the file is edited rarely.
2. Skip data IO to empty files entirely - arguably a special case appealing this synthetic benchmark (to great effect). The practical impact of this change will be rather negligible. It might be more …

Work on metadata handling speed

---

borg/archiver.py

the problem was that there neither was a do_debug implementation for the case someone just enters "borg debug", nor did the parser inherit from common_parser (so accessing .umask triggered an exception before setup_logging() was called, which triggered another exception when log output should have been emitted).

add a borg debug/key dummy command, fixes #1932

---

conftest.py

do not rewrite the borg application code, just the test code,
so the bytecode tested is identical / very close to the bytecode used in practice.
@RonnyPfannschmidt ^^
Hopefully it's better now, it was a bit unclear to me what you actually meant by "test helpers".
note: testsuite.helpers are not test helpers, but the tests for borg.helpers.

pytest: only rewrite the testsuite, fixes #1938

---

src/borg/archive.py
src/borg/archiver.py

on the one hand one can say it's ugly global state, on the other it's
totally handy!
just have to keep that in mind for MT, but it's rather obvious.

mention failed operation in per-file warnings

---

borg/testsuite/archiver.py

mknod raises this when running as non-root under Windows 10's Linux Subsystem.

catch errno.ENOSYS for mknod (win 10 lxsys)

---

borg/archive.py
borg/archiver.py
borg/helpers.py
docs/changes.rst

Fixes #1936 (at least partially, see ticket)
In 3.4 this is available on "Windows, Mac OS X, Linux, FreeBSD, OpenBSD, Solaris.", but it also works on NetBSD and OI/illumos. Note that it is unconditionally available with 3.5+. On Windows overflows are handled, so it won't roll over after ~50 days.

Fix some clock problems

---

src/borg/archiver.py
src/borg/testsuite/archiver.py

use --encryption=repokey for all the tests except if they
have special needs.
fixes #1891.
TODO: changelog entry, this is a incompatible change as in the past the --encryption option had a default, so it was not required to give it. it is now required.

borg init --encryption - remove default

---

borg/archiver.py
docs/changes.rst

Fix upgrade --tam, change-passphrase crashes if not encrypted

---

docs/faq.rst

Patch speaks for itself.  Just a very minor cleanup of some language I tripped on while reading the FAQ.  The for/before replacement being the most important part.

Docs: language clarification - VM backup FAQ

---

Vagrantfile

The packages which are required for ssh log-in and rsync synchronized
folders to work are separated from those specific for the borg
project. This makes it easier to reuse in other projects.

Vagrantfile: Split cygwin packaged to be installed into base and project

---

src/borg/key.py
src/borg/testsuite/key.py

```
.tox/py34/lib/python3.4/site-packages/borg/testsuite/key.py ......F...................
====================================================================== FAILURES =======================================================================
_____________________________________________________________ TestKey.test_keyfile_blake2 _____________________________________________________________
self = <borg.testsuite.key.TestKey object at 0x7f13fde42518>, monkeypatch = <_pytest.monkeypatch.MonkeyPatch object at 0x7f13fde4e9e8>
keys_dir = local('/tmp/pytest-of-tw/pytest-39/test_keyfile_blake20')
def test_keyfile_blake2(self, monkeypatch, keys_dir):
with keys_dir.join('keyfile').open('w') as fd:
fd.write(self.keyfile_blake2_key_file)
monkeypatch.setenv('BORG_PASSPHRASE', 'passphrase')
key = …
```

demonstrate mac key length issue

---

borg/repository.py
borg/testsuite/archive.py
borg/testsuite/repository.py
borg/upgrader.py
requirements.d/development.txt
tox.ini

Fixes #864.
Some measurements:
```
xdist x8 3.4 run 1: 3.24user 292.50system 1:46.75elapsed 277%CPU
xdist x8 3.4 run 2: 3.53user 293.37system 1:47.10elapsed 277%CPU
no xdist 3.4 run 1: 8.18user 160.31system 2:54.76elapsed 96%CPU
no xdist 3.4 run 2: 8.20user 159.57system 2:53.95elapsed 96%CPU
speedup: 1.63 (using 2 cores + HT)
```

use pytest-xdist to parallelize testing

---

src/borg/archiver.py
src/borg/platform/posix.pyx

The node ID is usually the 48 bit MAC of the primary network
interface.
This pretty much kills off any possibility of colliding hostnames unless one is bent on doing that (same hostnames, spoofing MAC etc.).

posix: use fully-qualified hostname + node ID

---

borg/archive.py
docs/changes.rst

Fixes #1997 
I didn't change the other branch to issue a warning/error if --prefix doesn't match anything or if there are not >=N archives with --last N because this might actually break scripts.
Edit: Made the described cases print a warning but nothing else (esp. not an exit code).

check: fail if single archive does not exist

---

src/borg/_crc32/crc32.c
src/borg/_crc32/slice_by_8.c

Should fix #2026
Note that the type errors from the paste in #2026 are follow-up errors because the ISA extension is disabled and hence no intrinsics are defined, so it assumes `int ... ()` as the function prototype, which is of course wrong.

crc: disable CLMUL version due to clang bugs.

---

borg/chunker.pyx
borg/crypto.pyx
borg/hashindex.pyx
borg/helpers.py
borg/platform.py
borg/platform_darwin.pyx
borg/platform_freebsd.pyx
borg/platform_linux.pyx

like '<numberspace>_<version>', e.g. '1.0_01' for version 01 (used in 1.0 maintenance branch).
this avoids overlap and accidental collisions between different release branches.

API_VERSION: use numberspaces, fixes #2023

---

src/borg/_crc32/crc32.c

Fixes #2043 
Fixes OpenBSD build, when #2045 is applied as well. `700 passed, 176 skipped, 2 xfailed, 1 pytest-warnings in 269.22 seconds`

crc: openbsd has no Intel intrinsics

---

setup.py
src/borg/platform/__init__.py
src/borg/platform/base.py

fixes #2041
rather use a inverted check like "not windows".
also: add a base implementation for this stuff, just raising NotImplementedError

WIP: posix platform module: only build / import on non-win32 platforms

---

tox.ini

it's either auto or env var XDISTN value.

pytest-xdist: adjust parallelism, fixes #2053

---

requirements.d/development.txt

sometimes the system pip/setuptools is rather old and causes
warnings or malfunctions in the primary virtual env.

add pip and setuptools to requirements file, fixes #2030

---

tox.ini

auto does not produce enough load, e.g. on freebsd64 vagrant VM,
cpu is 80-90% idle (1 core == 1 parallel tox worker).

pytest -n 4 as default (4 parallel workers)

---

Vagrantfile

The previous 10.2 got unusable due to missing backwards compatibility of 10.3 binaries it installed.
The 10.3 box from freebsd project has some issues:
- it needs "vagrant up" twice to start (first start with MAC warning)
- it needs shell set to sh

fix the freebsd64 vagrant machine, fixes #2037

---

.travis/install.sh

we test on old pythons (3.x.0) on Linux, so we can test on 3.x.latest on OS X.

travis: use latest pythons for OS X based testing

---

Vagrantfile

- use -RELEASE, it can be updated via binaries
- more RAM, otherwise the 4 workers run out of memory.
- do not install / use fakeroot, it seems broken.
- set a hostname, this VM has none

vagrant freebsd: some fixes, fixes #2067

---

MANIFEST.in

fixes #2066, supercedes #2068, PRed against 1.0-maint (merge into master later)

Manifest.in: simplify, also exclude *.so *.dll *.orig

---

borg/_hashindex.c

Fixes #2073
@oroppas feel free to check if this actually fixes it (although I have little doubt)
657ecfd aimed at master (crc, hashindex dedup).

detect mingw byte order

---

borg/repository.py

maybe not a problem, but cleaner like that in any case.

SyncFile: fix use of fd object after close

---

borg/repository.py

"ab" seems to make no sense here (if there is already a (crap, but non-empty) segment file,
we would write a MAGIC right into the middle of the resulting file) and cause #2099.
WIP, it is not sure yet that this is the right fix. It would naturally fix the magic being written into the middle of the file, but also kill previous file content. If that content was only from some (uncommitted) crap segment (of an aborted transaction), that might be valid. If not, maybe not - needs more code review.
The unit tests worked (before and after this change).

creating a new segment: use "xb" mode, fixes #2099

---

Vagrantfile

somehow without these cpuid settings it does not work for everybody.
also nice if we can get away without the extensions pack, which is proprietary.
do not update iTunes, we just want the OS security / bugfix updates

vagrant: improve darwin64 VM settings

---

borg/repository.py

a) fix potential reentrancy issue / confusing tracebacks
if anything blows up in the middle of a (first) invocation of close_segment()
and an exception gets raised, it could happen that close_segment() gets called
again (e.g. in `Repository.__del__` or elsewhere).
As the `self._write_fd` was set to None rather late, it would re-enter the if-block
then.
The new code gets the value of self._write_fd and also sets it to None in one tuple
assignment, so re-entrance does not happen.
Also, it uses try/finally to make sure the important parts (fd.close()) get executed,
even if there are exceptions in the other parts.
b) work around fadvise fail
Just ignore the error, as we also do in the C code.

Work around fadvise fail

---

setup.cfg

[tool:pytest] only works for pytest >= 3.0.
fixes issue #2112.

pytest: use [pytest] section in setup.cfg

---

src/borg/archiver.py
src/borg/helpers.py
src/borg/testsuite/archiver.py

This adds two new commands for low level debugging and maybe analysis. These are debug commands without stability guarantees.
The output is the decrypted contents of the manifest translated from msgpack to json for manifest and similar for archive. For archive the json has a synthetic top level object that combines the metadata from the manifest about the archive with the archive msgpack item and the items stream.
I don‘t think this will duplicate #1946 / #1812 as those are meant to be a nice and higher level interface while this is a debugging and development aid.
```
{
"item_keys": [
"acl_access",
"acl_default",
"acl_extended",
"acl_nfs4",
"atime",
"bsdflags",
"chunks",
"chunks_healthy",
"ctime",
"gid",
"group",
"hardlink_master",
"mode",
"mtime",
"part",
"path",
"rdev",
"source", …
```

Add 'debug dump-manifest' and 'debug dump-archive' commands.

---

borg/archiver.py
docs/usage/create.rst.inc

Fixes #2141
It's not possible to detect with Posix API submounts of same filesystems. Therefore borg create will traverse mountpoints even with -x, when FS of $MOUNTPOINT == FS of $MOUNTPOINT/.. .

clearify doc for same filesystems

---

docs/development.rst
docs/support.rst

Fixes #2155 
(When we have multiple backport labels we can just make them all the same colour, no real need for colour coding there, and keeps colours free [all 17 million of them :D])

new branching model

---

docs/faq.rst

docs: FAQ by categories as proposed by @anarcat in #1802
Usage & Limitations
Security
Common issues
Miscellaneous (only three items, two fork-related)
I immediately noticed that this makes it *much* easier to find FAQ items -- the list is just too long without any kind of hierarchy / order.
Note: This does not change/invalidate any links to FAQ items.

docs: FAQ by categories as proposed by @anarcat in #1802

---

docs/internals.rst
docs/security.rst
docs/usage.rst

The former section is a bit older (Nov 2016) and has been the piece
responsible for finding CVE-2016-10099, since while writing it I
wondered how the manifest was authenticated to actually
*be* the manifest. Well. There it is ;)
It has been edited to final form only recently (~mid Jan 2017 and
a few moments ago) and should now be ready for review.
The latter section is new.
---
I think it's sufficient to have this just in the 1.1.x docs.

add "Cryptography in Borg" and "Remote RPC protocol security" sections

---

borg/fuse.py

it's basically ceil(dsize / blocksize) now (without doing floating point ops).
(fallout from #2157)
st_blocks is not expected to be a floating point value.
also: reduces execution time and keeps fuse code better in sync with (future) master.

fuse: fix st_blocks to be an integer (not float) value

---

AUTHORS
src/borg/helpers.py
src/borg/testsuite/archiver.py

These keys shows the amount of deduplicated size and compressed size of each file in the archive. As suggested in #2164.

Add dsize and dcsize keys, fixes #2164

---

src/borg/hashindex.pyx

also: add some missing assertion messages
severity:
- no issue on little-endian platforms (== most, including x86/x64)
- harmless even on big-endian as long as refcount is below 0xfffbffff,
which is very likely always the case in practice anyway.

fix ChunkIndex.__contains__ assertion  for big-endian archs

---

docs/security.rst
src/borg/archive.py
src/borg/archiver.py
src/borg/remote.py
src/borg/repository.py

we do not trust the remote, so we are careful unpacking its responses.
the remote could return manipulated msgpack data that announces e.g.
a huge array or map or string. the local would then need to allocate huge
amounts of RAM in expectation of that data (no matter whether really
that much is coming or not).
by using limits in the Unpacker, a ValueError will be raised if unexpected
amounts of data shall get unpacked. memory DoS will be avoided.
Fixes #2139

borg rpc: use limited msgpack.Unpacker

---

src/borg/archive.py
src/borg/archiver.py
src/borg/constants.py
src/borg/repository.py

See #1452
"This is 100 % accurate."
Also increases maximum data size by ~41 bytes. Not 100 % side-effect free;
if you manage to exactly land in that area then older Borg would not read
it. OTOH it gives us a nice round number there. No hard opinion here.

info: show utilization of maximum archive size

---

src/borg/archive.py
src/borg/archiver.py
src/borg/cache.py
src/borg/helpers.py
src/borg/testsuite/archiver.py

Fixes #2200 
This is the data output, going out over stdout. JSON logging as proposed in #2024 would go out over stderr as usual, so no conflicts there.
There is some overlap between info (with --last/--first/--prefix) and list which is more obvious in the JSON output. The difference is that "info" reports more stuff, and takes longer for that, while "list" is fast (only looks at the manifest).

JSON output for major commands

---

docs/faq.rst
docs/quickstart.rst
docs/usage.rst
src/borg/archiver.py
src/borg/testsuite/archiver.py

not for create_src_archive() though as this triggers a bug that has to get fixed outside this PR first.

use lz4 compression by default, fixes #2179

---

src/borg/archive.py
src/borg/archiver.py
src/borg/cache.py
src/borg/constants.py
src/borg/fuse.py
src/borg/helpers.py
src/borg/item.pyx
src/borg/testsuite/item.py

if an item has a chunk list, pre-compute the total size and store it into "size" metadata entry.
this speeds up access to item size (e.g. for regular files) and could also be used to verify the validity of the chunks list.
note about hardlinks: size is only stored for hardlink masters (only they have an own chunk list)

archived file items: add size metadata

---

borg/helpers.py
borg/testsuite/archiver.py

This is a fix for the already merged #1971.
--patterns-from was accessing args.roots instead of args.paths
I also added a test case that parses a command containing --patterns-from.

Fix for PR #1971

---

src/borg/helpers.py
src/borg/testsuite/archiver.py

This is a fix against master for the already merged #1971.
--patterns-from was accessing args.roots instead of args.paths
add a test case that parses a command containing --patterns-from

Fix for PR #1971 (master)

---

docs/misc/benchmark-crud.txt
src/borg/archiver.py

fixes #1788.
result looks like this:
```
$ BORG_PASSPHRASE=secret borg init --encryption=repokey-blake2 repo
$ BORG_PASSPHRASE=secret borg benchmark crud repo testdir
C-Z-BIG         122.27 MB/s (10 * 100.00 MB all-zero files: 8.18s)
R-Z-BIG         190.21 MB/s (10 * 100.00 MB all-zero files: 5.26s)
U-Z-BIG         516.33 MB/s (10 * 100.00 MB all-zero files: 1.94s)
D-Z-BIG         850.42 MB/s (10 * 100.00 MB all-zero files: 1.18s)
C-R-BIG          43.38 MB/s (10 * 100.00 MB random files: 23.05s)
R-R-BIG         133.22 MB/s (10 * 100.00 MB random files: 7.51s)
U-R-BIG         534.41 MB/s (10 * 100.00 MB random files: 1.87s)
D-R-BIG         231.92 MB/s (10 * 100.00 MB random files: 4.31s)
C-Z-MEDIUM       93.89 MB/s (1000 * 1.00 MB all-zero files: 10.65s)
R-Z-MEDIUM      209.07 MB/s (1000 * …
```

borg benchmark crud command

---

borg/archiver.py
docs/usage.rst

As discussed in IRC, this is an improved wording of `remote-path` to not mix it up with borg's repo-path.

[docs] improve remote-path description

---

borg/_hashindex.c

if there are too many deleted buckets (tombstones), hashtable performance goes down the drain.
in the worst case of 0 empty buckets and lots of tombstones, this results in full table scans for
new / unknown keys.
thus we make sure we always have a good amount of empty buckets.

rebuild hashtable if we have too little empty buckets, fixes #2246

---

src/borg/archive.py
src/borg/testsuite/archiver.py

This will print a warning whenever extended attributes in the archive are too large to extract, and continues the extraction of the item instead of halting. Fixes #2161.

Handle big extended attributes. Fixes #2161

---

src/borg/key.py
src/borg/keymanager.py

Fixes #2267 
Needs no backport since 1.0.x does not support the added key types.

Redo key_creator, key_factory, centralise key knowledge

---

docs/installation.rst

BorgBackup 1.0.10 is only available in the experimental distribution for the moment.
Works perfectly for me. So I suggest to add this distribution as well.
http://metadata.ftp-master.debian.org/changelogs/main/b/borgbackup/borgbackup_1.0.10-2_changelog

Docs: one link per distro in the installation page

---

src/borg/archive.py
src/borg/testsuite/archiver.py

Previous PR: #2198
This sets a warning exit code whenever an xattr is too big.
Was waiting for #2199 to be merged.

extract: warning RC for unextracted big extended attributes, followup

---

docs/usage.rst

This adds a snippet in the `Additional notes` section of the docs about why to use the `-oBatchMode=yes` flag in automated backup scripts calling `ssh`.

Address SSH batch mode in docs (fixes #2202)

---

docs/development.rst

Python 3.6 added some new guaranteed hashing algorithms that will show up as available in the docs when they are built with >=3.6 even though the baseline for support is currently Python 3.4. We don't want to include hashing algorithms that might not exist on certain builds of borg in the docs, and running build_usage with Python 3.4 instead will fix this.
I wasn't sure where the diff attached to #2123 came from (which command? API docs?), but I'm pretty sure these changes will suffice.
It might be better to have the link point to the part of the Python 3.6 changelog where it tells about the new guaranteed algorithms instead of to the issue...

Add warning about running build_usage on Python >3.4 (fixes #2123)

---

borg/archive.py
borg/archiver.py
borg/compress.pyx
borg/hashindex.pyx
borg/helpers.py
borg/remote.py
borg/repository.py
borg/testsuite/archiver.py
borg/testsuite/helpers.py
docs/development.rst
docs/installation.rst
docs/support.rst

Changes from
#2156
#2159
#2171
#2181
#2187
#2198
#2206
#2224
#2254
-
#2199 
#2258 
-
#2184

picked cherries for 1.0-maint

---

src/borg/helpers.py
src/borg/repository.py

The SaveFile code, while ensuring atomicity, did not allow for secure
erasure of the config file (containing the old encrypted key). Now it
creates a hardlink to the file, lets SaveFile do its thing, and writes
random data over the old file (via the hardlink). A secure erase is
needed because the config file can contain the old key after changing
one's password.

Securely erase config file, fixes #2257

---

docs/internals/security.rst

This was kinda implied with the previous wording, but it should be said more explicitly.

docs/security: reiterate that RPC in Borg does no networking (in Borg itself)

---

src/borg/archive.py
src/borg/cache.py
src/borg/helpers.py
src/borg/item.pyx
src/borg/testsuite/helpers.py
src/borg/testsuite/item.py

Revert bigint removal

---

borg/archive.py
borg/cache.py
borg/helpers.py
borg/testsuite/helpers.py

filesystem -> clamp -> archive (create)
(cherry picked from commit b7a17a6db76283c9d9d6f246831c3010fbb35fe2)
backport of #2309.

clamp (nano)second values to unproblematic range, fixes #2304

---

src/borg/archive.py
src/borg/archiver.py
src/borg/helpers.py
src/borg/key.py
src/borg/testsuite/helpers.py

the bug was compr_args.update(compr_spec), helpers.py line 2168 - that mutated the compression
spec dict (and not just some local one, but the compr spec dict parsed from the commandline args.
so a change that was intended just for 1 chunk changed the desired compression
level on the archive scope.
I refactored the stuff to use a namedtuple (which is immutable, so such effects can not happen).

use immutable data structure for the compression spec, fixes #2331

---

src/borg/item.pyx
src/borg/testsuite/archiver.py
src/borg/testsuite/item.py

a symlink has a 'source' attribute, so it was confused with a hardlink
slave here. see also issue #2343.
also, a symlink's fs size is defined as the length of the target path.

fix symlink item fs size computation

---

src/borg/archiver.py
src/borg/helpers.py
src/borg/testsuite/helpers.py

not really a pattern (as in potentially having any variable parts) - it just does a full,
precise match, after the usual normalizations.
this is matched via set membership check within O(1) time.

add PathFullPattern / optimization for it

---

src/borg/archive.py

anything at <path> gets nuked already a few lines above, if possible.
see line 555 / 557.

extract: remove duplicate code

---

borg/archive.py

make_parent(path) helper to reduce code duplication.
also use it for directories although makedirs can also do it.
bugfix: also create parent dir for device files, if needed.
(cherry picked from commit d4e27e2952888d547c54d5b0f4be22892aa9e2f1)
Backported for the bugfix. I kept the small refactor also to keep the code better in sync.

extract: small bugfix and refactoring for parent dir creation

---

src/borg/archiver.py
src/borg/helpers.py
src/borg/testsuite/helpers.py

Also better error messages.
`Invalid placeholder "horstname" in string: testrepo::{horstname}-{now}`

placeholders: deny access to internals and other unspecified stuff

---

src/borg/platform/__init__.py
src/borg/platform/windows.pyx
src/borg/remote.py

Fix ssh not working on windows.
Use putty link (plink) as ssh client if openssh cant be found.
Interactive authenticating does not work so you need to use shh keys

Windows ssh

---

Vagrantfile

this fixes that the prelink cronjob on some distros kills the
borg binary by stripping away parts of it.

use pyinstaller v3.2.1, fixes #2396

---

src/borg/platform/linux.pyx

platform.linux: get rid of "resource" module

---

docs/faq.rst

In reference to #2341
Added an explanation about the risks associated with running `borg check --repair` and why the program presents a warning to the user.
Also, fixed some _very minor_ grammar.

FAQ to explain warning when running --repair

---

src/borg/archive.py
src/borg/archiver.py
src/borg/helpers.py
src/borg/testsuite/archiver.py
src/borg/testsuite/helpers.py

This fixes the problem raised by issue #2314 by requiring that each root subtree
be fully traversed.
The problem occurs when a patterns file excludes a parent directory P later in
the file, and earlier in the file a subdirectory S of P is included.  Because a
tree is processed recursively, P is processed before S is, but if P is
excluded, then S used to not even be considered, because we wouldn't recurse
into P.  With this fix, we now recurse into P nonetheless, but don't add P (as
a directory entry) to the archive.

allow excluding parent and including child, fixes #2314

---

docs/installation.rst

Some documentation was improperly formatted with #2392. This corrects those errors. Notably, links weren't formatted correct in the source docs.

Fix formatting in pre-installation section

---

src/borg/archive.py

just getting data from the repo can already raise IntegrityErrors
in LoggedIO, so we need to catch them also.
see also the code a few lines above where this is done in the same way.

verify_data: fix IntegrityError handling for defect chunks, fixes #2442

---

.travis/run.sh
Vagrantfile
scripts/faked-debug.sh

I have absolutely no idea why, but this seems to reliably fix the EISDIR test issues with no additional verbosity (except 2 messages at startup). I also didn't notice any significant slow downs.

Start fakeroot faked in debug mode - fixes EISDIR issues

---

src/borg/archiver.py

everything that touches the repository can take a long time and display
progress information, from compaction to replaying segments.

make --progress a common option

---

src/borg/_hashindex.c
src/borg/hashindex.pyx
src/borg/repository.py

- Preparation for #1688 / #1101
- Support hash indices >2 GB (fixes #1809)
- Better error reporting
---
Split off from #1688 for easier integration.
The downside is that hashindex.c now includes Python, so one needs to supply the appropriate -lpythonmX.Y etc. to compile it for stand-alone testing. The code is also a bit more complex, because it's (supposed to) correctly clean up references to objects on errors.

hashindex: Use Python I/O

---

src/borg/testsuite/archiver.py

looks like PyInstaller modifies the module names.

do not test logger name, fixes #2504

---

src/borg/archiver.py
src/borg/helpers.py
src/borg/logger.py
src/borg/remote.py
src/borg/testsuite/repository.py

Fixes #2241 
Remarkably annoying patch to create.
Compatiblity:
```
Remote |               |               |               |
|     1.0.x     |   <1.1.0b5    |   master      |
Client      |               |               |   (>1.1.0b6)  |
------------+---------------+---------------+---------------+
1.0.x       |log w/o prefix | sees log messages w/ prefix   |
|always progress| progress:never| always        |
------------+               +---------------+---------------+
<1.1.0b5    |progress spreads| broken *1    | always progress + spreads     |
------------+               +---------------+---------------+
>1.1.0b6    |progress stays |  log ok,      | superb *3     |
(master)    |in same line   | no progress *2|               |
------------+---------------+---------------+---------------+ …
```

Fix remote logging and progress

---

src/borg/testsuite/archiver.py

Suspecting this and xdist ordering are causing https://travis-ci.org/borgbackup/borg/jobs/234395993#L1858

testsuite: call setup_logging after destroying logging config

---

src/borg/testsuite/archiver.py

This tests whether the permissions metadata is preserved when a folder is excluded but still recursed into to find a matching file in a subfolder.
To my surprise, it passes, which seems to indicate that the concern raised by @ThomasWaldmann in PR #2322 may not be a problem after all.

add test for preserved intermediate folder permissions

---

docs/borg_domain.py
docs/conf.py
docs/usage/benchmark_crud.rst.inc
docs/usage/break-lock.rst.inc
docs/usage/change-passphrase.rst.inc
docs/usage/check.rst.inc
docs/usage/create.rst.inc
docs/usage/delete.rst.inc
docs/usage/diff.rst.inc
docs/usage/export-tar.rst.inc
docs/usage/extract.rst.inc
docs/usage/info.rst.inc
docs/usage/init.rst.inc
docs/usage/key_change-passphrase.rst.inc
docs/usage/key_export.rst.inc
docs/usage/key_import.rst.inc
docs/usage/key_migrate-to-repokey.rst.inc
docs/usage/list.rst.inc
docs/usage/mount.rst.inc
docs/usage/prune.rst.inc
docs/usage/recreate.rst.inc
docs/usage/rename.rst.inc
docs/usage/serve.rst.inc
docs/usage/umount.rst.inc
docs/usage/upgrade.rst.inc
docs/usage/with-lock.rst.inc
setup.py

This does NOT fix #1485, but it is infrastructure that makes it fixable.
Before:
After:

docs: borg_domain for custom priority index entries

---

src/borg/__init__.py

this helps to fail early when people do badly done scm based repackaging
this should resolve  #2538

fail in borg package if version metadata is completely broken

---

docs/installation.rst
src/borg/archive.py
src/borg/archiver.py
src/borg/helpers.py
src/borg/testsuite/__init__.py

first changeset is the fix.
2nd and 3rd rather cleanups (== always use generic call with follow_symlinks=False).
didn't touch lchmod related code, no lchmod on linux.
also didn't touch lchflags, except removing a unused related variable.

document follow_symlinks requirements, check libc, fixes #2507

---

docs/faq.rst
docs/quickstart.rst
docs/usage_general.rst.inc
src/borg/crypto/key.py

The BORG_PASSCOMMAND variable can be used to specify an external program that is asked to supply the passphrase.

Added BORG_PASSCOMMAND environment variable

---

src/borg/_hashindex.c
src/borg/cache.py
src/borg/crypto/file_integrity.py
src/borg/hashindex.pyx
src/borg/testsuite/archiver.py
src/borg/testsuite/file_integrity.py
src/borg/testsuite/hashindex.py

~~TODO: Corruption tests (manual testing: All good!); Add dedicated test cases for ICF (e: not really necessary).~~
Initially the design provided only the equivalent of "detached signatures", i.e. those .integrity files. However, that caused various design pains, because these files naturally did not use the same transaction mechanisms.
Therefore, I adjusted the design. Detached integrity files are now the exception, not the norm, and can be used where they are apt (archive.chunks.d). Otherwise, integrity data is stored where the surrounding code can accommodate it well. For the cache, this is the `config`. For the repository I will make it `N.ancillary`, since `N.hints` requires integrity checks (N>0 tickets with hints corruption; they're also much larger than the cache config).
Part of …

1101.integration.cache

---

docs/internals/data-structures.rst
docs/usage/init.rst.inc
docs/usage/serve.rst.inc
src/borg/archiver.py
src/borg/remote.py
src/borg/repository.py
src/borg/testsuite/archiver.py
src/borg/testsuite/repository.py

Fixes #2517 
I gave #2517 some thought; implementing it in Borg has some advantages:
- Error messages are more helpful
- Our pre-commit checks do not capture FS quotas
- As implemented, the client can always back out of a 100.0 % used quota, which is not possible with (hard) FS quotas
Disadvantages:
- More difficult to deploy compared to FS quotas
Perhaps a complementary option to --restrict-to-path that matches the path exactly would simplify handling of repo hosting in general?
- The storage quota and the actual bound on disk space use have a somewhat loose relationship.
(In case anyone feels reminded of file systems and filling them up completely... it's the same structures, the same math — an exercise for the reader: design a transactional data store that has a fixed upper bound X, …

Implement storage quotas

---

docs/internals/data-structures.rst

also cf. "Enforcing the quota":
The quota is enforcible only if *all* :ref:`borg_serve` versions
accessible to clients support quotas

docs: quotas: clarify compatbility; only relevant to serve side

---

AUTHORS
setup.py
src/borg/algorithms/checksums.pyx
src/borg/algorithms/crc32.pyx
src/borg/algorithms/xxh64/xxhash.c
src/borg/algorithms/xxh64/xxhash.h
src/borg/archiver.py
src/borg/crypto/file_integrity.py
src/borg/repository.py
src/borg/testsuite/checksums.py
src/borg/testsuite/crc32.py
src/borg/testsuite/file_integrity.py

A cryptographic hash is slow for providing features not required here. I don't want to use a CRC since we already know from both theory and practice (use in Repository) that they are not that good at detecting storage errors. So xxh64 it is, specifically designed as a fast storage checksum over large data blocks (used in LZ4, zstd and various media/footage-management products).
(If we ever redo the Repository format, using it as a checksum instead makes sense. The implementation is light on cache, unlike table-based CRC, but as fast as crc32_clmul - and for longer blocks it's a bit faster, without requiring more than plain C compiled to plain x64).
Part of my ongoing series to realize #1101 (#1688 #2496 #2502 #2568)

1101.integration.xxh

---

src/borg/repository.py
src/borg/testsuite/repository.py

Part of my ongoing series to realize #1101 (#1688 #2496 #2502 #2568 #2580)
~~Could use a few more tests for specific corruption scenarios.~~
Unlike the cache design this can have false positives whenever an older version rewrites the auxiliary files for a transaction created by a newer version, because that might result in a different index (resizing) or hints file (hash ordering), while not invalidating the integrity file. E.g. using 1.1 on a repository, noticing corruption or something, running 1.0 check --repair, which rewrites the index and hints, then using 1.1 again; 1.1 would complain about index and/or hints corruption and rebuild them. I don't think this is noteworthy enough to be included in the error messages, but is something to mention when I type up design docs for this …

repository: checksum index and hints

---

.coafile
docs/development.rst
requirements.d/coala.txt

ignores / disable are set up so that there are not many faults.
we can improve that iteratively.
for trying it: pip install coala coala-bears ; apt install cppcheck

add a .coafile for coala

---

src/borg/archive.py

the timestamps of the recreated archive (in the archive metadata and
also in the manifest) are now as they were for the original archive.
they are important metadata about the archive contents and should
therefore be kept "as is".
note: when using -v --stats, the timestamps shown there for recreate
are about the recreate start/end/duration.
console log:
[fix.txt](https://github.com/borgbackup/borg/files/1050760/fix.txt)

recreate: keep timestamps as in original archive, fixes #2384

---

src/borg/algorithms/crc32_dispatch.c

algorithms.checksums: work around GCC 4.4 bug by disabling CLMUL

---

src/borg/testsuite/archiver.py

in this case, it is expected as we archived a file with such a ts.

test: suppress tar's future timestamp warning

---

src/borg/archiver.py
src/borg/nanorst.py
src/borg/testsuite/archiver.py
src/borg/testsuite/nanorst.py

Strips a small subset of rST syntax from --help output and replaces it with standard vt100 escapes when on a terminal.
This solves the docs-formatting dichotomy between Sphinx and --help.

nanorst for --help

---

src/borg/remote.py
src/borg/testsuite/archiver.py
src/borg/testsuite/repository.py

the cygwin issue that caused these tests to break was fixed in cygwin
at least since cygwin 2.8.0 (maybe even since 2.7.0).
also added a comment to our workaround (os_write wrapper, that is needed
still for people running older cygwin versions) that it can be removed
when cygwin 2.8.0 is considered ancient (and everybody has upgraded to
some fixed version).

enable remote tests on cygwin

---

borg/archive.py
borg/archiver.py
borg/cache.py
borg/helpers.py
borg/testsuite/archiver.py
conftest.py

This should allow us to make sure older borg versions can be cleanly
prevented from doing operations that are no longer safe because of
repository format evolution. This allows more fine grained control than
just incrementing the manifest version. So for example a change that
still allows new archives to be created but would corrupt the repository
when an old version tries to delete an archive or check the repository
would add the new feature to the check and delete set but leave it out
of the write set.
This is somewhat inspired by ext{2,3,4} which uses sets for
compat (everything except fsck), ro-compat (may only be accessed
read-only by older versions) and features (refuse all access).
This implements #1806
Open questions:

Add minimal version of in repository mandatory feature flags.

---

docs/usage/create.rst

Fixes https://github.com/borgbackup/borg/issues/2458
The `/home`/`tmp` example has already been removed, so now there is no `re:` example in there, anymore.

Remove re docs

---

conftest.py
src/borg/__init__.py
src/borg/archive.py
src/borg/archiver.py
src/borg/cache.py
src/borg/helpers.py
src/borg/testsuite/archiver.py

[This is the forward port of #2134
Changes relative to the version committed on 1.0-maint:
mapping of new commands to features:
`borg export-tar` and `borg diff` use Manifest.Operation.READ
`borg recreate` uses Manifest.Operation.CHECK
`borg debug dump-manifest` uses Manifest.NO_OPERATION_CHECK as all other debug commands.
]
This should allow us to make sure older borg versions can be cleanly
prevented from doing operations that are no longer safe because of
repository format evolution. This allows more fine grained control than
just incrementing the manifest version. So for example a change that
still allows new archives to be created but would corrupt the repository
when an old version tries to delete an archive or check the repository
would add the new feature to the check and delete …

Add minimal version of in repository mandatory feature flags. (master)

---

docs/man/borg-init.1
docs/usage/init.rst.inc
src/borg/archiver.py
src/borg/crypto/key.py
src/borg/testsuite/key.py

rename authenticated to authenticated-blake2, consistent with the other
blake2 key modes
add authenticated mode that fills the blank and is consistent with the
other "unqualified" key modes
TYPE IDs remain of course unchanged and compatible.

normalize authenticated key modes

---

src/borg/cache_sync/unpack.h

warning: this decimal constant is unsigned only in ISO C90
Raised by GCC 4.9.2 on PowerPC.
The warning is bogus here due to the immediate explicit cast; newer
versions don't emit it.
Remove it, since GCC emits it on *every use of the macro*.

cache sync: suppress GCC C90/C99 int literal warning

---

docs/misc/prune-example.txt

Changed from 20. December to 19. December for easier comprehension (viewing the calendar.)
The missing 'd' at 20. December is hardly noticeable compared to e.g. the 19. December.

changed the date of "day without backup"

---

src/borg/archiver.py

if we always give stdout to extract_item(), it gets into the stdout-
processing branch which only emits data from items that have chunks
and does nothing for items which don't.

don't write to disk with --stdout, fixes #2645

---

src/borg/cache_sync/cache_sync.c

!ctx->buf => ctx->tail - ctx->head == 0
(ubsan is annoyed by this)

cache sync: don't do memcpy(..., 0, 0)

---

src/borg/_chunker.c

As luck would have it at least x86 already performs this masking. Others probably do as well. GCC knows this and emits the same code.
Found by ubsan. With #2670 and #2671 applied, running the test suite is ubsan-clean.

chunker: don't do uint32_t >> 32

---

src/borg/fuse.py

they could come into archives e.g. when backing up external drives under cygwin.

FUSE: fix negative uid/gid crash, fixes #2674

---

src/borg/archive.py
src/borg/cache_sync/cache_sync.c
src/borg/cache_sync/unpack.h
src/borg/hashindex.pyx
src/borg/helpers.py

Gets rid of the cache "abuse" (avoiding some I/O, should be nice for `borg info ... --last/--first/-a`) and is also faster. Also, cached archive chunks indices could be used, but that code is touched in the --no-cache-sync PR.
Logically, nothing changes. size and csize are taken from the master (Cache.chunks) index.

info: use CacheSynchronizer & HashIndex.stats_against

---

src/borg/chunker.pyx

With the argument specified as unsigned char \*, Cython emits
code in the Python wrapper to convert string-like objects to
unsigned char\* (essentially PyBytes_AS_STRING).
Because the len(data) call is performed on a cdef'd string-ish type,
Cython emits a strlen() call, on the result of PyBytes_AS_STRING.
This is not correct, since embedded null bytes are entirely possible.
Incidentally, the code generated by Cython was also not correct,
since the Clang Static Analyzer found a path of execution where
passing arguments in a weird way from Python resulted in strlen(NULL).
Formulated like this, Cython emits essentially:
c_buzhash(
PyBytes_AS_STRING(data),
PyObject_Length(data),
...
)
which is correct.
The impact is rather low/none here, since this is only used in the test suite.

chunker: fix invalid use of types

---

src/borg/archiver.py
src/borg/fuse.py
src/borg/lrucache.py
src/borg/testsuite/lrucache.py

~Halves time to load an archive, far less /tmp usage, slightly faster traversal of directories. There are still a lot of low-hanging fruits left in this code. Memory usage increases slightly due to the meta array (for 1 million items it is approx 10 MB - 9.0x bytes on average per Item).
Note: the next stable release of msgpack allows to avoid write_bytes, since a tell() method was added.

fuse: redo ItemCache

---

docs/_templates/globaltoc.html
docs/_templates/logo-text.html
docs/borg_theme/css/borg.css
docs/conf.py
docs/development.rst
docs/installation.rst
requirements.d/docs.txt

no backport of this, but the requirements file (it seems this was undocumented previously) might need to be touched in 1.0-maint, depending on RTD build configuration.

switch docs theme

---

conftest.py
docs/internals/frontends.rst
src/borg/archiver.py
src/borg/cache.py
src/borg/hashindex.pyx
src/borg/helpers.py
src/borg/item.pyx
src/borg/repository.py
src/borg/testsuite/archiver.py
src/borg/testsuite/cache.py
src/borg/testsuite/item.py

Fixes #2313 
There are likely some rough edges or smaller inconsistencies when using this, e.g. borg-diff might not quite work...? I don't know.
I'll be upfront; _this PR is not about fixing all these. It's called experimental for a reason._ This PR is about getting the data model, the basics right.
Stuff for the future:
- Add a dedicated RPC call like "get_size[_many]" -- perhaps even taking a list (over RPC) to allow the remote `Repository` to sort by (segment, offset).
- recreate could touch up chunk id lists with csize=0 with their correct csize (depending on mode it'll already do that as a side-effect). check--repair could do that as well.

create: --no-cache-sync

---

src/borg/cache.py

0.01 ~ "one tick or less". ymmv.
Fixes #2702

AdHocCache: avoid divison by zero

---

src/borg/archiver.py

Overlooked in #2692 
This -c also shadows create's -c option. I didn't even knew it existed.

delete: remove short option for --cache-only

---

src/borg/testsuite/archiver.py

I recently installed GNU/Hurd 2017 and found the atime test works now.

remove skipping the noatime tests on GNU/Hurd, fixes #2710

---

docs/deployment/central-backup-server.rst
docs/deployment/hosting-repositories.rst
docs/quickstart.rst
docs/usage/serve.rst

Just using "restrict"; closes https://github.com/borgbackup/borg/issues/2121
Reasoning:
Even Debian 9 (now stable) [uses v7.4](https://packages.debian.org/de/stretch/openssh-server).
AFAIK it is still not possible in Ubuntu Trusty, but hopefully nobody uses that anyway. And waiting for this really nice doc change until April 2019 is not a good idea, IMHO.
Of course, we could also just add another note saying that you need to have support for that. If using it with an older ssh version it likely does not work, so users do not get into an insecure state.
E.g. a line saying:
> If you're using openssh-server < 7.2, you have to explicitly specify the ssh features to restrict and cannot simply use the `restrict` option. Use `,no-port-forwarding,no-X11-forwarding,no-pty,no-agent-forwarding,no-use …

Simplify ssh authorized_keys file

---

Vagrantfile

mirrors.kernel.org no longer offers ftp.

Vagrantfile: Fix cygwin mirror URL.

---

Vagrantfile
docs/changes.rst
docs/installation.rst
src/borg/archiver.py
src/borg/fuse.py
src/borg/testsuite/__init__.py
src/borg/testsuite/archiver.py

fixes #2739 
there are some debug log messages in fuse.py where it is "fuse" still - I interpreted that as module name and kept it.

FUSE vs. fuse

---

src/borg/archiver.py
src/borg/helpers.py
src/borg/testsuite/helpers.py

Fixes #2610
Parse --keep-within argument early, via new validator method interval passed to argparse type=, so that better error messages can be given.
Also swallows ValueError stacktrace per the comment in the old code that including it wasn't desirable.

Split up interval parsing and filtering for --keep-within

---

borg/archiver.py
borg/helpers.py
borg/testsuite/helpers.py

Fixes #2610
Parse --keep-within argument early, via new method within_range passed to argparse type=, so that better error messages can be given.
Also swallows ValueError stacktrace per the comment in the old code that including it wasn't desirable.  I can split this out (maybe just for master?) if desired.

Split up parsing and filtering for --keep-within

---

src/borg/constants.py
src/borg/crypto/key.py
src/borg/helpers.py
src/borg/remote.py
src/borg/repository.py
src/borg/testsuite/key.py

fixes #2175 
the test is rather slow and now pointless. previously, i tested for going over MAX_ARCHIVES, but that does not work any more due to the assert in Manifest.write(), so I guess the test can be removed.

Manifest: use limited unpacker

---

src/borg/archiver.py
src/borg/testsuite/archiver.py

These are mostly "does it [not] crash?" tests. Still found a bug, though, and with benchmark_crud using do_create in interesting ways it's probably a good idea to have this. The env-var kills the expensive parts.

Add some missing tests

---

docs/_templates/globaltoc.html
docs/usage.rst

also fixes missing trailing newlines of the .rst.inc files.

docs: no third level toc on command usage pages ("Description", "Examples")

---

src/borg/_hashindex.c
src/borg/crypto/low_level.pyx

Borg requires further patches to work with Pypy3, see 
https://bitbucket.org/pypy/pypy/issues/2597/c-api-pymemoryview_frommemory-python-33
https://bitbucket.org/pypy/pypy/issues/2598/pwdgetpwnam-throws-systemerror-with
Even with some patches (PyMemoryView_FromMemory => PyBytes_FromStringAndSize), it still dumps after some time, see
https://bitbucket.org/pypy/pypy/issues/2600/cpyext-missing-slot-wrapper-wrap_del
Similarly the testsuite keeps dumping. Simple stuff like `borg list` works, though.

Some C/Cython cleanup

---

docs/usage/mount.rst
src/borg/fuse.py

some tools depend on seeing the correct file extension to operate
correctly, so put our version to the left of the file extension.

FUSE versions view: keep original file extension at end, fixes #2769

---

docs/usage/mount.rst

this is pretty vital, since the versions view is basically
useless without them.

docs: mount: show usage of archive filters

---

src/borg/testsuite/archiver.py

Note: I did not reproduce the issue, but this should fix it.

patching objects does not work with the borg.exe binary, fixes #2700

---

src/borg/archiver.py
src/borg/helpers.py
src/borg/shellpattern.py
src/borg/testsuite/shellpattern.py

- noticed that prune does own globbing, which Archives.list can do.
- also, checkpoint handling with glob option is broken there, because the checkpoints won't be in the list due to shellpatterns doing fullmatches, so the checkpoints are not in the list.

prune enhancements / fixes

---

src/borg/_hashindex.c
src/borg/crypto/low_level.pyx
src/borg/fuse.py
src/borg/hashindex.pyx
src/borg/helpers.py
src/borg/testsuite/archiver.py

The nested directories feel rather unergonomic to me.
This seems to regress about ~10 % compared to master. The effect of keep-exts seems similar.

fuse: versions view, linear numbering by archive time

---

docs/installation.rst

Fix the name of the borgbackup package in openSUSE and
add an openSUSE section on how to install development dependencies
to build borgbackup from sources.

Fix openSUSE command and add openSUSE section

---

src/borg/archive.py
src/borg/archiver.py
src/borg/helpers.py
src/borg/testsuite/archiver.py

Load full-blown Archive instance if required.
Also supported: {bcomment} for binary and {end}.

support borg list repo --format {comment}, fixes #2081

---

docs/usage/upgrade.rst
docs/usage/upgrade.rst.inc
src/borg/archiver.py
src/borg/upgrader.py

Because 'upgrade' can be confusing.
Closes gh-2811
This appears to be a straightforward change - as far as I can tell, borg doesn't attempt to use the backup directly, but relies on the user to handle it if upgrading fails. So there was only one place to change the code, and a few bits of documentation.

Name backup directories with 'before-upgrade'

---

docs/usage/notes.rst

Closes gh-2815
The diff here looks big, but it's mostly just indenting the text that was already there.
I've also fixed a Sphinx cross link in the page.
Before:
After:

Use code markup for command line option headings

---

borg/archive.py
borg/archiver.py

a user was (rightfully) complaining that borg does a whole lot of
writing to .cache and was also quite inefficient because that took
rather long and occurred too frequently.
this was caused by big indexes/caches and the relatively high default
checkpoint frequency (every 300s) in 1.0.
we already have increased that value to 1800s in master (which soon will
be 1.1), so this changeset just does the same for 1.0.x.

change --checkpoint-interval default from 600s to 1800s, fixes #2841

---

.travis/upload_coverage.sh
docs/quickstart.rst

This makes the scripts fully POSIX-compatible and fixes some other small errors.
Used shellcheck.
Also fixes https://github.com/borgbackup/borg/issues/2816
Some errors, which were in the script:
* https://github.com/koalaman/shellcheck/wiki/SC1090
* https://github.com/koalaman/shellcheck/wiki/SC2076
* https://github.com/koalaman/shellcheck/wiki/SC2064
The modified parts of the quickstart script have been tested and it has exactly the same behaviour, i.e. "info" starts with a newline character and ends with ~one~ two, so that the line is separated by an empty line above and below.
Also this line has an alternative way with the same behaviour, I included there too. Choose what you like best. :smiley:

Fix bashism in shell scripts

---

docs/internals/data-structures.rst

After a user changes `segments_per_dir`, the path returned by
`segment_filename()` is incorrect because it calculates the path with the
new `segments_per_dir` value.
In this case, we try to find the segment path manually.  If we still
can't find the segment, there could be two reasons:
- The segment to be read is missing on disk;
- The segment to be written is not created yet.
For either reason, we return the path calculated with new
`segments_per_dir` value as-is and let the caller decide what to do.
If everything goes well, after some period of time (new data get backed
up while old ones get pruned), segments will eventually be in their
right place.

Document consequences of changing the segments_per_dir value

---

src/borg/_hashindex.c

Integer division is slow, and this improves the speed of all operations on the hashmap.
Benchmarks:
https://cdn.rawgit.com/rciorba/e3eded290e91a361f74eefdbc84416bb/raw/9e5d61e03c5842712d629e3e5567da3a512f1d79/results.html
Benchmarked this patch on the [rciorba/master-bench](https://github.com/borgbackup/borg/compare/master...rciorba:master-bench), where I applied the robin-hood benchmarks on master, if anyone cares to check the benchmark code

replace modulo with if to check for wraparound in hashmap

---

src/borg/archive.py
src/borg/cache.py

chunk_incref was called when dealing with part files without giving the
known chunk size in the size_ parameter.
adjusted LocalCache.chunk_incref to have same signature.

give known chunk size to chunk_incref, fixes #2853

---

docs/faq.rst

I haven't tested the macOS instructions yet, they were made with a careful reading of the security man pages. I also haven't made the equivalent tutorial for the KDE keyring equivalent (KWallet) yet.

Detail how to use macOS/GNOME/KDE keyrings for repo passwords (fixes #392)

---

src/borg/archiver.py

with-lock, info docs

---

setup.py
src/borg/archive.py
src/borg/crypto/_crypto_helpers.c
src/borg/crypto/_crypto_helpers.h
src/borg/crypto/key.py
src/borg/crypto/low_level.pyx
src/borg/crypto/nonces.py
src/borg/helpers.py
src/borg/selftest.py
src/borg/testsuite/archiver.py
src/borg/testsuite/crypto.py
src/borg/testsuite/key.py
src/borg/testsuite/nonces.py

crypto.pyx now implements a AEAD style API:
- encrypt-then-mac inside encrypt(), optionally mac-ing additional data
- auth-then-decrypt inside decrypt(), optionally auth-ing additional data
Implements:
- aes-ctr-hmac-sha256, aes-gcm
- aes-ocb, chacha20-poly1305 (openssl 1.1)
- simple AES, still needed by the keyfile code
- unencrypted/unauthenticated (so we do not need to specialcase that)
Note about iv/nonce/counter handling:
cipher.encrypt() and .decrypt() always do a full openssl context init, thus it is required for encrypt to set a IV before the call (or give iv as encrypt() param). there is no IV state kept inside the openssl ctx which is used for next encrypt() call.
set_iv sets the iv to use for next encrypt() call, it also resets the blocks counter that is used to reflect how …

new crypto code, blackbox, aead internally

---

src/borg/crypto/low_level.pyx
src/borg/testsuite/crypto.py

crypto: fixes & remove AES-GCM

---

Vagrantfile

Vagrantfile is maintained in 1.1-maint for now, master copy has no netbsd.

Vagrant fixes

---

borg/archiver.py

(cherry picked from commit 583de3eeb15ba9f1c5574691eb42a9d10270a5a9)
backport of #2918

fix exitcode of borg serve, fixes #2910

---

src/borg/fuse.py
src/borg/helpers/checks.py
src/borg/helpers/process.py
src/borg/locking.py
src/borg/platform/base.py
src/borg/platform/darwin.pyx
src/borg/platform/freebsd.pyx
src/borg/platform/linux.pyx
src/borg/platform/posix.pyx
src/borg/repository.py
src/borg/testsuite/locking.py

fixes #2923 
the pid change due to daemonize didn't work well with the stale lock detection (as the initial/parent process was gone). thus we better transfer the locks to the new pid.
this is only needed for client-side (local) repos because the daemonize happens there.
remote repos are locked by borg serve and the pid problem does not happen there.

migrate locks to child PID when daemonize is used

---

docs/internals/frontends.rst
src/borg/remote.py
src/borg/repository.py
src/borg/testsuite/archiver.py
src/borg/testsuite/upgrader.py
src/borg/upgrader.py

When coming accross an invalid segment, explicitly check for the Attic
segment MAGIC. If an Attic segment is detected, raise a dedicated
exception, telling the user to upgrade the repository first.
Fixes #1933.

Detect non-upgraded Attic repositories

---

borg/cache.py

this addresses a problem that was already fixed in 1.1+ in a different
way (by protecting important files with hashes/checksum and invalidating
them when the check fails).
for 1.0, just do a simpler fix, ignore the files cache when corrupt and
emit a warning message so the users notices that there is a problem.

ignore corrupt files cache, fixes #2939

---

src/borg/cache.py

Currently begin_txn is not explicitly used outside tests, but its not really private.

cache: adjust AdHocCache API

---

.travis.yml

if a branch build is stopped, then codecov will complain about
missing base branch coverage.

travis: only short-circuit docs-only changes for pull requests

---

src/borg/helpers/datastruct.py

Instead of backporting, just remove threading-related things from older branches.

Buffer: fix wrong thread-local storage use

---

borg/helpers.py

Buffer: delete support for multiple threads
Thread-local objects are a fairly complex footgun, so avoid them in
the first place. When a Compressor uses a Buffer (for example),
just create multiple Compressor instances for each thread, owned by
each thread. Minimize multiple ownership of objects across
threads if at all possible!
(cherry picked from commit f7ed5d72201b0791a50707aefc68bcd22f12c800)

Buffer: fix wrong thread-local storage use (#2951)

---

src/borg/testsuite/archiver.py

since mount is not always available and if it works for all the other
commands, then it is likely it works for mount as well.
Fixes #2975

test_detect_attic_repo: don't test mount

---

src/borg/repository.py

so we can know whether it did a cleanup and if so,
which and how many segments were cleaned up.

add debug logging for repository cleanup

---

docs/faq.rst

The macOS keychain integration guide is missing a `-w` in the `BORG_PASSCOMMAND` environment variable. This flag causes only the password to be written to stdout. Without this flag the integration does not work.

Improve macOS faq entry

---

src/borg/archiver.py

found this while debugging, guess it is a little cleaner with this change, esp. when people invoke rsync as subprocess to sync the repo elsewhere.

with-lock: close segment file before invoking subprocess

---

src/borg/helpers/progress.py

if borg stderr is not connected to a tty, but to ssh (when using
borg client/server), sys.stderr is block buffered (tty: line buffered).
thus we better flush explicitly after emitting a line as the receiving
side can not handle partial json at the end of the block.
also, it might solve some delays, when output didn't arrive at
receiving side in time.
hopefully a partial fix for #2637 (progress indication in json mode)

flush json mode progress stderr output

---

src/borg/helpers.py

if borg stderr is not connected to a tty, but to ssh (when using
borg client/server), sys.stderr is block buffered (tty: line buffered).
thus we better flush explicitly after emitting a line as the receiving
side can not handle partial json at the end of the block.
also, it might solve some delays, when output didn't arrive at
receiving side in time.
(cherry picked from commit 2b75b278dab59b18a64aeb627bfcfc259804e825)

 flush json mode progress stderr output (1.1-maint)

---

Vagrantfile

3.5.4 is the latest (and maybe also the last) python 3.5 release.

use python 3.5.4 to build the binaries

---

Vagrantfile

v3.3 release does not work on freebsd, so fetch it from a branch where I can quickly commit fixes.

pyinstaller: use v3.3, fetch from v3.3-fixed branch

---

src/borg/remote.py

the client_supports_log_v3 flag was added to differentiate 1.1.0 beta3
to beta5 clients (which did not support parsing json log format from
server) from >= 1.1.0beta6 clients (which support it).
for clients older than 1.1.0b3, no json log format will be negotiated
anyway.
by removing the client_supports_log_v3 flag support, we drop support for
clients using 1.1.0beta3..5.
thus, a client is now expected to either support old log format (like
borg 1.0.x) or new json format (like borg 1.1.0 >= beta6).
```
client     server comment
===========================================
any        0.29+  uses $LOG plain remote log format
any        1.0.x  uses $LOG plain remote log format
1.0.x      1.1.0  uses $LOG plain remote log format
1.1.0b1/b2 1.1.0  (uses $LOG plain remote log format)
1.1.0b3-b5 …
```

remove client_supports_log_v3 flag, fixes #3033

---

docs/faq.rst

Exporting $RATE as environment variable is not need in this case.
And example does not use any bash specific features.
It should use default system shell instead.

Simplified rate limiting wrapper in FAQ

---

src/borg/remote.py
src/borg/testsuite/repository.py

due to block buffering (in borg, pipes, sshd, ssh) partial lines might
be received. for plain text, this causes cosmetic issues, for json it
causes tracebacks due to parse errors.
the code now makes sure handle_remote_line() only gets called with a
complete line.
it also fixes a yet undiscovered partial utf-8-sequence decoding issue
that might occur for the same reason.

remote: deal with partial lines, fixes #2637

---

docs/faq.rst

Exporting $RATE as environment variable is not need in this case.
And example does not use any bash specific features.
It should use default system shell instead.
(cherry picked from commit f7ec13eabb3751de93bda08003b58e5a76be6f9e)

Simplified rate limiting wrapper in FAQ (1.1-maint)

---

docs/faq.rst

Exporting $RATE as environment variable is not need in this case.
And example does not use any bash specific features.
It should use default system shell instead.
(cherry picked from commit d3533de5f7f113dbcf4668524c89a04467947ee8)

Simplified rate limiting wrapper in FAQ (1.0-maint)

---

src/borg/remote.py
src/borg/testsuite/repository.py

due to block buffering (in borg, pipes, sshd, ssh) partial lines might
be received. for plain text, this causes cosmetic issues, for json it
causes tracebacks due to parse errors.
the code now makes sure handle_remote_line() only gets called with a
complete line (which is terminated by any universal newline char, a
pure \r seems to be needed for remote progress displays).
it also fixes a yet undiscovered partial utf-8-sequence decoding issue
that might occur for the same reason.
(cherry picked from commit 8646216a062364efb3179285d21884d95b87f1c8)

remote: deal with partial lines, fixes #2637 (1.1-maint)

---

requirements.d/development.txt

https://github.com/cython/cython/issues/1880

exclude Cython 0.27(.0) in requirements, fixes #3066

---

docs/internals/data-structures.rst
src/borg/archive.py
src/borg/archiver.py
src/borg/cache.py
src/borg/constants.py
src/borg/helpers/parseformat.py
src/borg/testsuite/archiver.py

You can now control the files cache mode using this option:
--files-cache={ctime,mtime,size,inode,rechunk,disabled}*
(only some combinations are supported)
Previously, only these modes were supported:
- mtime,size,inode (default of borg < 1.1.0rc4)
- mtime,size (by using --ignore-inode)
- disabled (by using --no-files-cache)
Now, you additionally get:
- ctime alternatively to mtime (more safe), e.g.:
ctime,size,inode (this is the new default of borg >= 1.1.0rc4)
- rechunk (consider all files as changed, rechunk them)
Deprecated:
- --ignore-inodes (use modes without "inode")
- --no-files-cache (use "disabled" mode)
The tests needed some changes:
- previously, we use os.utime() to set a files mtime (atime) to specific
values, but that does not work for ctime.
- now use time.sleep() to …

implement files cache mode control, fixes #911

---

docs/quickstart.rst

Minor grammar correction and added consistency with substitution of 'Borg' in quickstart guide.

Quickstart guide minor corrections

---

setup.py

we do not test on 3.4 any more and have dropped support for it.
so we better enforce it in setup.py also.

check for py 3.5 minimum requirement in setup.py

---

docs/faq.rst

(cherry picked from commit 1e370d4d23033214e0bcd52ad8daca58beda0d19)
also backport comment about borg check --repair warning.

faq: we do not implement futile attempts of ETA / progress displays

---

src/borg/compress.pyx
src/borg/testsuite/compress.py

if it is not significantly better compressed, we just store lz4 compressed data (which we already have computed anyway), because that at least decompresses super fast.

auto compression: make sure expensive compression is actually better

---

docs/man_intro.rst

(cherry picked from commit 62e0f7a64e8950863ab53c05f9bf8c4597d16e6e)

manpage: fix typos, update homepage

---

docs/usage/list.rst

Should be pushed to master and 1.1-maint.

use --format rather than --list-format in examples, the latter is deprecated

---

src/borg/archive.py

filenames like ..foobar are valid, so, to detect stuff in upper dirs,
we need to include the path separator and check if it starts with '../'.

fix detection of non-local path, fixes #3108

---

src/borg/archiver.py
src/borg/crypto/key.py

(cherry picked from commit b00179ff784fbd959d7ee1e331ac62a1c9bbc25a)

init: fix wrong encryption choices in command line parser

---

src/borg/helpers.py

(cherry picked from commit 7a689b1295ca647a7f9008df508f303214930d08)

don't crash in first part of truncate_and_unlink, fixes #3117

---

src/borg/repository.py

(cherry picked from commit 203a5c8f197904b51fbced32f42cf0c383130292)

catch ENOTSUP for os.link, fixes #3107

---

src/borg/archiver.py

while the files cache is only really used by borg create, the value
of this argument is used for the Cache context manager at more places,
e.g. also for borg prune.

move files-cache related options to borg create, fixes #3146

---

src/borg/archiver.py

for borg prune, just use do_files=False (it only needs the chunks cache, not the files cache).
(cherry picked from commit 19ed725a58b58901d22dbcdb74d22cf029c468d1)

move --no-files-cache from common to borg create options, fixes #3146

---

src/borg/archive.py

when doing in-file checkpointing, borg creates *.borg_part_N files.
complete_file = part_1 + part_2 + ... + part_N
the source item for recreate already has a precomputed (total) size
member, thus we must force recomputation from the (partial) chunks
list to correct the size to be the part's size only.
borg create avoided this problem by computing the size member after
writing all the parts. this is now not required any more.
the bug is mostly cosmetic, borg check will complain, borg extract on
a part file would also complain. but all the complaints only refer to
the wrong metadata of the part files, the part files' contents are
correct.
usually you will never extract or look at part files, but only deal
with the full file, which will be completely valid, all metadata and
content.
you can …

borg recreate: correctly compute part file sizes, fixes #3157

---

src/borg/cache.py

Looks like under unfortunate circumstances, these files could become
0 byte files (see #3158). SaveFile usage should prevent that.

cache: use SaveFile for more safety, fixes #3158

---

src/borg/archive.py
src/borg/archiver.py
src/borg/testsuite/archiver.py

do no read/archive bsdflags: borg create --nobsdflags ...
do not extract/set bsdflags: borg extract --nobsdflags ...
use cases:
- fs shows wrong / random bsdflags (bug in filesystem)
- fs does not support bsdflags anyway
- already archived bsdflags are wrong / unwanted
- borg shows any sort of unwanted effect due to get_flags, esp. on Linux
the nodump flag ("do not backup this file") is not honoured any more by
default because this functionality (esp. if it happened by error or
unexpected) was rather confusing and unexplainable at first to users.
if you want that "do not backup NODUMP-flagged files" behaviour, use:
borg create --exclude-nodump ...
(cherry picked from commit 10adadf685df0fa4da9f7c3d23891d997ff3395e)

implement --nobsdflags and --exclude-nodump, fixes #3160

---

docs/faq.rst
src/borg/archive.py

the warning was annoying for people with a lot of such items and
they can not do anything about it anyway.
thus, just document this as a limitation.
(cherry picked from commit e674822888d12932216cfd9ff15f18ad77676d67)

remove hardlinked symlinks warning, update docs, fixes #3175

---

docs/installation.rst

It may be more common to use declarative means, but this will tell NixOS users the package name and it's a valid install command.

Add Nix/NixOS install command

---

src/borg/crypto/key.py

(cherry picked from commit 7136e2c93c4de7d2500dfe5f3d1e5120b58eee21)

fix crash with relative BORG_KEY_FILE, fixes #3197

---

src/borg/remote.py

borg 1.1(.0) server didn't support the 4 argument open() calls made by < 1.0.7 clients.
@textshell can you have a look at this and #3192 also?

fix server-side IndexError for 4-arg open() of old clients, fixes #3192

---

src/borg/archiver.py

This is a fixup for #3155, which was broken on at least python <= 3.4.2.
Also clarify when to use which *func in set_defaults.
(cherry picked from commit 5ce4fa970413e3cedbc36e2f728863eaa69dad21)

arg parsing: fix fallback function, refactor, fixes #3205

---

docs/faq.rst

Fixes #3214. Also corrected the [password example](http://www.bash.org/?244321).

Clarify using a blank passphrase in keyfile mode

---

docs/faq.rst

Clarify using a blank passphrase in keyfile mode (1.1 backport)

---

docs/usage_general.rst.inc

As discussed in the PR: https://github.com/borgbackup/borg/pull/3217, added the documentation for BORG_CONFIG_DIR. 
@ThomasWaldmann, Please let me know if any changes are required.

Added documentation for BORG_CONFIG_DIR

---

docs/development.rst
docs/faq.rst
docs/global.rst.inc
docs/installation.rst
docs/internals/data-structures.rst
docs/quickstart.rst
docs/support.rst

Removed |project_name| in documentation to make it more readable.  Replaced with "Borg".

Removal of |project_name|.

---

src/borg/fuse.py

Still on the way to #2475. This again does not alter any functionality, it just does what @enkore proposed in a comment on the linked issue:
> (Edit: In fact, it seems like a fairly good idea in general to separate the generation of items from the actual FuseOps implementation).
This is a straight separation without changing the concepts. Probably when actually working with it to create the diff mounting functionality, there will be reason for "real" change.

fuse: Separate creation of filesystem from implementation of llfuse funcs

---

src/borg/archiver.py
src/borg/helpers/misc.py
src/borg/testsuite/archiver.py
src/borg/testsuite/helpers.py

Prune now shows for each kept archive:
* Which rule is responsible for keeping this archive
* How many archives have been kept by this rule so far
Ref #2886
Here's an example output:
```
Sun Oct 29 16:14:18 CET 2017 Pruning repository
Keeping archive (rule: secondly #1):     somehost-2017-10-29T16:14:17            Sun, 2017-10-29 16:14:17 [585c3f70354e0af201c7eb921a7bcf255178641712ca6f6a1ca1bfe3cf5668e8]
Pruning archive (1/1):                   somehost-2017-10-29T14:57:33            Sun, 2017-10-29 14:57:33 [9e9d5dd39948802af0f15c4ef19671f0ba90fad4bca134f62d9c5933acfde070]
Keeping archive (rule: daily #1):        somehost-2017-10-28T17:21:03            Sat, 2017-10-28 17:21:03 [b38fb5535b29e587b9332b8804bd9adc7a6a914b0910da4b8d392b8feb4305da]
```

prune: Show which rule was applied to keep archive

---

src/borg/remote.py

value type of compatMap is a tuple of strings.
due to the trailing comma, this was a 1-tuple of a tuple of strings.

remove evil trailing comma, fixes #3244

---

src/borg/remote.py

value type of compatMap is a tuple of strings.
due to the trailing comma, this was a 1-tuple of a tuple of strings.
(cherry picked from commit 117d30d17126f2118e43dec2f08d502d3369f6c8)

remove evil trailing comma, fixes #3244 (1.1)

---

src/borg/archiver.py

they are not used for borg list.
```
$ borg list --help
...
--exclude-caches      exclude directories that contain a CACHEDIR.TAG file
(http://www.brynosaurus.com/cachedir/spec.html)
--exclude-if-present NAME
exclude directories that are tagged by containing a
filesystem object with the given NAME
--keep-exclude-tags, --keep-tag-files
if tag objects are specified with ``--exclude-if-
present``, don't omit the tag objects themselves from
the backup archive
```

borg list: remove tag-file options, fixes #3226

---

src/borg/archiver.py

they are not used for borg diff.

borg diff: remove tag-file options, fixes #3226

---

src/borg/archiver.py

always use sys.stdout.write as in main() we have replaced that with a
handler that deals with BrokenPipe exceptions.
also simplify (remove) encode/decode dance as format_item (get_item_data) already removes surrogates.

borg list: fix broken pipe handling, fixes #3245

---

src/borg/archive.py

(cherry picked from commit 66cd1cd240f078e2d5c9e32656b42dccf2d62935)

stats: do not count data volume twice when checkpointing, fixes #3224

---

src/borg/archiver.py

Fixes #3298. `borg create --dry-run` doesn't actually compress/dedupe data, so it can't display stats on the created archive. Previously, running `borg create --dry-run --stats` would fail silently (by not showing stats).

Show an error message when --dry-run & --stats are used simultaneously

---

src/borg/archiver.py

Fixes #3296. Also explicitly documented the `--qr-html` option in the `borg key export` help.

Clarify encryption of key for borg key export

---

docs/changes.rst
docs/faq.rst
docs/internals/data-structures.rst

Documentation corrections to replace incorrect usage of the word "less" with the word "fewer". See 
https://en.oxforddictionaries.com/usage/less-or-fewer or https://en.wikipedia.org/wiki/Fewer_vs._less for further explanation.

Correct usage of "fewer" in place of "less"

---

docs/faq.rst

Clarify create --stats duration vs. wall time (1.1-maint)

---

src/borg/archiver.py

Show an error when --dry-run & --stats are both used (1.1-maint)

---

docs/usage/borgfs.rst
setup.py
src/borg/archiver.py

I also fixed the borgfs help text so it no longer says it needs the `mount` subcommand as well.
Fixes #3287 and #3216.

Generate usage & man page for borgfs

---

src/borg/archive.py
src/borg/archiver.py
src/borg/constants.py
src/borg/item.pyx
src/borg/testsuite/__init__.py
src/borg/testsuite/archiver.py

This adds birth times (macOS creation date) to the archive, to resolve #3272. I'm new to this codebase so I expect there will be things I messed up. I took a wild guess that adding keys to `Item` was OK and that a new (post-1.1) `int` field didn't need a `bigint` wrapper.

include item birthtime in archive (where available)

---

src/borg/testsuite/archiver.py

I only realized after #3290 was merged that the code used for finding which man pages to generate was duplicated in the testsuite (I assume since setup.py can't import from the installed module and vice versa) to know what .rst files to check. Apparently the validity of the `borgfs` help document wasn't being checked, but the document itself was fine. I copied this fix into #3311 (the 1.1 backport for the original `borgfs` man page) because it was still open, so this PR doesn't need a backport.

Check borgfs rst formatting in tests

---

src/borg/algorithms/crc32_slice_by_8.c
src/borg/testsuite/checksums.py

fixing only the (generic) slice-by-8 crc32 implementation,
it is assumed that CPUs supporting CLMUL can also efficiently
and correctly deal with unaligned accesses.
slice-by-8 is used e.g. on ARM cpus and they might not (efficiently)
support unaligned memory access, leading to bus errors or low
performance.

crc32: deal with unaligned buffer, tests, fixes #3317

---

src/borg/cache.py

Deleting the cache will not bypass this error in the event the user knows this is a legitimate repo.
Change points the user in the right direction in the event that they obtain an old copy of a repo and want to resume backups to it.

Highlight that information is obtained from security dir

---

docs/faq.rst

See #3325, the fixup is rolled into the commit on this PR

Document sshfs rename workaround (1.1 backport)

---

docs/changes.rst
docs/faq.rst
docs/internals/data-structures.rst

Correct usage of "fewer" in place of "less" (1.1 backport)

---

src/borg/archiver.py
src/borg/fuse.py
src/borg/testsuite/archiver.py

borg mount [options] repo_or_archive mountpoint path [paths...]
paths: you can just give some "root paths" (like for borg extract) to
only partially populate the FUSE filesystem.
Similar for these exclusion group options:
--exclude
--exclude-from
--pattern
--patterns-from
--strip-components

borg mount: support exclusion group options and paths, fixes #2138

---

docs/faq.rst
docs/quickstart.rst
docs/usage.rst
docs/usage/config.rst
docs/usage/notes.rst
setup.cfg
src/borg/archiver.py
src/borg/helpers/parseformat.py
src/borg/testsuite/archiver.py

Fixes #3304. Similar to [`git config`](https://git-scm.com/docs/git-config), this command parses repo and cache configs to get, set, and delete values. It only works on local repos so a malicious client can't do something like override their `storage_quota` or reset `append_only`. It's a small addition, but the docs mention editing the config file often enough that I think it makes sense to have a command for it.
I still need to:

Add borg config command

---

MANIFEST.in
setup.py

1.1.2 was released with a sdist that included quite some files that
did not belong into the package (I tried nuitka at some time).
This was because the old MANIFEST.in / setup.py included all the stuff
in the package dir.
Now, setuptools_scm is to automatically deal with the INCLUDES and
MANIFEST.in only handles the EXCLUDES, so only committed files get
into the sdist (minus some we do not want).
Also, no .c .h .pyx files will be installed - they are not needed as
they have been compiled into binary files.
(cherry picked from commit feb428b4e012686d42cf0240663660757dcf231a)

clean up and simplify packaging (1.1-maint)

---

src/borg/archiver.py

This is really pedantic, but I forgot to change this earlier when @ThomasWaldmann suggested it and now it's really bugging me :P. `borg config` changes cfg values in general, not just the repo ones. I squashed this change into #3359 already.

Reword borg config help

---

setup.py
src/borg/archiver.py

Fixes #3364, except for the last warnings, which seem harmless anyway. Somebody could open an issue for sphinx as detailed [here](https://github.com/borgbackup/borg/issues/3364#issuecomment-346976483) to get rid of the last warnings if they were a little less lazy than me.

Fix build_man issues

---

README.rst
docs/development.rst

fixed support links
(cherry picked from commit 6dd54f93cefe1a1e273fce796a5fb3a39a882b27)
backport features added in https://github.com/borgbackup/borg/pull/3379

fixed support links (#3379)

---

docs/support.rst

otherwise people ONLY reading the docs (and not coming from the
homepage) will miss these options.
(cherry picked from commit 7438cb2ef48e3cad9c220fc25de0a462a425bed8)

link to the homepage for support/service

---

setup.py

Fixes #3404. This one was my fault: I thought because it wasn't listed in the TOC, there was no harm in generating it anyway; turns out it still shows up in the search results :P

Don't generate HTML docs page for borgfs

---

setup.py

Don't generate HTML docs page for borgfs (1.1 backport)

---

docs/usage.rst
docs/usage/config.rst.inc

also: move a bit upwards in the use docs
(cherry picked from commit 278ed640e909a50641a8e410d414dd4de9ba8879)

add auto-generated docs for borg config

---

docs/usage.rst
docs/usage/config.rst.inc

also: move a bit upwards in the use docs

add auto-generated docs for borg config (1.1)

---

docs/man/borg-placeholders.1
docs/usage/help.rst.inc
src/borg/archiver.py
src/borg/helpers/parseformat.py

This allows for having lexicographic sorting coincide with domain structure without having to hardcode fqdns in automated scripts.

Add placeholder for fqdn in reverse notation

---

src/borg/archiver.py

Currently, the available help topics are only listed manually, scattered throughout different parts of the documentation.  
It would be helpful to have an option for `borg help` that lists all available topics (e.g. `borg help --list-topics`).
Until that's implemented, this commit adds a list of available topics to the "topic not found" error message.  
This might also remain useful even after the separate flag has been added. Alternatively, we could replace the list with a mention of the new `--list-topics` once that exists.

List help topics when invalid topic is requested

---

setup.py

will fix all ".. highlight:: none" issues (just killing it).
also a slight punctuation fix, so there is a dot at the end of the prune man page.

fix building the "borg prune" man page, fixes #3398

---

src/borg/_chunker.c
src/borg/_hashindex.c

this is needed for correctness because the preprocessor is just doing text replacement.
This is the correct way:
```
#define MUL(x, y) ((x) * (y))
MUL(1+2, 3-4) -> ((1+2) * (3-4))    # not: (1+2 * 3-4)
```
I didn't put parens around all arg usages for readability.
Some stuff (like index) is not expected to be an expression.
Also, when a arg is only used in another macro or function call, no parens are needed either.
I reviewed the code: no harm was done (yet) due to this fault.
Thanks to @rciorba for finding this.

add parens for C preprocessor macro argument usages

---

src/borg/archive.py
src/borg/testsuite/archiver.py

due to a malfunctioning validator, resyncing to the next item metadata dict in the archive metadata stream after a lost / zero-replaced chunk did not work.
this is a borg 1.1 regression, code in 1.0 is fine.

fix for borg check --repair malfunction, #3444 (1.1-maint)

---

docs/3rd_party/lz4/LICENSE
docs/installation.rst
docs/usage_general.rst.inc
setup.py
setup_lz4.py
src/borg/algorithms/lz4-libselect.h
src/borg/algorithms/lz4/lib/lz4.c
src/borg/algorithms/lz4/lib/lz4.h
src/borg/compress.pyx
src/borg/helpers/checks.py

Bundle lz4 and do it like the zstd part, for code consistency. See #3415.
We can finally get rid of the deprecation warning and raise lz4 requirement to >= 1.7.0 / r129.
readthedocs build: checked source, should be still fine.

compress ext building (lz4 part)

---

docs/internals/security.rst

docs: Fix missing apostrophe

---

src/borg/archiver.py

This is a really unimportant issue, but when the message about the manifest spoofing check is printed by `borg init`, if your repository path has a quote in it, then the command Borg prints won't be valid. This fixes that by passing the path through [`shlex.quote`].
[`shlex.quote`]: https://docs.python.org/3/library/shlex.html#shlex.quote
example: this invalid command
borg upgrade --disable-tam '/path/test'repo'
is now printed as
borg upgrade --disable-tam '/path/test'"'"'repo'

Properly quote repo path in `borg init` output

---

src/borg/archiver.py

writing the storage_quota into the repo config at `borg init` time worked for remote repos, but not for local ones.

borg init: use given --storage-quota for local repo, fixes #3470

---

src/borg/archiver.py

Instead of printing this invalid command:
borg upgrade --disable-tam '/path/test'repo'
print this valid one:
borg upgrade --disable-tam '/path/test'"'"'repo'
(cherry picked from commit e7806608309b52e4aa71be306d967083b28d46f9)

Properly quote repo path in `borg init` output (1.1)

---

borg/_chunker.c
borg/_hashindex.c

this is needed for correctness because the preprocessor is just
doing text replacement.
This is the correct way:
#define MUL(x, y) ((x) * (y))
MUL(1+2, 3-4) -> ((1+2) * (3-4))    # not: (1+2 * 3-4)
I didn't put parens around all arg usages for readability.
Some stuff (like index) is not expected to be an expression.
Also, when a arg is only used in another macro or function call,
no parens are needed either.
I reviewed the code: no harm was done (yet) due to this fault.
Thanks to @rciorba who found this.
(cherry picked from commit 981a936f47473e8c3a16595264a1be0b064fad12)

add parens for C preprocessor macro argument usages (1.0-maint)

---

src/borg/repository.py

Fixes #3465.
Examples:
```
$ borg init -e none /tmp/borg-test/
Files not created by Borg already exist at /tmp/borg-test.
$ borg init -e none /tmp/borg-test/foo
/tmp/borg-test/foo is not a directory.
```
whereas previously this would have happened:
```
$ borg init -e none /tmp/borg-test/
A repository already exists at /tmp/borg-test.
$ borg init -e none /tmp/borg-test/foo 
A repository already exists at /tmp/borg-test/foo.
```
Notes:
- this presumably needs tests, I have no idea how to even start doing that
- I'm open to suggestions on the exact wording of the new error messages

Correct some confusing error messages from `borg init`

---

docs/internals/data-structures.rst

Storage in the keyfile implies to me that the chunk seed is unique per /repository/ not archive; otherwise deduplication would hardly work.
Is this correct?

Chunk seed is generated per /repository/

---

setup.py

maybe this is the easiest way for us to deal with msgpack compatibility.
0.5.0 release had some troubles:
- FutureWarning on stderr disturbing other output there, breaking tests
- pip install -U broken due to a pip issue with the transisition pkg
which was needed due to the package rename (ImportError for msgpack)
- some linux dists not packaging the transition pkg
- dropped py34 support/testing

require msgpack >= 0.4.6 and < 0.5.0 (1.0-maint).

---

setup.py

maybe this is the easiest way for us to deal with msgpack compatibility.
0.5.0 release had some troubles:
- FutureWarning on stderr disturbing other output there, breaking tests
- pip install -U broken due to a pip issue with the transisition pkg
which was needed due to the package rename (ImportError for msgpack)
- some linux dists not packaging the transition pkg
- dropped py34 support/testing

require msgpack >= 0.4.6 and < 0.5.0 (1.1-maint).

---

setup.py

maybe this is the easiest way for us to deal with msgpack compatibility.

require msgpack >= 0.4.6 and < 0.6.0, exclude 0.5.0

---

.travis/install.sh

suggested as work around on the travis issue about this ruby version
issue (wanted: 2.3, having: 2.0).

travis osx: run brew update first, fixes #3527

---

.travis/install.sh

suggested as work around on the travis issue about this ruby version
issue (wanted: 2.3, having: 2.0).
(cherry picked from commit e4828078bbc6ceba34a1b923b4c50a31b10b4f08)

travis osx: run brew update first, fixes #3527 (1.0)

---

src/borg/cache.py
src/borg/testsuite/archiver.py

now deals with:
- corrupted files cache (truncated or modified not by borg)
- inaccessible/unreadable files cache
- missing files cache
The latter fix is not sufficient, the cache transaction processing
would still stumble over expected, but missing files in the cache.

files cache: improve exception handling, fixes #3553

---

src/borg/cache.py
src/borg/testsuite/archiver.py

now deals with:
- corrupted files cache (truncated or modified not by borg)
- inaccessible/unreadable files cache
- missing files cache
The latter fix is not sufficient, the cache transaction processing
would still stumble over expected, but missing files in the cache.

files cache: improve exception handling, fixes #3553 (1.1)

---

setup.py
setup_b2.py
setup_lz4.py
setup_zstd.py

we can't know the encoding header file authors will use, so using binary for our simple checks is the safest way.

do .h file content checks in binary mode, fixes #3544

---

src/borg/archive.py
src/borg/cache.py
src/borg/testsuite/archiver.py
src/borg/testsuite/cache.py

the problem was that the upper layer code did not have enough information
about the file, whether it is known or not - and thus, could not decide
correctly whether status should be M)odified or A)dded.
now, file_known_and_unchanged method returns an additional "known"
boolean to fix this.
another small fix is to not load the files cache in cache_mode='r' -
in this rechunk mode, files are always considered unknown and get
rechunked, so the files cache is not needed.

fix borg create never showing M status

---

docs/internals.rst

This backports #3520 to 1.0-maint as requested in #3644. Hopefully I've understood the request correctly and got it how you want, let me know if not.

Backport #3520 to 1.0-maint

---

docs/internals/data-structures.rst

This backports #3520 to 1.1-maint as requested in #3644

Backport 3520 to 1.1-maint

---

README.rst
docs/usage_general.rst.inc

This backports #3589 to 1.1-maint as requested in #3645.

Backport 3589 to 1.1-maint

---

.travis/install.sh

This backports #3604 to 1.1-maint as requested in #3646.

Backport #3604 to 1.1-maint

---

src/borg/testsuite/compress.py

This backports #3607 to 1.1-maint as requested in #3646.

Backport #3607 to 1.1-maint

---

src/borg/archive.py
src/borg/cache.py
src/borg/testsuite/archiver.py
src/borg/testsuite/cache.py

This backports #3633 to 1.1-maint as requested in #3646.

Backport #3633 to 1.1-maint

---

src/borg/crypto/low_level.pyx

fix a false positive compiler warning about olen being referenced
before assignment (which is not true, see comments in #3490).
master only, no 1.1 / 1.0 backport needed.

make the C compiler happy, fixes #3490

---

docs/support.rst

Previously the GPG output in support.rst was formatted as a blockquote, so the linebreaks would not be preserved (at least when viewing directly on GitHub):
Formatting it as a literal block preserves the linebreaks:

Improve formatting of GPG output in documentation

---

src/borg/patterns.py

say what the real problem is.
say what is valid.
fixes #3575.
TODO: there is still the ugly traceback. is this expected when raising that argparse exception?

be more helpful when parsing invalid --pattern values

---

docs/support.rst

Improve formatting of GPG output in documentation (backport to 1.0)

---

docs/support.rst

Improve formatting of GPG output in documentation (backport to 1.1)

---

src/borg/archiver.py

Just checking for None in patterns.py (and removing the set_defaults
calls in archiver.py) did not work as other arg parsing code relies on
having an empty list (in .patterns, .paths) to append to.
Thus I stayed away from pattern.py and rather fixed the defaults for
.paths and .patterns in all parsers.
@nachtgeist ^

fix borgfs patterns/paths processing, fixes #3551

---

docs/conf.py

Running Sphinx v1.4.8
WARNING: the config value 'copyright' is set to a string with non-ASCII characters; this can lead to Unicode errors occurring. Please use Unicode strings, e.g. u'Content'.
[...]
Encoding error:
'ascii' codec can't decode byte 0xc3 in position 23: ordinal not in range(128)
Running `make epub` on a Ubuntu 16.10 system.

Mark up Unicode string

---

docs/internals/security.rst

I thought I included this from the start, but obviously I didn't.

sec docs: explicitly note what happens OUTSIDE the attack model

---

src/borg/archive.py
src/borg/archiver.py

When called with --progress, the progress was always showing
0 B O 0 B C 0 B D 0 N.
This is fixed by this commit.
Fixes https://github.com/borgbackup/borg/issues/3431

Fix --progress option.

---

src/borg/archiver.py

@enkore ^^^
borg recreate --help looks now like this:
```
...
--recompress [MODE]   recompress data chunks according to ``--compression``.
MODE `if-different`: recompress if current compression
is with a different compression algorithm (the level
is not considered). MODE `always`: recompress even if
current compression is with the same compression
algorithm (use this to change the compression level).
MODE `never` (default): do not recompress.
...
```

recreate --recompress: add metavar, clarify description

---

src/borg/archive.py
src/borg/archiver.py
src/borg/cache.py
src/borg/testsuite/cache.py

read files cache early, if at all - not lazy loading it.
this fixes checkpoint timing as the cache loading happens before the timer is initialized (see #3394).
also cleaned up: do_files and ignore_inode (used by legacy options) now mapped onto cache_mode.
needs forward port to master.

non-lazy files cache

---

src/borg/cache.py

This caused a really stupid bug with borg config --cache, see https://github.com/borgbackup/borg/issues/3304#issuecomment-371896766

Set cache previous_location on load instead of save (fixes #3304)

---

src/borg/crypto/key.py

if interactive passphrase query fails and the env vars are not set,
show a clear error message about this.
users often do 'BORG_PASSPHRASE=secret', forgetting the 'export'.
or they use sudo (and not sudo -E).
in both cases, the env vars won't be available for the borg process.

improve getpass user experience, see #3689

---

src/borg/testsuite/archiver.py

the borg command in the test has 0 path arguments.
Our PATH arg is specified with nargs='*', so that should be valid,
but it crashes python 3.4.0 .. 3.4.2. Python >=3.4.3 works.
no port to master needed, we require >= 3.5 there.

skip test if argparse is broken, fixes #3705

---

Vagrantfile

so after a vagrant up or vagrant reload (which both rsync), we
can just call the fs_init and run_tests provisioning steps and do
not need to call install_borg again.

Vagrant: move cleanup steps to fs_init, fixes #3706

---

src/borg/cache.py

See #3682. Applicable since #3700 included backport of config validation.

Set cache previous_location on load instead of save (1.1 backport)

---

Vagrantfile

Vagrant: xenial64 box now uses username 'vagrant' (1.2 forward-port)

---

Vagrantfile

Vagrant: move cleanup steps to fs_init (1.2 forward-port)

---

src/borg/archive.py
src/borg/archiver.py

- size inconsistencies
- file has all-zero replacement chunks
introduced new BackupError exception. when raised while extracting
files, gets handled via emitting a warning, setting rc=1 and
proceeding to next file.

set rc=1 when extracting damaged files, fixes #3448

---

src/borg/helpers/parseformat.py

{now} and {utcnow} should point to the same exact moment, but they don't because .now() and .utcnow() create two different objects at different times. Although the difference will be on the order of microseconds on all but the slowest machines, this bug still tickles my inner pedant...

Use same datetime object for {now} and {utcnow} (fixes #3548)

---

src/borg/helpers.py

Use same datetime object for {now} and {utcnow} (1.1 backport)

---

docs/usage_general.rst.inc
src/borg/helpers.py

Can be used:
- in case of troubles with the sysinfo code
- by borg backup providers who do not want to show system information

BORG_SHOW_SYSINFO=no to hide system information from exceptions

---

.github/ISSUE_TEMPLATE.md

This is a first stab at Github new issue template for borgbackup. Questions based on https://github.com/borgbackup/borg/issues/3773

Github new ISSUE_TEMPLATE.md

---

MANIFEST.in
setup.py

Hi, this is my first PR. I think my comments are mostly contained in the commit comments.
I've tried to keep it clean, but I couldn't resist unifying the setuptools/distutils imports up the top.
I'm not sure if moving the files needed to compile the C extensions into the manifest is desirable, but it seemed like the most sensible place. I think it's essentially the same behaviour as subclassing sdist and adding them to the file list there, but it's already built in.
I also don't know how readthedocs works, so I'm not sure if the lines that call cythonize (765-772) should be in the if not on_rtd block or out of it.

Update setup.py to use a newer Cython/setuptools API for compiling .pyx -> .c

---

MANIFEST.in

I noticed that archlinux has an identical coveragerc and wondered why.
Then noticed that our tox.ini (which we bundle into the pypi package)
needs .coveragerc, but we did not bundle it until now.

include .coveragerc, needed by tox.ini

---

docs/quickstart.rst

just refer to "borg init" docs rather than duplicating it in quickstart.

docs: fix and deduplicate encryption quickstart docs

---

setup.py

Python 3.7 requires llfuse >= 1.3.4.
Fixes https://github.com/borgbackup/borg/issues/3804

Add a version hint for llfuse for python3.7

---

.travis.yml

builds on xcode6.4 are broken since quite a while.
other xcode versions < 8.3 are also broken in the same way.

travis OS X: use xcode 8.3 (not broken)

---

src/borg/archiver.py

the `with_repository` context manager was setting up repository and cache (because the cache config can also get changed via `borg config`).
but, setting up the cache needed to load the manifest because it did some checks against that - and that needs the key / passphrase to unlock the key (which is unneeded if we just want to use borg config on the repo config).
to solve, I only set up the repository with `with_repository` CM and only set up the cache (and key/manifest) when a cache configuration change is desired.
the individual, minimal commits are easier to review than the overall change.

make "borg config repo" possible without key

---

src/borg/archiver.py

debug dump-repo-objs should not depend on a manifest obj (fwd port to master)

---

src/borg/archiver.py

borg delete was slower than required when it deleted multiple archives
as it committed repo and cache once per archive.
borg prune (doing a similar job) is faster as it commits only once for
all deleted archives.
borg delete now also only commits once and also (similar to borg prune)
only outputs a overall statistics for all deleted archives.
log output of borg delete was made similar to borg prune.

borg delete: only commit once, fixes #3823

---

src/borg/archiver.py

the old progress output was kind of broken:
Archiver() did output some progress when add_item was called.
Archive.delete() did output progress for a single archive deletion
but what we really want is a overall progress indication, advancing
the progress for each deleted archive.
fixes #3851

borg prune: improve progress display

---

setup.py

we temporarily used the updated, bundled lz4 and zstd code for testing
purposes, but now going back to using system provided libs by default.

revert to using system compression libs, fixes #3797

---

src/borg/archiver.py
src/borg/testsuite/archiver.py

Add --list option to dump the repo configuration / the default values.
Also: fixes argument order in borg config tests
(cherry picked from commit 73410861aef2fb4129469673a54e34e65f775422)

borg config --list <repo>, fixes #3612 (1.1 backport)

---

setup.py

Failure to use environment markers means the dependencies are unconditionally added at build time based on the host instead of being always present and evaluated at runtime on the target; e.g. wheels have the wrong information.
Also use python_requires. This teaches pip how to natively comprehend when the current version of python is not supported by borg.
Returns errors in the format:
borgbackup requires Python '>=3.5' but the running Python is $oldver
...
Doesn't look like borg officially provides wheels, and since it includes binary extensions anyway the wheels are both OS and python version dependent, but it's the principle of the matter. :D
Environment markers are nicer. They've also been around since late 2015, so they should be getting used more in projects.

Embrace environment markers (a.k.a. PEP 508 compliance)!

---

setup.py

MASTER BRANCH ONLY, DO NOT BACKPORT TO 1.1 or 1.0!
As there are no 0.4.x msgpack releases (under this new name, 0.4.x
used to be named "msgpack-python"), currently only 0.5.6 can be
recommended. See comments for other versions that are acceptable
under certain conditions.
We will add new msgpack versions later, after testing them.

switch to "msgpack" pypi pkg name, fixes #3890

---

src/borg/platform/__init__.py
src/borg/platform/darwin.pyx
src/borg/platform/freebsd.pyx
src/borg/platform/linux.pyx

it is assumed that posix == everything else than win32.

make swidth available on all posix platforms, fixes #2667

---

src/borg/archive.py
src/borg/cache.py
src/borg/hashindex.pyx

we just give how many "usable" hashtable entries we want and it computes
the hashtable capacity internally via int(usable / MAX_LOAD_FACTOR).

move capacity calculation to IndexBase, fixes #2646

---

src/borg/archiver.py

by better reflecting the syntax that should be used
(ie `REPO::ARCHIVE1`)

docs: improve diff doc

---

docs/usage_general.rst.inc

Linking tempfile docs helps to figure out, which default value might be
used, if TMPDIR is not set.

docs: add link to tempfile module

---

Vagrantfile

remove 3.5.0 pyenv python build - does not build (due to openssl 1.1?).

vagrant: stretch64: use pyenv to test on py36

---

src/borg/testsuite/compress.py

freebsd12 is unhappy with having to deliver 50MiB random in one go
and fails with BlockingIOError "temporary unavailable" when trying.
for test_lz4_buffer_allocation, it is good enough to fetch 5MiB and
concatenate that 10 times.

tests: fetch less data via os.urandom

---

.travis.yml
.travis/install.sh
Vagrantfile
setup.py
src/borg/archiver.py
tox.ini

if you do not have python 3.6.x, you can still use borg 1.1.x or 1.0.x.
another option is to use the fat binary from github releases, which includes python 3.6 and all other stuff needed.

drop support for python 3.5, fixes #3919

---

src/borg/xattr.py

found while working on #3918.
if #3918 gets merged into master, we do not need to forward port this to master as it replaces the buggy code.

Fix xattr ctypes

---

docs/installation.rst

- Updated `OS X` to the new `macOS` name
- Fuse 3.x is no longer just a prerelease
- Added instructions to install fuse via homebrew

Update installation instructions for macOS

---

src/borg/archive.py
src/borg/platform/base.py
src/borg/platform/linux.pyx

make bsdflags linux code fd-based

---

src/borg/archiver.py
src/borg/cache.py
src/borg/locking.py

in the absence of a specific lock_wait / timeout value (int, to timeout after waiting n seconds), the default of lock_wait / timeout is None (meaning to never timeout and wait forever).

cache lock: use lock_wait everywhere to fix infinite wait

---

docs/installation.rst

If you have python 3.7 installed and you would like to force 3.6 when installing from source.
Tested with MacOS High Sierra.

Installation from source - setting python interpreter version

---

src/borg/testsuite/archiver.py

It causes problems with the new caching in the py37 logger module.
Removing loggerDict.clear() fixes this and makes the tests work again.
Also, it does not seem to have any negative effect, neither on py36
nor on py37.
See also: https://bugs.python.org/issue34269
Thank you for contributing code to Borg, your help is appreciated!
Please, before you submit a pull request, make sure it complies with the
guidelines given in our documentation:
https://borgbackup.readthedocs.io/en/latest/development.html#contributions
**Please remove all above text before submitting your pull request.**

remove loggerDict.clear() from tearDown method, fixes #3805

---

src/borg/testsuite/archiver.py

most of the files created via self.create_test_files() are not needed.
the only one is the empty file, so just create it here.
also: move repo init to after test file creation.

minor change: simplify test setup

---

src/borg/archiver.py

if we are recursing an explicitly excluded directory, we are only
looking for explicitly included items, but we do not need to archive
tagged directories or the tag files themselves - they are all excluded
by the explicit exclusion already.
for performance reasons, we still determine whether a directory is
tagged and if it is, we do not recurse into it as there can't be any
included items in there.

don't archive tagged dir when recursing an excluded dir, fixes #3991

---

src/borg/archive.py
src/borg/archiver.py
src/borg/cache.py
src/borg/crypto/key.py
src/borg/fuse.py
src/borg/helpers/__init__.py
src/borg/helpers/msgpack.py
src/borg/remote.py
src/borg/repository.py
src/borg/testsuite/archive.py
src/borg/testsuite/archiver.py
src/borg/testsuite/helpers.py
src/borg/testsuite/key.py
src/borg/testsuite/repository.py

wrap msgpack to avoid future upstream api changes making troubles
or that we would have to globally spoil our code with extra params.
make sure the packing is always with use_bin_type=False,
thus generating "old" msgpack format (as borg always did) from
bytes objects.
make sure the unpacking is always with raw=True,
thus generating bytes objects.
note:
safe unicode encoding/decoding for some kinds of data types is done in Item
class (see item.pyx), so it is enough if we care for bytes objects on the
msgpack level.
also wrap exception handling, so borg code can catch msgpack specific
exceptions even if the upstream msgpack code raises way too generic
exceptions typed Exception, TypeError or ValueError.

wrap msgpack to avoid api troubles

---

.travis.yml

also remove quotes around version number, not needed for 3.7.

travis: reorder envs, add 3.7-dev

---

src/borg/helpers/time.py

If specified, the argument `format_spec` is forwarded from the method
`OutputTimestamp.__format__` to the method `format_time` method.  Thus,
we are able to specify the format, in a way supported by the class
`datetime`.
The default behaviour of `format_time` is not affected.  The other parts
of code that does not provide a `format_spec` are not affected by the
change.
Also refer audeoudh/borg@5957d713 for history.

Forward the `format_spec` to `datetime` class

---

src/borg/archiver.py

Without this, the client will always override the `storage_quota` set at the server.

Add argument storage_quota to forced_result. Avoids override by client.

---

src/borg/archiver.py

Add storage_quota for forced_result if set by serve-command.

---

src/borg/shellpattern.py

As the title says, after setting up my environment and the tests, I think I fixed this one. All tests seem to pass. So unless there is some regex magic that I missed it should be fine.
As far as I can tell, I complied with all the contribution guidelines.

Moving the flags of the compiled regex to the front to fix #4137

---

conftest.py
src/borg/testsuite/key.py

After running the tests again locally, it seems I had already found all relevant places. Assuming tests pass.

Explicitly convert environment variable to str to address #4136

---

src/borg/archiver.py
src/borg/helpers/fs.py

As far as I am aware, all other instances of the link should be derived/created for doc/man/etc.

 Fixed links to cachedir spec in docs and code to address #4140 

---

docs/quickstart.rst

This is an addition to the documentation explaining that files sometimes change during the backup process and by the time Borg gets to the file, it is not in the same shape as when things began.  See [issue 4081](https://github.com/borgbackup/borg/issues/4081), where a user asked about this and the documentation label was added to the issue.

4081 - Add note about files changing during backup

---

borg/key.py
docs/usage.rst

Read a passpharase from a file descriptor specified in the
BORG_PASSPHRASE_FD environment variable.

read a passphrase from a file descriptor

---

src/borg/archiver.py

Fixes #3561
"PATH::archive" output is added onto info log level into do_create() function.

Added PATH::archive output for creation function on info log level.

---

src/borg/archiver.py

Fixes #4134 
Help text in code has been fixed and appropriate documentation files been rebuilt.

Fixed help string in CRUD documentation. Backport to 1.1-maint

---

src/borg/helpers.py

also: use a more generic get_meta() access method to avoid duplication.
(cherry picked from commit e9ac9beef0960fb8a514c04db9987c58f945e12d)

list repo: add placeholders for hostname and username, fixes #4130

---

docs/installation.rst

docs: tell that our binaries are amd/intel, bauerj has ARM

---

docs/internals/frontends.rst

borg list by default does not compute expensive values except when
they are needed. whether they are needed is determined by the format,
in standard mode as well as in --json mode.
(cherry picked from commit fc6e81c8bbefacc5f2b762c2e97b4005d6f392cf)

docs: --format is required for some expensive-to-compute values

---

src/borg/algorithms/checksums.pyx
src/borg/chunker.pyx
src/borg/compress.pyx
src/borg/crypto/low_level.pyx
src/borg/hashindex.pyx
src/borg/item.pyx
src/borg/platform/darwin.pyx
src/borg/platform/freebsd.pyx
src/borg/platform/linux.pyx
src/borg/platform/posix.pyx

in master branch, it was possible to do this via setup.py's
cythonize() calls, but we do not have them in 1.1.
thus, i modified the source files, setting the language level to 3,
which is supported since long in Cython (3str is only supported since
recently so might fail with older Cython versions).
Before this changeset, current Cython 0.29.x emitted a FutureWarning,
but still compiled. The next major release of Cython is said to emit
an error instead, so this changeset hopefully avoids the build breaking
after a Cython upgrade.
Note: I also removed some "coding utf-8" lines as this is the default nowadays anyway.

add "# cython: language_level=3" directive to .pyx files, fixes #4214

---

src/borg/helpers/msgpack.py

for the Unpacker class, our msgpack wrapper already enforced own
defaults (identical to msgpack < 0.6.0 defaults) - no problem there.
for the unpack and unpackb functions, this changeset enforces the
same defaults in the wrapper, overriding the msgpack 0.6.0+ new
defaults (which caused breakage as seen in #4220).

avoid breakage with msgpack 0.6.0+, keep old limits, fixes #4220

---

src/borg/cache.py
src/borg/repository.py

this will fail early with correct error msg / exception traceback if a config file is not readable.

avoid diaper pattern in configparser by opening files, fixes #4263

---

src/borg/repository.py

seen in #4243:
```
File "/usr/lib/python3/dist-packages/borg/repository.py", line 911, in check
objects = list(self.io.iter_objects(segment))
File "/usr/lib/python3/dist-packages/borg/repository.py", line 1341, in iter_objects
read_data=read_data)
File "/usr/lib/python3/dist-packages/borg/repository.py", line 1428, in _read
segment, offset))
borg.helpers.IntegrityError: Data integrity error: Segment entry checksum mismatch [segment 4405, offset 936892]
During handling of the above exception, another exception occurred:
File "/usr/lib/python3/dist-packages/borg/repository.py", line 1373, in recover_segment
if crc32(data[4:size]) & 0xffffffff != crc:
File "/usr/lib/python3/dist-packages/borg/helpers.py", line 2239, in …
```

correctly release memoryview

---

src/borg/repository.py

nothing left to recover there, but at least we must not crash in mmap().

recover_segment: handle too small segment files correctly, see #4272

---

docs/faq.rst
docs/man/borg.1
docs/usage_general.rst.inc

Updates the `BORG_PASSCOMMAND` example in the FAQ to use `$HOME` instead of `~`, with the latter not being expanded by `cat`.
Next it adds a note regarind the lack of a full shell when executing the `BORG_PASSCOMMAND` in HTML- and man-docs.

Update BORG_PASSCOMMAND example and clarify variable expansion.

---

src/borg/remote.py
src/borg/repository.py

(cherry picked from commit c3a882b509d9213bb9fc4ff2af561c09c07afe97)

Use f_frsize instead of f_bsize to calculate free space. Fixes #4289

---

src/borg/platform/base.py

(cherry picked from commit 111c34f92e8bcd37ae0805cb4c97682d6b7f1610)

make "hostname" short, even on misconfigured systems, fixes #4262

---

src/borg/archiver.py

supercedes #4280 - thanks to AJ Jordan @strugee for finding this.
while using "\\" gives a single backslash when using "borg help pattern"
on the shell, our rendered html docs did not show the single backslash
at all.
i was lazy do dig into that issue, so i just used the word "backslash".
:-)

work around the backslash issue, see #4280

---

src/borg/archive.py
src/borg/cache_sync/cache_sync.c
src/borg/cache_sync/unpack.h
src/borg/hashindex.pyx

1.1-maint backports (16)

---

src/borg/archiver.py
src/borg/fuse.py

platform testing will be done as part of release process.

borg mount / borgfs security fix (1.1-maint)

---

docs/faq.rst

add warnings on repository copies to avoid future problem like #4272

---

src/borg/archiver.py
src/borg/fuse.py

"default_permissions" is now enforced by borg by default to let the
kernel check uid/gid/mode based permissions.
"ignore_permissions" can be given to not enforce "default_permissions".
note: man mount.fuse explicitly tells about the security issue:
default_permissions
By  default FUSE doesn't check file access permissions, ...
This option enables permission checking, restricting access
based on file mode.
This option is usually useful together with the allow_other
mount option.
We consider this a pitfall waiting for someone to fall into and this is
why we chose to change the default behaviour for borg.

security fix: configure FUSE with "default_permissions", fixes #3903

---

src/borg/testsuite/archiver.py

test_mount_hardlinks: get rid of fakeroot-caused test fails, fixes #3389

---

docs/internals.rst
docs/internals/data-structures.rst
docs/internals/frontends.rst
docs/internals/security.rst
docs/usage/create.rst
docs/usage/notes.rst
src/borg/archive.py
src/borg/archiver.py
src/borg/chunker.pyx
src/borg/constants.py
src/borg/helpers/checks.py
src/borg/helpers/parseformat.py
src/borg/item.pyx
src/borg/testsuite/chunker.py
src/borg/testsuite/helpers.py

also:
- bump chunker API_VERSION
- prepend algorithm specification to chunker_params
- make ChunkerParams parsing more flexible
compatibility:
- chunker_params stored in archive metadata now start with the
algorithm, this makes them incompatible with older borg versions
even if the standard buzhash algorithm is used.
- chunker_params given on the commandline are still understood in
the old format, internally defaulting to buzhash then.
- chunker_params in old archives are understood for borg recreate, avoiding rechunking if unnecessary

implement a fixed block size chunker, fixes #1086

---

borg/cache.py
borg/locking.py

1.1 had some bug due to this, see PR #3981,
changeset 2f3e60d9d50d04dd5f09c7351acbcbba28646f36.
the bug does not apply to 1.0, but the improved doc strings might still be useful.

clarify lock_wait docstring

---

docs/usage.rst

Fixes #4133. `window.location.pathname = window.location.pathname` triggers a redirect, which caused `usage.html` to refresh the page on `pathname.replace()` even if the URL wasn't changing.

Only modify window.location when redirecting

---

src/borg/archive.py
src/borg/archiver.py
src/borg/helpers/fs.py
src/borg/platform/linux.pyx
src/borg/testsuite/archiver.py

guess this is mostly done, fixes issues mentioned in #908 and #1038.

use more FDs, avoid race conditions on active fs

---

Vagrantfile

the freebsd12-amd64 one is broken due to some pkg vs. openssl111 issue.

for now, use old freebsd64 vagrant box for testing

---

src/borg/archiver.py
src/borg/helpers/fs.py

basename('/') == '' and we can't use that for openat/statat.
also, there is no parent FD for the root directory...

fix openat/statat issues for root directory, fixes #4405

---

src/borg/crypto/_crypto_helpers.h
src/borg/crypto/low_level.pyx

See #4403, fixes issue below while running the testsuite.
```
borgbackup version 1.2.0a2
self test test_AE (borg.testsuite.crypto.CryptoTestCase) FAILED:
File "/tmp/ports/pobj/borgbackup-1.2.0a2/borgbackup-1.2.0a2/src/borg/testsuite/crypto.py", line 115, in test_AE
hdr_mac_iv_cdata = cs.encrypt(data, header=header)
File "src/borg/crypto/low_level.pyx", line 544, in borg.crypto.low_level._AEAD_BASE.encrypt
borg.crypto.low_level.CryptoError: EVP_EncryptInit_ex failed
self test test_AEAD (borg.testsuite.crypto.CryptoTestCase) FAILED:
File "/tmp/ports/pobj/borgbackup-1.2.0a2/borgbackup-1.2.0a2/src/borg/testsuite/crypto.py", line 159, in test_AEAD
hdr_mac_iv_cdata = cs.encrypt(data, header=header)
File …
```

1.2.0a: fix LibreSSL support, see #4403

---

src/borg/crypto/_crypto_helpers.c
src/borg/crypto/_crypto_helpers.h

While here improve spacing a bit (indentation of 4 spaces instead of 3).

crypto: LibreSSL has HMAC_CTX_free and *HMAC_CTX_new

---

src/borg/archiver.py
src/borg/helpers/fs.py
src/borg/testsuite/archiver.py

The O_NONBLOCK caused EAGAIN errors borg did not deal with, so we
better block and wait until read data is available from e.g. a fifo.
Fixed the --read-special test so it creates a FIFO, feeds it from a
thread and backs it up with borg. Then extracts and checks if correct
data has been backed up.
Also: renamed flags_follow to flags_special_follow (its only intended
use is on symlinks to special files with --read-special).

fix backing up FIFOs. fixes #4394

---

docs/usage/notes.rst

I explained the importance of verifying repository integrity before writing in append-only mode, and some simple ways to do so.
Related to #3504. If you find these docs adequately explain the situation with append-only mode it can be closed. I agree it is kind of confusing; the ideal solution (aside from completely replacing append-only mode) would be to implement something like #2251.

Elaborate on append-only mode docs

---

src/borg/archiver.py
src/borg/remote.py
src/borg/repository.py

incremental repo check
